# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=filesys

# Source files
MODULE_SRC= Volume.cpp Dir.cpp Path.cpp File.cpp

# Actually include the makefile
include ../makefile
