# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=fileSys

# Source files
MODULE_SRC= Volume.cpp Dir.cpp Path.cpp File.cpp FileInfo.cpp FileDrv.cpp DirInfo.cpp

# Actually include the makefile
include ../makefile
