# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=Applications

# Source files
MODULE_SRC=Shell.cpp Logout.cpp neofetch.cpp badapple.cpp Smile.cpp Boot.cpp

# Actually include the makefile
include ../makefile
