# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=Applications

# Source files
MODULE_SRC= Shell.cpp Smile.cpp

# Actually include the makefile
include ../makefile
