# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= stdlib

# Source files
MODULE_SRC= cstdio.cpp Except.cpp filecstd.cpp filedrv.cpp Resources.cpp PageAllocator.cpp HashedDictionary.cpp ObjectAllocator.cpp stdint.cpp stdio.cpp Strings.cpp Hashing.cpp Hashmap.cpp Executable.cpp DynamicPage.cpp Signal.cpp FileNode.cpp Interrupts.cpp screendrv.cpp screencstd.cpp

# Actually include the makefile
include ../makefile
