# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= stdlib

# Source files
MODULE_SRC=Except.cpp Resources.cpp stdint.cpp stdio.cpp Strings.cpp Executable.cpp DynamicPage.cpp Signal.cpp FileNode.cpp

# Actually include the makefile
include ../makefile
