# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= stdlib

# Source files
MODULE_SRC= cstdio.cpp intenv.cpp Except.cpp ErrStrings.cpp filecstd.cpp Resources.cpp PageAllocator.cpp HashedDictionary.cpp ObjectAllocator.cpp stdint.cpp stdio.cpp Strings.cpp Hashing.cpp Hashmap.cpp Executable.cpp DynamicPage.cpp Signal.cpp FileNode.cpp Interrupts.cpp screencstd.cpp split.cpp stitch.cpp Time.cpp

# Actually include the makefile
include ../makefile
