# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=RAE

# Source files
MODULE_SRC= Registers.cpp InstructionCycle.cpp BinaryExecutables.cpp ThreadState.cpp StateMachine.cpp StateMachineOpcodes.cpp lvalue.cpp rvalue.cpp xvalue.cpp pvalue.cpp HypervisorFunctors.cpp

# Actually include the makefile
include ../makefile
