# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= parser

# Source files
MODULE_SRC= Lexer.cpp

# Actually include the makefile
include ../makefile
