# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= System

# Source files
MODULE_SRC=Ctrl.cpp Daemon.cpp Fini.cpp Init.cpp Shell.cpp Drivers.cpp BootRecords.cpp SoftwareDrivers.cpp HardwareDriver.cpp IRQHandler.cpp Shell.cpp ShellHelpers.cpp Syscalls.cpp Taskpool.cpp FirmwareInterface.cpp FirmwareInterfaceFile.cpp FirmwareInterfaceKeyboard.cpp FirmwareInterfaceScreen.cpp FirmwareInterfaceSyscalls.cpp FirmwareInterfaceTime.cpp

# Actually include the makefile
include ../makefile
