# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= System

# Source files
MODULE_SRC=Daemon.cpp Fini.cpp Init.cpp Kernel.cpp Shell.cpp Bootloader.cpp KernelDrivers.cpp KernelSubsystems.cpp OS.cpp BootRecords.cpp SoftwareDrivers.cpp HardwareDriver.cpp KernelSetters.cpp

# Actually include the makefile
include ../makefile
