# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=Kernel

# Source files
MODULE_SRC= Boot.cpp Bootloader.cpp BootSelect.cpp DriverLoaders.cpp ErrorHandling.cpp FileDriver.cpp FileNodes.cpp FileSystem.cpp Input.cpp RAE.cpp Scheduler.cpp ScreenDriver.cpp Singleton.cpp StackTrace_x86.cpp StackTrace_arm.cpp StackTraceDB.cpp Time.cpp TTYTerm.cpp

# Actually include the makefile
include ../makefile
