#define IGNORE 1

#define FLAG_SYMBOLDEFINITION 0
#define FLAG_SYMBOLAUTOMANGLE 1
#define FLAG_SYMBOLFILEMANGLE 2
#define FLAG_SYMBOLINCOMPLETE 3
#define FLAG_SYMBOLFUNCTION 4
#define FLAG_SYMBOLHASVALUE 5
#define FLAG_FUNCPARAMSAVAIL 6
#define FLAG_EXTDEFINEDNAME 7

#define FLAG_INCLUDERELFILE 70

#define FLAG_STOPQUOTEATNEWLINE 80