# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=ELSAnew

# Source files
MODULE_SRC= BinaryOutput.cpp ELF.cpp ELFHeader.cpp ELFHeaderIdent.cpp ELFSection.cpp TranslationUnit.cpp TranslationUnitBackend.cpp TranslationUnitRegistrar.cpp KeywordDatabase.cpp Keywords.cpp Numerical.cpp ProcessorDB.cpp ProcessorFunctor.cpp SectionBuilder.cpp SymbolData.cpp SymbolDatabase.cpp Symbols.cpp SymbolIdentifier.cpp SectionDB.cpp

# Actually include the makefile
include ../makefile
