# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=ELSAnew

# Source files
MODULE_SRC= Numerical.cpp SectionBuilder.cpp SymbolData.cpp SymbolDatabase.cpp Symbols.cpp SymbolIdentifier.cpp SectionDB.cpp

# Actually include the makefile
include ../makefile
