# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE= Terminal

# Source files
MODULE_SRC=ApplicationInput.cpp Args.cpp C0Actions.cpp C1Actions.cpp Constructors.cpp CSIInters.cpp CSINoInters.cpp ECMAUtils.cpp Home.cpp Lines.cpp Move.cpp Pass.cpp Present.cpp Render.cpp Scroll.cpp SGR.cpp State.cpp StateBehaviour.cpp

# Actually include the makefile
include ../makefile
