# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=Builtin

# Source files
MODULE_SRC= builtin.cpp Builtins.cpp cd.cpp context.cpp cp.cpp daemons.cpp driver.cpp dumpelf.cpp echo.cpp elsa.cpp exit.cpp hash.cpp help.cpp hyperv.cpp interrupt.cpp joblist.cpp jobset.cpp kill.cpp logout.cpp ls.cpp mkdir.cpp mount.cpp neofetch.cpp rae.cpp readelf.cpp rm.cpp sallie.cpp status.cpp sudo.cpp trap.cpp type.cpp

# Actually include the makefile
include ../makefile
