# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=Glib

# Source files
MODULE_SRC= Background.cpp Box.cpp Colours.cpp Fill.cpp Fonts.cpp Frame.cpp HRule.cpp Line.cpp PixelMask.cpp Pixels.cpp Print.cpp PrintChar.cpp Rect.cpp RectPixelMask.cpp R2D.cpp Stroke.cpp VRule.cpp Window.cpp

# Actually include the makefile
include ../makefile
