# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=ELSA

# Source files
MODULE_SRC= Actions.cpp Auxiliary.cpp Backend.cpp Builder.cpp DebugEmissions.cpp Frontend.cpp Lexer.cpp LexerInput.cpp Processor.cpp Secondary.cpp EABI.cpp

# Actually include the makefile
include ../makefile
