.TH "Source Directory Reference" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBApplications\fP"
.br
.ti -1c
.RI "directory \fBELF\fP"
.br
.ti -1c
.RI "directory \fBELSA\fP"
.br
.ti -1c
.RI "directory \fBFile\fP"
.br
.ti -1c
.RI "directory \fBGraphics\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBParser\fP"
.br
.ti -1c
.RI "directory \fBstdlib\fP"
.br
.in -1c
