.TH "Applications Directory Reference" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Applications Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbadapple\&.cpp\fP"
.br
.ti -1c
.RI "file \fBL++\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLogout\&.cpp\fP"
.br
.ti -1c
.RI "file \fBneofetch\&.cpp\fP"
.br
.ti -1c
.RI "file \fBShell\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSmile\&.cpp\fP"
.br
.in -1c
