.TH "Backend.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Backend.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/ELSA\&.h'\fP
.br
\fC#include '\&.\&./include/ELSABackend\&.h'\fP
.br
\fC#include 'Actions\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBBP::std::static_string\fP< 100 > \fBIdentifier\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBBBP::std::static_string\fP<100> Identifier"

.PP
Definition at line 5 of file Backend\&.cpp\&.
.PP
Referenced by BBP::esa::esaProcessor::hashIdentifier(), BBP::esa::esaProcessor::mangleSymbolIdentifier(), and BBP::esa::esaProcessor::saveIdentifier()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
