.TH "badapple.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
badapple.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/stdio\&.h'\fP
.br
\fC#include '\&.\&./include/Signal\&.h'\fP
.br
\fC#include '\&.\&./include/Resources\&.h'\fP
.br
\fC#include '\&.\&./include/ELF\&.h'\fP
.br
\fC#include '\&.\&./include/FileSys\&.h'\fP
.br
\fC#include '\&.\&./include/Lex\&.h'\fP
.br
\fC#include '\&.\&./include/CPPApplications\&.h'\fP
.br
\fC#include '\&.\&./include/Executable\&.h'\fP
.br
\fC#include '\&.\&./include/System\&.h'\fP
.br
\fC#include '\&.\&./include/Time\&.h'\fP
.br
\fC#include '\&.\&./include/Graphics\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <cstdio>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFRAMECOUNT\fP   6572"
.br
.ti -1c
.RI "#define \fBFRAMERATE\fP   30"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBBP::std::ResourceManager\fP \fBframePage\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FRAMECOUNT   6572"

.PP
Definition at line 16 of file badapple\&.cpp\&.
.SS "#define FRAMERATE   30"

.PP
Definition at line 17 of file badapple\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBBBP::std::ResourceManager\fP framePage"

.PP
Definition at line 31 of file badapple\&.cpp\&.
.PP
Referenced by BBP::badapple_main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
