BBP
NAME
BBP
SYNOPSIS
Namespaces
 esa
 Locale
 std
 userspace
Typedefs
typedef signed char int8_t
typedef short int16_t
typedef int int32_t
typedef long long int64_t
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef unsigned int uint32_t
typedef unsigned long long uint64_t
typedef signed char int_least8_t
typedef short int_least16_t
typedef int int_least32_t
typedef long long int_least64_t
typedef unsigned char uint_least8_t
typedef unsigned short uint_least16_t
typedef unsigned int uint_least32_t
typedef unsigned long long uint_least64_t
typedef signed char int_fast8_t
typedef int int_fast16_t
typedef int int_fast32_t
typedef long long int_fast64_t
typedef unsigned char uint_fast8_t
typedef unsigned int uint_fast16_t
typedef unsigned int uint_fast32_t
typedef unsigned long long uint_fast64_t
Functions
int shell (BBP::std::string &str)
int shell (const char *ss)
int shell_main (int argc, char **argv)
int boot_main (int, char **)
int logout_main (int, char **)
int neofetch_main (int, char **)
int badapple_main (int, char **)
int smile_main (int, char **)
Variables
BBP::std::static_string< 509 > linePage
Typedef Documentation
typedef short BBP::int16_t
Definition at line 8 of file stdint.h.
typedef int BBP::int32_t
Definition at line 9 of file stdint.h.
typedef long long BBP::int64_t
Definition at line 11 of file stdint.h.
typedef signed char BBP::int8_t
Definition at line 7 of file stdint.h.
typedef int BBP::int_fast16_t
Definition at line 34 of file stdint.h.
typedef int BBP::int_fast32_t
Definition at line 35 of file stdint.h.
typedef long long BBP::int_fast64_t
Definition at line 37 of file stdint.h.
typedef signed char BBP::int_fast8_t
Definition at line 33 of file stdint.h.
typedef short BBP::int_least16_t
Definition at line 21 of file stdint.h.
typedef int BBP::int_least32_t
Definition at line 22 of file stdint.h.
typedef long long BBP::int_least64_t
Definition at line 24 of file stdint.h.
typedef signed char BBP::int_least8_t
Definition at line 20 of file stdint.h.
typedef unsigned short BBP::uint16_t
Definition at line 14 of file stdint.h.
typedef unsigned int BBP::uint32_t
Definition at line 15 of file stdint.h.
typedef unsigned long long BBP::uint64_t
Definition at line 17 of file stdint.h.
typedef unsigned char BBP::uint8_t
Definition at line 13 of file stdint.h.
typedef unsigned int BBP::uint_fast16_t
Definition at line 40 of file stdint.h.
typedef unsigned int BBP::uint_fast32_t
Definition at line 41 of file stdint.h.
typedef unsigned long long BBP::uint_fast64_t
Definition at line 43 of file stdint.h.
typedef unsigned char BBP::uint_fast8_t
Definition at line 39 of file stdint.h.
typedef unsigned short BBP::uint_least16_t
Definition at line 27 of file stdint.h.
typedef unsigned int BBP::uint_least32_t
Definition at line 28 of file stdint.h.
typedef unsigned long long BBP::uint_least64_t
Definition at line 30 of file stdint.h.
typedef unsigned char BBP::uint_least8_t
Definition at line 26 of file stdint.h.
Function Documentation
int BBP::badapple_main (int argc, char ** argv)
Definition at line 33 of file badapple.cpp.
{
    char *fileName = (char *)BBP::std::activemem->calloc(34, sizeof(char));
    BBP::std::ResourceManager *oldMem = BBP::std::activemem;
    BBP::std::activemem = &framePage;
    for (unsigned int i = 1; i < FRAMECOUNT + 1; i += 1)
    {
        BBP::std::sprintf(fileName, "/home/bapple/ascii/%04u.txt", i);
        
        std::FILE frame(fileName);
        ::std::printf("%s", frame.b().page->data);
        
        frame.close();
        std::delay(1000 / FRAMERATE);
        std::printf("\033[2J\033[1;1H");
        system("clear");
        
        if (i % 50 == 0)
            BBP::std::activemem->deleteAll();
    }
    BBP::std::activemem->deleteAll();
    BBP::std::activemem = oldMem;
    std::activemem->free(fileName);
    return 0;
}
References BBP::std::activemem, BBP::std::FILE::b(), BBP::std::FILE::close(), BBP::std::PAGE< T >::data, BBP::std::delay(), BBP::std::ResourceManager::deleteAll(), FRAMECOUNT, framePage, FRAMERATE, BBP::std::ResourceManager::free(), BBP::Locale::Japanese::i, BBP::std::Stack< K >::page, BBP::std::printf(), and BBP::std::sprintf().
int BBP::boot_main (int, char **)
int BBP::logout_main (int argc, char ** argv)
Definition at line 10 of file Logout.cpp.
{
    __SIGNAL__(SIGSHTDN);
}
References __SIGNAL__, and BBP::std::SIGSHTDN.
int BBP::neofetch_main (int argc, char ** argv)
Definition at line 17 of file neofetch.cpp.
{
    //std::printf(RED "BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB" NORM "\n");
    //std::printf(RED "B::::::::::::::::B B::::::::::::::::B" NORM "\n");
    //std::printf(RED "B::::::BBBBBB:::::B B::::::BBBBBB:::::B" NORM "\n");
    //std::printf(RED "BB:::::B B:::::BBB:::::B B:::::B" NORM "\n");
    //std::printf(RED " B::::B B:::::B B::::B B:::::B" NORM "\n");
    //std::printf(RED " B::::B B:::::B B::::B B:::::B" NORM "\n");
    //std::printf(RED " B::::BBBBBB:::::B B::::BBBBBB:::::B" NORM "\n");
    //std::printf(RED " B:::::::::::::BB B:::::::::::::BB" NORM "\n");
    //std::printf(RED " B::::BBBBBB:::::B B::::BBBBBB:::::B" NORM "\n");
    //std::printf(RED " B::::B B:::::B B::::B B:::::B" NORM "\n");
    //std::printf(RED " B::::B B:::::B B::::B B:::::B" NORM "\n");
    //std::printf(RED " B::::B B:::::B B::::B B:::::B" NORM "\n");
    //std::printf(RED "BB:::::BBBBBB::::::BBB:::::BBBBBB::::::B" NORM "\n");
    //std::printf(RED "B:::::::::::::::::B B:::::::::::::::::B" NORM "\n");
    //std::printf(RED "B::::::::::::::::B B::::::::::::::::B" NORM "\n");
    //std::printf(RED "BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB" NORM "\n");
    std::printf(RED " 66666666 " NORM " 000000000 77777777777777777777" NORM "\n");
    std::printf(RED " 6::::::6 " NORM " 00:::::::::00 7::::::::::::::::::7" NORM " " RED HOSTNAME NORM "\n");
    std::printf(RED " 6::::::6 " NORM " 00:::::::::::::00 7::::::::::::::::::7" NORM " ---------- " "\n");
    std::printf(RED " 6::::::6 " NORM " 0:::::::000:::::::0 777777777777:::::::7" NORM " " RED "OS: " NORM OS "\n");
    std::printf(RED " 6::::::6 " NORM " 0::::::0 0::::::0 7::::::7 " NORM " " RED "Kernel: " NORM KERNEL "\n");
    std::printf(RED " 6::::::6 " NORM " 0:::::0 0:::::0 7::::::7 " NORM " " RED "Shell: " NORM SHELL "\n");
    std::printf(RED " 6::::::6 " NORM " 0:::::0 0:::::0 7::::::7 " NORM " " RED "Terminal: " NORM TERMINAL "\n");
    std::printf(RED " 6::::::::66666 " NORM " 0:::::0 000 0:::::0 7::::::7 " NORM " " RED "CPU: " NORM CPU "\n");
    std::printf(RED "6::::::::::::::66 " NORM " 0:::::0 000 0:::::0 7::::::7 " NORM " " RED "Awesome: " NORM "Yes" "\n");
    std::printf(RED "6::::::66666:::::6 " NORM " 0:::::0 0:::::0 7::::::7 " NORM "\n");
    std::printf(RED "6:::::6 6:::::6 " NORM " 0:::::0 0:::::0 7::::::7 " NORM "\n");
    std::printf(RED "6:::::6 6:::::6 " NORM " 0::::::0 0::::::0 7::::::7 " NORM "\n");
    std::printf(RED "6::::::66666::::::6 " NORM " 0:::::::000:::::::0 7::::::7 " NORM "\n");
    std::printf(RED " 66:::::::::::::66 " NORM " 00:::::::::::::00 7::::::7 " NORM "\n");
    std::printf(RED " 66:::::::::66 " NORM " 00:::::::::00 7::::::7 " NORM "\n");
    std::printf(RED " 666666666 " NORM " 000000000 77777777 " NORM "\n");
    return 0;
}
References CPU, HOSTNAME, KERNEL, NORM, OS, BBP::std::printf(), RED, SHELL, and TERMINAL.
int BBP::shell (BBP::std::string & str)
Definition at line 18 of file Shell.cpp.
    {
        // Get the first command line arg
        std::c_string command = std::read_a(&str, 0);
        
        // Then go until space
        for (std::index_t index = 0; index < str.dataSize; index++)
        {
            // Read char at index index
            std::string_element c = std::read(&str, index);
            // Check if 'c' is a space
            if (c != ' ')
                continue;
            
            str.data[index] = 0;
            break;
        }
        // If string is just empty, do nothing
        if (command[0] == 0)
            return 0;
        // Create paths
        std::PATH procPath("/proc/exec/");
        procPath.makeAbsolutePath(std::workingDirectory);
        std::PATH executable(command);
        executable.makeAbsolutePath(&procPath);
        
        try
        {
            // Create file, if it exists, no error will be thrown. Otherwise, an error will be thrown.
            std::FILE executableFile(executable);
            // The file exists. Check if the page has the correct magic numbers.
            std::mem_t magic0 = std::read_r(executableFile.data()->fileData.page, BBP_EXEC_MAGIC0IDX);
            std::mem_t magic1 = std::read_r(executableFile.data()->fileData.page, BBP_EXEC_MAGIC1IDX);
            std::mem_t magic2 = std::read_r(executableFile.data()->fileData.page, BBP_EXEC_MAGIC2IDX);
            std::mem_t magic3 = std::read_r(executableFile.data()->fileData.page, BBP_EXEC_MAGIC3IDX);
            // If the magic matches up, this file is an executable.
            bool isMachineCodeExecutable = (magic0 == BBP_EXEC_MAGIC0) && (magic1 == BBP_EXEC_MAGIC1) && (magic2 == BBP_EXEC_MAGIC2) && (magic3 == BBP_EXEC_MAGIC3);
            
            if (isMachineCodeExecutable)
            {
                // This file is an executable in machine code format. Extract the function from the page, and execute.
                std::executable_main _entry = ((std::executable_main *)executableFile.data()->fileData.page->raw)[0];
                std::execute(_entry, 0, nullptr);
            }
            else
            {
                std::printf("%s: Exec format error.\n", command);
            }
            return std::__errno;
        }
        catch (std::except const &e)
        {
            switch (std::__errno)
            {
            case ENOENT:
                std::printf("%s: command not found.\n", command);
                std::__errno = 0;
                return -1;
                break;
            default:
                // Unkown error, rethrow
                throw;
            }
        }
    }
References BBP_EXEC_MAGIC0, BBP_EXEC_MAGIC0IDX, BBP_EXEC_MAGIC1, BBP_EXEC_MAGIC1IDX, BBP_EXEC_MAGIC2, BBP_EXEC_MAGIC2IDX, BBP_EXEC_MAGIC3, BBP_EXEC_MAGIC3IDX, BBP::std::PAGE< T >::data, BBP::std::FILE::data(), BBP::std::PAGE< T >::dataSize, BBP::Locale::Japanese::e, ENOENT, BBP::std::execute(), BBP::std::FileNode::fileData, BBP::std::PATH::makeAbsolutePath(), BBP::std::Stack< K >::page, BBP::std::printf(), BBP::std::PAGE< T >::raw, BBP::std::read(), BBP::std::read_a(), BBP::std::read_r(), and BBP::std::workingDirectory.
Referenced by shell(), and shell_main().
int BBP::shell (const char * ss)
Definition at line 95 of file Shell.cpp.
    {
        // Get string length
        std::size_t strL = std::strlen(ss);
        // Create new string of that size
        std::string str(strL + 1, (std::string_element *)BBP::std::activemem->calloc(strL + 1, sizeof(std::string_element)));
        // Copy string
        std::strcpy(&str, ss);
        // save shell return value
        int s = shell(str);
        // Free string mem
        BBP::std::activemem->free(str.data);
        // Return shell result
        return s;
    }
References BBP::std::activemem, BBP::std::PAGE< T >::data, BBP::std::ResourceManager::free(), shell(), BBP::std::strcpy(), and BBP::std::strlen().
int BBP::shell_main (int argc, char ** argv)
Definition at line 120 of file Shell.cpp.
    {
        // This surpresses the g++ unused parameters warnings
        argc = argc;
        argv = argv;
        int count = 0;
        bool doLoop = true;
        shell("elsa");
        return 0;
        while (true)
        {
            std::printf("\[0;92m" HOSTNAME "\[0;37m:\[1;34m%s\[0;37m$ ", std::workingDirectory->relName());
            while (doLoop)
            {
                std::getC();
                if (std::STDIN.atElement)
                {
                    char c = 0;
                    char del = 0x08;
                    std::STDIN >> c;
                    //std::printf("0x%02x ", c);
                    switch (c)
                    {
                    case 0x0a:
                    case 0x0d:
                        doLoop = false;
                        
                        break;
                    case 12:
                        // Screen clear
                        std::printf("\033[2J\033[1;1H");
                        std::printf("\[0;92m" HOSTNAME "\[0;37m:\[1;34m%s\[0;37m$ ", std::workingDirectory->relName());
                        break;
                    case 0x7f:
                        
                        if (line.atElement)
                        {
                            std::STDOUT <<= del;
                            std::STDOUT <<= ' ';
                            std::STDOUT <<= del;
                            line--;
                        }
                        break;
                    default:
                        std::STDOUT <<= c;
                        line << c;
                        break;
                    }
                }
            }
            line << '\0';
            std::printf("\n");
            shell(linePage);
            line.atElement = 0;
            count++;
            doLoop = true;
        }
        return 0;
    }
References BBP::std::getC(), HOSTNAME, linePage, BBP::std::printf(), shell(), BBP::std::STDIN, BBP::std::STDOUT, and BBP::std::workingDirectory.
int BBP::smile_main (int argc, char ** argv)
Definition at line 21 of file Smile.cpp.
{
    /*
    
    std::window *w = &BBP::std::kernelDisplay;
    for (std::index_t idx = 0; idx < points - 1; idx++)
        std::R2D::Line(w, xpoints[idx], ypoints[idx], xpoints[idx + 1], ypoints[idx + 1]);
    std::R2D::Line(w, xpoints[0], ypoints[0], xpoints[points - 1], ypoints[points - 1]);
    std::R2D::Line(w, 770, 405, 770, 420);
    std::R2D::Line(w, 780, 405, 780, 420);
    std::R2D::Line(w, 740, 470, 810, 470);
    std::R2D::Line(w, 740, 470, 735, 465);
    std::R2D::Line(w, 810, 470, 815, 465);
    
    std::pos_t xo = w->cursorPosX;
    std::pos_t yo = w->cursorPosY;
    std::pos_t co = w->coloumn;
    std::pos_t lo = w->line;
    w->fontSize = 5;
    w->cursorPosX = 500;
    w->cursorPosY = 200;
    w->coloumn = 0;
    w->line = 0;
    const char *hello = "\xe1\xe1!\n";
    std::R2D::print(w, hello);
    w->fontSize = 0;
    w->cursorPosX = 0;
    w->cursorPosY = yo;
    w->coloumn = co;
    w->line = lo;
    
    */
    std::PATH testFile("/boot/ELSA.esa");
    std::PATH dstFile("/boot/ELSA.o");
    // Compile source
    esa::processor.translate(testFile, dstFile);
    // Now try and deconstruct it
    std::FILE compiledFile(dstFile);
    // Get processor
    std::ELF::ELFBuilder compiled(compiledFile.b().page, std::activemem);
    // Now we can do whatever
    for (std::index_t index = 0; index < compiled.symbolCount; index++)
    {
        // Check symbol stuff
        if (compiled.symbols[index].info() & std::ELF::SYM_FUNC)
            std::printf("Symbol %u is a function.\n", index);
    }
    // Spawn thread
    userspace::Thread t;
    userspace::setRegister(t.eip, 0);
    for (std::byte ii = 0; ii < 16; ii++)
    {
        // Get Instruction pointer
        std::word instructionIndex = userspace::readRegister(t.eip);
        // Instruction header
        std::offset_t textAt = compiled._text().offset();
        std::byte prefix = compiled.file.data[textAt + instructionIndex * 4 + 0];
        std::byte opcode = compiled.file.data[textAt + instructionIndex * 4 + 1];
        std::byte suffix = compiled.file.data[textAt + instructionIndex * 4 + 2];
        std::byte args = compiled.file.data[textAt + instructionIndex * 4 + 3];
        // Decode stuff
        std::printf(".text+0x%04x:\t0x%02x %02x %02x %02x\n\t", instructionIndex * 4, prefix, opcode, suffix, args);
        for (std::byte idx = 0; idx < args; idx++)
            if (prefix & (1 << idx))
                std::printf("r");
            else
                std::printf("c");
        std::printf(" ");
        switch (opcode)
        {
        case userspace::NIL:
            std::printf("NIL");
            break;
        case userspace::STACK:
            std::printf("STACK");
            break;
        case userspace::CTRL:
            std::printf("CTRL");
            break;
        case userspace::MEM:
            std::printf("MEM");
            break;
        case userspace::INC:
            std::printf("INC");
            break;
        case userspace::DEC:
            std::printf("DEC");
            break;
        case userspace::NEG:
            std::printf("NEG");
            break;
        case userspace::ADD:
            std::printf("ADD");
            break;
        case userspace::SUB:
            std::printf("SUB");
            break;
        case userspace::MUL:
            std::printf("MUL");
            break;
        case userspace::DIV:
            std::printf("DIV");
            break;
        case userspace::MOD:
            std::printf("MOD");
            break;
        case userspace::LBS:
            std::printf("LBS");
            break;
        case userspace::RBS:
            std::printf("RBS");
            break;
        case userspace::OR:
            std::printf("OR");
            break;
        case userspace::XOR:
            std::printf("XOR");
            break;
        case userspace::AND:
            std::printf("AND");
            break;
        case userspace::NOT:
            std::printf("NOT");
            break;
        case userspace::FLAG:
            std::printf("FLAG");
            break;
        case userspace::JMP:
            std::printf("JMP");
            break;
        case userspace::JMPZ:
            std::printf("JMPZ");
            break;
        case userspace::JMPC:
            std::printf("JMPC");
            break;
        case userspace::PAGE:
            std::printf("PAGE");
            break;
        case userspace::SIGNAL:
            std::printf("SIGNAL");
            break;
        case userspace::HALT:
            std::printf("HALT");
            break;
        default:
            std::printf("(error)");
        }
        std::printf("\t(%u args)\n", args);
        // Increase pointer
        userspace::setRegister(t.eip, instructionIndex + 1);
    }
    
    // Close
    compiled.close();
    compiledFile.close();
    __SIGNAL__(SIGILL);
    /*
    std::PATH bootPath("/boot/test.lua");
    lua::initializeParser();
    lua::luaParser.parseFile(bootPath);
    */
    /*
    // Emit header
    builder.emitHeader();
    builder.shstrtab = 1;
    builder.strtab = 2;
    builder.symtab = 3;
    builder.sections[0].type(std::ELF::SHT_NILL);
    builder._shstrtab().Append(64);
    builder._shstrtab().stack++;
    builder._shstrtab().stack <<= ".shstrtab";
    builder._shstrtab().type(std::ELF::SHT_STRTAB);
    builder._shstrtab().name(1);
    builder._strtab().Append(64);
    builder._strtab().name(builder._shstrtab().stack.atElement);
    builder._shstrtab().stack <<= ".strtab";
    builder._strtab().type(std::ELF::SHT_STRTAB);
    builder._symtab().Append(32);
    builder._symtab().type(std::ELF::SHT_SYMTAB);
    builder._symtab().name(builder._shstrtab().stack.atElement);
    builder._symtab().info(builder.strtab);
    builder._symtab().link(builder.strtab);
    builder._symtab().entsize(16);
    builder._strtab().stack++;
    builder._shstrtab().stack <<= ".symtab";
    builder.shstrndx(1);
    builder._shstrtab().Extend(16);
    */
    
    /*
    std::ELF::ELFBuilder builder(std::activemem, 0, 13, 3);
    std::Stack<std::string_element> builderStack(&builder.file, std::seqlen(builder.file));
    std::FILE file(builderStack, "/bin/test.o");
    const char *msg = "Hello, world!";
    builder.formStandard(24, 14, 0, 0);
    builder.renameSymbol(1, "Hello");
    builder.renameSymbol(2, "HoHo");
    builder._data().stack <<= "Hello, World!";
    file.writeFileToDisk();
    builder.close();
    file.close();
    */
    /*
    std::ESAM::dataEntry data("Hello, World!", std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
    std::ESAM::dataEntry data2("4 + 5 is %d\n", std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
    std::ESAM::dataEntry program("\x32\xa1\xa2", std::ELF::SYM_FILE | std::ELF::SYM_GLOBAL);
    std::ESAM::dataEntry program2("\xFF\xFF\xFF", std::ELF::SYM_SECTION | std::ELF::SYM_GLOBAL);
    std::ESAM::BinaryApplication application("/bin/test.o", 0, 0, 4);
    application.setSource("/home/test.esa");
    application.emitSymbol(application.builder.rodata, data, "myString");
    application.emitSymbol(application.builder.rodata, data2, "fmtString");
    application.emitSymbol(application.builder.text, program, "_ZfooIi");
    application.emitSymbol(application.builder.text, program2, "_ZfffIi");
    application.save();
    application.close();
    std::ESAM::BinaryApplication application2("/bin/test2.o", 0, 0, 4);
    application2.setSource("/home/test.esa");
    application2.emitSymbol(application2.builder.rodata, data, "myString");
    application2.emitSymbol(application2.builder.rodata, data2, "fmtString");
    application2.emitSymbol(application2.builder.text, program, "_ZfooIi");
    application2.emitSymbol(application2.builder.text, program2, "_ZfffIi");
    application2.appendSymbols(1);
    application2.emitSymbol(application2.builder.text, program2, "_ZfofIi");
    application2.save();
    application2.close();
    */
    return 0;
}
References __SIGNAL__, BBP::std::ELF::ELFBuilder::_text(), BBP::std::activemem, BBP::userspace::ADD, BBP::userspace::AND, BBP::std::FILE::b(), BBP::std::FILE::close(), BBP::std::ELF::ELFBuilder::close(), BBP::userspace::CTRL, BBP::std::PAGE< T >::data, BBP::userspace::DEC, BBP::userspace::DIV, BBP::userspace::Thread::eip, BBP::std::ELF::ELFBuilder::file, BBP::userspace::FLAG, BBP::userspace::HALT, BBP::userspace::INC, BBP::userspace::JMP, BBP::userspace::JMPC, BBP::userspace::JMPZ, BBP::userspace::LBS, BBP::userspace::MEM, BBP::userspace::MOD, BBP::userspace::MUL, BBP::userspace::NEG, BBP::userspace::NIL, BBP::userspace::NOT, BBP::std::ELF::SectionBuilder::offset(), BBP::userspace::OR, BBP::userspace::PAGE, BBP::std::Stack< K >::page, BBP::std::printf(), BBP::esa::processor, BBP::userspace::RBS, BBP::userspace::readRegister(), BBP::userspace::setRegister(), BBP::std::SIGILL, BBP::userspace::SIGNAL, BBP::userspace::STACK, BBP::userspace::SUB, BBP::std::ELF::SYM_FUNC, BBP::std::ELF::ELFBuilder::symbolCount, BBP::std::ELF::ELFBuilder::symbols, BBP::esa::esaProcessor::translate(), and BBP::userspace::XOR.
Variable Documentation
BBP::std::Stack< BBP::std::string_element > line & BBP::linePage
Definition at line 117 of file Shell.cpp.
Referenced by shell_main().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.