BBP::std::FileNode
NAME
BBP::std::FileNode
SYNOPSIS
#include <FileSys.h>
Public Member Functions
FileNode ()
FileNode (std::ResourceManager *res, std::conststring path)
FileNode (std::Stack< std::string_element > &data, std::conststring path)
FileNode (std::ResourceManager *res, std::VOLUME *v, std::conststring path)
FileNode (std::ResourceManager *res, std::size_t size, std::VOLUME *v, std::conststring path)
FileNode (std::ResourceManager *res, std::size_t size, std::PATH &path)
FileNode (std::Stack< std::string_element > &data, std::VOLUME *v, std::conststring path)
Data Fields
std::ResourceManager * allocator
std::Stack< std::string_element > fileData
std::PATH filePath
std::hash_t filePathHash
Detailed Description
Definition at line 159 of file FileSys.h.
Constructor & Destructor Documentation
BBP::std::FileNode::FileNode () [inline]
Definition at line 169 of file FileSys.h.
                : allocator(nullptr),
                fileData((std::PAGE<std::string_element> *)nullptr, 0),
                filePath(),
                filePathHash(0)
            {}
BBP::std::FileNode::FileNode (std::ResourceManager * res, std::conststring path) [inline]
Definition at line 176 of file FileSys.h.
                : allocator(res),
                fileData((std::PAGE<std::string_element> *)nullptr),
                filePath(path),
                filePathHash(0)
            {
                filePath.makeAbsolutePath(std::workingDirectory);
                filePathHash = std::strhsh(filePath.relName());
            }
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory.
BBP::std::FileNode::FileNode (std::Stack< std::string_element > & data, std::conststring path) [inline]
Definition at line 186 of file FileSys.h.
                : allocator(nullptr),
                fileData(data),
                filePath(path),
                filePathHash(0)
            {
                filePath.makeAbsolutePath(std::workingDirectory);
                filePathHash = std::strhsh(filePath.relName());
            }
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory.
BBP::std::FileNode::FileNode (std::ResourceManager * res, std::VOLUME * v, std::conststring path) [inline]
Definition at line 196 of file FileSys.h.
                : allocator(res),
                fileData((std::PAGE<std::string_element> *)nullptr, 0),
                filePath(v, path),
                filePathHash(0)
            {
                filePath.makeAbsolutePath(std::workingDirectory);
                filePathHash = std::strhsh(filePath.relName());
            }
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory.
BBP::std::FileNode::FileNode (std::ResourceManager * res, std::size_t size, std::VOLUME * v, std::conststring path) [inline]
Definition at line 206 of file FileSys.h.
                : allocator(res),
                fileData(
                    (std::PAGE<std::string_element> *)res->add_object(new std::PAGE<std::string_element>(size, (std::string_element *)res->calloc(size, sizeof(std::string_element)))),
                    size),
                filePath(v, path),
                filePathHash(0)
            {
                filePath.makeAbsolutePath(std::workingDirectory);
                filePathHash = std::strhsh(filePath.relName());
            }
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory.
BBP::std::FileNode::FileNode (std::ResourceManager * res, std::size_t size, std::PATH & path) [inline]
Definition at line 218 of file FileSys.h.
                : allocator(res),
                fileData(
                    (std::PAGE<std::string_element> *)res->add_object(new std::PAGE<std::string_element>(size, (std::string_element *)res->calloc(size, sizeof(std::string_element)))),
                    size),
                filePath(path),
                filePathHash(0)
            {
                filePath.makeAbsolutePath(std::workingDirectory);
                filePathHash = std::strhsh(filePath.relName());
            }
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory.
BBP::std::FileNode::FileNode (std::Stack< std::string_element > & data, std::VOLUME * v, std::conststring path) [inline]
Definition at line 232 of file FileSys.h.
                : allocator(nullptr),
                fileData(data),
                filePath(v, path),
                filePathHash(0)
            {
                filePath.makeAbsolutePath(std::workingDirectory);
                filePathHash = std::strhsh(filePath.relName());
            }
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory.
Field Documentation
std::ResourceManager* BBP::std::FileNode::allocator
Definition at line 162 of file FileSys.h.
std::Stack<std::string_element> BBP::std::FileNode::fileData
Definition at line 163 of file FileSys.h.
Referenced by BBP::std::fprintf(), and BBP::shell().
std::PATH BBP::std::FileNode::filePath
Definition at line 166 of file FileSys.h.
Referenced by FileNode().
std::hash_t BBP::std::FileNode::filePathHash
Definition at line 167 of file FileSys.h.
Referenced by BBP::std::FILE::checkIfIsOpen(), FileNode(), and BBP::std::FILE::findClosedFile().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.