.TH "BBP::userspace::Instruction" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::userspace::Instruction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Instructions\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBArg\fP"
.br
.ti -1c
.RI "struct \fBHead\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBBBP::userspace::Instruction::Head\fP \fBheader\fP"
.br
.ti -1c
.RI "struct \fBBBP::userspace::Instruction::Arg\fP \fBargs\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Instructions\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBBBP::userspace::Instruction::Arg\fP BBP::userspace::Instruction::args[8]"

.SS "struct \fBBBP::userspace::Instruction::Head\fP BBP::userspace::Instruction::header"

.PP
Referenced by BBP::esa::TOKEN()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
