BBP::std::Lexer::lex_context
NAME
BBP::std::Lexer::lex_context
SYNOPSIS
#include <Lex.h>
Public Member Functions
lex_context ()
void translateUnit (std::PATH &)
void parseFile ()
void parseFile (std::PATH &)
void executeKeywordAction (lex_keywordhandle, lex_keyword *&)
void executeSpecialFunction (std::index_t a, std::index_t b)
bool isWhitespace (char)
bool isNewLine (char)
char isBinaryNumeral (char)
char isOctalNumeral (char)
char isDecimalNumeral (char)
char isHexadecimalNumeral (char)
char isNumericalBase (std::string_element, std::byte &)
bool tryParseNumerical (std::index_t from, std::index_t to, bool &isFloat, float &fresult, int &iresult)
void moveToEndOfLastWord (bool stopAtNewLine)
void moveToStartOfLastWord (bool stopAtNewLine)
void moveToEndOfThisWord (bool stopAtNewLine)
void moveToStartOfThisWord (bool stopAtNewLine)
void moveToEndOfNextWord (bool stopAtNewLine)
void moveToStartOfNextWord (bool stopAtNewLine)
bool moveToAndHashThisWord (std::hash_t &, char)
bool moveToAndHashNextWord (std::hash_t &, char)
void calculateDebugPosition ()
lex_keywordhandle moveToNextKeyword ()
void resetInfo (lex_debugInfo &info)
void Log (lex_debugInfo &info)
void Log (std::conststring msg)
void Log (std::conststring from, std::conststring msg, std::conststring name)
void LogError (std::conststring from, std::conststring msg, std::conststring name)
void LogNote (std::conststring from, std::conststring msg, std::conststring name)
void LogWarning (std::conststring from, std::conststring msg, std::conststring name)
void LogAbort (std::conststring from, std::conststring msg, std::conststring name)
void Highlight (lex_debugInfo info)
Data Fields
std::static_string< 128 > activeFile
std::PAGE< string_element > data
std::size_t dataSize
std::index_t atPosition
std::STATIC_PAGE< lex_keyword, 256 > keywords
std::Stack< lex_keyword > keywordStack
bool inhibitSpecialFunctions
std::conststring(* onUnkown )(index_t, index_t)
std::conststring(* onNumericalLiteral )(numerical_t numerical, bool isFloat)
index_t lastWhiteSpace
char commentDepth
char literalDepth
lex_debugInfo debugInformation
bool abort
bool illformed
std::static_string< 1024 > usrpathPage
std::static_string< 1024 > syspathPage
std::Stack< std::string_element > usrpaths
std::Stack< std::string_element > syspaths
Detailed Description
Definition at line 98 of file Lex.h.
Constructor & Destructor Documentation
BBP::std::Lexer::lex_context::lex_context ()
Definition at line 955 of file Lexer.cpp.
    : keywordStack(&keywords, 64),
    usrpaths(&usrpathPage, usrpathPage.dataSize),
    syspaths(&syspathPage, syspathPage.dataSize),
    abort(false),
    atPosition(0),
    commentDepth(0),
    literalDepth(0),
    dataSize(0),
    lastWhiteSpace(0),
    inhibitSpecialFunctions(false)
{
}
Member Function Documentation
void BBP::std::Lexer::lex_context::calculateDebugPosition ()
Definition at line 659 of file Lexer.cpp.
{
    // TODO: You are telling me that this is the most inefficient part of the whole program? O(N^2) worst case? Really?
    // To store position
    std::index_t pos = 0;
    // Reset debug info
    debugInformation.coloumn = 0;
    debugInformation.line = 1;
    if (activeFile.data[0] == '\0')
        return;
    // Catch up to where we are, counting the newlines and stuff
    while (pos < atPosition && pos < dataSize)
    {
        char c = __UNSAFE__(read)(&data, pos++);
        
        if (isNewLine(c))
        {
            debugInformation.line++;
            debugInformation.coloumn = 0;
        }
        else
        {
            debugInformation.coloumn++;
        }
    }
}
References __UNSAFE__, and BBP::std::read().
void BBP::std::Lexer::lex_context::executeKeywordAction (Lexer::lex_keywordhandle handle, Lexer::lex_keyword *& keyword)
Definition at line 58 of file Lexer.cpp.
{
    // If keyword is nullptr, do nothing
    if (keyword == nullptr)
        return;
    // Otherwise, if action exists, execute it.
    if (keyword->action)
    {
        // Call action
        debugInformation.msg = keyword->action(this, atPosition - keyword->length, handle);
        // if msg exists, log error
        if (debugInformation.msg)
        {
            Log(debugInformation);
            resetInfo(debugInformation);
        }
    }
}
References BBP::std::Lexer::lex_keyword::action, and BBP::std::Lexer::lex_keyword::length.
void BBP::std::Lexer::lex_context::executeSpecialFunction (std::index_t a, std::index_t b)
Definition at line 213 of file Lexer.cpp.
{
    // If special functions are inhibited, do nothing
    if (inhibitSpecialFunctions)
        return;
    // Check if it is number
    {
        // Check for number
        bool isFloat = false;
        int iresult = 0;
        float fresult = 0;
        // Try to parse
        bool isNumber = tryParseNumerical(from, to, isFloat, fresult, iresult);
        // If a number, run and debug.
        if (isNumber && onNumericalLiteral)
        {
            // Build numerical
            numerical_t number;
            if (isFloat)
                number.f = fresult;
            else
                number.i = iresult;
            // Call action
            debugInformation.msg = onNumericalLiteral(number, isFloat);
            // if msg exists, log error
            if (debugInformation.msg)
            {
                Log(debugInformation);
                resetInfo(debugInformation);
            }
            return;
        }
        else if (isNumber)
        {
            Log("ELSA", "WNumerical found, but no action is defined.", "-Wmissing-function");
            return;
        }
    }
    // Nothing found, call unkown
    if (onUnkown)
    {
        // Call action
        debugInformation.msg = onUnkown(to, from);
        // if msg exists, log error
        if (debugInformation.msg)
        {
            Log(debugInformation);
            resetInfo(debugInformation);
        }
        return;
    }
    Log("ELSA", "WUnkown sequence found, but no action is defined.", "-Wmissing-function");
}
References BBP::std::Lexer::numerical_t::f, BBP::std::Lexer::numerical_t::i, and BBP::Locale::Japanese::to.
void BBP::std::Lexer::lex_context::Highlight (lex_debugInfo info)
Definition at line 865 of file Lexer.cpp.
{
    // This pointer traverses the highlighted text
    std::index_t highlitingText = info.highlight;
    bool isSingleLine = true;
    unsigned int length = 0;
    unsigned int linelength = 0;
    unsigned int runningLength = 0;
    std::index_t line = info.line;
    std::index_t character = info.character;
    std::index_t coloumn = info.coloumn;
    char c = 0;
    // Continue highlighting until end of string
    while ((std::read(&this->data, highlitingText) && !info.highlightLength) || (info.highlightLength && runningLength < info.highlightLength))
    {
        // Print location information
        if (info.showWhere)
        {
            if (info.showLinesAndColoumns)
                std::putf(std::STDOUT, "%5u |\t\[0;96m", line);
            else
                std::putf(std::STDOUT, "%4u~ |\t\[0;96m", character);
        }
        // Continue highlighting until end of string
        while ((!info.highlightLength) || (info.highlightLength && runningLength < info.highlightLength))
        {
            // Get character to be highlighted
            c = std::read(&this->data, highlitingText++);
            // If character is null, break
            if (c == 0)
                goto end; // break out of nested whiles
            character++;
            coloumn++;
            linelength++;
            runningLength++;
            // if character is newline, continue
            if (isNewLine(c))
            {
                // If c is not '\n', just continue
                if (c != '\n')
                    continue;
                // Else, increment line and coloumn info
                line += 1;
                character = 0;
                std::STDOUT << "\[0;37m" <<= endl;
                isSingleLine = false;
                length = (length < linelength) ? linelength - 1 : length;
                linelength = 0;
                break;
            }
            // Print character to screen
            std::STDOUT << c;
            length = (length < linelength) ? linelength : length;
        }
    }
    end:
    // Emit last new line
    if (c != '\n')
        std::STDOUT << "\[0;37m\n | \[0;96m";
    else if (runningLength > 1)
        std::STDOUT << "\[0;37m | \[0;96m";
    for (unsigned int index = 0; index < length; index++)
    {
        if (isSingleLine)
            std::STDOUT << "^";
        else
            std::STDOUT << "~";
    }
    std::STDOUT << "\[0;37m" <<= std::endl;
    
}
References BBP::std::Lexer::lex_debugInfo::character, BBP::std::Lexer::lex_debugInfo::coloumn, BBP::std::endl, BBP::std::Lexer::lex_debugInfo::highlight, BBP::std::Lexer::lex_debugInfo::highlightLength, BBP::std::Lexer::lex_debugInfo::line, BBP::std::putf(), BBP::std::read(), BBP::std::Lexer::lex_debugInfo::showLinesAndColoumns, BBP::std::Lexer::lex_debugInfo::showWhere, and BBP::std::STDOUT.
char BBP::std::Lexer::lex_context::isBinaryNumeral (char c)
Definition at line 333 of file Lexer.cpp.
{
    switch (c)
    {
    case '0':
        return 10;
    case '1':
        return 11;
    default:
        return 0;
    }
}
char BBP::std::Lexer::lex_context::isDecimalNumeral (char c)
Definition at line 371 of file Lexer.cpp.
{
    switch (c)
    {
    case '0':
        return 10;
    case '1':
        return 11;
    case '2':
        return 12;
    case '3':
        return 13;
    case '4':
        return 14;
    case '5':
        return 15;
    case '6':
        return 16;
    case '7':
        return 17;
    case '8':
        return 18;
    case '9':
        return 19;
    default:
        return 0;
    }
}
char BBP::std::Lexer::lex_context::isHexadecimalNumeral (char c)
Definition at line 400 of file Lexer.cpp.
{
    switch (c)
    {
    case '0':
        return 10;
    case '1':
        return 11;
    case '2':
        return 12;
    case '3':
        return 13;
    case '4':
        return 14;
    case '5':
        return 15;
    case '6':
        return 16;
    case '7':
        return 17;
    case '8':
        return 18;
    case '9':
        return 19;
    case 'A':
    case 'a':
        return 20;
    case 'B':
    case 'b':
        return 21;
    case 'C':
    case 'c':
        return 22;
    case 'D':
    case 'd':
        return 23;
    case 'E':
    case 'e':
        return 24;
    case 'F':
    case 'f':
        return 25;
    default:
        return 0;
    }
}
bool BBP::std::Lexer::lex_context::isNewLine (char c)
Definition at line 328 of file Lexer.cpp.
{
    return (c == '\n' || c == '\r');
}
Referenced by BBP::esa::esaProcessor::ExpectDelimiters().
char BBP::std::Lexer::lex_context::isNumericalBase (std::string_element c, std::byte & base)
Definition at line 447 of file Lexer.cpp.
{
    switch (c)
    {
    case 'b':
        base = 2;
        return 30;
    case 'o':
        base = 8;
        return 31;
    case 'f':
        base = 10;
        return 32;
    case 'x':
        base = 16;
        return 33;
    default:
        base = 0;
        return 0;
    }
}
char BBP::std::Lexer::lex_context::isOctalNumeral (char c)
Definition at line 346 of file Lexer.cpp.
{
    switch (c)
    {
    case '0':
        return 10;
    case '1':
        return 11;
    case '2':
        return 12;
    case '3':
        return 13;
    case '4':
        return 14;
    case '5':
        return 15;
    case '6':
        return 16;
    case '7':
        return 17;
    default:
        return 0;
    }
}
bool BBP::std::Lexer::lex_context::isWhitespace (char c)
Definition at line 323 of file Lexer.cpp.
{
    return (c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == 1 || c == 2);
}
void BBP::std::Lexer::lex_context::Log (lex_debugInfo & info)
Definition at line 797 of file Lexer.cpp.
{
    
    if (info.showWhere)
    {
        // Reset debug position
        if (activeFile.data[0] != '\0')
            calculateDebugPosition();
        if (info.procedure.data)
        {
            if (info.procedure.data[0] != '\0')
            {
                if (activeFile.data[0] == '\0')
                    std::printf("(<Binary>): In procedure: `\[0;97m%s\[0;37m`:\n", info.procedure.data);
                else
                    std::printf("\[0;97m%s:\[0;37m In procedure: `\[0;97m%s\[0;37m`:\n", activeFile.data, info.procedure.data);
            }
        }
        if (info.showLinesAndColoumns)
        {
            if (activeFile.data[0] == '\0')
                std::putf(std::STDOUT, "(<Binary>:%u:%u): ", info.coloumn, info.line);
            else
                std::putf(std::STDOUT, "\[0;97m%s:%u:%u:\[0;37m ", activeFile.data, info.coloumn, info.line);
        }
        else
        {
            if (activeFile.data[0] == '\0')
                std::putf(std::STDOUT, "(<Binary>~%4u): ", info.character);
            else
                std::putf(std::STDOUT, "\[0;97m%s~%4u:\[0;37m ", activeFile.data, info.character);
        }
    }
    Log(nullptr, info.msg, info.errName);
    
    if (info.highlightmsg)
    {
        if (info.showWhere)
        {
            if (info.showLinesAndColoumns)
            {
                if (activeFile.data[0] == '\0')
                    std::putf(std::STDOUT, "(<Binary>:%u:%u): ", info.coloumn, info.line);
                else
                    std::putf(std::STDOUT, "(%s:%u:%u): ", activeFile.data, info.coloumn, info.line);
            }
            else
            {
                if (activeFile.data[0] == '\0')
                    std::putf(std::STDOUT, "(<Binary>~%4u): ", info.character);
                else
                    std::putf(std::STDOUT, "(%s~%4u): ", activeFile.data, info.character);
            }
        }
        Log(info.highlightmsg);
        Highlight(info);
    }
    std::putf(std::STDOUT, "\n");
}
References BBP::std::Lexer::lex_debugInfo::character, BBP::std::Lexer::lex_debugInfo::coloumn, BBP::std::PAGE< T >::data, BBP::std::Lexer::lex_debugInfo::errName, BBP::std::Lexer::lex_debugInfo::highlightmsg, BBP::std::Lexer::lex_debugInfo::line, BBP::std::Lexer::lex_debugInfo::msg, BBP::std::printf(), BBP::std::Lexer::lex_debugInfo::procedure, BBP::std::putf(), BBP::std::Lexer::lex_debugInfo::showLinesAndColoumns, BBP::std::Lexer::lex_debugInfo::showWhere, and BBP::std::STDOUT.
Referenced by translateUnit().
void BBP::std::Lexer::lex_context::Log (std::conststring from, std::conststring msg, std::conststring name)
void BBP::std::Lexer::lex_context::Log (std::conststring msg)
void BBP::std::Lexer::lex_context::LogAbort (std::conststring from, std::conststring msg, std::conststring name)
Definition at line 740 of file Lexer.cpp.
{
    if (from)
        std::STDOUT << "\[0;30;101m" << from << "\[0;37m: " << msg;
    else
        std::STDOUT << "\[0;30;101mfatal error\[0;37m: " << msg;
    if (name)
        std::STDOUT << " [\[0;30;101m" << name << "\[0;37m]" <<= endl;
    else
        std::STDOUT <<= endl;
}
References BBP::std::endl, and BBP::std::STDOUT.
void BBP::std::Lexer::lex_context::LogError (std::conststring from, std::conststring msg, std::conststring name)
Definition at line 704 of file Lexer.cpp.
{
    if (from)
        std::STDOUT << "\[0;31m" << from << "\[0;37m: " << msg;
    else
        std::STDOUT << "\[0;31merror\[0;37m: " << msg;
    if (name)
        std::STDOUT << " [\[0;31m" << name << "\[0;37m]" <<= endl;
    else
        std::STDOUT <<= endl;
}
References BBP::std::endl, and BBP::std::STDOUT.
void BBP::std::Lexer::lex_context::LogNote (std::conststring from, std::conststring msg, std::conststring name)
Definition at line 716 of file Lexer.cpp.
{
    if (from)
        std::STDOUT << "\[0;36m" << from << "\[0;37m: " << msg;
    else
        std::STDOUT << "\[0;96mnote\[0;37m: " << msg;
    if (name)
        std::STDOUT << " [\[0;36m" << name << "\[0;37m]" <<= endl;
    else
        std::STDOUT <<= endl;
}
References BBP::std::endl, and BBP::std::STDOUT.
void BBP::std::Lexer::lex_context::LogWarning (std::conststring from, std::conststring msg, std::conststring name)
Definition at line 728 of file Lexer.cpp.
{
    if (from)
        std::STDOUT << "\[0;35m" << from << "\[0;37m: " << msg;
    else
        std::STDOUT << "\[0;35mwarning\[0;37m: " << msg;
    if (name)
        std::STDOUT << " [\[0;35m" << name << "\[0;37m]" <<= endl;
    else
        std::STDOUT <<= endl;
}
References BBP::std::endl, and BBP::std::STDOUT.
bool BBP::std::Lexer::lex_context::moveToAndHashNextWord (std::hash_t & hash, char stop)
Definition at line 604 of file Lexer.cpp.
{
    // Returns true when it hashed anything, false otherwise.
    // Move back one position
    atPosition--;
    // Move to start of next word
    moveToStartOfNextWord(true);
    return moveToAndHashThisWord(hash, stop);
}
References BBP::Locale::Japanese::hash.
bool BBP::std::Lexer::lex_context::moveToAndHashThisWord (std::hash_t & hash, char stop)
Definition at line 616 of file Lexer.cpp.
{
    // Check if character is newline
    if (isNewLine(__UNSAFE__(std::read)(&data, atPosition)) || atPosition + 1 >= dataSize)
        return false;
    // Calculate size of macro, hash, and index
    std::word Power = 1;
    std::index_t idx = 0;
    bool isOnlyWhitespace = true;
    // Now calculate running hash
    for (; idx < dataSize; idx++)
    {
        // Get character at index
        std::string_element c = __UNSAFE__(std::read)(&data, atPosition + idx);
        // Keep isOnlyWhiteSpace updated
        isOnlyWhitespace &= (isWhitespace(c) || c == 0);
        // If asked to stop here, we stop. We also stop for whitespaces.
        if (c == stop || (!isOnlyWhitespace && isWhitespace(c) && stop == '\n'))
            break;
        // If we are at end character, error.
        if (c == 0)
            return false;
        // Run the hashing algorithm
        std::strhsh(hash, Power, c);
    }
    // Move to end here
    moveToEndOfThisWord(true);
    // If macro is only whitespace, there isn't really anything to do.
    if (isOnlyWhitespace)
        return false;
    return true;
}
References __UNSAFE__, BBP::Locale::Japanese::hash, BBP::std::read(), and BBP::std::strhsh().
void BBP::std::Lexer::lex_context::moveToEndOfLastWord (bool stopAtNewLine)
Definition at line 543 of file Lexer.cpp.
{
    // Move until start of this word
    moveToStartOfThisWord(stopAtNewLine);
    // While possible, move back one character until no whitespace is found
    while (--atPosition < dataSize)
    {
        char c = __UNSAFE__(read)(&data, atPosition);
        if (!isWhitespace(c) || (isNewLine(c) && stopAtNewLine))
        {
            if (isNewLine(c))
                atPosition++;
            break;
        }
    }
}
References __UNSAFE__, and BBP::std::read().
void BBP::std::Lexer::lex_context::moveToEndOfNextWord (bool stopAtNewLine)
Definition at line 586 of file Lexer.cpp.
{
    moveToStartOfNextWord(stopAtNewLine);
    moveToEndOfThisWord(stopAtNewLine);
}
void BBP::std::Lexer::lex_context::moveToEndOfThisWord (bool stopAtNewLine)
Definition at line 566 of file Lexer.cpp.
{
    // While possible, move forward one character until whitespace is found
    while (++atPosition < dataSize)
    {
        char c = __UNSAFE__(read)(&data, atPosition);
        if (isWhitespace(c))
            break;
    }
    atPosition--;
}
References __UNSAFE__, and BBP::std::read().
BBP::std::Lexer::lex_keywordhandle BBP::std::Lexer::lex_context::moveToNextKeyword ()
Definition at line 81 of file Lexer.cpp.
{
    lex_keywordhandle handle = 0;
    size_t kwCount = keywordStack.atElement;
    // These flags keep track of if any non-whitespace sequence had any meaning.
    bool hasFoundMeaningfulToken = false;
    std::index_t foundAt = 0;
    // Loop until something is found
    while (atPosition < dataSize && !abort)
    {
        // Get character
        char character = std::read(&data, atPosition++);
        debugInformation.coloumn++;
        if (isWhitespace(character))
        {
            // If the lexer has previously found meaningful text but now sees a whitespace, do some stuff.
            // Only do this when not intentionally skipping over meaningful tokens (such as comments, literals).
            if (hasFoundMeaningfulToken && !commentDepth && !literalDepth && onUnkown)
            {
                // Call action
                executeSpecialFunction(foundAt, atPosition - 1);
                // Reset flag
                hasFoundMeaningfulToken = false;
                // If need to abort, break out.
                if (abort)
                    return keywordStack.atElement + 1;
            }
        }
        else
        {
            if (!hasFoundMeaningfulToken)
                foundAt = atPosition - 1;
            hasFoundMeaningfulToken = true;
        }
        if (character == '\n')
        {
            debugInformation.coloumn = 0;
            debugInformation.line++;
        }
        // Mask each keyword word
        for (handle = 0; handle < kwCount; handle++)
        {
            
            // Get a handle on the keyword
            lex_keyword *keyword = &read(&keywords, handle);
            // If inside a literal context, and the word is not forced to be evalated,
            if ((literalDepth && !keyword->forceParseOutsideLiterals) && !keyword->forceEvaluation)
            {
                // Continue only if keyword's mask equals literal depth
                if (literalDepth != keyword->considerLiteralDepth && !keyword->forceParseInLiterals)
                    continue;
            }
            // If inside a comment context, and the word is not forced to be evalated,
            if ((commentDepth && !keyword->forceParseOutsideComments) && !keyword->forceEvaluation)
            {
                // Continue only if keyword's mask equals comment depth
                if (commentDepth != keyword->considerCommentDepth && !keyword->forceParseInComments)
                    continue;
            }
            // Operate on keywords mask based on current character
            keyword->mask +=
                (character == keyword->word[keyword->mask]) ?
                1 :
                -keyword->mask;
            // Check if we are in white space, if so, reset flag and stop searching, since it is no use.
            // This must occur after mask code, since otherwise "whi le" would register as "while", unless
            // the keyword consists of whitespaces.
            if (isWhitespace(character))
            {
                lastWhiteSpace = atPosition;
                // Check each character in the word
                for (index_t idx = 0; idx < keyword->length; idx++)
                    if (!isWhitespace(keyword->word[idx]))
                        continue; // If any of these are not whitespaces, skip
            }
            // If the mask is not the same as the length of the keyword, the keyword is not found
            if (keyword->mask != keyword->length)
                continue;
            // If keyword needs to be treated like a delimiter, do that here.
            if (keyword->actAsDelimiter)
            {
                // Check for any prefixed things here.
                if (atPosition - lastWhiteSpace > keyword->length && onUnkown && !literalDepth && !commentDepth)
                {
                    // Call action
                    executeSpecialFunction(lastWhiteSpace, atPosition - keyword->length);
                    // If need to abort, break out.
                    if (abort)
                        return keywordStack.atElement + 1;
                }
                lastWhiteSpace = atPosition;
            }
            // Something was found anyway.
            hasFoundMeaningfulToken = false;
            // Check if keyword is infixed. Delimiters can, however, be infixed.
            if (atPosition - lastWhiteSpace > keyword->length && !keyword->actAsDelimiter)
                continue;
            // Reset mask, since keywords may come after eachother.
            keyword->mask = 0;
            // Keyword found, return that.
            return handle;
        }
    }
    // Nothing was found, return invalid handle
    return kwCount;
}
References BBP::std::Lexer::lex_keyword::actAsDelimiter, BBP::std::Lexer::lex_keyword::considerCommentDepth, BBP::std::Lexer::lex_keyword::considerLiteralDepth, BBP::std::Lexer::lex_keyword::forceEvaluation, BBP::std::Lexer::lex_keyword::forceParseInComments, BBP::std::Lexer::lex_keyword::forceParseInLiterals, BBP::std::Lexer::lex_keyword::forceParseOutsideComments, BBP::std::Lexer::lex_keyword::forceParseOutsideLiterals, BBP::esa::keywords, BBP::std::Lexer::lex_keyword::length, BBP::std::Lexer::lex_keyword::mask, BBP::std::read(), and BBP::std::Lexer::lex_keyword::word.
Referenced by BBP::esa::esaProcessor::ExpectDelimiters().
void BBP::std::Lexer::lex_context::moveToStartOfLastWord (bool stopAtNewLine)
Definition at line 560 of file Lexer.cpp.
{
    moveToEndOfLastWord(stopAtNewLine);
    moveToStartOfThisWord(stopAtNewLine);
}
void BBP::std::Lexer::lex_context::moveToStartOfNextWord (bool stopAtNewLine)
Definition at line 591 of file Lexer.cpp.
{
    moveToEndOfThisWord(stopAtNewLine);
    // While possible, move forward one character until no whitespace is found
    while (++atPosition < dataSize)
    {
        char c = __UNSAFE__(read)(&data, atPosition);
        if (!isWhitespace(c) || (isNewLine(c) && stopAtNewLine))
            break;
    }
}
References __UNSAFE__, and BBP::std::read().
void BBP::std::Lexer::lex_context::moveToStartOfThisWord (bool stopAtNewLine)
Definition at line 577 of file Lexer.cpp.
{
    // While possible, move backward one character until whitespace is found
    while (--atPosition < dataSize)
        if (isWhitespace(__UNSAFE__(read)(&data, atPosition)))
            break;
    atPosition++;
}
References __UNSAFE__, and BBP::std::read().
void BBP::std::Lexer::lex_context::parseFile ()
Definition at line 275 of file Lexer.cpp.
{
    // Reset debug information
    debugInformation.line = 1;
    // While within bounds...
    while (atPosition < dataSize)
    {
        // Calculate the amount of keywords.
        size_t kwCount = keywordStack.atElement;
        // Find the next keyword
        lex_keywordhandle handle = moveToNextKeyword();
        if (abort)
        {
            Log(activeFile.data, "ECompilation terminated.", nullptr);
            return;
        }
        // If no keyword is found, exit out.
        if (handle == kwCount)
            break;
        // Otherwise, get keyword pointer
        lex_keyword *keyword = &__UNSAFE__(read)(&keywords, handle);
        // Then execute the keyword action
        executeKeywordAction(handle, keyword);
        if (abort)
        {
            Log(activeFile.data, "ECompilation terminated.", nullptr);
            return;
        }
    }
    // Do final checks
    if (literalDepth)
        Log("lexer", "EExpected literal termination before 'EOF'", nullptr);
    if (commentDepth)
        Log("lexer", "EExpected comment termination before 'EOF'", nullptr);
    literalDepth = 0;
    commentDepth = 0;
}
References __UNSAFE__, BBP::esa::keywords, and BBP::std::read().
Referenced by BBP::esa::esaProcessor::includeFile(), and translateUnit().
void BBP::std::Lexer::lex_context::parseFile (std::PATH & file)
Definition at line 25 of file Lexer.cpp.
{
    // Read the file
    std::FILE source(file);
    // Read the data from the file
    data = *source.b().page;
    // Calculate data size
    dataSize = std::seqlen(data);
    // Set string
    std::c_string name = file.fileName();
    strcpy(&activeFile, name);
    // Reset flags
    commentDepth = 0;
    literalDepth = 0;
    atPosition = 0;
    // Parse everything
    parseFile();
    // Close file
    source.close();
    // Clear file data
    data = PAGE<string_element>(0, nullptr);
    // Reset file name
    strcpy(&activeFile, "");
}
References BBP::std::FILE::b(), BBP::std::FILE::close(), BBP::std::PATH::fileName(), BBP::std::Stack< K >::page, BBP::std::seqlen(), and BBP::std::strcpy().
void BBP::std::Lexer::lex_context::resetInfo (lex_debugInfo & info)
Definition at line 694 of file Lexer.cpp.
{
    info.showLinesAndColoumns = true;
    info.showWhere = true;
    info.highlightmsg = nullptr;
    info.highlight = 0;
    info.errName = nullptr;
    info.highlightLength = 0;
}
References BBP::std::Lexer::lex_debugInfo::errName, BBP::std::Lexer::lex_debugInfo::highlight, BBP::std::Lexer::lex_debugInfo::highlightLength, BBP::std::Lexer::lex_debugInfo::highlightmsg, BBP::std::Lexer::lex_debugInfo::showLinesAndColoumns, and BBP::std::Lexer::lex_debugInfo::showWhere.
Referenced by BBP::esa::esaProcessor::includeFile().
void BBP::std::Lexer::lex_context::translateUnit (std::PATH & file)
Definition at line 5 of file Lexer.cpp.
{
    // Reset user paths
    usrpaths.atElement = 0;
    usrpaths <<= file.pathName();
    usrpaths <<= workingDirectory->relName();
    // Parse the source file.
    parseFile(file);
    // Check if ill-formed
    if (illformed)
    {
        debugInformation.showLinesAndColoumns = false;
        Log(file.relName(), "ETranslation unit failed to compile.", nullptr);
        return;
    }
}
References BBP::std::Stack< K >::atElement, debugInformation, illformed, Log(), parseFile(), BBP::std::PATH::pathName(), BBP::std::PATH::relName(), BBP::std::Lexer::lex_debugInfo::showLinesAndColoumns, usrpaths, and BBP::std::workingDirectory.
bool BBP::std::Lexer::lex_context::tryParseNumerical (std::index_t from, std::index_t to, bool & isFloat, float & fresult, int & iresult)
Definition at line 469 of file Lexer.cpp.
{
    // Define some variables to idk, figure it out goddamn
    std::byte base;
    std::string_element firstCharacter = std::read(&data, from);
    bool hasPrefix = (isNumericalBase(firstCharacter, base) != 0);
    // If base is 0, it means the first character is not a valid numerical character.
    if (base == 0 && !isDecimalNumeral(firstCharacter))
        return false;
    else if (base == 0)
        base = 10;
    // This is used for the float
    float divideBy = 1;
    // Loop over each character now
    for (std::index_t idx = from + hasPrefix; idx < to; idx++)
    {
        // Fetch a character
        std::string_element c = std::read(&data, idx);
        // If the character is a dot, switch over to float mode.
        if (c == '.' && !isFloat)
        {
            isFloat = true;
            continue;
        }
        else if (c == '.')
            return false; // Since isFloat must be true, a return value of zero still gives a unique return value.
        // TODO: Explain wtf that means.
        // If character is not numerical number based on base type, return
        std::byte number = 0;
        switch (base)
        {
        case 2:
            number = isBinaryNumeral(c);
            break;
        case 8:
            number = isOctalNumeral(c);
            break;
        case 10:
            number = isDecimalNumeral(c);
            break;
        case 16:
            number = isHexadecimalNumeral(c);
            break;
        }
        // If not a number, return false.
        if (number == 0)
            return false;
        // If not a float, increment both accordingly
        if (!isFloat)
        {
            iresult = (iresult * base) + (number - 10);
            fresult = (fresult * base) + (number - 10);
            divideBy *= base;
        }
        else
        {
            fresult += (number - 10) / divideBy;
            divideBy *= base;
        }
    }
    // Done
    return true;
}
References BBP::std::read(), and BBP::Locale::Japanese::to.
Field Documentation
bool BBP::std::Lexer::lex_context::abort
Definition at line 147 of file Lex.h.
std::static_string<128> BBP::std::Lexer::lex_context::activeFile
Definition at line 117 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile().
std::index_t BBP::std::Lexer::lex_context::atPosition
Definition at line 124 of file Lex.h.
Referenced by BBP::esa::esaProcessor::ExpectDelimiters(), and BBP::esa::esaProcessor::includeFile().
char BBP::std::Lexer::lex_context::commentDepth
Definition at line 140 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile().
std::PAGE<string_element> BBP::std::Lexer::lex_context::data
Definition at line 120 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile(), and BBP::esa::esaProcessor::saveIdentifier().
std::size_t BBP::std::Lexer::lex_context::dataSize
Definition at line 121 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile().
lex_debugInfo BBP::std::Lexer::lex_context::debugInformation
Definition at line 144 of file Lex.h.
Referenced by BBP::esa::esaProcessor::ExpectDelimiters(), BBP::esa::esaProcessor::includeFile(), BBP::esa::INSTRUCTION(), and translateUnit().
bool BBP::std::Lexer::lex_context::illformed
Definition at line 148 of file Lex.h.
Referenced by translateUnit().
bool BBP::std::Lexer::lex_context::inhibitSpecialFunctions
Definition at line 133 of file Lex.h.
std::STATIC_PAGE<lex_keyword, 256> BBP::std::Lexer::lex_context::keywords
Definition at line 127 of file Lex.h.
std::Stack<lex_keyword> BBP::std::Lexer::lex_context::keywordStack
Definition at line 130 of file Lex.h.
Referenced by BBP::esa::esaProcessor::esaProcessor(), and BBP::esa::esaProcessor::ExpectDelimiters().
index_t BBP::std::Lexer::lex_context::lastWhiteSpace
Definition at line 138 of file Lex.h.
char BBP::std::Lexer::lex_context::literalDepth
Definition at line 141 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile().
std::conststring(* BBP::std::Lexer::lex_context::onNumericalLiteral) (numerical_t numerical, bool isFloat)
Definition at line 135 of file Lex.h.
std::conststring(* BBP::std::Lexer::lex_context::onUnkown) (index_t, index_t)
Definition at line 134 of file Lex.h.
std::static_string<1024> BBP::std::Lexer::lex_context::syspathPage
Definition at line 152 of file Lex.h.
std::Stack<std::string_element> BBP::std::Lexer::lex_context::syspaths
Definition at line 154 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile().
std::static_string<1024> BBP::std::Lexer::lex_context::usrpathPage
Definition at line 151 of file Lex.h.
std::Stack<std::string_element> BBP::std::Lexer::lex_context::usrpaths
Definition at line 153 of file Lex.h.
Referenced by BBP::esa::esaProcessor::includeFile(), and translateUnit().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.