.TH "BBP::std::Driver" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::Driver
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdrawWindow\fP (\fBwindow\fP *)"
.br
.ti -1c
.RI "int \fBinitializeGraphics\fP (\fBwindow\fP *, int width, int height)"
.br
.ti -1c
.RI "void \fBdestructGraphics\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BBP::std::Driver::destructGraphics ()"

.SS "void BBP::std::Driver::drawWindow (\fBwindow\fP *)"

.SS "int BBP::std::Driver::initializeGraphics (\fBwindow\fP *, int width, int height)"

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
