.TH "BBP::std::Executable" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::Executable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Executable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBexecutable_main\fP \fBentry\fP"
.br
.ti -1c
.RI "\fBstd::conststring\fP \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Executable\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBexecutable_main\fP BBP::std::Executable::entry"

.PP
Definition at line 30 of file Executable\&.h\&.
.SS "\fBstd::conststring\fP BBP::std::Executable::name"

.PP
Definition at line 31 of file Executable\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
