.TH "BBP::std::FileNode" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::FileNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileSys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileNode\fP ()"
.br
.ti -1c
.RI "\fBFileNode\fP (\fBstd::ResourceManager\fP *res, \fBstd::conststring\fP path)"
.br
.ti -1c
.RI "\fBFileNode\fP (\fBstd::Stack\fP< \fBstd::string_element\fP > &data, \fBstd::conststring\fP path)"
.br
.ti -1c
.RI "\fBFileNode\fP (\fBstd::ResourceManager\fP *res, \fBstd::VOLUME\fP *v, \fBstd::conststring\fP path)"
.br
.ti -1c
.RI "\fBFileNode\fP (\fBstd::ResourceManager\fP *res, \fBstd::size_t\fP size, \fBstd::VOLUME\fP *v, \fBstd::conststring\fP path)"
.br
.ti -1c
.RI "\fBFileNode\fP (\fBstd::ResourceManager\fP *res, \fBstd::size_t\fP size, \fBstd::PATH\fP &path)"
.br
.ti -1c
.RI "\fBFileNode\fP (\fBstd::Stack\fP< \fBstd::string_element\fP > &data, \fBstd::VOLUME\fP *v, \fBstd::conststring\fP path)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::ResourceManager\fP * \fBallocator\fP"
.br
.ti -1c
.RI "\fBstd::Stack\fP< \fBstd::string_element\fP > \fBfileData\fP"
.br
.ti -1c
.RI "\fBstd::PATH\fP \fBfilePath\fP"
.br
.ti -1c
.RI "\fBstd::hash_t\fP \fBfilePathHash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 159 of file FileSys\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BBP::std::FileNode::FileNode ()\fC [inline]\fP"

.PP
Definition at line 169 of file FileSys\&.h\&.
.PP
.nf
170                 : allocator(nullptr),
171                 fileData((std::PAGE<std::string_element> *)nullptr, 0),
172                 filePath(),
173                 filePathHash(0)
174             {}
.fi
.SS "BBP::std::FileNode::FileNode (\fBstd::ResourceManager\fP * res, \fBstd::conststring\fP path)\fC [inline]\fP"

.PP
Definition at line 176 of file FileSys\&.h\&.
.PP
.nf
177                 : allocator(res),
178                 fileData((std::PAGE<std::string_element> *)nullptr),
179                 filePath(path),
180                 filePathHash(0)
181             {
182                 filePath\&.makeAbsolutePath(std::workingDirectory);
183                 filePathHash = std::strhsh(filePath\&.relName());
184             }
.fi
.PP
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory\&.
.SS "BBP::std::FileNode::FileNode (\fBstd::Stack\fP< \fBstd::string_element\fP > & data, \fBstd::conststring\fP path)\fC [inline]\fP"

.PP
Definition at line 186 of file FileSys\&.h\&.
.PP
.nf
187                 : allocator(nullptr),
188                 fileData(data),
189                 filePath(path),
190                 filePathHash(0)
191             {
192                 filePath\&.makeAbsolutePath(std::workingDirectory);
193                 filePathHash = std::strhsh(filePath\&.relName());
194             }
.fi
.PP
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory\&.
.SS "BBP::std::FileNode::FileNode (\fBstd::ResourceManager\fP * res, \fBstd::VOLUME\fP * v, \fBstd::conststring\fP path)\fC [inline]\fP"

.PP
Definition at line 196 of file FileSys\&.h\&.
.PP
.nf
197                 : allocator(res),
198                 fileData((std::PAGE<std::string_element> *)nullptr, 0),
199                 filePath(v, path),
200                 filePathHash(0)
201             {
202                 filePath\&.makeAbsolutePath(std::workingDirectory);
203                 filePathHash = std::strhsh(filePath\&.relName());
204             }
.fi
.PP
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory\&.
.SS "BBP::std::FileNode::FileNode (\fBstd::ResourceManager\fP * res, \fBstd::size_t\fP size, \fBstd::VOLUME\fP * v, \fBstd::conststring\fP path)\fC [inline]\fP"

.PP
Definition at line 206 of file FileSys\&.h\&.
.PP
.nf
207                 : allocator(res),
208                 fileData(
209                     (std::PAGE<std::string_element> *)res->add_object(new std::PAGE<std::string_element>(size, (std::string_element *)res->calloc(size, sizeof(std::string_element)))),
210                     size),
211                 filePath(v, path),
212                 filePathHash(0)
213             {
214                 filePath\&.makeAbsolutePath(std::workingDirectory);
215                 filePathHash = std::strhsh(filePath\&.relName());
216             }
.fi
.PP
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory\&.
.SS "BBP::std::FileNode::FileNode (\fBstd::ResourceManager\fP * res, \fBstd::size_t\fP size, \fBstd::PATH\fP & path)\fC [inline]\fP"

.PP
Definition at line 218 of file FileSys\&.h\&.
.PP
.nf
219                 : allocator(res),
220                 fileData(
221                     (std::PAGE<std::string_element> *)res->add_object(new std::PAGE<std::string_element>(size, (std::string_element *)res->calloc(size, sizeof(std::string_element)))),
222                     size),
223                 filePath(path),
224                 filePathHash(0)
225             {
226                 filePath\&.makeAbsolutePath(std::workingDirectory);
227                 filePathHash = std::strhsh(filePath\&.relName());
228             }
.fi
.PP
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory\&.
.SS "BBP::std::FileNode::FileNode (\fBstd::Stack\fP< \fBstd::string_element\fP > & data, \fBstd::VOLUME\fP * v, \fBstd::conststring\fP path)\fC [inline]\fP"

.PP
Definition at line 232 of file FileSys\&.h\&.
.PP
.nf
233                 : allocator(nullptr),
234                 fileData(data),
235                 filePath(v, path),
236                 filePathHash(0)
237             {
238                 filePath\&.makeAbsolutePath(std::workingDirectory);
239                 filePathHash = std::strhsh(filePath\&.relName());
240             }
.fi
.PP
References filePath, filePathHash, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), BBP::std::strhsh(), and BBP::std::workingDirectory\&.
.SH "Field Documentation"
.PP 
.SS "\fBstd::ResourceManager\fP* BBP::std::FileNode::allocator"

.PP
Definition at line 162 of file FileSys\&.h\&.
.SS "\fBstd::Stack\fP<\fBstd::string_element\fP> BBP::std::FileNode::fileData"

.PP
Definition at line 163 of file FileSys\&.h\&.
.PP
Referenced by BBP::std::fprintf(), and BBP::shell()\&.
.SS "\fBstd::PATH\fP BBP::std::FileNode::filePath"

.PP
Definition at line 166 of file FileSys\&.h\&.
.PP
Referenced by FileNode()\&.
.SS "\fBstd::hash_t\fP BBP::std::FileNode::filePathHash"

.PP
Definition at line 167 of file FileSys\&.h\&.
.PP
Referenced by BBP::std::FILE::checkIfIsOpen(), FileNode(), and BBP::std::FILE::findClosedFile()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
