.TH "BBP::std::Lexer" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::Lexer
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBlex_context\fP"
.br
.ti -1c
.RI "struct \fBlex_debugInfo\fP"
.br
.ti -1c
.RI "struct \fBlex_keyword\fP"
.br
.ti -1c
.RI "struct \fBlex_thing\fP"
.br
.ti -1c
.RI "union \fBnumerical_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBuint32_t\fP \fBlex_type\fP"
.br
.ti -1c
.RI "typedef \fBuint32_t\fP \fBlex_specialty\fP"
.br
.ti -1c
.RI "typedef \fBuint32_t\fP \fBlex_keywordhandle\fP"
.br
.ti -1c
.RI "typedef \fBstd::conststring\fP(* \fBlex_action\fP) (\fBlex_context\fP *, \fBstd::index_t\fP, \fBlex_keywordhandle\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBstd::conststring\fP(* BBP::std::Lexer::lex_action) (\fBlex_context\fP *, \fBstd::index_t\fP, \fBlex_keywordhandle\fP)"

.PP
Definition at line 25 of file Lex\&.h\&.
.SS "typedef \fBuint32_t\fP \fBBBP::std::Lexer::lex_keywordhandle\fP"

.PP
Definition at line 22 of file Lex\&.h\&.
.SS "typedef \fBuint32_t\fP \fBBBP::std::Lexer::lex_specialty\fP"

.PP
Definition at line 19 of file Lex\&.h\&.
.SS "typedef \fBuint32_t\fP \fBBBP::std::Lexer::lex_type\fP"

.PP
Definition at line 14 of file Lex\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
