BBP::std::FILE
NAME
BBP::std::FILE
SYNOPSIS
#include <FileSys.h>
Public Member Functions
FILE ()
FILE (std::PATH)
FILE (std::conststring)
FILE (std::Stack< std::string_element > &data, std::conststring path)
FileNode * data ()
std::Stack< std::string_element > & b ()
bool is_open ()
bool on_disk ()
void close ()
FILE & write (std::conststring str)
FILE & write (std::c_string &str)
FILE & write (std::string &str)
FILE & finish (std::conststring str)
FILE & finish (std::c_string &str)
FILE & finish (std::string &str)
FILE & finish ()
bool doesFileExistOnDisk (std::PATH &)
std::size_t getFileSizeFromDisk (std::PATH &)
std::size_t readFileFromDisk (std::FileNode *, std::PATH &)
void writeFileToDisk (std::PATH &)
void writeFileToDisk ()
Private Member Functions
std::index_t checkIfIsOpen (std::conststring path)
std::index_t findClosedFile ()
void getINodeIndex (std::PATH &)
Private Attributes
bool _is_on_disk = false
bool _dealloc_page = false
bool _loaded_intomem = false
bool _unload_inode = false
noderef_t node
Detailed Description
Definition at line 100 of file FileSys.h.
Constructor & Destructor Documentation
BBP::std::FILE::FILE ()
Definition at line 4 of file File.cpp.
    : node(max_open_files)
{
    // Empty file, no nothing.
}
BBP::std::FILE::FILE (std::PATH path)
Definition at line 55 of file File.cpp.
{
    getINodeIndex(path);
    // Check if file exists on disk
    bool exists = doesFileExistOnDisk(path);
    // If file does not exist on disk or in memory, throw error
    if (!is_open() && !on_disk())
        throw std::exception("ERR_FILE_NOEXIST", ENOENT);
    // Only read from disk if file exists on disk, but is also not already in memory
    if (exists && !is_open())
    {
        // Read file Size
        std::size_t fileSize = getFileSizeFromDisk(path);
        // Create new node
        std::fileTable.data[this->node] = std::FileNode(std::activemem, fileSize + 1, path);
        _dealloc_page = true;
        _unload_inode = true;
        // Read data from file
        readFileFromDisk(&std::fileTable.data[this->node], path);
    }
    std::fileTable.data[this->node].fileData.page->prevPage = nullptr;
    std::fileTable.data[this->node].fileData.page->nextPage = nullptr;
}
References BBP::std::activemem, ENOENT, BBP::std::exception(), and BBP::std::fileTable.
BBP::std::FILE::FILE (std::conststring _path)
Definition at line 87 of file File.cpp.
    : FILE(std::PATH(_path))
{
}
BBP::std::FILE::FILE (std::Stack< std::string_element > & data, std::conststring path)
Definition at line 10 of file File.cpp.
{
    // Get INode info
    std::PATH p(path);
    getINodeIndex(p);
    // Check if it already exists
    _unload_inode = !is_open();
#ifndef BBP_STDLIB_FILESYS_OVERWRITEEXISTINGFILES
    // If BBP_STDLIB_FILESYS_OVERWRITEEXISTINGFILES is set, check if file already exists and throw exception if it does
    if (doesFileExistOnDisk(_path))
        throw std::exception("FILE_ALREADY_EXISTS", EEXIST);
#endif
    // Create file node at corresponding INode
    std::fileTable.data[this->node] = BBP::std::FileNode(data, BBP::std::primaryVolume, path);
}
References EEXIST, BBP::std::exception(), BBP::std::fileTable, and BBP::std::primaryVolume.
Member Function Documentation
BBP::std::Stack< BBP::std::string_element > & BBP::std::FILE::b ()
Definition at line 168 of file File.cpp.
{
    return data()->fileData;
}
Referenced by BBP::badapple_main(), BBP::std::R2D::GetFontFromFile(), BBP::std::Lexer::lex_context::parseFile(), and BBP::smile_main().
BBP::std::index_t BBP::std::FILE::checkIfIsOpen (std::conststring path) [private]
Definition at line 92 of file File.cpp.
{
    // Get path hash
    std::hash_t hash = std::strhsh(path);
    // Fetch each table hash
    for (std::index_t idx = 0; idx < std::fileTable.dataSize; idx++)
    {
        // Get reference to node
        std::FileNode *node = &__UNSAFE__(read)(&std::fileTable, idx);
        // If entry is nullptr, skip
        if (node == nullptr)
            continue;
        // Get hash
        std::hash_t file_hash = node->filePathHash;
        if (hash == file_hash)
            return idx;
    }
    // Nothing found, return false.
    return std::fileTable.dataSize;
}
References __UNSAFE__, BBP::std::FileNode::filePathHash, BBP::std::fileTable, BBP::Locale::Japanese::hash, BBP::std::read(), and BBP::std::strhsh().
void BBP::std::FILE::close ()
Definition at line 146 of file File.cpp.
{
    // Deallocate the page if marked allocated
    if (_dealloc_page)
    {
        BBP::std::activemem->free(data()->fileData.page->data);
        BBP::std::activemem->_delete(data()->fileData.page);
    }
    if (_unload_inode)
        BBP::std::fileTable.data[this->node].fileData.page = nullptr;
    this->node = BBP::std::fileTable.dataSize;
}
References BBP::std::ResourceManager::_delete(), BBP::std::activemem, BBP::std::fileTable, and BBP::std::ResourceManager::free().
Referenced by BBP::badapple_main(), BBP::std::R2D::GetFontFromFile(), BBP::esa::esaProcessor::includeFile(), BBP::std::Lexer::lex_context::parseFile(), and BBP::smile_main().
BBP::std::FileNode * BBP::std::FILE::data ()
Definition at line 141 of file File.cpp.
{
    return &std::read(&std::fileTable, this->node);
}
References BBP::std::fileTable, and BBP::std::read().
Referenced by BBP::std::fprintf(), and BBP::shell().
bool BBP::std::FILE::doesFileExistOnDisk (std::PATH &)
BBP::std::index_t BBP::std::FILE::findClosedFile () [private]
Definition at line 118 of file File.cpp.
{
    // Fetch each table hash
    for (std::index_t idx = 0; idx < std::fileTable.dataSize; idx++)
    {
        // Get reference to node
        std::FileNode *node = &__UNSAFE__(read)(&std::fileTable, idx);
        // If entry is nullptr, skip
        if (node == nullptr)
            return idx;
        // Get hash
        std::hash_t file_hash = node->filePathHash;
        if (file_hash == 0)
            return idx;
    }
    // Nothing found, return false.
    return std::fileTable.dataSize;
}
References __UNSAFE__, BBP::std::FileNode::filePathHash, BBP::std::fileTable, and BBP::std::read().
BBP::std::FILE & BBP::std::FILE::finish ()
Definition at line 209 of file File.cpp.
{
    b() <<= std::endl;
    return *this;
}
References BBP::std::endl.
BBP::std::FILE & BBP::std::FILE::finish (std::c_string & str)
Definition at line 197 of file File.cpp.
{
    b() <<= str;
    return *this;
}
BBP::std::FILE & BBP::std::FILE::finish (std::conststring str)
Definition at line 191 of file File.cpp.
{
    b() <<= str;
    return *this;
}
BBP::std::FILE & BBP::std::FILE::finish (std::string & str)
Definition at line 203 of file File.cpp.
{
    b() <<= str;
    return *this;
}
std::size_t BBP::std::FILE::getFileSizeFromDisk (std::PATH &)
void BBP::std::FILE::getINodeIndex (std::PATH & path) [private]
Definition at line 29 of file File.cpp.
{
    // Resolve names
    path.makeAbsolutePath(std::workingDirectory);
    // Check if file is open
    BBP::std::index_t idx = checkIfIsOpen(path.relName());
    if (idx == std::fileTable.dataSize)
    {
        // Look for next empty file
        std::index_t emptyIndex = findClosedFile();
        // Check if there are empty files
        if (emptyIndex == std::fileTable.dataSize)
            throw std::exception("ERR_NO_EMPTYFILENODE", ENFILE);
        // Save node index
        this->node = emptyIndex;
    }
    else
    {
        this->node = idx;
    }
}
References ENFILE, BBP::std::exception(), BBP::std::fileTable, BBP::std::PATH::makeAbsolutePath(), BBP::std::PATH::relName(), and BBP::std::workingDirectory.
bool BBP::std::FILE::is_open ()
Definition at line 161 of file File.cpp.
{
    if (data() == nullptr)
        return false;
    return BBP::std::fileTable.data[this->node].fileData.page != nullptr;
}
References BBP::std::fileTable.
Referenced by BBP::std::fprintf().
bool BBP::std::FILE::on_disk () [inline]
Definition at line 115 of file FileSys.h.
{ return _is_on_disk; }
References _is_on_disk.
std::size_t BBP::std::FILE::readFileFromDisk (std::FileNode *, std::PATH &)
BBP::std::FILE & BBP::std::FILE::write (std::c_string & str)
Definition at line 179 of file File.cpp.
{
    b() << str;
    return *this;
}
BBP::std::FILE & BBP::std::FILE::write (std::conststring str)
Definition at line 173 of file File.cpp.
{
    b() << str;
    return *this;
}
BBP::std::FILE & BBP::std::FILE::write (std::string & str)
Definition at line 185 of file File.cpp.
{
    b() << str;
    return *this;
}
void BBP::std::FILE::writeFileToDisk ()
void BBP::std::FILE::writeFileToDisk (std::PATH &)
Field Documentation
bool BBP::std::FILE::_dealloc_page = false [private]
Definition at line 141 of file FileSys.h.
bool BBP::std::FILE::_is_on_disk = false [private]
Definition at line 140 of file FileSys.h.
Referenced by on_disk().
bool BBP::std::FILE::_loaded_intomem = false [private]
Definition at line 142 of file FileSys.h.
bool BBP::std::FILE::_unload_inode = false [private]
Definition at line 143 of file FileSys.h.
noderef_t BBP::std::FILE::node [private]
Definition at line 145 of file FileSys.h.
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.