BBP::std
NAME
BBP::std
SYNOPSIS
Namespaces
 Driver
 ELF
 Lexer
 R2D
 R3D
Data Structures
struct AbstractGCEntry
struct colour
class DIRECTORY
struct DirectoryNode
struct Executable
struct executableFrame
class FILE
struct FileNode
class GCEntry
struct PAGE
class PATH
class ResourceManager
struct SIGNAL
class Stack
struct STATIC_PAGE
class Terminal
class VOLUME
struct window
Typedefs
typedef int errno_t
typedef int(* executable_main) (int argc, char **argv)
typedef uint8_t PID_t
typedef std::index_t noderef_t
typedef word RGBA_t
typedef byte chan_t
typedef word pos_t
typedef word mask_t
typedef int signal_t
typedef uint32_t word
typedef int32_t sword
typedef uint64_t dword
typedef uint16_t halfword
typedef uint8_t byte
typedef uint8_t nibble
typedef uint8_t crumb
typedef word offset_t
typedef sword s_offset_t
typedef word address_t
typedef word index_t
typedef word size_t
typedef byte mem_t
typedef char string_element
typedef unsigned char ustring_element
typedef PAGE< string_element > string
template<int N> using static_string = STATIC_PAGE< string_element, N >
typedef string_element * c_string
typedef ustring_element * uc_string
typedef uint32_t hash_t
typedef uint32_t time_t
Functions
void swap (int *a, int *b)
float absolute (float x)
int iPartOfNumber (float x)
int roundNumber (float x)
float fPartOfNumber (float x)
float rfPartOfNumber (float x)
except exception (const char *msg, errno_t _errno)
PID_t getNextAvailablePID ()
PID_t spawnExecutable (executable_main, std::string &)
void execute (executable_main, int argc, char **argv)
void exit ()
template<typename... Args> void fprintf (BBP::std::FILE &file, std::conststring format, Args... args)
template<typename T > void write (PAGE< T > *page, T &data, index_t index)
template<typename T > void write_r (PAGE< T > *page, mem_t &data, index_t index)
template<typename T > void write_a (PAGE< T > *page, T *data, index_t index, size_t amount)
template<typename T > void write_ar (PAGE< T > *page, mem_t *data, index_t index, size_t amount)
template<typename T > void __UNSAFE__() write (PAGE< T > *page, T &data, index_t index)
template<typename T > void __UNSAFE__() write_a (PAGE< T > *page, T *data, index_t index, size_t amount)
template<typename T > void __UNSAFE__() write_r (PAGE< T > *page, mem_t &data, index_t index)
template<typename T > T & read (PAGE< T > *page, index_t index)
template<typename T > mem_t & read_r (PAGE< T > *page, index_t index)
template<typename T > T * read_a (PAGE< T > *page, index_t index)
template<typename T > mem_t * read_ar (PAGE< T > *page, index_t index)
template<typename T > T &__UNSAFE__() read (PAGE< T > *page, index_t index)
template<typename T > mem_t &__UNSAFE__() read_r (PAGE< T > *page, index_t index)
template<typename T > T *__UNSAFE__() read_a (PAGE< T > *page, index_t index)
template<typename T > mem_t *__UNSAFE__() read_ar (PAGE< T > *page, index_t index)
template<typename T > std::PAGE< T > & last (std::PAGE< T > &)
template<typename T > std::PAGE< T > & first (std::PAGE< T > &)
template<typename T > size_t seqlen (PAGE< T > &page)
template<typename T > size_t seqlen_r (PAGE< T > &page)
template<typename T > size_t __UNSAFE__() seqlen (PAGE< T > &page)
template<typename T > size_t __UNSAFE__() seqlen_r (PAGE< T > &page)
template<typename T > void memcpy (PAGE< T > &src, PAGE< T > &dst, size_t amount)
template<typename T > void memcpy (PAGE< T > &src, PAGE< T > &dst)
template<typename T > bool memcmp (PAGE< T > &src, PAGE< T > &dst)
void ext_free (void *)
void * ext_malloc (std::size_t)
void * ext_calloc (std::size_t, std::size_t)
uint32_t decimals (uint32_t value)
uint8_t getDecimal (uint32_t value, uint32_t position)
void print_to_terminal (std::Stack< std::string_element > *stack)
int sprintf (std::c_string buffer, std::conststring format,...)
int printf (std::conststring format,...)
int putf (std::Stack< std::string_element > &stream, std::conststring format,...)
void captureInput ()
void stopCapturingInput ()
char getC ()
void getLine ()
void strcpy (string *dst, conststring src)
void operator<= (string &dst, conststring src)
void strcpy (string *dst, c_string src)
void operator<= (string &dst, c_string src)
void strcpy (c_string dst, conststring src)
bool strcmp (string *sta, conststring stb)
bool strcmp (string *sta, c_string stb)
size_t strlen (conststring str)
size_t strlen (c_string str)
size_t strlen (string &str)
size_t strlen (string str, offset_t offset)
hash_t strhsh (string &str)
hash_t strhsh (c_string str)
hash_t strhsh (conststring str)
constexpr std::hash_t operator''_hash (const char *str, long unsigned int hehe)
void strhsh (hash_t &, word &, string_element &)
size_t __UNSAFE__() strlen (string str)
std::Stack< std::string_element > & operator<<= (std::Stack< std::string_element > &stack, std::conststring str)
std::Stack< std::string_element > & operator<<= (std::Stack< std::string_element > &stack, std::c_string str)
std::Stack< std::string_element > & operator<<= (std::Stack< std::string_element > &stack, std::string &str)
std::Stack< std::string_element > & operator<<= (std::Stack< std::string_element > &stack, char c)
std::Stack< std::string_element > & operator<= (std::Stack< std::string_element > &stack, int value)
std::Stack< std::string_element > & operator<< (std::Stack< std::string_element > &stack, std::conststring str)
std::Stack< std::string_element > & operator<< (std::Stack< std::string_element > &stack, std::c_string str)
std::Stack< std::string_element > & operator<< (std::Stack< std::string_element > &stack, std::string &str)
std::Stack< std::string_element > & operator< (std::Stack< std::string_element > &stack, int value)
std::Stack< std::string_element > & operator>>= (std::Stack< std::string_element > &stack, std::c_string *str)
std::Stack< std::string_element > & operator>>= (std::Stack< std::string_element > &stack, std::string *str)
std::Stack< std::string_element > & operator>> (std::Stack< std::string_element > &lh, std::Stack< std::string_element > &rh)
std::Stack< std::string_element > & operator<< (std::Stack< std::string_element > &lh, std::Stack< std::string_element > &rh)
std::Stack< std::string_element > & operator>>= (std::Stack< std::string_element > &lh, std::Stack< std::string_element > &rh)
std::Stack< std::string_element > & operator<<= (std::Stack< std::string_element > &lh, std::Stack< std::string_element > &rh)
std::Stack< std::string_element > & operator> (std::Stack< std::string_element > &stack, std::c_string *str)
std::Stack< std::string_element > & operator> (std::Stack< std::string_element > &stack, std::string *str)
time_t millis ()
void delay (time_t)
time_t now ()
void initClock ()
Variables
const typedef string_element * conststring
const typedef ustring_element * uconststring
ResourceManager vmem
STATIC_PAGE< executableFrame, 12 > procFrames
Stack< executableFrame > Processes
PID_t activeExecutable = 0
const Executable executables [] = {{shell_main, '/proc/shell'}}
static constexpr std::size_t max_open_files = 32
static constexpr std::size_t max_path_length = 128
std::STATIC_PAGE< FileNode, max_open_files > fileTable
PATH * workingDirectory
VOLUME * primaryVolume
bool gINIT
constexpr word max_page_elements = 20000
constexpr word max_page_static_size = 20000
constexpr word max_page_pointer_size = max_page_elements
constexpr word max_page_sequence_length = 64
constexpr word max_lpage_static_size = 0x2000
std::window kernelDisplay
static constexpr size_t max_objects = 1000
static constexpr size_t max_allocations = 1000
ResourceManager progmem
ResourceManager * activemem
constexpr signal_t SIGINV = 1
constexpr signal_t SIGTERM = 2
constexpr signal_t SIGSEGV = 3
constexpr signal_t SIGINT = 4
constexpr signal_t SIGILL = 5
constexpr signal_t SIGABRT = 6
constexpr signal_t SIGFPE = 7
constexpr signal_t SIGSHTDN = 8
constexpr signal_t SIGADJ = 150
static_string< 509 > str_STDOUT
static_string< 509 > str_STDIN
static_string< 509 > str_STDERR
std::Stack< std::string_element > STDOUT
std::Stack< std::string_element > STDIN
std::Stack< std::string_element > STDERR
volatile bool _waitforline
volatile bool _echoStuffToTerminal
const size_t max_string_length = 0xFFFF
const std::conststring space = ' '
const std::conststring endl = '\n'
Typedef Documentation
typedef word BBP::std::address_t
Definition at line 45 of file stddef.h.
typedef uint8_t BBP::std::byte
Definition at line 30 of file stddef.h.
typedef string_element* BBP::std::c_string
Definition at line 25 of file Strings.h.
typedef byte BBP::std::chan_t
Definition at line 19 of file Graphics.h.
typedef uint8_t BBP::std::crumb
Definition at line 36 of file stddef.h.
typedef uint64_t BBP::std::dword
Definition at line 23 of file stddef.h.
typedef int BBP::std::errno_t
Definition at line 10 of file errno.h.
typedef int(* BBP::std::executable_main) (int argc, char **argv)
Definition at line 22 of file Executable.h.
typedef uint16_t BBP::std::halfword
Definition at line 27 of file stddef.h.
typedef uint32_t BBP::std::hash_t
Definition at line 36 of file Strings.h.
typedef word BBP::std::index_t
Definition at line 48 of file stddef.h.
typedef word BBP::std::mask_t
Definition at line 25 of file Graphics.h.
typedef byte BBP::std::mem_t
Definition at line 54 of file stddef.h.
typedef uint8_t BBP::std::nibble
Definition at line 33 of file stddef.h.
typedef std::index_t BBP::std::noderef_t
Definition at line 32 of file FileSys.h.
typedef word BBP::std::offset_t
Definition at line 39 of file stddef.h.
typedef uint8_t BBP::std::PID_t
Definition at line 25 of file Executable.h.
typedef word BBP::std::pos_t
Definition at line 22 of file Graphics.h.
typedef word BBP::std::RGBA_t
Definition at line 16 of file Graphics.h.
typedef sword BBP::std::s_offset_t
Definition at line 42 of file stddef.h.
typedef int BBP::std::signal_t
Definition at line 15 of file Signal.h.
typedef word BBP::std::size_t
Definition at line 51 of file stddef.h.
template<int N> using BBP::std::static_string = typedef STATIC_PAGE<string_element, N>
Definition at line 22 of file Strings.h.
typedef PAGE<string_element> BBP::std::string
Definition at line 18 of file Strings.h.
typedef char BBP::std::string_element
Definition at line 14 of file Strings.h.
typedef int32_t BBP::std::sword
Definition at line 18 of file stddef.h.
typedef uint32_t BBP::std::time_t
Definition at line 12 of file Time.h.
typedef ustring_element* BBP::std::uc_string
Definition at line 26 of file Strings.h.
typedef unsigned char BBP::std::ustring_element
Definition at line 15 of file Strings.h.
typedef uint32_t BBP::std::word
Definition at line 15 of file stddef.h.
Function Documentation
float BBP::std::absolute (float x)
Definition at line 294 of file R2D.cpp.
        {
            if (x < 0) return -x;
            else return x;
        }
Referenced by BBP::std::R2D::Line().
void BBP::std::captureInput ()
BBP::uint32_t BBP::std::decimals (uint32_t value)
Definition at line 3 of file stdint.cpp.
{
    uint32_t decim = 1;
    for (uint32_t val = value; val >= 10; val /= 10)
        decim++;
    return decim;
}
Referenced by operator<().
void BBP::std::delay (time_t)
Referenced by BBP::badapple_main().
BBP::std::except BBP::std::exception (const char * msg, errno_t _errno)
Definition at line 7 of file Except.cpp.
{
    // set error number
    BBP::std::__errno = _errno;
    // Stream msg into STDERR
    BBP::std::STDERR << "\[0;31mError: " << msg << "\[0;37m" <<= std::endl;
    except exc = {_errno};
    return exc;
}
References endl, and STDERR.
Referenced by BBP::std::ResourceManager::add_alloc(), BBP::std::ResourceManager::add_object(), BBP::esa::esaProcessor::addReservedIdentifier(), BBP::std::ELF::SectionBuilder::Append(), BBP::std::ResourceManager::calloc(), BBP::std::ELF::ELFBuilder::ELFBuilder(), BBP::esa::esaProcessor::emitProcedure(), BBP::esa::BinaryApplication::emitSymbol(), execute(), BBP::std::ELF::SectionBuilder::Extend(), BBP::std::FILE::FILE(), fprintf(), BBP::std::FILE::getINodeIndex(), BBP::std::PATH::makeAbsolutePath(), BBP::std::ResourceManager::malloc(), BBP::std::Stack< BBP::std::DIRECTORY >::operator+=(), BBP::std::Stack< BBP::std::DIRECTORY >::operator<<(), operator<<(), BBP::std::Stack< BBP::std::DIRECTORY >::operator>>(), operator>>=(), BBP::std::ELF::ELFBuilder::renameSymbol(), and strlen().
void BBP::std::execute (std::executable_main mainFunc, int argc, char ** argv)
Definition at line 14 of file Executable.cpp.
{
    // Find a new PID
    PID_t procPID = getNextAvailablePID();
    // Create new process stack
    executableFrame procFrame = std::read(&procFrames, procPID);
    // Set pid
    procFrame.PID = procPID;
    // Create process memory
    procFrame.pmem = BBP::std::progmem.add_object(new std::ResourceManager());
    // Swap that in for the old activemem
    BBP::std::ResourceManager *oldActiveMem = BBP::std::activemem;
    BBP::std::activemem = procFrame.pmem;
    // Store old active executable
    PID_t oldActiveExecutable = std::activeExecutable;
    // Set active executable to this one
    std::activeExecutable = procPID;
    // Run main function in try block
    try
    {
        // Set 'Is executing' flag to true
        procFrame.isExecuting = true;
        // Acually execute the program
        BBP::std::__errno = mainFunc(argc, argv);
        // Reset the 'is executing' flag
        procFrame.isExecuting = false;
        // Reset terminal
        BBP::std::kernelDisplay.fontSize = 1;
        BBP::std::kernelDisplay.fontSpacing = 6;
        BBP::std::R2D::fill(&BBP::std::kernelDisplay, 0xFFFFFFFF);
    }
    catch (const std::SIGNAL &signal)
    {
        switch (signal._sig)
        {
        case BBP::std::SIGSHTDN:
            // System shutdown, rethrow signal, but before doing that, reset the state of this program
            
            // Garbage collection
            procFrame.pmem->deleteAll();
            procFrame.pmem->freeAll();
            // Delete garbage collector
            BBP::std::progmem._delete(procFrame.pmem);
            // Restore active mem and active proc
            BBP::std::activemem = oldActiveMem;
            BBP::std::activeExecutable = oldActiveExecutable;
            throw;
        default:
            BBP::std::printf("[bbp] Program terminated after receiving signal %u", signal._sig);
            if (signal._sig == std::SIGILL)
                BBP::std::printf(" (SIGILL).");
            BBP::std::printf("\r\n");
            break;
        }
    }
    catch (std::except exception)
    {
        BBP::std::printf("[bbp] Uncaught exception: halting program.\r\n");
        std::STDOUT <<= std::STDERR;
    }
    catch (...)
    {
        BBP::std::printf("[bbp] Program terminated after uncaught object.\r\n");
    }
    if (std::__errno && std::STDERR[0])
        BBP::std::printf("Program terminated with code %d: %s\n\r", std::__errno, &std::STDERR[0]);
    // Print stuff
    //std::printf("(%p) Allocated a total of %u bytes during runtime.\n", procFrame.pmem, procFrame.pmem->totalAllocations);
    // Garbage collection
    BBP::std::size_t deletedCount = procFrame.pmem->deleteAll();
    BBP::std::size_t freedCount = procFrame.pmem->freeAll();
    if (deletedCount || freedCount)
    {
        printf("\nNot all memory on the heap was released.\n");
        printf("\tAmount of blocks free'd: %u\n", freedCount);
        printf("\tAmount of objects delete'd: %u\n", deletedCount);
    }
    // Delete garbage collector
    BBP::std::progmem._delete(procFrame.pmem);
    // Restore active mem and active proc
    BBP::std::activemem = oldActiveMem;
    BBP::std::activeExecutable = oldActiveExecutable;
}
References BBP::std::ResourceManager::_delete(), BBP::std::SIGNAL::_sig, activeExecutable, activemem, BBP::std::ResourceManager::add_object(), BBP::std::ResourceManager::deleteAll(), exception(), BBP::std::R2D::fill(), BBP::std::window::fontSize, BBP::std::window::fontSpacing, BBP::std::ResourceManager::freeAll(), getNextAvailablePID(), BBP::std::executableFrame::isExecuting, kernelDisplay, BBP::std::executableFrame::PID, BBP::std::executableFrame::pmem, printf(), procFrames, progmem, BBP::userspace::read, SIGILL, SIGSHTDN, STDERR, and STDOUT.
Referenced by BBP::shell().
void BBP::std::exit ()
Definition at line 126 of file Executable.cpp.
{
    printf("\n\r");
    __SIGNAL__(SIGABRT);
}
References __SIGNAL__, printf(), and SIGABRT.
void* BBP::std::ext_calloc (std::size_t, std::size_t)
Referenced by BBP::std::ResourceManager::calloc().
void BBP::std::ext_free (void *)
Referenced by BBP::std::ResourceManager::free().
void* BBP::std::ext_malloc (std::size_t)
Referenced by BBP::std::ResourceManager::malloc().
template<typename T > std::PAGE<T>& BBP::std::first (std::PAGE< T > &)
Referenced by BBP::std::PATH::isRelativeToRoot().
float BBP::std::fPartOfNumber (float x)
Definition at line 313 of file R2D.cpp.
        {
            if (x > 0) return x - iPartOfNumber(x);
            else return x - (iPartOfNumber(x) + 1);
        }
References iPartOfNumber().
Referenced by rfPartOfNumber().
template<typename... Args> void BBP::std::fprintf (BBP::std::FILE & file, std::conststring format, Args... args) [inline]
Definition at line 262 of file FileSys.h.
        {
            // Check if can write to file
            if (!file.is_open())
                throw std::exception("ERR_FILE_NOT_OPEN", EBADF);
            // Allocate a buffer
            std::string buffer(BBP::std::max_page_elements, (BBP::std::string_element *)BBP::std::activemem->calloc(BBP::std::max_page_elements, sizeof(BBP::std::string_element)));
            // Format the string
            std::sprintf(buffer.data, format, args...);
            // Then print
            file.data()->fileData <<= buffer;
            // Then free the buffer
            BBP::std::activemem->free(buffer.data);
        }
References activemem, BBP::std::PAGE< T >::data, BBP::std::FILE::data(), EBADF, exception(), BBP::std::FileNode::fileData, BBP::std::ResourceManager::free(), BBP::std::FILE::is_open(), max_page_elements, and sprintf().
char BBP::std::getC ()
Referenced by BBP::shell_main().
BBP::uint8_t BBP::std::getDecimal (uint32_t value, uint32_t position)
Definition at line 11 of file stdint.cpp.
{
    uint32_t divisor = 1;
    for (uint32_t p = 0; p < position; p++)
        divisor *= 10;
    return (value / divisor) % 10;
}
Referenced by operator<().
void BBP::std::getLine ()
BBP::std::PID_t BBP::std::getNextAvailablePID ()
Definition at line 121 of file Executable.cpp.
{
    return pidCounter++;
}
References pidCounter.
Referenced by execute().
void BBP::std::initClock ()
int BBP::std::iPartOfNumber (float x)
Definition at line 301 of file R2D.cpp.
        {
            return (int)x;
        }
Referenced by fPartOfNumber(), BBP::std::R2D::Line(), and roundNumber().
template<typename T > std::PAGE<T>& BBP::std::last (std::PAGE< T > &)
Referenced by BBP::std::ELF::SectionBuilder::Append(), and BBP::std::ELF::SegmentBuilder::Append().
template<typename T > bool BBP::std::memcmp (PAGE< T > & src, PAGE< T > & dst)
template<typename T > void BBP::std::memcpy (PAGE< T > & src, PAGE< T > & dst) [inline]
Definition at line 160 of file Memory.h.
        {
            // Get sequence length of src
            std::size_t srcLen = std::seqlen(src);
            std::size_t dstLen = std::seqlen(dst);
            memcpy(src, dst, (srcLen < dstLen) ? srcLen : dstLen);
        }
References memcpy(), and seqlen().
template<typename T > void BBP::std::memcpy (PAGE< T > & src, PAGE< T > & dst, size_t amount)
Referenced by BBP::std::Stack< BBP::std::DIRECTORY >::Extend(), BBP::esa::esaProcessor::includeFile(), and memcpy().
time_t BBP::std::millis ()
time_t BBP::std::now ()
constexpr std::hash_t BBP::std::operator''_hash (const char * str, long unsigned int hehe) [inline], [constexpr]
Definition at line 72 of file Strings.h.
        {
            // Hashing constants
            const int p = 31;
            const int m = 1e9 + 9;
            // Working variables
            std::hash_t hash = 0;
            uint32_t Power = 1;
            // Get the size of the string
            std::size_t length = hehe;
            // Actual hashing algorithm. Taken from:
            for (std::index_t index = 0; index < length; index++)
            {
                char c = str[index];
                hash = (hash + (c - 'a' + 1) * Power) % m;
                Power = (p * Power) % m;
            }
            return hash;
        }
References BBP::Locale::Japanese::hash.
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator< (std::Stack< std::string_element > & stack, int value)
Definition at line 269 of file Strings.cpp.
{
    // Print sign
    if (value < 0)
    {
        stack << '-';
        value *= -1;
    }
    // Get the amount of decimals
    uint32_t decimals = std::decimals(value);
    for (uint32_t decimal = 0; decimal < decimals; decimal++)
    {
        std::word dec = std::getDecimal(value, decimals - decimal - 1);
        stack << (char)(dec + 48);
    }
    return stack;
}
References decimals(), and getDecimal().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<< (std::Stack< std::string_element > & lh, std::Stack< std::string_element > & rh)
Definition at line 443 of file Strings.cpp.
{
    char c = 0;
    rh >> c;
    lh << c;
    return lh;
}
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<< (std::Stack< std::string_element > & stack, std::c_string str)
Definition at line 238 of file Strings.cpp.
{
    // Check string exists
    if (str == nullptr)
        throw std::exception("Failed to stream string into buffer: string is null.", EINVAL);
    // Calculate string size
    size_t strLen = std::strlen(str);
    // Check if stack has enough space
    if (stack.atElement + strLen >= stack.max_elements)
        throw std::exception("Failed to stream string into buffer: operation would cause buffer overflow.", EPERM);
    // Write unsafely (since we already checked everything)
    for (index_t idx = 0; idx < strLen; idx++)
        stack <= str[idx];
    return stack;
}
References BBP::std::Stack< K >::atElement, EINVAL, EPERM, exception(), BBP::std::Stack< K >::max_elements, and strlen().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<< (std::Stack< std::string_element > & stack, std::conststring str)
Definition at line 218 of file Strings.cpp.
{
    // Check string exists
    if (str == nullptr)
        throw std::exception("Failed to stream string into buffer: string is null.", EINVAL);
    // Calculate string size
    size_t strLen = std::strlen(str);
    // Check if stack has enough space
    if (stack.atElement + strLen >= stack.max_elements)
        throw std::exception("Failed to stream string into buffer: operation would cause buffer overflow.", EPERM);
    // Write unsafely (since we already checked everything)
    for (index_t idx = 0; idx < strLen; idx++)
        stack <= str[idx];
    return stack;
}
References BBP::std::Stack< K >::atElement, EINVAL, EPERM, exception(), BBP::std::Stack< K >::max_elements, and strlen().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<< (std::Stack< std::string_element > & stack, std::string & str)
Definition at line 258 of file Strings.cpp.
{
    // Fetch the underlying c string
    std::c_string cstr = std::read_a(&str, 0);
    // Write that cstring
    stack <<= cstr;
    return stack;
}
References read_a().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<<= (std::Stack< std::string_element > & lh, std::Stack< std::string_element > & rh)
Definition at line 459 of file Strings.cpp.
{
    char c = 0;
    rh >> c;
    lh <<= c;
    return lh;
}
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<<= (std::Stack< std::string_element > & stack, char c)
Definition at line 195 of file Strings.cpp.
{
    stack << c;
    stack << (char)0;
    // If writeTo is defined: execute
    if (stack.writeTo)
        stack.writeTo(&stack);
    return stack;
}
References BBP::std::Stack< K >::writeTo.
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<<= (std::Stack< std::string_element > & stack, std::c_string str)
Definition at line 172 of file Strings.cpp.
{
    stack << str;
    stack << '\0';
    // If writeTo is defined: execute
    if (stack.writeTo)
        stack.writeTo(&stack);
    return stack;
}
References BBP::std::Stack< K >::writeTo.
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<<= (std::Stack< std::string_element > & stack, std::conststring str)
Definition at line 160 of file Strings.cpp.
{
    stack << str;
    stack << '\0';
    // If writeTo is defined: execute
    if (stack.writeTo)
        stack.writeTo(&stack);
    return stack;
}
References BBP::std::Stack< K >::writeTo.
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<<= (std::Stack< std::string_element > & stack, std::string & str)
Definition at line 184 of file Strings.cpp.
{
    // Fetch the underlying c string
    std::c_string cstr = std::read_a(&str, 0);
    // Write that cstring
    stack <<= cstr;
    return stack;
}
References read_a().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator<= (std::Stack< std::string_element > & stack, int value)
Definition at line 207 of file Strings.cpp.
{
    // Just write 'value' with the << operator
    stack << value;
    // Write '0'
    stack <<= "";
    return stack;
}
void BBP::std::operator<= (string & dst, c_string src)
Definition at line 155 of file Strings.cpp.
{
    BBP::std::strcpy(&dst, src);
}
References strcpy().
void BBP::std::operator<= (string & dst, conststring src)
Definition at line 150 of file Strings.cpp.
{
    BBP::std::strcpy(&dst, src);
}
References strcpy().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator> (std::Stack< std::string_element > & stack, std::c_string * str)
Definition at line 370 of file Strings.cpp.
{
    // Move pointer back by one.
    stack--;
    // Check if the current element is not a null character
    if (stack %= 0)
        stack--; // If this is the case, move the pointer back one.
    char c = 0; // Allocate char already
    do
    {
        // Peek once character (unsafe since we know where we are)
        c = stack %= 0;
        // Check if character is null
        if (c == 0)
        {
            // If null, return here
            *str = __UNSAFE__(std::read_a)(stack.page, stack.atElement + 1);
            // If readFrom is defined: execute
            if (stack.readFrom)
                stack.readFrom(&stack);
            return stack;
        }
        if (stack.atElement == 0)
            break; // Must be done, logic allows it and WILL cause errors if not handled, even for unsafe functions.
        // Character not null, go back
        stack--;
    } while (stack.atElement);
    // Reached element 0, so return element 0.
    *str = __UNSAFE__(std::read_a)(stack.page, stack.atElement);
    // If readFrom is defined: execute
    if (stack.readFrom)
        stack.readFrom(&stack);
    return stack;
}
References __UNSAFE__, BBP::std::Stack< K >::atElement, BBP::std::Stack< K >::page, read_a(), and BBP::std::Stack< K >::readFrom.
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator> (std::Stack< std::string_element > & stack, std::string * str)
Definition at line 416 of file Strings.cpp.
{
    // Fetch the underlying c string
    std::c_string cstr;
    stack > &cstr;
    // Get the size of the string
    size_t length = __UNSAFE__(std::strlen)(cstr);
    // Write that cstring into string
    __UNSAFE__(std::write_a)(str, cstr, 0, length);
    // If readFrom is defined: execute
    if (stack.readFrom)
        stack.readFrom(&stack);
    return stack;
}
References __UNSAFE__, BBP::std::Stack< K >::readFrom, strlen(), and write_a().
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator>> (std::Stack< std::string_element > & lh, std::Stack< std::string_element > & rh)
Definition at line 435 of file Strings.cpp.
{
    char c = 0;
    lh >> c;
    rh << c;
    return lh;
}
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator>>= (std::Stack< std::string_element > & lh, std::Stack< std::string_element > & rh)
Definition at line 451 of file Strings.cpp.
{
    char c = 0;
    lh >> c;
    rh <<= c;
    return lh;
}
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator>>= (std::Stack< std::string_element > & stack, std::c_string * str)
Definition at line 290 of file Strings.cpp.
{
    // Check target exists
    if (str == nullptr)
        throw std::exception("Failed to stream string from buffer: string is null.", EINVAL);
    // If stack is already at 0, throw error (since this only occurs if there is 'nothing' in the buffer)
    if (stack.atElement == 0)
        throw std::exception("Could not stream string from buffer: buffer is empty.", EPERM);
    // Move the pointer back by one
    stack--;
    // Check if the current element is not a null character
    if ((stack %= 0) == 0)
        stack--; // If this is the case, move the pointer back one.
    // If this caused buffer overflow: return error.
    if (stack.atElement > stack.max_elements)
    {
        stack++; // Rectify the overflow
        throw std::exception("Failed to stream string from buffer: Caused overflow. (rectified).", EPERM);
    }
    char c = 0; // Allocate char already
    do
    {
        // Peek once character (unsafe since we know where we are)
        c = stack %= 0;
        // Check if character is null
        if (c == 0)
        {
            // If null, return here
            *str = std::read_a(stack.page, stack.atElement + 1);
            // If readFrom is defined: execute
            if (stack.readFrom)
                stack.readFrom(&stack);
            return stack;
        }
        if (stack.atElement == 0)
            break; // Must be done, logic allows it and WILL cause errors if not handled, even for unsafe functions.
        // Character not null, go back
        stack--;
    } while (stack.atElement);
    // Reached element 0, so return element 0.
    *str = __UNSAFE__(std::read_a)(stack.page, stack.atElement);
    // If readFrom is defined: execute
    if (stack.readFrom)
        stack.readFrom(&stack);
    return stack;
}
References __UNSAFE__, BBP::std::Stack< K >::atElement, EINVAL, EPERM, exception(), BBP::std::Stack< K >::max_elements, BBP::std::Stack< K >::page, read_a(), and BBP::std::Stack< K >::readFrom.
BBP::std::Stack< BBP::std::string_element > & BBP::std::operator>>= (std::Stack< std::string_element > & stack, std::string * str)
Definition at line 351 of file Strings.cpp.
{
    // Fetch the underlying c string
    std::c_string cstr;
    stack >>= &cstr;
    // Get the size of the string
    size_t length = std::strlen(cstr);
    // Write that cstring into string
    std::write_a(str, cstr, 0, length);
    // If readFrom is defined: execute
    if (stack.readFrom)
        stack.readFrom(&stack);
    return stack;
}
References BBP::std::Stack< K >::readFrom, strlen(), and write_a().
void BBP::std::print_to_terminal (std::Stack< std::string_element > * stack)
int BBP::std::printf (std::conststring format, ...)
Referenced by BBP::badapple_main(), BBP::esa::esaProcessor::emitProcedure(), BBP::esa::BinaryApplication::emitSymbol(), execute(), exit(), BBP::esa::esaProcessor::includeFile(), BBP::esa::esaProcessor::includeFromPath(), BBP::std::Lexer::lex_context::Log(), BBP::esa::esaProcessor::logInstruction(), BBP::neofetch_main(), BBP::esa::PRAGMA(), BBP::shell(), BBP::shell_main(), and BBP::smile_main().
int BBP::std::putf (std::Stack< std::string_element > & stream, std::conststring format, ...)
Referenced by BBP::std::Lexer::lex_context::Highlight(), and BBP::std::Lexer::lex_context::Log().
template<typename T > T& BBP::std::read (PAGE< T > * page, index_t index)
Referenced by BBP::esa::esaProcessor::addReservedIdentifier(), BBP::std::Stack< BBP::std::DIRECTORY >::all(), BBP::std::Stack< BBP::std::DIRECTORY >::any(), BBP::esa::esaProcessor::buildSymbol(), BBP::std::Lexer::lex_context::calculateDebugPosition(), BBP::std::FILE::checkIfIsOpen(), BBP::std::FILE::data(), BBP::std::ResourceManager::deleteAll(), BBP::esa::BinaryApplication::emitSymbolHash(), BBP::std::ResourceManager::find_Alloc_pointer(), BBP::std::ResourceManager::find_next_empty_alloc(), BBP::std::ResourceManager::find_next_empty_object(), BBP::std::ResourceManager::find_Object_pointer(), BBP::std::FILE::findClosedFile(), BBP::std::Stack< BBP::std::DIRECTORY >::foreach(), BBP::std::ResourceManager::freeAll(), BBP::std::PATH::getFileAndPaths(), BBP::std::Lexer::lex_context::Highlight(), BBP::esa::esaProcessor::includeFile(), BBP::std::PATH::isDefinedFromRoot(), BBP::std::PATH::isRelativeToRoot(), BBP::esa::esaProcessor::lookupSymbol(), BBP::std::Lexer::lex_context::moveToAndHashThisWord(), BBP::std::Lexer::lex_context::moveToEndOfLastWord(), BBP::std::Lexer::lex_context::moveToEndOfThisWord(), BBP::std::Lexer::lex_context::moveToNextKeyword(), BBP::std::Lexer::lex_context::moveToStartOfNextWord(), BBP::std::Lexer::lex_context::moveToStartOfThisWord(), BBP::std::Stack< BBP::std::DIRECTORY >::operator%=(), BBP::std::Stack< BBP::std::DIRECTORY >::operator+=(), BBP::std::Stack< BBP::std::DIRECTORY >::operator>=(), BBP::std::Stack< BBP::std::DIRECTORY >::operator>>(), BBP::std::Stack< BBP::std::DIRECTORY >::operator[](), BBP::std::Lexer::lex_context::parseFile(), BBP::esa::esaProcessor::resolve(), BBP::std::PATH::resolveAbsolutes(), BBP::esa::esaProcessor::setProcedureIdentifier(), BBP::shell(), strlen(), and BBP::std::Lexer::lex_context::tryParseNumerical().
template<typename T > T& __UNSAFE__() BBP::std::read (PAGE< T > * page, index_t index) [inline]
template<typename T > T* BBP::std::read_a (PAGE< T > * page, index_t index)
Referenced by BBP::std::PATH::fileName(), BBP::std::R2D::GetFontFromFile(), operator<<(), operator<<=(), operator>(), operator>>=(), BBP::std::PATH::pathName(), BBP::shell(), and strhsh().
template<typename T > T* __UNSAFE__() BBP::std::read_a (PAGE< T > * page, index_t index) [inline]
template<typename T > mem_t* BBP::std::read_ar (PAGE< T > * page, index_t index)
Referenced by BBP::std::R2D::GetFontFromFile().
template<typename T > mem_t* __UNSAFE__() BBP::std::read_ar (PAGE< T > * page, index_t index) [inline]
template<typename T > mem_t& BBP::std::read_r (PAGE< T > * page, index_t index)
Referenced by BBP::shell().
template<typename T > mem_t& __UNSAFE__() BBP::std::read_r (PAGE< T > * page, index_t index) [inline]
float BBP::std::rfPartOfNumber (float x)
Definition at line 321 of file R2D.cpp.
        {
            return 1 - fPartOfNumber(x);
        }
References fPartOfNumber().
int BBP::std::roundNumber (float x)
Definition at line 307 of file R2D.cpp.
        {
            return iPartOfNumber(x + 0.5);
        }
References iPartOfNumber().
template<typename T > size_t BBP::std::seqlen (PAGE< T > & page)
Referenced by BBP::std::ELF::SectionBuilder::Append(), BBP::std::ELF::SegmentBuilder::Append(), BBP::std::ELF::ELFBuilder::ELFBuilder(), memcpy(), and BBP::std::Lexer::lex_context::parseFile().
template<typename T > size_t __UNSAFE__() BBP::std::seqlen (PAGE< T > & page)
template<typename T > size_t BBP::std::seqlen_r (PAGE< T > & page)
template<typename T > size_t __UNSAFE__() BBP::std::seqlen_r (PAGE< T > & page)
PID_t BBP::std::spawnExecutable (executable_main, std::string &)
int BBP::std::sprintf (std::c_string buffer, std::conststring format, ...)
Referenced by BBP::badapple_main(), fprintf(), and BBP::std::PATH::makeAbsolutePath().
void BBP::std::stopCapturingInput ()
bool BBP::std::strcmp (string * sta, c_string stb)
bool BBP::std::strcmp (string * sta, conststring stb)
Definition at line 125 of file Strings.cpp.
{
    // If lenghts are unequal, just return false
    size_t len1 = BBP::std::strlen(str1->data);
    size_t len2 = BBP::std::strlen(str2);
    // If lengths are unequal, just return
    if (len1 != len2)
        return false;
    // Loop over each character
    for (size_t index = 0; index < len1; index++)
    {
        // Fetch each character
        char c1 = std::read(str1, index);
        char c2 = str2[index];
        // If characters are unequal, return false
        if (c1 != c2)
            return false;
    }
    return true;
}
References BBP::std::PAGE< T >::data, BBP::userspace::read, and strlen().
void BBP::std::strcpy (c_string dst, conststring src)
Definition at line 118 of file Strings.cpp.
{
    size_t len = BBP::std::strlen(src) + 1;
    for (std::index_t idx = 0; idx < len; idx++)
        dst[idx] = src[idx];
}
References strlen().
void BBP::std::strcpy (string * dst, c_string src)
Definition at line 111 of file Strings.cpp.
{
    size_t len = BBP::std::strlen(src);
    BBP::std::write_a(dst, src, 0, len + 1);
}
References strlen(), and write_a().
void BBP::std::strcpy (string * dst, conststring src)
Definition at line 104 of file Strings.cpp.
{
    BBP::std::c_string cstring = (BBP::std::c_string)src;
    BBP::std::strcpy(dst, cstring);
}
Referenced by BBP::std::PATH::makeAbsolutePath(), operator<=(), BBP::std::Lexer::lex_context::parseFile(), BBP::std::PATH::PATH(), and BBP::shell().
BBP::std::hash_t BBP::std::strhsh (std::c_string str)
Definition at line 477 of file Strings.cpp.
{
    // Hashing constants
    const int p = 31;
    const int m = 1e9 + 9;
    // Working variables
    std::hash_t hash = 0;
    uint32_t Power = 1;
    // Get the size of the string
    std::size_t length = std::strlen(str);
    // Actual hashing algorithm. Taken from:
    for (std::index_t index = 0; index < length; index++)
    {
        char c = str[index];
        hash = (hash + (c - 'a' + 1) * Power) % m;
        Power = (p * Power) % m;
    }
    
    return hash;
}
References BBP::Locale::Japanese::hash, and strlen().
hash_t BBP::std::strhsh (conststring str)
void BBP::std::strhsh (std::hash_t & hash, std::word & Power, std::string_element & c)
Definition at line 501 of file Strings.cpp.
{
    // Hashing constants
    const int p = 31;
    const int m = 1e9 + 9;
    
    // Run the hashing equation once
    hash = (hash + (c - 'a' + 1) * Power) % m;
    Power = (p * Power) % m;
}
References BBP::Locale::Japanese::hash.
BBP::std::hash_t BBP::std::strhsh (std::string & str)
Definition at line 467 of file Strings.cpp.
{
    return std::strhsh(std::read_a(&str, 0));
}
References read_a().
Referenced by BBP::std::FILE::checkIfIsOpen(), BBP::std::ELF::ELFBuilder::ELFBuilder(), BBP::std::FileNode::FileNode(), and BBP::std::Lexer::lex_context::moveToAndHashThisWord().
BBP::std::size_t BBP::std::strlen (c_string str)
Definition at line 21 of file Strings.cpp.
{
    // Check if string is valid
    if (str == nullptr)
        throw BBP::std::exception("Could not calculate string length: string is null.", EINVAL);
    // Create length variable
    size_t length = 0;
    for (; str[length]; length++)
        if (length >= BBP::std::max_string_length)
            throw BBP::std::exception("Failed to calculate string length: string is calculated to be bigger than maximum permissible size.", ENOBUFS);
    return length;
}
References EINVAL, ENOBUFS, exception(), and max_string_length.
size_t BBP::std::strlen (conststring str)
Referenced by BBP::esa::esaProcessor::addReservedIdentifier(), BBP::esa::esaProcessor::esaProcessor(), BBP::std::PATH::getFileAndPaths(), BBP::esa::esaProcessor::includeFile(), BBP::std::PATH::isDefinedFromRoot(), BBP::std::PATH::makeAbsolutePath(), BBP::esa::BinaryApplication::mangle(), operator<<(), operator>(), operator>>=(), BBP::std::PATH::PATH(), BBP::std::PATH::resolveAbsolutes(), BBP::shell(), strcmp(), strcpy(), and strhsh().
BBP::std::size_t BBP::std::strlen (string & str)
Definition at line 37 of file Strings.cpp.
{
    // Create length variable
    size_t length = 0;
    for (; BBP::std::read(&str, length); length++)
        if (length >= BBP::std::max_string_length)
            throw BBP::std::exception("Failed to calculate string length: string is calculated to be bigger than maximum permissible size.", ENOBUFS);
    return length;
}
References ENOBUFS, exception(), max_string_length, and read().
size_t __UNSAFE__() BBP::std::strlen (string str)
BBP::std::size_t BBP::std::strlen (string str, offset_t offset)
Definition at line 49 of file Strings.cpp.
{
    // Create length variable
    size_t length = 0;
    for (; BBP::std::read(&str, length + offset); length++)
        if (length >= BBP::std::max_string_length)
            throw BBP::std::exception("Failed to calculate string length: string is calculated to be bigger than maximum permissible size.", ENOBUFS);
    return length;
}
References ENOBUFS, exception(), max_string_length, and read().
void BBP::std::swap (int * a, int * b)
Definition at line 286 of file R2D.cpp.
        {
            int temp = *a;
            *a = *b;
            *b = temp;
        }
References BBP::Locale::Japanese::a.
Referenced by BBP::std::R2D::Line().
template<typename T > void BBP::std::write (PAGE< T > * page, T & data, index_t index)
Referenced by BBP::std::ResourceManager::add_alloc(), BBP::esa::esaProcessor::addReservedIdentifier(), BBP::std::R2D::background(), BBP::esa::esaProcessor::buildSymbol(), BBP::esa::BinaryApplication::emitSymbolHash(), BBP::std::PATH::getFileAndPaths(), BBP::esa::esaProcessor::includeFile(), BBP::std::Stack< BBP::std::DIRECTORY >::operator<<(), BBP::std::Stack< BBP::std::DIRECTORY >::operator<=(), BBP::std::PATH::resolveAbsolutes(), BBP::std::ResourceManager::ResourceManager(), and BBP::esa::esaProcessor::setProcedureIdentifier().
template<typename T > void __UNSAFE__() BBP::std::write (PAGE< T > * page, T & data, index_t index) [inline]
template<typename T > void BBP::std::write_a (PAGE< T > * page, T * data, index_t index, size_t amount)
Referenced by operator>(), operator>>=(), and strcpy().
template<typename T > void __UNSAFE__() BBP::std::write_a (PAGE< T > * page, T * data, index_t index, size_t amount) [inline]
template<typename T > void BBP::std::write_ar (PAGE< T > * page, mem_t * data, index_t index, size_t amount)
template<typename T > void BBP::std::write_r (PAGE< T > * page, mem_t & data, index_t index)
template<typename T > void __UNSAFE__() BBP::std::write_r (PAGE< T > * page, mem_t & data, index_t index) [inline]
Variable Documentation
volatile bool BBP::std::_echoStuffToTerminal
volatile bool BBP::std::_waitforline
BBP::std::PID_t BBP::std::activeExecutable = 0
Definition at line 12 of file Executable.cpp.
Referenced by execute().
ResourceManager* BBP::std::activemem
Referenced by BBP::badapple_main(), BBP::std::FILE::close(), BBP::esa::esaProcessor::discardAndClose(), execute(), BBP::std::FILE::FILE(), fprintf(), BBP::esa::esaProcessor::saveAndClose(), BBP::esa::esaProcessor::setupBackend(), BBP::shell(), and BBP::smile_main().
const typedef string_element* BBP::std::conststring
Definition at line 29 of file Strings.h.
Referenced by BBP::esa::ACTION(), BBP::esa::esaProcessor::buildSymbol(), BBP::esa::esaProcessor::resolve(), and BBP::esa::TOKEN().
const std::conststring BBP::std::endl = '\n'
Definition at line 139 of file Strings.h.
Referenced by BBP::std::ResourceManager::_delete(), exception(), BBP::std::FILE::finish(), BBP::std::ResourceManager::free(), BBP::std::Lexer::lex_context::Highlight(), BBP::std::Lexer::lex_context::LogAbort(), BBP::std::Lexer::lex_context::LogError(), BBP::std::Lexer::lex_context::LogNote(), BBP::std::Lexer::lex_context::LogWarning(), and BBP::std::ResourceManager::mark_deleted().
const BBP::std::Executable BBP::std::executables = {{shell_main, '/proc/shell'}}
Definition at line 7 of file Executable.cpp.
std::STATIC_PAGE<FileNode, max_open_files> BBP::std::fileTable
Referenced by BBP::std::FILE::checkIfIsOpen(), BBP::std::FILE::close(), BBP::std::FILE::data(), BBP::std::FILE::FILE(), BBP::std::FILE::findClosedFile(), BBP::std::FILE::getINodeIndex(), and BBP::std::FILE::is_open().
bool BBP::std::gINIT
std::window BBP::std::kernelDisplay
Referenced by execute().
constexpr size_t BBP::std::max_allocations = 1000 [static], [constexpr]
Definition at line 17 of file Resources.h.
constexpr word BBP::std::max_lpage_static_size = 0x2000 [constexpr]
Definition at line 30 of file Memory.h.
constexpr size_t BBP::std::max_objects = 1000 [static], [constexpr]
Definition at line 16 of file Resources.h.
constexpr std::size_t BBP::std::max_open_files = 32 [static], [constexpr]
Definition at line 28 of file FileSys.h.
constexpr word BBP::std::max_page_elements = 20000 [constexpr]
Definition at line 18 of file Memory.h.
Referenced by fprintf(), and BBP::std::PATH::makeAbsolutePath().
constexpr word BBP::std::max_page_pointer_size = max_page_elements [constexpr]
Definition at line 24 of file Memory.h.
constexpr word BBP::std::max_page_sequence_length = 64 [constexpr]
Definition at line 27 of file Memory.h.
constexpr word BBP::std::max_page_static_size = 20000 [constexpr]
Definition at line 21 of file Memory.h.
Referenced by BBP::std::STATIC_PAGE< std::index_t, 32 >::STATIC_PAGE().
constexpr std::size_t BBP::std::max_path_length = 128 [static], [constexpr]
Definition at line 29 of file FileSys.h.
const size_t BBP::std::max_string_length = 0xFFFF
Definition at line 33 of file Strings.h.
Referenced by strlen().
VOLUME* BBP::std::primaryVolume
Referenced by BBP::std::FILE::FILE(), and BBP::esa::esaProcessor::includeFromPath().
Stack<executableFrame> BBP::std::Processes
BBP::std::STATIC_PAGE< BBP::std::executableFrame, 12 > BBP::std::procFrames
Definition at line 9 of file Executable.cpp.
Referenced by execute().
ResourceManager BBP::std::progmem
Referenced by execute().
constexpr signal_t BBP::std::SIGABRT = 6 [constexpr]
Definition at line 32 of file Signal.h.
Referenced by exit().
constexpr signal_t BBP::std::SIGADJ = 150 [constexpr]
Definition at line 35 of file Signal.h.
constexpr signal_t BBP::std::SIGFPE = 7 [constexpr]
Definition at line 33 of file Signal.h.
constexpr signal_t BBP::std::SIGILL = 5 [constexpr]
Definition at line 31 of file Signal.h.
Referenced by execute(), and BBP::smile_main().
constexpr signal_t BBP::std::SIGINT = 4 [constexpr]
Definition at line 30 of file Signal.h.
constexpr signal_t BBP::std::SIGINV = 1 [constexpr]
Definition at line 27 of file Signal.h.
constexpr signal_t BBP::std::SIGSEGV = 3 [constexpr]
Definition at line 29 of file Signal.h.
Referenced by BBP::std::ResourceManager::_delete(), BBP::std::ELF::SectionBuilder::Append(), BBP::std::ELF::SegmentBuilder::Append(), BBP::std::ELF::SectionBuilder::close(), BBP::std::ELF::SegmentBuilder::close(), BBP::std::ELF::SectionBuilder::Extend(), and BBP::std::ResourceManager::free().
constexpr signal_t BBP::std::SIGSHTDN = 8 [constexpr]
Definition at line 34 of file Signal.h.
Referenced by execute(), and BBP::logout_main().
constexpr signal_t BBP::std::SIGTERM = 2 [constexpr]
Definition at line 28 of file Signal.h.
const std::conststring BBP::std::space = ' '
Definition at line 138 of file Strings.h.
std::Stack<std::string_element> BBP::std::STDERR
Referenced by BBP::std::ResourceManager::_delete(), exception(), execute(), BBP::std::ResourceManager::free(), and BBP::std::ResourceManager::mark_deleted().
std::Stack<std::string_element> BBP::std::STDIN
Referenced by BBP::shell_main().
std::Stack<std::string_element> BBP::std::STDOUT
Referenced by execute(), BBP::std::Lexer::lex_context::Highlight(), BBP::std::Lexer::lex_context::Log(), BBP::std::Lexer::lex_context::LogAbort(), BBP::std::Lexer::lex_context::LogError(), BBP::std::Lexer::lex_context::LogNote(), BBP::std::Lexer::lex_context::LogWarning(), and BBP::shell_main().
BBP::std::Stack< BBP::std::string_element > BBP::std::STDERR & BBP::std::str_STDERR
Definition at line 5 of file stdio.cpp.
BBP::std::Stack< BBP::std::string_element > BBP::std::STDIN & BBP::std::str_STDIN
Definition at line 4 of file stdio.cpp.
BBP::std::Stack< BBP::std::string_element > BBP::std::STDOUT & BBP::std::str_STDOUT
Definition at line 3 of file stdio.cpp.
const typedef ustring_element* BBP::std::uconststring
Definition at line 30 of file Strings.h.
ResourceManager BBP::std::vmem
Definition at line 33 of file R2D.cpp.
Referenced by BBP::std::R2D::GetFontFromFile(), and BBP::std::R2D::newWindow().
PATH* BBP::std::workingDirectory
Referenced by BBP::std::FileNode::FileNode(), BBP::std::FILE::getINodeIndex(), BBP::shell(), BBP::shell_main(), and BBP::std::Lexer::lex_context::translateUnit().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.