.TH "BBP::userspace::HyperVisor" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::userspace::HyperVisor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hyperv\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::size_t\fP \fBactiveThreadCount\fP = 0"
.br
.ti -1c
.RI "\fBstd::index_t\fP \fBactiveThread\fP = 0"
.br
.ti -1c
.RI "\fBstd::STATIC_PAGE\fP< \fBThread\fP, \fBthreadCount\fP > \fBthreads\fP"
.br
.ti -1c
.RI "\fBstd::ELF::ELFBuilder\fP \fBsharedlib\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr \fBstd::size_t\fP \fBthreadCount\fP = 16"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file Hyperv\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBstd::index_t\fP BBP::userspace::HyperVisor::activeThread = 0"

.PP
Definition at line 19 of file Hyperv\&.h\&.
.SS "\fBstd::size_t\fP BBP::userspace::HyperVisor::activeThreadCount = 0"

.PP
Definition at line 18 of file Hyperv\&.h\&.
.SS "\fBstd::ELF::ELFBuilder\fP BBP::userspace::HyperVisor::sharedlib"

.PP
Definition at line 25 of file Hyperv\&.h\&.
.SS "constexpr \fBstd::size_t\fP BBP::userspace::HyperVisor::threadCount = 16\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definition at line 17 of file Hyperv\&.h\&.
.SS "\fBstd::STATIC_PAGE\fP<\fBThread\fP, \fBthreadCount\fP> BBP::userspace::HyperVisor::threads"

.PP
Definition at line 22 of file Hyperv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
