BBP::esa
NAME
BBP::esa
SYNOPSIS
Data Structures
class BinaryApplication
struct dataEntry
class esaProcessor
Enumerations
enum ELSA_TYPE : uint32_t { UNKOWN_T, SYMBOL_T, PROCEDURE_T, INSTRUCTION_T }
enum SYMBOL_TYPE : uint32_t { SYMTACC_VIRTUAL = 0b1, SYMTACC_STATIC = SYMTACC_VIRTUAL << 1, SYMTMOD_EXTERN = SYMTACC_STATIC << 1, SYMTMOD_CONST = SYMTMOD_EXTERN << 1, SYMTMOD_STATIC = SYMTMOD_CONST << 1, SYMTSZ_NIL = SYMTMOD_STATIC << 1, SYMTSZ_DN = SYMTSZ_NIL << 1, SYMTSZ_DB = SYMTSZ_DN << 1, SYMTSZ_DH = SYMTSZ_DB << 1, SYMTSZ_DI = SYMTSZ_DH << 1, SYMTSZ_DA = SYMTSZ_DI << 1, SYMTSZ_DW = SYMTSZ_DA << 1 }
Functions
PRAGMA (include)
PRAGMA (handler)
PRAGMA (define)
PRAGMA (undef)
PRAGMA (ifndef)
PRAGMA (ifdef)
PRAGMA (endif)
PRAGMA (else)
PRAGMA (atomic)
PRAGMA (handover)
PRAGMA (continue)
ACTION (static)
ACTION (const)
ACTION (virtual)
ACTION (extern)
ACTION (procedure)
ACTION (end)
ACTION (endroutine)
TOKEN (newline)
TOKEN (semicolon)
TOKEN (openDelimiter)
TOKEN (closeDelimiter)
TOKEN (comma)
TOKEN (caret)
TOKEN (doubleQuote)
TOKEN (singleQuote)
TOKEN (colon)
TOKEN (backslash)
TOKEN (size)
INSTRUCTION (nil)
INSTRUCTION (stack)
INSTRUCTION (ctrl)
INSTRUCTION (mem)
INSTRUCTION (inc)
INSTRUCTION (dec)
INSTRUCTION (neg)
INSTRUCTION (add)
INSTRUCTION (sub)
INSTRUCTION (mul)
INSTRUCTION (div)
INSTRUCTION (mod)
INSTRUCTION (lbs)
INSTRUCTION (rbs)
INSTRUCTION (or)
INSTRUCTION (xor)
INSTRUCTION (and)
INSTRUCTION (not)
INSTRUCTION (flag)
INSTRUCTION (jmp)
INSTRUCTION (jmpc)
INSTRUCTION (jmpz)
INSTRUCTION (page)
INSTRUCTION (signal)
INSTRUCTION (halt)
Variables
static const char *const keywords []
static const char *const tokens [] = { '\r', '\n', ';', '(', ')', ',', '[', ']', '{', '}', '^', '<', '>', '\'', ''', ':', '\\', 'dn', 'db', 'dh', 'di', 'da', 'dw' }
static const char *const mnemonics []
static constexpr std::size_t keywordCount = 18
static constexpr std::size_t tokenCount = 23
static constexpr std::size_t mnemonicsCount = 110
static const std::Lexer::lex_action keywordActions []
static const std::Lexer::lex_action tokenActions []
static const std::Lexer::lex_action mnemonicsActions []
static const char flags [23][8]
esaProcessor processor
Enumeration Type Documentation
enum BBP::esa::ELSA_TYPE : uint32_t
Enumerator
UNKOWN_T
SYMBOL_T
PROCEDURE_T
INSTRUCTION_T
Definition at line 148 of file ELSA.h.
                       : uint32_t
        {
            UNKOWN_T,
            SYMBOL_T,
            PROCEDURE_T,
            INSTRUCTION_T
        };
enum BBP::esa::SYMBOL_TYPE : uint32_t
Enumerator
SYMTACC_VIRTUAL
SYMTACC_STATIC
SYMTMOD_EXTERN
SYMTMOD_CONST
SYMTMOD_STATIC
SYMTSZ_NIL
SYMTSZ_DN
SYMTSZ_DB
SYMTSZ_DH
SYMTSZ_DI
SYMTSZ_DA
SYMTSZ_DW
Definition at line 156 of file ELSA.h.
                         : uint32_t
        {
            // Defines the access of a symbol. If none used, it is a quasi-symbol.
            SYMTACC_VIRTUAL = 0b1,
            SYMTACC_STATIC = SYMTACC_VIRTUAL << 1,
            // Modifiers that can be used
            SYMTMOD_EXTERN = SYMTACC_STATIC << 1,
            SYMTMOD_CONST = SYMTMOD_EXTERN << 1,
            SYMTMOD_STATIC = SYMTMOD_CONST << 1,
            // The size of the symbol
            SYMTSZ_NIL = SYMTMOD_STATIC << 1,
            SYMTSZ_DN = SYMTSZ_NIL << 1,
            SYMTSZ_DB = SYMTSZ_DN << 1,
            SYMTSZ_DH = SYMTSZ_DB << 1,
            SYMTSZ_DI = SYMTSZ_DH << 1,
            SYMTSZ_DA = SYMTSZ_DI << 1,
            SYMTSZ_DW = SYMTSZ_DA << 1
        };
Function Documentation
BBP::esa::ACTION (const)
Definition at line 380 of file Actions.cpp.
{
    return processor.markConst();
}
References BBP::esa::esaProcessor::markConst(), and processor.
BBP::esa::ACTION (end)
Definition at line 410 of file Actions.cpp.
{
    // Check if inside a procedure
    if (processor.procedureHash == 0)
        return "EInvalid 'end'; Must be matched with 'procedure'.";
    // Save end
    processor.endedAt = processor.application->builder._text().stack.atElement;
    // Push function
    std::conststring error = processor.emitProcedure();
    // Now reset procedure flags
    processor.procedureName.static_data[0] = 0;
    processor.procedureHash = 0;
    processor.startedAt = 0;
    processor.endedAt = 0;
    processor.procedureArgumentCount = 0;
    processor.doneDeclaringProcedure = false;
    processor.externProcedure = false;
    // Check for any subscribers.
    if (processor.routineStarts.atElement)
    {
        // Reset them
        processor.routineStarts.atElement = 0;
        // Return error
        return "EUnterminated ':' tokens before end of procedure.";
    }
    // Then return error
    return error;
}
References BBP::std::ELF::ELFBuilder::_text(), BBP::esa::esaProcessor::application, BBP::std::Stack< K >::atElement, BBP::esa::BinaryApplication::builder, BBP::std::conststring, BBP::esa::esaProcessor::doneDeclaringProcedure, BBP::esa::esaProcessor::emitProcedure(), BBP::esa::esaProcessor::endedAt, BBP::esa::esaProcessor::externProcedure, BBP::esa::esaProcessor::procedureArgumentCount, BBP::esa::esaProcessor::procedureHash, BBP::esa::esaProcessor::procedureName, processor, BBP::esa::esaProcessor::routineStarts, BBP::std::ELF::SectionBuilder::stack, BBP::esa::esaProcessor::startedAt, and BBP::std::STATIC_PAGE< T, K >::static_data.
BBP::esa::ACTION (endroutine)
Definition at line 445 of file Actions.cpp.
{
    // If no subscribers, emit warning
    if (processor.routineStarts.atElement == 0)
    {
        context->resetInfo(context->debugInformation);
        context->debugInformation.errName = "-Wignored-double-at";
        return "WIgnored stray '@@' because no ':' tokens precedes it.";
    }
    // Get current index in .text
    std::index_t currentIndex = processor.application->builder.sections[processor.application->builder.text].stack.atElement;
    // Loop over subscribers
    for (std::index_t index = 0; index < std::read(&processor.routineSubscriberCount, processor.routineStarts.atElement); index++)
    {
        // Get target offset
        std::offset_t target = processor.subscribers[index];
        // Write into section
        processor.application->builder.sections[processor.application->builder.text].stack[target] = (currentIndex >> 24) & 0xFF;
        processor.application->builder.sections[processor.application->builder.text].stack[target+1] = (currentIndex >> 16) & 0xFF;
        processor.application->builder.sections[processor.application->builder.text].stack[target+2] = (currentIndex >> 8) & 0xFF;
        processor.application->builder.sections[processor.application->builder.text].stack[target+3] = (currentIndex >> 0) & 0xFF;
    }
    // Now reset
    std::index_t zero = 0;
    std::write(&processor.routineSubscriberCount, zero, processor.routineStarts.atElement);
    processor.routineStarts--;
    return nullptr;
}
References BBP::esa::esaProcessor::application, BBP::std::Stack< K >::atElement, BBP::esa::BinaryApplication::builder, processor, BBP::userspace::read, BBP::esa::esaProcessor::routineStarts, BBP::esa::esaProcessor::routineSubscriberCount, BBP::std::ELF::ELFBuilder::sections, BBP::esa::esaProcessor::subscribers, BBP::std::ELF::ELFBuilder::text, BBP::userspace::write, and BBP::Locale::Japanese::zero.
BBP::esa::ACTION (extern)
Definition at line 390 of file Actions.cpp.
{
    return processor.markExtern();
}
References BBP::esa::esaProcessor::markExtern(), and processor.
BBP::esa::ACTION (procedure)
Definition at line 395 of file Actions.cpp.
{
    // Check appropriate flags
    if (processor.lineIsDefiningInstruction || processor.lineIsDefiningSymbolDefinition)
        return "E'procedure' is a reserved keyword."; // If any of these flags are true, return error.
    // Set appropriate flags
    processor.lineIsDefiningProcedure = true;
    // Set index to here
    processor.setProcedureAddress();
    return nullptr;
}
References BBP::esa::esaProcessor::lineIsDefiningInstruction, BBP::esa::esaProcessor::lineIsDefiningProcedure, BBP::esa::esaProcessor::lineIsDefiningSymbolDefinition, processor, and BBP::esa::esaProcessor::setProcedureAddress().
BBP::esa::ACTION (static)
Definition at line 375 of file Actions.cpp.
{
    return processor.markStatic();
}
References BBP::esa::esaProcessor::markStatic(), and processor.
BBP::esa::ACTION (virtual)
Definition at line 385 of file Actions.cpp.
{
    return processor.markVirtual();
}
References BBP::esa::esaProcessor::markVirtual(), and processor.
BBP::esa::INSTRUCTION (add)
Definition at line 1037 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case ADD_HANDLE:
        suffix = 0;
        break;
    case ADDF_HANDLE:
        suffix = userspace::ffloat;
        break;
    case ADDIF_HANDLE:
        suffix = userspace::sfloat;
        break;
    case ADDFF_HANDLE:
        suffix = userspace::ffloat | userspace::sfloat;
        break;
    }
    // If the handle is ADD, expect any amount of args
    if (handle == ADD_HANDLE)
    {
        processor.setInstruction(userspace::ADD, suffix, 0, 8);
        processor.surpressArgCountWarning();
        processor.expectAny(0);
        processor.expectAny(1);
        processor.expectAny(2);
        processor.expectAny(3);
        processor.expectAny(4);
        processor.expectAny(5);
        processor.expectAny(6);
        processor.expectAny(7);
        return nullptr;
    }
    processor.setInstruction(userspace::ADD, suffix, 0, 2);
    processor.expectAny(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::userspace::ADD, ADD_HANDLE, ADDF_HANDLE, ADDFF_HANDLE, ADDIF_HANDLE, BBP::esa::esaProcessor::expectAny(), BBP::userspace::ffloat, processor, BBP::esa::esaProcessor::setInstruction(), BBP::userspace::sfloat, and BBP::esa::esaProcessor::surpressArgCountWarning().
BBP::esa::INSTRUCTION (and)
Definition at line 1325 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case AND_HANDLE:
        suffix = 0;
        break;
    case ANDIP_HANDLE:
        suffix = userspace::inplace;
        break;
    case ANDB_HANDLE: // I AM ORB!!!!!!!!!!!!!!!!!!!!!!!!! FUCK YOU MOTHERFUCKERSSSSSSSSSSSSSSSSS
        suffix = userspace::bitwise;
        break;
    case ANDBIP_HANDLE:
        suffix = userspace::bitwise | userspace::inplace;
        break;
    }
    // Set instruction
    processor.setInstruction(userspace::AND, suffix, 0, 2);
    // If in place, expect writeable value
    if (suffix | userspace::inplace)
        processor.expectAddress(0);
    else
        processor.expectAny(0);
    // Expect anything on second arg
    processor.expectAny(1);
    return nullptr;
}
References BBP::userspace::AND, AND_HANDLE, ANDB_HANDLE, ANDBIP_HANDLE, ANDIP_HANDLE, BBP::userspace::bitwise, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::inplace, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (ctrl)
Definition at line 841 of file Actions.cpp.
{
    std::byte suffix = 0;
    std::byte argCount = 0;
    switch (handle)
    {
    case RET_HANDLE:
        suffix = userspace::ret;
        argCount = 1;
        processor.surpressArgCountWarning(0);
        processor.setInstruction(userspace::CTRL, suffix, 0, argCount);
        break;
    case CALL_HANDLE:
        suffix = userspace::call;
        argCount = 8;
        processor.surpressArgCountWarning();
        processor.surpress[0] = false;
        processor.setInstruction(userspace::CTRL, suffix, 0, argCount);
        processor.expectAddress(0);
        for (std::byte n = 1; n < 8; n++)
            processor.expectAny(n);
        break;
    case CALLP_HANDLE:
        suffix = userspace::callp;
        argCount = 8;
        processor.surpressArgCountWarning();
        processor.surpress[0] = false;
        processor.setInstruction(userspace::CTRL, suffix, 0, argCount);
        processor.expectAddress(0);
        for (std::byte n = 1; n < 8; n++)
            processor.expectAny(n);
        break;
    case SYSCALL_HANDLE:
        suffix = userspace::syscall;
        argCount = 8;
        processor.surpressArgCountWarning();
        processor.surpress[0] = false;
        processor.setInstruction(userspace::CTRL, suffix, 0, argCount);
        processor.expectLiteral(0);
        for (std::byte n = 1; n < 8; n++)
            processor.expectAny(n);
        break;
    case ROUTINE_HANDLE:
        suffix = userspace::routine;
        argCount = 1;
        processor.setInstruction(userspace::CTRL, suffix, 0, argCount);
        processor.expectLiteral(0);
        break;
    }
    return nullptr;
}
References BBP::userspace::call, CALL_HANDLE, BBP::userspace::callp, CALLP_HANDLE, BBP::userspace::CTRL, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::esa::esaProcessor::expectLiteral(), BBP::Locale::Japanese::n, processor, BBP::userspace::ret, RET_HANDLE, BBP::userspace::routine, ROUTINE_HANDLE, BBP::esa::esaProcessor::setInstruction(), BBP::esa::esaProcessor::surpress, BBP::esa::esaProcessor::surpressArgCountWarning(), BBP::userspace::syscall, and SYSCALL_HANDLE.
BBP::esa::INSTRUCTION (dec)
Definition at line 997 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case DEC_HANDLE:
        suffix = 0;
        break;
    case DECF_HANDLE:
        suffix = userspace::ffloat;
        break;
    }
    processor.setInstruction(userspace::DEC, suffix, 0, 1);
    processor.expectAddress(0);
    return nullptr;
}
References BBP::userspace::DEC, DEC_HANDLE, DECF_HANDLE, BBP::esa::esaProcessor::expectAddress(), BBP::userspace::ffloat, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (div)
Definition at line 1169 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case DIV_HANDLE:
        suffix = 0;
        break;
    case DIVF_HANDLE:
        suffix = userspace::ffloat;
        break;
    case DIVIF_HANDLE:
        suffix = userspace::sfloat;
        break;
    case DIVFF_HANDLE:
        suffix = userspace::ffloat | userspace::sfloat;
        break;
    }
    // Divide always expects 2 arguments
    processor.setInstruction(userspace::DIV, suffix, 0, 2);
    processor.expectAny(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::userspace::DIV, DIV_HANDLE, DIVF_HANDLE, DIVFF_HANDLE, DIVIF_HANDLE, BBP::esa::esaProcessor::expectAny(), BBP::userspace::ffloat, processor, BBP::esa::esaProcessor::setInstruction(), and BBP::userspace::sfloat.
BBP::esa::INSTRUCTION (flag)
Definition at line 1397 of file Actions.cpp.
{
    // If simple flag handle, then just do this
    if (handle == FLAG_HANDLE)
    {
        processor.setInstruction(userspace::FLAG, 1, 0, 1);
        processor.expectLiteral(0);
        return nullptr;
    }
    // Otherwise, this is compare flag.
    processor.setInstruction(userspace::FLAG, 0, 0, 2);
    processor.surpressArgCountWarning(1);
    processor.expectAny(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAny(), BBP::esa::esaProcessor::expectLiteral(), BBP::userspace::FLAG, FLAG_HANDLE, processor, BBP::esa::esaProcessor::setInstruction(), and BBP::esa::esaProcessor::surpressArgCountWarning().
BBP::esa::INSTRUCTION (halt)
Definition at line 1609 of file Actions.cpp.
{
    switch (handle)
    {
    case HLT_HANDLE:
        processor.setInstruction(userspace::HALT, 0, 0, 0);
        return nullptr;
    case HCF_HANDLE:
        processor.setInstruction(userspace::HALT, 1, 0, 0);
        processor.esaParser.debugInformation.errName = "-Wuse-of-hcf";
        return "WHCF instruction emitted.";
    case HBU_HANDLE:
        processor.setInstruction(userspace::HALT, 2, 0, 0);
        processor.esaParser.debugInformation.errName = "-Wuse-of-hbu";
        return "WHBU instruction emitted.";
        return nullptr;
    }
    return "AUnrecognized halt instruction. Please make sure you are using the right version of ELSA.";
}
References BBP::std::Lexer::lex_context::debugInformation, BBP::std::Lexer::lex_debugInfo::errName, BBP::esa::esaProcessor::esaParser, BBP::userspace::HALT, HBU_HANDLE, HCF_HANDLE, HLT_HANDLE, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (inc)
Definition at line 977 of file Actions.cpp.
{
    std::byte suffix = 0;
    
    switch (handle)
    {
    case INC_HANDLE:
        suffix = 0;
        break;
    case INCF_HANDLE:
        suffix = userspace::ffloat;
        break;
    }
    processor.setInstruction(userspace::INC, suffix, 0, 1);
    processor.expectAddress(0);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::userspace::ffloat, BBP::userspace::INC, INC_HANDLE, INCF_HANDLE, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (jmp)
Definition at line 1417 of file Actions.cpp.
{
    if (handle == JMP_HANDLE)
    {
        processor.setInstruction(userspace::JMP, 0, 0, 1);
        processor.expectAddress(0);
        
        return nullptr;
    }
    processor.setInstruction(userspace::JMP, userspace::jmproutine, 0, 0);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::userspace::JMP, JMP_HANDLE, BBP::userspace::jmproutine, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (jmpc)
Definition at line 1431 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case JLTNR_HANDLE:
        suffix = userspace::negated;
    case JLTR_HANDLE:
        suffix |= userspace::lessthan | userspace::jmproutine;
        processor.setInstruction(userspace::JMPC, suffix, 0, 0);
        return nullptr;
    case JLTN_HANDLE:
        suffix = userspace::negated;
    case JLT_HANDLE:
        suffix |= userspace::lessthan;
        processor.setInstruction(userspace::JMPC, suffix, 0, 1);
        processor.expectAddress(0);
        return nullptr;
    case JGTNR_HANDLE:
        suffix = userspace::negated;
    case JGTR_HANDLE:
        suffix |= userspace::greaterthan | userspace::jmproutine;
        processor.setInstruction(userspace::JMPC, suffix, 0, 0);
        return nullptr;
    case JGTN_HANDLE:
        suffix = userspace::negated;
    case JGT_HANDLE:
        suffix |= userspace::greaterthan;
        processor.setInstruction(userspace::JMPC, suffix, 0, 1);
        processor.expectAddress(0);
        return nullptr;
    }
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::userspace::greaterthan, JGT_HANDLE, JGTN_HANDLE, JGTNR_HANDLE, JGTR_HANDLE, JLT_HANDLE, JLTN_HANDLE, JLTNR_HANDLE, JLTR_HANDLE, BBP::userspace::JMPC, BBP::userspace::jmproutine, BBP::userspace::lessthan, BBP::userspace::negated, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (jmpz)
Definition at line 1473 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case JLZNR_HANDLE:
        suffix = userspace::negated;
    case JLZR_HANDLE:
        suffix |= userspace::jmproutine | userspace::lessthan;
        processor.setInstruction(userspace::JMPZ, suffix, 0, 0);
        return nullptr;
    case JLZN_HANDLE:
        suffix = userspace::negated;
    case JLZ_HANDLE:
        suffix |= userspace::lessthan;
        processor.setInstruction(userspace::JMPZ, suffix, 0, 1);
        processor.expectAddress(0);
        return nullptr;
    case JEZNR_HANDLE:
        suffix = userspace::negated;
    case JEZR_HANDLE:
        suffix |= userspace::jmproutine | userspace::equalto;
        processor.setInstruction(userspace::JMPZ, suffix, 0, 0);
        return nullptr;
    case JEZN_HANDLE:
        suffix = userspace::negated;
    case JEZ_HANDLE:
        suffix |= userspace::equalto;
        processor.setInstruction(userspace::JMPZ, suffix, 0, 1);
        processor.expectAddress(0);
        return nullptr;
    case JGZNR_HANDLE:
        suffix = userspace::negated;
    case JGZR_HANDLE:
        suffix |= userspace::jmproutine | userspace::greaterthan;
        processor.setInstruction(userspace::JMPZ, suffix, 0, 0);
        return nullptr;
    case JGZN_HANDLE:
        suffix = userspace::negated;
    case JGZ_HANDLE:
        suffix |= userspace::greaterthan;
        processor.setInstruction(userspace::JMPZ, suffix, 0, 1);
        processor.expectAddress(0);
        return nullptr;
    }
    return nullptr;
}
References BBP::userspace::equalto, BBP::esa::esaProcessor::expectAddress(), BBP::userspace::greaterthan, JEZ_HANDLE, JEZN_HANDLE, JEZNR_HANDLE, JEZR_HANDLE, JGZ_HANDLE, JGZN_HANDLE, JGZNR_HANDLE, JGZR_HANDLE, JLZ_HANDLE, JLZN_HANDLE, JLZNR_HANDLE, JLZR_HANDLE, BBP::userspace::jmproutine, BBP::userspace::JMPZ, BBP::userspace::lessthan, BBP::userspace::negated, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (lbs)
Definition at line 1225 of file Actions.cpp.
{
    // Set based on handle
    processor.setInstruction(userspace::LBS, handle == LBS_HANDLE ? 0 : userspace::inplace, 0, 2);
    if (handle == LBS_HANDLE)
        processor.expectAny(0);
    else
        processor.expectAddress(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::inplace, BBP::userspace::LBS, LBS_HANDLE, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (mem)
Definition at line 899 of file Actions.cpp.
{
    
    std::byte firsttype = 0;
    std::byte secondtype = 0;
    // Decode first type
    switch (handle)
    {
    case MOVB_HANDLE:
    case MOVBH_HANDLE:
    case MOVBW_HANDLE:
    case MOVBA_HANDLE:
        firsttype = userspace::fbyte;
        break;
    case MOVH_HANDLE:
    case MOVHB_HANDLE:
    case MOVHW_HANDLE:
    case MOVHA_HANDLE:
        firsttype = userspace::fhalfword;
        break;
    case MOVW_HANDLE:
    case MOVWB_HANDLE:
    case MOVWH_HANDLE:
    case MOVWA_HANDLE:
        firsttype = userspace::fword;
        break;
    case MOVA_HANDLE:
    case MOVAB_HANDLE:
    case MOVAH_HANDLE:
    case MOVAW_HANDLE:
        firsttype = userspace::faddress;
        break;
    }
    // Decode second type
    switch (handle)
    {
    case MOVB_HANDLE:
    case MOVHB_HANDLE:
    case MOVWB_HANDLE:
    case MOVAB_HANDLE:
        secondtype = userspace::sbyte;
        break;
    case MOVH_HANDLE:
    case MOVBH_HANDLE:
    case MOVWH_HANDLE:
    case MOVAH_HANDLE:
        secondtype = userspace::shalfword;
        break;
    case MOVW_HANDLE:
    case MOVBW_HANDLE:
    case MOVHW_HANDLE:
    case MOVAW_HANDLE:
        secondtype = userspace::sword;
        break;
    case MOVA_HANDLE:
    case MOVBA_HANDLE:
    case MOVHA_HANDLE:
    case MOVWA_HANDLE:
        secondtype = userspace::saddress;
        break;
    }
    processor.setInstruction(userspace::MEM, firsttype | secondtype, 0, 2);
    processor.expectAddress(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::faddress, BBP::userspace::fbyte, BBP::userspace::fhalfword, BBP::userspace::fword, BBP::userspace::MEM, MOVA_HANDLE, MOVAB_HANDLE, MOVAH_HANDLE, MOVAW_HANDLE, MOVB_HANDLE, MOVBA_HANDLE, MOVBH_HANDLE, MOVBW_HANDLE, MOVH_HANDLE, MOVHA_HANDLE, MOVHB_HANDLE, MOVHW_HANDLE, MOVW_HANDLE, MOVWA_HANDLE, MOVWB_HANDLE, MOVWH_HANDLE, processor, BBP::userspace::saddress, BBP::userspace::sbyte, BBP::esa::esaProcessor::setInstruction(), and BBP::userspace::shalfword.
BBP::esa::INSTRUCTION (mod)
Definition at line 1197 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case ADD_HANDLE:
        suffix = 0;
        break;
    case ADDF_HANDLE:
        suffix = userspace::ffloat;
        break;
    case ADDIF_HANDLE:
        suffix = userspace::sfloat;
        break;
    case ADDFF_HANDLE:
        suffix = userspace::ffloat | userspace::sfloat;
        break;
    }
    
    // Mod always expects 2 arguments
    processor.setInstruction(userspace::MOD, suffix, 0, 2);
    processor.expectAny(0);
    processor.expectAny(1);
    return nullptr;
}
References ADD_HANDLE, ADDF_HANDLE, ADDFF_HANDLE, ADDIF_HANDLE, BBP::esa::esaProcessor::expectAny(), BBP::userspace::ffloat, BBP::userspace::MOD, processor, BBP::esa::esaProcessor::setInstruction(), and BBP::userspace::sfloat.
BBP::esa::INSTRUCTION (mul)
Definition at line 1125 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case MUL_HANDLE:
        suffix = 0;
        break;
    case MULF_HANDLE:
        suffix = userspace::ffloat;
        break;
    case MULIF_HANDLE:
        suffix = userspace::sfloat;
        break;
    case MULFF_HANDLE:
        suffix = userspace::ffloat | userspace::sfloat;
        break;
    }
    // If the handle is MUL, expect any amount of args
    if (handle == MUL_HANDLE)
    {
        processor.setInstruction(userspace::MUL, suffix, 0, 8);
        processor.surpressArgCountWarning();
        processor.expectAny(0);
        processor.expectAny(1);
        processor.expectAny(2);
        processor.expectAny(3);
        processor.expectAny(4);
        processor.expectAny(5);
        processor.expectAny(6);
        processor.expectAny(7);
        return nullptr;
    }
    processor.setInstruction(userspace::MUL, suffix, 0, 2);
    processor.expectAny(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAny(), BBP::userspace::ffloat, BBP::userspace::MUL, MUL_HANDLE, MULF_HANDLE, MULFF_HANDLE, MULIF_HANDLE, processor, BBP::esa::esaProcessor::setInstruction(), BBP::userspace::sfloat, and BBP::esa::esaProcessor::surpressArgCountWarning().
BBP::esa::INSTRUCTION (neg)
Definition at line 1017 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case NEG_HANDLE:
        suffix = 0;
        break;
    case NEGF_HANDLE:
        suffix = userspace::ffloat;
        break;
    }
    processor.setInstruction(userspace::NEG, suffix, 0, 1);
    processor.expectAddress(0);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::userspace::ffloat, BBP::userspace::NEG, NEG_HANDLE, NEGF_HANDLE, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (nil)
Definition at line 808 of file Actions.cpp.
{
    processor.setInstruction(userspace::NIL, 0, 0, 0);
    return nullptr;
}
References BBP::userspace::NIL, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (not)
Definition at line 1361 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case NOT_HANDLE:
        suffix = 0;
        break;
    case NOTIP_HANDLE:
        suffix = userspace::inplace;
        break;
    case NOTB_HANDLE: // I AM ORB!!!!!!!!!!!!!!!!!!!!!!!!! FUCK YOU MOTHERFUCKERSSSSSSSSSSSSSSSSS
        suffix = userspace::bitwise;
        break;
    case NOTBIP_HANDLE:
        suffix = userspace::bitwise | userspace::inplace;
        break;
    }
    // Set instruction
    processor.setInstruction(userspace::NOT, suffix, 0, 2);
    // If in place, expect writeable value
    if (suffix | userspace::inplace)
        processor.expectAddress(0);
    else
        processor.expectAny(0);
    // Expect anything on second arg
    processor.expectAny(1);
    return nullptr;
}
References BBP::userspace::bitwise, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::inplace, BBP::userspace::NOT, NOT_HANDLE, NOTB_HANDLE, NOTBIP_HANDLE, NOTIP_HANDLE, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (or)
Definition at line 1253 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case OR_HANDLE:
        suffix = 0;
        break;
    case ORIP_HANDLE:
        suffix = userspace::inplace;
        break;
    case ORB_HANDLE: // I AM ORB!!!!!!!!!!!!!!!!!!!!!!!!! FUCK YOU MOTHERFUCKERSSSSSSSSSSSSSSSSS
        suffix = userspace::bitwise;
        break;
    case ORBIP_HANDLE:
        suffix = userspace::bitwise | userspace::inplace;
        break;
    }
    // Set instruction
    processor.setInstruction(userspace::OR, suffix, 0, 2);
    // If in place, expect writeable value
    if (suffix | userspace::inplace)
        processor.expectAddress(0);
    else
        processor.expectAny(0);
    // Expect anything on second arg
    processor.expectAny(1);
    return nullptr;
}
References BBP::userspace::bitwise, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::inplace, BBP::userspace::OR, OR_HANDLE, ORB_HANDLE, ORBIP_HANDLE, ORIP_HANDLE, processor, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (page)
Definition at line 1536 of file Actions.cpp.
{
   switch(handle)
   {
   case PAGE_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::assign | userspace::read | userspace::write, 0, 1);
       processor.expectLiteral(0);
       return nullptr;
   case PAGEAW_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::assign | userspace::write, 0, 1);
       processor.expectLiteral(0);
       return nullptr;
   case PAGEAR_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::assign | userspace::read, 0, 1);
       processor.expectLiteral(0);
       return nullptr;
   case PAGEW_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::write, 0, 2);
       processor.expectLiteral(0);
       processor.expectAny(1);
       return nullptr;
   case PAGER_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::read, 0, 2);
       processor.expectLiteral(0);
       processor.expectAny(1);
       return nullptr;
   case PALLOC_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::assign | userspace::memoryOp | userspace::sizeOp, 0, 1);
       processor.expectLiteral(0);
       return nullptr;
   case PFREE_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::memoryOp | userspace::sizeOp, 0, 0);
       return nullptr;
   case PAGES_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::sizeOp | userspace::read, 0, 2);
       processor.expectAddress(0);
       processor.expectLiteral(1);
       return nullptr;
   case PAGEBC_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::sizeOp | userspace::read | userspace::bytes, 0, 2);
       processor.expectAddress(0);
       processor.expectLiteral(1);
       return nullptr;
   case PASSIGN_HANDLE:
       processor.setInstruction(userspace::PAGE, userspace::assign | userspace::read | userspace::write | userspace::memoryOp, 0, 1);
       processor.expectAddress(0);
       return nullptr;
   }
   return "APage instruction not recognized. Please ensure you are using the right version of ELSA.";
}
References BBP::userspace::assign, BBP::userspace::bytes, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::esa::esaProcessor::expectLiteral(), BBP::userspace::memoryOp, BBP::userspace::PAGE, PAGE_HANDLE, PAGEAR_HANDLE, PAGEAW_HANDLE, PAGEBC_HANDLE, PAGER_HANDLE, PAGES_HANDLE, PAGEW_HANDLE, PALLOC_HANDLE, PASSIGN_HANDLE, PFREE_HANDLE, processor, BBP::userspace::read, BBP::esa::esaProcessor::setInstruction(), BBP::userspace::sizeOp, and BBP::userspace::write.
BBP::esa::INSTRUCTION (rbs)
Definition at line 1239 of file Actions.cpp.
{
    // Set based on handle
    processor.setInstruction(userspace::LBS, handle == RBS_HANDLE ? 0 : userspace::inplace, 0, 2);
    if (handle == RBS_HANDLE)
        processor.expectAny(0);
    else
        processor.expectAddress(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::inplace, BBP::userspace::LBS, processor, RBS_HANDLE, and BBP::esa::esaProcessor::setInstruction().
BBP::esa::INSTRUCTION (signal)
Definition at line 1593 of file Actions.cpp.
{
    processor.setInstruction(userspace::SIGNAL, handle == SIGNALF_HANDLE ? 1 : 0, 0, handle == SIGNALF_HANDLE ? 2 : 1);
    if (handle == SIGNALF_HANDLE)
    {
        processor.expectLiteral(0);
        processor.expectLiteral(1);
    }
    else
    {
        processor.expectLiteral(0);
    }
    return nullptr;
}
References BBP::esa::esaProcessor::expectLiteral(), processor, BBP::esa::esaProcessor::setInstruction(), BBP::userspace::SIGNAL, and SIGNALF_HANDLE.
BBP::esa::INSTRUCTION (stack)
Definition at line 815 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case PUSH_HANDLE:
        suffix = userspace::push;
        break;
    case POP_HANDLE:
        suffix = userspace::pop;
        break;
    case POPA_HANDLE:
        suffix = userspace::pop | userspace::argument;
        break;
    }
    processor.setInstruction(userspace::STACK, suffix, 0, 1);
    if (handle == PUSH_HANDLE)
        processor.expectAny(0);
    else
        processor.expectAddress(0);
    return nullptr;
}
References BBP::userspace::argument, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::pop, POP_HANDLE, POPA_HANDLE, processor, BBP::userspace::push, PUSH_HANDLE, BBP::esa::esaProcessor::setInstruction(), and BBP::userspace::STACK.
BBP::esa::INSTRUCTION (sub)
Definition at line 1081 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case SUB_HANDLE:
        suffix = 0;
        break;
    case SUBF_HANDLE:
        suffix = userspace::ffloat;
        break;
    case SUBIF_HANDLE:
        suffix = userspace::sfloat;
        break;
    case SUBFF_HANDLE:
        suffix = userspace::ffloat | userspace::sfloat;
        break;
    }
    // If the handle is SUB, expect any amount of args
    if (handle == SUB_HANDLE)
    {
        processor.setInstruction(userspace::SUB, suffix, 0, 8);
        processor.surpressArgCountWarning();
        processor.expectAny(0);
        processor.expectAny(1);
        processor.expectAny(2);
        processor.expectAny(3);
        processor.expectAny(4);
        processor.expectAny(5);
        processor.expectAny(6);
        processor.expectAny(7);
        return nullptr;
    }
    processor.setInstruction(userspace::SUB, suffix, 0, 2);
    processor.expectAny(0);
    processor.expectAny(1);
    return nullptr;
}
References BBP::esa::esaProcessor::expectAny(), BBP::userspace::ffloat, processor, BBP::esa::esaProcessor::setInstruction(), BBP::userspace::sfloat, BBP::userspace::SUB, SUB_HANDLE, SUBF_HANDLE, SUBFF_HANDLE, SUBIF_HANDLE, and BBP::esa::esaProcessor::surpressArgCountWarning().
BBP::esa::INSTRUCTION (xor)
Definition at line 1289 of file Actions.cpp.
{
    std::byte suffix = 0;
    switch (handle)
    {
    case XOR_HANDLE:
        suffix = 0;
        break;
    case XORIP_HANDLE:
        suffix = userspace::inplace;
        break;
    case XORB_HANDLE: // I AM ORB!!!!!!!!!!!!!!!!!!!!!!!!! FUCK YOU MOTHERFUCKERSSSSSSSSSSSSSSSSS
        suffix = userspace::bitwise;
        break;
    case XORBIP_HANDLE:
        suffix = userspace::bitwise | userspace::inplace;
        break;
    }
    // Set instruction
    processor.setInstruction(userspace::XOR, suffix, 0, 2);
    // If in place, expect writeable value
    if (suffix | userspace::inplace)
        processor.expectAddress(0);
    else
        processor.expectAny(0);
    // Expect anything on second arg
    processor.expectAny(1);
    return nullptr;
}
References BBP::userspace::bitwise, BBP::esa::esaProcessor::expectAddress(), BBP::esa::esaProcessor::expectAny(), BBP::userspace::inplace, processor, BBP::esa::esaProcessor::setInstruction(), BBP::userspace::XOR, XOR_HANDLE, XORB_HANDLE, XORBIP_HANDLE, and XORIP_HANDLE.
BBP::esa::PRAGMA (atomic)
Definition at line 358 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::PRAGMA (continue)
Definition at line 368 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::PRAGMA (define)
Definition at line 83 of file Actions.cpp.
{
    // Hash next word.
    std::hash_t macroHash = 0;
    bool couldHash = context->moveToAndHashNextWord(macroHash, '\n');
    // Then move up one more.
    context->atPosition++;
    // If the word could not be hashed, return an error.
    if (!couldHash)
    {
        // Reset debug info
        context->resetInfo(context->debugInformation);
        // Set other pertinent info
        context->debugInformation.errName = "-Wempty-define";
        return "WEmpty #define directive ignored.";
    }
    // Otherwise print
    if (processor.beVerbose)
        std::printf("Defining 0x%08x\n", macroHash);
    // Look for empty definition in define pages.
    std::index_t reserved = 0;
    for (std::index_t idx = 0; idx < 256; idx++)
    {
        // If we have not found a spot yet, look for an empty slot.
        if (defines[idx] == 0 && reserved == 0)
            reserved = idx;
        // We can continue checking for duplicates
        if (defines[idx] == macroHash)
        {
            if (processor.beVerbose)
                std::printf("Found duplicate hash at index %u.\n", idx);
            // Reset debug info
            context->resetInfo(context->debugInformation);
            // Set other pertinent info
            context->debugInformation.errName = "-Wduplicate-define";
            context->debugInformation.highlight = index;
            context->debugInformation.highlightLength = context->atPosition - index + 1;
            context->debugInformation.highlightmsg = "N#define found here";
            return "WDuplicate #define directive ignored.";
        }
    }
    // If we have not reserved anything yet, return error.
    if (reserved == 0)
    {
        // Reset debug info
        context->resetInfo(context->debugInformation);
        // Set other pertinent info
        return "E#define directive failed: page is full.";
    }
    // Just write the hash in, and maybe be verbose
    defines[reserved] = macroHash;
    if (processor.beVerbose)
        std::printf("Stored hash 0x%08x in %u.\n", macroHash, reserved);
    return nullptr;
}
References BBP::esa::esaProcessor::beVerbose, BBP::std::printf(), and processor.
BBP::esa::PRAGMA (else)
Definition at line 328 of file Actions.cpp.
{
    // If else is found in isolation, emit warning
    if (shouldEmit.atElement == 0 || alreadyElsed.atElement == 0)
    {
        context->resetInfo(context->debugInformation);
        context->debugInformation.errName = "-Wstray-else";
        context->debugInformation.highlight = index;
        context->debugInformation.highlightLength = context->atPosition - index + 1;
        context->debugInformation.highlightmsg = "N#else found here";
        return "WConsider removing stray #else.";
    }
    if (alreadyElsed[alreadyElsed.atElement - 1])
    {
        // If already elsed, emit error.
        context->debugInformation.highlight = index;
        context->debugInformation.highlightLength = context->atPosition - index + 1;
        context->debugInformation.highlightmsg = "NHere";
        return "eMultiple #else directives used, only one is allowed.";
    }
    // Now flip it
    alreadyElsed[alreadyElsed.atElement - 1] = true;
    shouldEmit[shouldEmit.atElement - 1] = !shouldEmit[shouldEmit.atElement - 1];
    context->commentDepth = shouldEmit[shouldEmit.atElement - 1] ? 0 : 4;
    return nullptr;
}
BBP::esa::PRAGMA (endif)
Definition at line 280 of file Actions.cpp.
{
    // If endif is found in isolation, emit warning
    if (shouldEmit.atElement == 0 || alreadyElsed.atElement == 0)
    {
        context->resetInfo(context->debugInformation);
        context->debugInformation.errName = "-Wstray-endif";
        context->debugInformation.highlight = index;
        context->debugInformation.highlightLength = context->atPosition - index + 1;
        context->debugInformation.highlightmsg = "N#endif found here";
        return "WConsider removing stray #endif.";
    }
    {
        // A place where variables go to die.
        bool thebin;
        //Bye-Bye!
        shouldEmit >> thebin;
        alreadyElsed >> thebin;
    }
    // If there is nothing in the stack, just go back to normal.
    if (shouldEmit.atElement == 0 || alreadyElsed.atElement == 0)
    {
        context->commentDepth = 0;
        if (processor.beVerbose)
            std::printf("#endif resulted in comment depth %u (nesting at %u).\n", context->commentDepth, shouldEmit.atElement);
        return nullptr;
    }
    // Restore last settings.
    bool shouldContinue = shouldEmit[shouldEmit.atElement - 1];
    context->commentDepth = shouldContinue ? 0 : 4;
    if (processor.beVerbose)
    {
        std::printf("#endif resulted in comment depth %u (nesting at %u).\n#endif: Restored ", context->commentDepth, shouldEmit.atElement);
        if (shouldContinue)
            std::printf("\[0;32mGo\[0;37m.\n\n");
        else
            std::printf("\[0;31mStop\[0;37m.\n\n");
    }
    return nullptr;
}
References BBP::esa::esaProcessor::beVerbose, BBP::std::printf(), and processor.
BBP::esa::PRAGMA (handler)
Definition at line 78 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::PRAGMA (handover)
Definition at line 363 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::PRAGMA (ifdef)
Definition at line 243 of file Actions.cpp.
{
    // Hash next word.
    std::hash_t macroHash = 0;
    bool couldHash = context->moveToAndHashNextWord(macroHash, '\n');
    // If the word could not be hashed, return an error.
    if (!couldHash)
    {
        // Reset debug info
        context->resetInfo(context->debugInformation);
        // Set other pertinent info
        context->debugInformation.errName = "-Wempty-ifdef";
        return "WEmpty #ifdef directive ignored.";
    }
    // Look for that definition on the page
    for (std::index_t idx = 0; idx < 256; idx++)
    {
        // We don't care about anything that isn't our hash
        if (defines[idx] != macroHash)
            continue;
        // Entry found, which means that ifdef turns on.
        alreadyElsed << true;
        shouldEmit << false;
        return nullptr;
    }
    // Macro does not exist, so ifdef goes off.
    context->commentDepth = 4;
    alreadyElsed << false;
    shouldEmit << false;
    return nullptr;
}
BBP::esa::PRAGMA (ifndef)
Definition at line 197 of file Actions.cpp.
{
    // Hash next word.
    std::hash_t macroHash = 0;
    bool couldHash = context->moveToAndHashNextWord(macroHash, '\n');
    // Then move up one more.
    context->atPosition++;
    // If the word could not be hashed, return an error.
    if (!couldHash)
    {
        // Reset debug info
        context->resetInfo(context->debugInformation);
        // Set other pertinent info
        context->debugInformation.errName = "-Wempty-ifndef";
        return "WEmpty #ifndef directive ignored.";
    }
    // Look for that definition on the page
    for (std::index_t idx = 0; idx < 256; idx++)
    {
        // We don't care about anything that isn't our hash
        if (defines[idx] != macroHash)
            continue;
        // Entry found, which means that ifndef turns off.
        context->commentDepth = 4;
        alreadyElsed << false;
        shouldEmit << false;
        if (processor.beVerbose)
            std::printf("Processing #ifndef, hash 0x%08x. Nesting at %u.\n#ifndef: \[0;31mStop\[0;37m.\n\n", macroHash, shouldEmit.atElement);
        return nullptr;
    }
    // Macro does not exist, so ifndef stays on, so do nothing
    alreadyElsed << false;
    shouldEmit << true;
    if (processor.beVerbose)
        std::printf("Processing #ifndef, hash 0x%08x. Nesting at %u.\n#ifndef: \[0;32mGo\[0;37m.\n\n", macroHash, shouldEmit.atElement);
    return nullptr;
}
References BBP::esa::esaProcessor::beVerbose, BBP::std::printf(), and processor.
BBP::esa::PRAGMA (include)
Definition at line 14 of file Actions.cpp.
{
    // Move back one position
    context->atPosition--;
    // Move to the start of the next word, keeping in mind the newline.
    context->moveToStartOfNextWord(true);
    // Recalculate position
    context->calculateDebugPosition();
    // Since file names can appear between '<>' or '""' (but not both), create the following handle
    std::Lexer::lex_keywordhandle handles[] = { OPENANGLEBRACKET_HANDLE, CLOSEANGLEBRACKET_HANDLE, DOUBLEQUOTES_HANDLE, DOUBLEQUOTES_HANDLE };
    // Read delimiter information, and update debug information.
    std::errno_t error = processor.ExpectDelimiters(context, 4, handles, true, 1, 1, BACKSLASH_HANDLE, context->keywordStack.atElement + 2);
    context->debugInformation.highlightLength = context->atPosition - index;
    // Switch based on error code
    switch (error)
    {
    case EFAULT: // Somehow a nullpointer got here. Abort immediately.
        context->resetInfo(context->debugInformation);
        return "AMemory instability detected.";
    case EDOM: // Somehow, an odd number ended up as argc. Either programmer fault, or stack error. Abort immediately.
        context->resetInfo(context->debugInformation);
        return "APossible stack smashing detected.";
    case EEOF: // Found End Of File before anything was found.
        context->resetInfo(context->debugInformation);
        return "EExpected filename before end of file.";
    case ENOMSG:// Found End of Line before anything was found.
        context->resetInfo(context->debugInformation);
        return "EExpected filename before end of line.";
    case ELINEEND: // End of Line found before second delimiter
        context->resetInfo(context->debugInformation);
        return "EExpected closing delimiter before end of line.";
    case ENOANO: // Attempted to close delimiter before starting it.
        context->debugInformation.highlightmsg = "NHere";
        context->debugInformation.highlight = index;
        if (processor.handle == CLOSEANGLEBRACKET_HANDLE)
            return "eExpected '<' before '>'.";
        return "EExpected '\"' before filename.";
    case EILSEQ: // Mismatched delimiters
        context->debugInformation.highlightmsg = "NHere";
        context->debugInformation.highlight = index;
        if (processor.handle == CLOSEANGLEBRACKET_HANDLE)
            return "eExpected '>' after '<'.";
        return "EExpected '\"' after '\"'.";
    case EUNFOCS: // Somehow unfocused?
        context->resetInfo(context->debugInformation);
        return "AEncountered bug 0x01.";
    case EOVERFLOW: // More than one delimiter, can only really happen with <
        context->debugInformation.highlightmsg = "NHere";
        context->debugInformation.highlight = index;
        return "EUnexpected '<' after '<'.";
    }
    //context->resetInfo(context->debugInformation);
    context->debugInformation.highlight = processor.lastOpener;
    context->debugInformation.highlightLength = processor.firstCloser - processor.lastOpener;
    context->debugInformation.highlightmsg = "NHere";
    return processor.includeFile(context, index);
}
References BACKSLASH_HANDLE, CLOSEANGLEBRACKET_HANDLE, DOUBLEQUOTES_HANDLE, EDOM, EEOF, EFAULT, EILSEQ, ELINEEND, ENOANO, ENOMSG, EOVERFLOW, EUNFOCS, BBP::esa::esaProcessor::ExpectDelimiters(), BBP::esa::esaProcessor::firstCloser, BBP::esa::esaProcessor::handle, BBP::esa::esaProcessor::includeFile(), BBP::esa::esaProcessor::lastOpener, OPENANGLEBRACKET_HANDLE, and processor.
BBP::esa::PRAGMA (undef)
Definition at line 152 of file Actions.cpp.
{
    // Hash next word.
    std::hash_t macroHash = 0;
    bool couldHash = context->moveToAndHashNextWord(macroHash, '\n');
    // If the word could not be hashed, return an error.
    if (!couldHash)
    {
        // Reset debug info
        context->resetInfo(context->debugInformation);
        // Set other pertinent info
        context->debugInformation.errName = "-Wempty-undefine";
        return "WEmpty #undefine directive ignored.";
    }
    // Otherwise print
    if (processor.beVerbose)
        std::printf("Undefining 0x%08x\n", macroHash);
    // Look for that definition on the page
    for (std::index_t idx = 0; idx < 256; idx++)
    {
        // We don't care about anything that isn't our hash
        if (defines[idx] != macroHash)
            continue;
        // Entry found, now delete it and be verbose
        if (processor.beVerbose)
            std::printf("Removed hash 0x%08x from %u.\n", macroHash, idx);
        defines[idx] = 0;
        return nullptr;
    }
    // Macro does not exist
    context->resetInfo(context->debugInformation);
    context->debugInformation.errName = "-Wundef";
    context->debugInformation.highlight = index;
    context->debugInformation.highlightLength = context->atPosition - index + 1;
    context->debugInformation.highlightmsg = "N#undef found here";
    return "W#undef directive failed: macro does not exist.";
}
References BBP::esa::esaProcessor::beVerbose, BBP::std::printf(), and processor.
BBP::esa::TOKEN (backslash)
Definition at line 770 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::TOKEN (caret)
Definition at line 681 of file Actions.cpp.
{
    // Check if any routines are available
    if (processor.routineStarts.atElement == 0)
    {
        // Reset info and throw error
        context->resetInfo(context->debugInformation);
        return "ECannot find address of routine since '^' is not within routine.";
    }
    // Set argument
    processor.numericalArgument({ processor.routineStarts[processor.routineStarts.atElement - 1] }, false);
    // If instruction is part of a jmp, jmpr, or jmpc set, flag suffix absolute.
    if (processor.instruction.header.opcode == userspace::JMP || processor.instruction.header.opcode == userspace::JMPZ || processor.instruction.header.opcode == userspace::JMPC)
        processor.instruction.header.suffix |= userspace::absoluteJmp;
    return nullptr;
}
References BBP::userspace::absoluteJmp, BBP::std::Stack< K >::atElement, BBP::userspace::Instruction::header, BBP::esa::esaProcessor::instruction, BBP::userspace::JMP, BBP::userspace::JMPC, BBP::userspace::JMPZ, BBP::esa::esaProcessor::numericalArgument(), BBP::userspace::Instruction::Head::opcode, processor, BBP::esa::esaProcessor::routineStarts, and BBP::userspace::Instruction::Head::suffix.
BBP::esa::TOKEN (closeDelimiter)
Definition at line 671 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::TOKEN (colon)
Definition at line 736 of file Actions.cpp.
{
    // If not defining a instruction, return error
    if (!processor.lineIsDefiningInstruction)
        return "E':' Can only be used when constructing an instruction.";
    // Get offset
    std::offset_t subscriber = processor.calculateAbsoluteArgumentOffset();
    // Check if instruction is routine. If so, Add routine start. Also flag absolute (Since this measures distance in bytes, not instructions)
    if (processor.instruction.header.opcode == userspace::CTRL && processor.instruction.header.suffix == userspace::routine)
    {
        // Add routine start
        processor.routineStarts << subscriber;
        // Flag absolute
        processor.instruction.header.suffix |= userspace::absolute;
    }
    // Check if allowed to add subscribers
    if (processor.subscribers.atElement >= processor.subscribers.max_elements)
        return "EReached the limit of consecutive ':' tokens allowed.";
    // Add subscriber to subscribers stack
    processor.subscribers << subscriber;
    // Increase subscriber count
    std::read(&processor.routineSubscriberCount, processor.routineStarts.atElement)++;
    // Set argument
    processor.numericalArgument({'EMMA'}, false);
    return nullptr;
}
References BBP::userspace::absolute, BBP::std::Stack< K >::atElement, BBP::esa::esaProcessor::calculateAbsoluteArgumentOffset(), BBP::userspace::CTRL, BBP::userspace::Instruction::header, BBP::esa::esaProcessor::instruction, BBP::esa::esaProcessor::lineIsDefiningInstruction, BBP::std::Stack< K >::max_elements, BBP::esa::esaProcessor::numericalArgument(), BBP::userspace::Instruction::Head::opcode, processor, BBP::userspace::read, BBP::userspace::routine, BBP::esa::esaProcessor::routineStarts, BBP::esa::esaProcessor::routineSubscriberCount, BBP::esa::esaProcessor::subscribers, and BBP::userspace::Instruction::Head::suffix.
BBP::esa::TOKEN (comma)
Definition at line 676 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::TOKEN (doubleQuote)
Definition at line 702 of file Actions.cpp.
{
    
    // If inside a string, exit out of the string
    if (context->literalDepth)
    {
        // Exit the string
        context->literalDepth = 0;
        // Check if symbol is extern
        if (processor.symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN)
            return "ECannot add data to extern symbol";
        // If also defining symbol, add numericals.
        if (processor.lineIsDefiningSymbolDefinition)
        {
            for (std::index_t i = stringStart; i < context->atPosition - 1; i++)
                processor.addNumerical(std::Lexer::numerical_t{ (std::word)context->data.data[i] }, false);
        }
        return nullptr;
    }
    context->literalDepth = context->keywordStack[handle].considerLiteralDepth;
    stringStart = context->atPosition;
    return nullptr;
}
References BBP::esa::esaProcessor::addNumerical(), BBP::Locale::Japanese::i, BBP::esa::esaProcessor::lineIsDefiningSymbolDefinition, processor, stringStart, BBP::std::Lexer::lex_thing::subtype, BBP::esa::esaProcessor::symbol, and SYMTMOD_EXTERN.
BBP::esa::TOKEN (newline)
Definition at line 482 of file Actions.cpp.
{
    // Check if procedure is being defined, and is also marked extern. Because if so, emit empty function
    if (processor.lineIsDefiningProcedure && processor.externProcedure)
    {
        // Emit procedure
        std::conststring error = processor.emitProcedure();
        // Now reset procedure flags
        processor.procedureName.static_data[0] = 0;
        processor.procedureHash = 0;
        processor.startedAt = 0;
        processor.endedAt = 0;
        processor.procedureArgumentCount = 0;
        processor.doneDeclaringProcedure = false;
        processor.externProcedure = false;
        // Also reset symbol
        processor.resetSymbol();
        // Just for logging
        return error;
    }
    // Reset this flag
    processor.lineIsDefiningProcedure = false;
    // If inside a comment, exit out and continue as normals
    if (context->commentDepth == 1)
    {
        context->commentDepth = 0;
        return nullptr;
    }
    // If this line was for a symbol definition, reset it here.
    // Also, if symbol is marked extern and this point is reached, also run it. Because this is definately not a procedure then.
    if (processor.lineIsDefiningSymbolDefinition || (processor.symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN))
    {
        // Also reset extern procedure flag
        processor.externProcedure = false;
        processor.lineIsDefiningSymbolDefinition = false;
        switch (processor.buildSymbol())
        {
        case 0:
            return nullptr;
        case ENOBUFS:
            return "EUnable to register quasi symbol: quasi symbol limit reached.";
        case EADDRINUSE:
            return "EIdentifier already used.";
        case EBADR:
            return "ECannot assign symbol to procedure marked extern.";
        case 2:
            return "NOverriding extern symbol.";
        default:
            return "ECould not export symbol.";
        }
    }
    // If this line was for a instruction definition, reset it here.
    if (processor.lineIsDefiningInstruction)
    {
        // Emit instruction
        processor.emitInstruction();
        // We want to clear remains
        processor.resetInstruction();
        
        // Stop defining instructions
        processor.lineIsDefiningInstruction = false;
        return nullptr;
    }
    return nullptr;
}
References BBP::esa::esaProcessor::buildSymbol(), BBP::std::conststring, BBP::esa::esaProcessor::doneDeclaringProcedure, EADDRINUSE, EBADR, BBP::esa::esaProcessor::emitInstruction(), BBP::esa::esaProcessor::emitProcedure(), BBP::esa::esaProcessor::endedAt, ENOBUFS, BBP::esa::esaProcessor::externProcedure, BBP::esa::esaProcessor::lineIsDefiningInstruction, BBP::esa::esaProcessor::lineIsDefiningProcedure, BBP::esa::esaProcessor::lineIsDefiningSymbolDefinition, BBP::esa::esaProcessor::procedureArgumentCount, BBP::esa::esaProcessor::procedureHash, BBP::esa::esaProcessor::procedureName, processor, BBP::esa::esaProcessor::resetInstruction(), BBP::esa::esaProcessor::resetSymbol(), BBP::esa::esaProcessor::startedAt, BBP::std::STATIC_PAGE< T, K >::static_data, BBP::std::Lexer::lex_thing::subtype, BBP::esa::esaProcessor::symbol, and SYMTMOD_EXTERN.
BBP::esa::TOKEN (openDelimiter)
Definition at line 566 of file Actions.cpp.
{
    // Not interested if this keyword is not '('.
    if (handle != OPENBRACKET_HANDLE)
        return nullptr;
    // Not doing anything with procedures, do this
    if (!processor.lineIsDefiningProcedure)
    {
        // Well, we might as well flag quasi symbol
        processor.lineIsDefiningSymbolDefinition = true;
        // Start of the name is here
        processor.symbol.start = context->atPosition;
        // When in isolation, this means symbol definition. Get a hash, and move on.
        std::hash_t hash = 0;
        bool couldHash = context->moveToAndHashThisWord(hash, ')');
        // End of the name is here
        processor.symbol.end = context->atPosition;
        // If the hasher could not hash, return error.
        if (!couldHash)
            return "EInvalid symbol identifier.";
        // If the hasher reads 0, it means empty object.
        if (hash == 0 || hash == 0x1194d79c) // Magic number UwU
            return "ESymbol identifier cannot be empty.";
        // Move up and recalculate position
        context->atPosition++;
        context->calculateDebugPosition();
        return processor.setHash(hash);
    }
    // This must be the procedure identifier if this is the first time this is found
    if (std::read(&processor.procedureName, 0) == 0)
    {
        // Get procedure hash
        std::word start = context->atPosition;
        // Hash procedure identifier
        std::hash_t hash = 0;
        bool couldHash = context->moveToAndHashThisWord(hash, ')');
        // End of the name is here
        std::word end = context->atPosition;
        // If hashing failed, return error
        if (!couldHash)
            return "Einvalid procedure Identifier.";
        // Otherwise, if hash is empty, return error
        if (hash == 0 || hash == 0x1194d79c) // OMG, stop it with the magic numbers daddy ~~
            return "EProcedure identifier cannot be empty.";
        // Move up one and calculate position again
        context->atPosition++;
        context->calculateDebugPosition();
        // Set procedure names
        processor.setProcedureIdentifier(start, end, hash);
        // Return success
        return nullptr;
    }
    else if (!processor.doneDeclaringProcedure)
    {
        // This must be the second argument, I.E., the size.
        // Then read the character, and do something based on it.
        std::string_element c = std::read(&context->data, context->atPosition);
        // Check if within '0' and '8' (48 and 56)
        if (c >= '0' && c <= '8')
            processor.setProcedureArgCount(c - '0');
        else if (c == ')')
            return "EExpected a numerical constant between '0' and '8' (inclusive) between '()'.";
        else
            return "EInvalid procedure argument count.";
        // Now check for ')' immediately after
        context->atPosition++;
        context->calculateDebugPosition();
        // Then read the character, and do something based on it.
        c = std::read(&context->data, context->atPosition);
        if (c == ')')
            return nullptr;
        return "EExpected ')' immediately after numerical constant.";
    }
    else
    {
        return "EUnexpected argument supplied during procedure declaration.";
    }
    return nullptr;
}
References BBP::esa::esaProcessor::doneDeclaringProcedure, BBP::std::Lexer::lex_thing::end, BBP::Locale::Japanese::hash, BBP::esa::esaProcessor::lineIsDefiningProcedure, BBP::esa::esaProcessor::lineIsDefiningSymbolDefinition, OPENBRACKET_HANDLE, BBP::esa::esaProcessor::procedureName, processor, BBP::userspace::read, BBP::esa::esaProcessor::setHash(), BBP::esa::esaProcessor::setProcedureArgCount(), BBP::esa::esaProcessor::setProcedureIdentifier(), BBP::std::Lexer::lex_thing::start, and BBP::esa::esaProcessor::symbol.
BBP::esa::TOKEN (semicolon)
Definition at line 559 of file Actions.cpp.
{
    // Set comment depth to 1
    context->commentDepth = 1;
    return nullptr;
}
BBP::esa::TOKEN (singleQuote)
Definition at line 731 of file Actions.cpp.
{
    return nullptr;
}
BBP::esa::TOKEN (size)
Definition at line 775 of file Actions.cpp.
{
    switch (handle)
    {
    case DN_HANDLE:
        return processor.setSize(4);
    case DB_HANDLE:
        return processor.setSize(8);
    case DH_HANDLE:
        return processor.setSize(16);
    case DI_HANDLE:
        return processor.setSize(20);
    case DA_HANDLE:
        return processor.setSize(24);
    case DW_HANDLE:
        return processor.setSize(32);
    }
    // Will select default
    return processor.setSize(1);
}
References DA_HANDLE, DB_HANDLE, DH_HANDLE, DI_HANDLE, DN_HANDLE, DW_HANDLE, processor, and BBP::esa::esaProcessor::setSize().
Variable Documentation
const char BBP::esa::flags[23][8] [static]
Initial value:
= { {true, false, false, false, false, true, 0, 0},
                                            {true, false, false, false, false, true, 0, 0},
                                            {false, false, false, true, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, false, false, true, true, 0, 1},
                                            {false, false, false, false, true, true, 0, 2},
                                            {false, false, false, false, false, true, 0, 0},
                                            {false, false, true, false, false, true, 0, 0},
                                            {false, false, false, false, false, false, 0, 0},
                                            {false, false, false, false, false, false, 0, 0},
                                            {false, false, false, false, false, false, 0, 0},
                                            {false, false, false, false, false, false, 0, 0},
                                            {false, false, false, false, false, false, 0, 0},
                                            {false, false, false, false, false, false, 0, 0} }
Definition at line 64 of file Processor.cpp.
Referenced by BBP::std::ELF::ELFBuilder::emitHeader(), and BBP::esa::esaProcessor::setInstruction().
const std::Lexer::lex_action BBP::esa::keywordActions[] [static]
Initial value:
= { pragma_include, pragma_handler, pragma_define, pragma_undef, pragma_ifndef, pragma_ifdef, pragma_endif, pragma_else,
                                                                pragma_atomic, pragma_handover, pragma_continue, kw_static, kw_const, kw_virtual, kw_extern, kw_procedure, kw_end, kw_endroutine }
Definition at line 39 of file Processor.cpp.
Referenced by BBP::esa::esaProcessor::esaProcessor().
constexpr std::size_t BBP::esa::keywordCount = 18 [static], [constexpr]
Definition at line 35 of file Processor.cpp.
Referenced by BBP::esa::esaProcessor::esaProcessor().
const char* const BBP::esa::keywords[] [static]
Initial value:
= { "#include", "#handler", "#define", "#undef", "#ifndef", "#ifdef", "#endif", "#else", "#atomic", "#handover", "#continue",
                                                "static", "const", "virtual", "extern", "procedure", "end", "@@" }
Definition at line 9 of file Processor.cpp.
Referenced by BBP::esa::esaProcessor::esaProcessor(), BBP::std::Lexer::lex_context::moveToNextKeyword(), and BBP::std::Lexer::lex_context::parseFile().
const char* const BBP::esa::mnemonics[] [static]
Initial value:
= {"nil$","push$","pop$","popa$","ret$","call$",
        "callp$","syscall$",
        "movb$","movh$","movw$","mova$",
        "movbh$", "movbw$", "movba$",
        "movhb$", "movhw$", "movha$",
        "movwb$", "movwh$", "movwa$",
        "movab$", "movah$", "movaw$",
        "inc$","dec$","neg$",
        "add$","sub$","mul$","div$","mod$","incf$","decf$",
        "negf$","addf$","subf$","mulf$","divf$","modf$","addff$",
        "subff$","mulff$","divff$","modff$","addif$","subif$",
        "mulif$","divif$","modif$","lbs$","rbs$","or$","xor$",
        "and$","not$","orb$","xorb ","andb$","notb$","lbsip$","rbsip$","orip$",
        "xorip$","andip$","notip$","orbip$","xorbip$","andbip ","notbip$",
        "comp$","flag$","routine$","jmp$","jlz$","jgz$","jez$","jlt$",
        "jgt$","jlzn$","jgzn$","jezn$","jltn$","jgtn$","jmpr$","jlzr$",
        "jgzr$","jezr$","jltr$","jgtr$","jlznr$","jgznr$","jeznr$",
        "jltnr$","jgtnr$","page$","pageaw$","pagear$","pagew$",
        "pager$","palloc$","pfree$","pages$","pagebc$","passign$",
        "signal$","signalf$","hlt$","hcf$","hbu$"}
Definition at line 14 of file Processor.cpp.
const std::Lexer::lex_action BBP::esa::mnemonicsActions[] [static]
Initial value:
= {mn_nil,mn_stack,mn_stack,mn_stack,mn_ctrl,
    mn_ctrl,mn_ctrl,mn_ctrl,mn_mem,mn_mem,
    mn_mem,mn_mem,mn_mem,mn_mem,mn_mem,mn_mem,
    mn_mem,mn_mem,mn_mem,mn_mem,mn_mem,mn_mem,
    mn_mem,mn_mem,mn_inc,mn_dec,mn_neg,mn_add,
    mn_sub,mn_mul,mn_div,mn_mod,mn_inc,mn_dec,
    mn_neg,mn_add,mn_sub,mn_mul,mn_div,mn_mod,
    mn_add,mn_sub,mn_mul,mn_div,mn_mod,mn_add,
    mn_sub,mn_mul,mn_div,mn_mod,mn_lbs,mn_rbs,
    mn_or,mn_xor,mn_and,mn_not,mn_or,mn_xor,mn_and,
    mn_not,mn_lbs,mn_rbs,mn_or,mn_xor,mn_and,
    mn_not,mn_or,mn_xor,mn_and,mn_not,mn_flag,mn_flag,mn_ctrl,
    mn_jmp,mn_jmpz,mn_jmpz,mn_jmpz,mn_jmpc,mn_jmpc,
    mn_jmpz,mn_jmpz,mn_jmpz,mn_jmpc,mn_jmpc,mn_jmp,
    mn_jmpz,mn_jmpz,mn_jmpz,mn_jmpc,mn_jmpc,mn_jmpz,
    mn_jmpz,mn_jmpz,mn_jmpc,mn_jmpc,mn_page,mn_page,
    mn_page,mn_page,mn_page,mn_page,mn_page,
    mn_page,mn_page,mn_page,mn_signal,mn_signal,
    mn_halt,mn_halt,mn_halt}
Definition at line 44 of file Processor.cpp.
constexpr std::size_t BBP::esa::mnemonicsCount = 110 [static], [constexpr]
Definition at line 37 of file Processor.cpp.
Referenced by BBP::esa::esaProcessor::esaProcessor().
esaProcessor BBP::esa::processor
Definition at line 88 of file Processor.cpp.
Referenced by _numerical(), _unkown(), ACTION(), BBP::esa::esaProcessor::addReservedIdentifier(), BBP::esa::esaProcessor::buildSymbol(), INSTRUCTION(), PRAGMA(), BBP::esa::esaProcessor::saveIdentifier(), BBP::esa::esaProcessor::setInstruction(), BBP::esa::esaProcessor::setProcedureAddress(), BBP::smile_main(), and TOKEN().
const std::Lexer::lex_action BBP::esa::tokenActions[] [static]
Initial value:
= { tk_newline, tk_newline, tk_semicolon, tk_openDelimiter, tk_closeDelimiter, tk_comma, tk_openDelimiter, tk_closeDelimiter,
                                                                tk_openDelimiter, tk_closeDelimiter, tk_caret, tk_openDelimiter, tk_closeDelimiter, tk_doubleQuote, tk_singleQuote, tk_colon, tk_backslash,
                                                                tk_size, tk_size, tk_size, tk_size, tk_size, tk_size }
Definition at line 41 of file Processor.cpp.
constexpr std::size_t BBP::esa::tokenCount = 23 [static], [constexpr]
Definition at line 36 of file Processor.cpp.
Referenced by BBP::esa::esaProcessor::esaProcessor().
const char* const BBP::esa::tokens[] = { '\r', '\n', ';', '(', ')', ',', '[', ']', '{', '}', '^', '<', '>', '\'', ''', ':', '\\', 'dn', 'db', 'dh', 'di', 'da', 'dw' } [static]
Definition at line 12 of file Processor.cpp.
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.