.TH "BBP::std::colour" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::colour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Graphics\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBchan_t\fP \fBR\fP = 0xFF"
.br
.ti -1c
.RI "\fBchan_t\fP \fBG\fP = 0xFF"
.br
.ti -1c
.RI "\fBchan_t\fP \fBB\fP = 0xFF"
.br
.ti -1c
.RI "\fBchan_t\fP \fBA\fP = 0xFF"
.br
.ti -1c
.RI "\fBRGBA_t\fP \fBRGBA\fP = 0xFFFFFFFF"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file Graphics\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBchan_t\fP BBP::std::colour::A = 0xFF"

.PP
Definition at line 35 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::fill(), BBP::std::R2D::Hrule(), BBP::std::R2D::stroke(), and BBP::std::R2D::Vrule()\&.
.SS "\fBchan_t\fP BBP::std::colour::B = 0xFF"

.PP
Definition at line 34 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::Box(), BBP::std::R2D::fill(), BBP::std::R2D::Hrule(), BBP::std::R2D::stroke(), and BBP::std::R2D::Vrule()\&.
.SS "\fBchan_t\fP BBP::std::colour::G = 0xFF"

.PP
Definition at line 33 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::Box(), BBP::std::R2D::fill(), BBP::std::R2D::Hrule(), BBP::std::R2D::stroke(), and BBP::std::R2D::Vrule()\&.
.SS "\fBchan_t\fP BBP::std::colour::R = 0xFF"

.PP
Definition at line 32 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::Box(), BBP::std::R2D::fill(), BBP::std::R2D::Hrule(), BBP::std::R2D::stroke(), and BBP::std::R2D::Vrule()\&.
.SS "\fBRGBA_t\fP BBP::std::colour::RGBA = 0xFFFFFFFF"

.PP
Definition at line 36 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::fill(), BBP::std::R2D::setPixel(), and BBP::std::R2D::stroke()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
