.TH "BBP::std::DIRECTORY" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::DIRECTORY
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileSys\&.h>\fP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectoryNode\fP * \fBgetNode\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBnoderef_t\fP \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 148 of file FileSys\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDirectoryNode\fP* BBP::std::DIRECTORY::getNode ()\fC [private]\fP"

.SH "Field Documentation"
.PP 
.SS "\fBnoderef_t\fP BBP::std::DIRECTORY::node\fC [private]\fP"

.PP
Definition at line 155 of file FileSys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
