BBP::std::ResourceManager
NAME
BBP::std::ResourceManager
SYNOPSIS
#include <Resources.h>
Public Member Functions
ResourceManager ()
void * malloc (std::size_t)
void * calloc (std::size_t, std::size_t)
template<typename T > T * add_object (T *ptr)
void add_alloc (void *)
void free (void *)
void mark_deleted (void *)
void _delete (void *)
std::index_t freeAll ()
std::index_t deleteAll ()
std::index_t dealloc ()
Data Fields
std::size_t totalAllocations = 0
Private Member Functions
void free (void *, std::index_t)
void _delete (std::index_t)
std::index_t find_next_empty_alloc ()
std::index_t find_next_empty_object ()
std::index_t find_Alloc_pointer (void *)
std::index_t find_Object_pointer (void *)
Private Attributes
std::index_t invalidAllocationIndex
std::index_t nextAllocationAvailable
std::STATIC_PAGE< void *, max_allocations > allocations
std::index_t invalidObjectIndex
std::index_t nextObjectAvailable
std::STATIC_PAGE< AbstractGCEntry *, max_objects > objects
Detailed Description
Definition at line 50 of file Resources.h.
Constructor & Destructor Documentation
BBP::std::ResourceManager::ResourceManager ()
Definition at line 329 of file Resources.cpp.
{
    // I should really remove that pesky lvalue restriction..... Oh well, idc
    void *nul = nullptr;
    AbstractGCEntry *nul2 = nullptr;
    // Zero initialize allocations
    for (std::index_t t = 0; t < allocations.dataSize; t++)
        write(&allocations, nul, t);
    // Zero initialize objects
    for (std::index_t t = 0; t < objects.dataSize; t++)
        write(&objects, nul2, t);
    // Set invalid indicies
    this->invalidAllocationIndex = allocations.dataSize;
    this->invalidObjectIndex = objects.dataSize;
    // Zero-init next available things
    this->nextAllocationAvailable = 0;
    this->nextObjectAvailable = 0;
}
References BBP::std::write().
Member Function Documentation
void BBP::std::ResourceManager::_delete (std::index_t ptrIndex) [private]
Definition at line 125 of file Resources.cpp.
{
    // If index invalid, throw sigsegv signal
    if (ptrIndex == this->invalidObjectIndex)
    {
        __SIGNAL__(SIGSEGV);
    }
    // Pointer exists, so delete it.
    this->objects.data[ptrIndex]->_delete();
    delete(this->objects.data[ptrIndex]);
    this->objects.data[ptrIndex] = nullptr;
}
References __SIGNAL__, and BBP::std::SIGSEGV.
void BBP::std::ResourceManager::_delete (void * ptr)
Definition at line 108 of file Resources.cpp.
{
    // Check if pointer is not actually nullptr
    if (ptr == nullptr)
    {
        // Attempting to free nullptr: Do nothing but output something to stderr
        std::STDERR << "Attempt to delete nullptr was made." <<= std::endl;
        return;
    }
    // Attempt to find index of pointer
    std::index_t ptrIndex = find_Object_pointer(ptr);
    // Call to internal _delete function
    this->_delete(ptrIndex);
}
References BBP::std::endl, and BBP::std::STDERR.
Referenced by BBP::std::FILE::close(), BBP::esa::esaProcessor::discardAndClose(), BBP::std::execute(), and BBP::esa::esaProcessor::saveAndClose().
void BBP::std::ResourceManager::add_alloc (void * ptr)
Definition at line 44 of file Resources.cpp.
{
    // See if allocation is possible
    if (this->nextAllocationAvailable == this->invalidAllocationIndex)
        throw std::exception("Could not register alloc'd data to Resource manager: Out of allocation space.", ENOMEM);
    // Store that write into next possible alloc
    std::write(&this->allocations, ptr, this->nextAllocationAvailable);
    // Find next possible location
    this->nextAllocationAvailable = find_next_empty_alloc();
}
References ENOMEM, BBP::std::exception(), and BBP::std::write().
Referenced by malloc().
template<typename T > T* BBP::std::ResourceManager::add_object (T * ptr) [inline]
Definition at line 62 of file Resources.h.
            {
                // See if allocation is possible
                if (this->nextObjectAvailable == this->invalidObjectIndex)
                    throw std::exception("Could not register new'd data to Resource manager: Out of allocation space.", ENOMEM);
                // Store that write into next possible object
                GCEntry<T> *entry = new GCEntry<T>();
                entry->ptr = ptr;
                this->objects.data[this->nextObjectAvailable] = entry;
                totalAllocations += sizeof(T);
                // Find next possible location
                this->nextObjectAvailable = find_next_empty_object();
                // Return ptr, in case it is needed for something
                return ptr;
            }
References ENOMEM, BBP::std::exception(), find_next_empty_object(), invalidObjectIndex, nextObjectAvailable, objects, BBP::std::GCEntry< T >::ptr, and totalAllocations.
Referenced by BBP::std::execute(), and BBP::esa::esaProcessor::setupBackend().
void * BBP::std::ResourceManager::calloc (std::size_t count, std::size_t size)
Definition at line 26 of file Resources.cpp.
{
    // See if allocation is possible
    if (this->nextAllocationAvailable == this->invalidAllocationIndex)
        throw std::exception("Could not allocate bytes to Resource manager: Out of allocation space.", ENOMEM);
    // Actually calloc data
    void *data = std::ext_calloc(count, size);
    this->totalAllocations += size * count;
    //std::printf("(%p) Application allocated %u bytes during runtime. (calloc: %u)\n", this, totalAllocations, size * count);
    // Add that data
    add_alloc(data);
    // Return data
    return data;
}
References ENOMEM, BBP::std::exception(), and BBP::std::ext_calloc().
Referenced by BBP::std::ELF::SectionBuilder::Append(), BBP::std::ELF::SegmentBuilder::Append(), BBP::std::ELF::ELFBuilder::ELFBuilder(), BBP::std::Stack< BBP::std::DIRECTORY >::Extend(), BBP::std::R2D::GetFontFromFile(), and BBP::std::R2D::newWindow().
BBP::std::index_t BBP::std::ResourceManager::dealloc ()
Definition at line 321 of file Resources.cpp.
{
    std::index_t count = 0;
    count += this->freeAll();
    count += this->deleteAll();
    return count;
}
BBP::std::index_t BBP::std::ResourceManager::deleteAll ()
Definition at line 293 of file Resources.cpp.
{
    // Keep track of objects that were delete'd
    std::index_t deleteCount = 0;
    // Loop over each pointer
    for (std::index_t idx = 0; idx < objects.dataSize; idx++)
    {
        // Check if pointer exists
        if (!__UNSAFE__(std::read)(&objects, idx))
            continue;
        // Read pointer
        void *ptr = __UNSAFE__(std::read)(&objects, idx)->getRawPtr();
        // If ptr is nullptr, skip
        if (ptr == nullptr)
            continue;
        // Since this pointer has something, delete it. Also, since we know the index, just pass it.
        this->_delete(idx);
        deleteCount++;
    }
    // Return the amount of things delete'd
    return deleteCount;
}
References __UNSAFE__, and BBP::std::read().
Referenced by BBP::badapple_main(), and BBP::std::execute().
BBP::std::index_t BBP::std::ResourceManager::find_Alloc_pointer (void * ptr) [private]
Definition at line 231 of file Resources.cpp.
{
    // Loop over every pointer
    for (std::index_t idx = 0; idx < allocations.dataSize; idx++)
    {
        // Read value stored at 'idx'
        void *stored = __UNSAFE__(std::read)(&allocations, idx);
        // If 'stored' and 'ptr' are equal, return idx
        if (stored == ptr)
            return idx;
    }
    // Nothing found, return invalid pointer
    return invalidAllocationIndex;
}
References __UNSAFE__, and BBP::std::read().
BBP::std::index_t BBP::std::ResourceManager::find_next_empty_alloc () [private]
Definition at line 139 of file Resources.cpp.
{
    // Check if we are not already at free pointer
    void *ptr = std::read(&this->allocations, this->nextAllocationAvailable);
    // If we are at nullptr already, just return current location
    if (ptr == nullptr)
        return this->nextAllocationAvailable;
    // Check +1, since chances are next pointer is free
    // Careful not to cause overflow
    if (this->nextAllocationAvailable + 1 < this->allocations.dataSize)
    {
        // Read pointer
        ptr = std::read(&this->allocations, this->nextAllocationAvailable + 1);
        
        // If null, return.
        if (ptr == nullptr)
            return this->nextAllocationAvailable + 1;
    }
    // Here and Here + 1 are not free. Just search entire page.
    for (std::index_t idx = 0; idx < this->allocations.dataSize; idx++)
    {
        // Read one pointer
        ptr = __UNSAFE__(std::read)(&this->allocations, idx);
        
        // If pointer is not free, skip
        if (ptr)
            continue;
        // Return idx
        return idx;
    }
    // Nothing found at all. Return invalid pointer
    return this->invalidAllocationIndex;
}
References __UNSAFE__, and BBP::std::read().
BBP::std::index_t BBP::std::ResourceManager::find_next_empty_object () [private]
Definition at line 178 of file Resources.cpp.
{
    // Declare ptr
    void *ptr = nullptr;
    // Check if pointer exists
    if (this->objects.data[this->nextObjectAvailable])
    {
        // Check if we are not already at free pointer
        ptr = std::read(&this->objects, this->nextObjectAvailable)->getRawPtr();
        // If we are at nullptr already, just return current location
        if (ptr == nullptr)
            return this->nextObjectAvailable;
    }
    else
    {
        // Since th object at this index is apparently empty, return this index
        return this->nextObjectAvailable;
    }
    // Check +1, since chances are next pointer is free
    // Careful not to cause overflow
    if (this->nextObjectAvailable + 1 < this->objects.dataSize)
    {
        // Check if pointer exists
        if (this->objects.data[this->nextAllocationAvailable + 1] == nullptr)
            // Since th object at this index is apparently empty, return this index
            return this->nextObjectAvailable + 1;
    }
    // Here and Here + 1 are not free. Just search entire page.
    for (std::index_t idx = 0; idx < this->objects.dataSize; idx++)
    {
        // Check if pointer exists. If not, this object is empty, so return this index
        if (!this->objects.data[idx])
            return idx;
        // Read one pointer
        ptr = __UNSAFE__(std::read)(&this->objects, idx)->getRawPtr();
        // If pointer is not free, skip
        if (ptr)
            continue;
        // Return idx
        return idx;
    }
    // Nothing found at all. Return invalid pointer
    return this->invalidObjectIndex;
}
References __UNSAFE__, and BBP::std::read().
Referenced by add_object().
BBP::std::index_t BBP::std::ResourceManager::find_Object_pointer (void * ptr) [private]
Definition at line 248 of file Resources.cpp.
{
    // Loop over every pointer
    for (std::index_t idx = 0; idx < objects.dataSize; idx++)
    {
        // Check if pointer exists
        if (!this->objects.data[idx])
            continue;
        // Read value stored at 'idx'
        void *stored = __UNSAFE__(std::read)(&objects, idx)->getRawPtr();
        // If 'stored' and 'ptr' are equal, return idx
        if (stored == ptr)
            return idx;
    }
    // Nothing found, return invalid pointer
    return invalidObjectIndex;
}
References __UNSAFE__, and BBP::std::read().
void BBP::std::ResourceManager::free (void * ptr)
Definition at line 57 of file Resources.cpp.
{
    // Check if pointer is not actually nullptr
    if (ptr == nullptr)
    {
        // Attempting to free nullptr: Do nothing but output something to stderr
        std::STDERR << "Attempt to free nullptr was made." <<= std::endl;
        return;
    }
    // Attempt to find index of pointer
    std::index_t ptrIndex = find_Alloc_pointer(ptr);
    // Call to internal free function
    this->free(ptr, ptrIndex);
}
References BBP::std::endl, and BBP::std::STDERR.
Referenced by BBP::badapple_main(), BBP::std::FILE::close(), BBP::std::Stack< BBP::std::DIRECTORY >::Extend(), BBP::std::fprintf(), BBP::std::R2D::GetFontFromFile(), BBP::std::R2D::newWindow(), and BBP::shell().
void BBP::std::ResourceManager::free (void * ptr, std::index_t ptrIndex) [private]
Definition at line 74 of file Resources.cpp.
{
    // If index invalid, throw sigsegv signal
    if (ptrIndex == this->invalidAllocationIndex)
    {
        __SIGNAL__(SIGSEGV);
    }
    // Pointer exists, so free it.
    std::ext_free(ptr);
    // Then also write nullptr to index
    this->allocations.data[ptrIndex] = (void *)0;
    //__UNSAFE__(std::write)(&this->allocations, nul, ptrIndex);
}
References __SIGNAL__, BBP::std::ext_free(), and BBP::std::SIGSEGV.
BBP::std::index_t BBP::std::ResourceManager::freeAll ()
Definition at line 269 of file Resources.cpp.
{
    // Keep track of objects that were free'd
    std::index_t freeCount = 0;
    // Loop over each pointer
    for (std::index_t idx = 0; idx < allocations.dataSize; idx++)
    {
        // Read pointer
        void *ptr = __UNSAFE__(std::read)(&allocations, idx);
        // If ptr is nullptr, skip
        if (ptr == nullptr)
            continue;
        // Since this pointer has something, free it. Also, since we know the index, just pass it.
        this->free(ptr, idx);
        freeCount++;
    }
    // Return the amount of things free'd
    return freeCount;
}
References __UNSAFE__, and BBP::std::read().
Referenced by BBP::std::execute().
void * BBP::std::ResourceManager::malloc (std::size_t size)
Definition at line 8 of file Resources.cpp.
{
    // See if allocation is possible
    if (this->nextAllocationAvailable == this->invalidAllocationIndex)
        throw std::exception("Could not allocate bytes to Resource manager: Out of allocation space.", ENOMEM);
    // Actually malloc data
    void *data = std::ext_malloc(size);
    this->totalAllocations += size;
    //std::printf("(%p) Application allocated %u bytes during runtime. (malloc: %u)\n", this, this->totalAllocations, size);
    // Add that data
    add_alloc(data);
    // Return data
    return data;
}
References add_alloc(), ENOMEM, BBP::std::exception(), BBP::std::ext_malloc(), invalidAllocationIndex, nextAllocationAvailable, and totalAllocations.
void BBP::std::ResourceManager::mark_deleted (void * ptr)
Definition at line 90 of file Resources.cpp.
{
    // Check if pointer is not actually nullptr
    if (ptr == nullptr)
    {
        // Attempting to free nullptr: Do nothing but output something to stderr
        std::STDERR << "Attempt to delete nullptr was made." <<= std::endl;
        return;
    }
    // Attempt to find index of pointer
    std::index_t ptrIndex = find_Object_pointer(ptr);
    // Write nullptr to index
    delete(this->objects.data[ptrIndex]);
    this->objects.data[ptrIndex] = nullptr;
}
References BBP::std::endl, and BBP::std::STDERR.
Field Documentation
std::STATIC_PAGE<void *, max_allocations> BBP::std::ResourceManager::allocations [private]
Definition at line 110 of file Resources.h.
std::index_t BBP::std::ResourceManager::invalidAllocationIndex [private]
Definition at line 108 of file Resources.h.
Referenced by malloc().
std::index_t BBP::std::ResourceManager::invalidObjectIndex [private]
Definition at line 113 of file Resources.h.
Referenced by add_object().
std::index_t BBP::std::ResourceManager::nextAllocationAvailable [private]
Definition at line 109 of file Resources.h.
Referenced by malloc().
std::index_t BBP::std::ResourceManager::nextObjectAvailable [private]
Definition at line 114 of file Resources.h.
Referenced by add_object().
std::STATIC_PAGE<AbstractGCEntry *, max_objects> BBP::std::ResourceManager::objects [private]
Definition at line 115 of file Resources.h.
Referenced by add_object().
std::size_t BBP::std::ResourceManager::totalAllocations = 0
Definition at line 59 of file Resources.h.
Referenced by add_object(), and malloc().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.