.TH "BBP::std::ELF::RelEntry" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::ELF::RelEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ELF32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::address_t\fP \fBr_offset\fP"
.br
.ti -1c
.RI "\fBstd::word\fP \fBr_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 221 of file ELF32\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBstd::word\fP BBP::std::ELF::RelEntry::r_info"

.PP
Definition at line 223 of file ELF32\&.h\&.
.PP
Referenced by BBP::esa::esaProcessor::emitRelocation()\&.
.SS "\fBstd::address_t\fP BBP::std::ELF::RelEntry::r_offset"

.PP
Definition at line 222 of file ELF32\&.h\&.
.PP
Referenced by BBP::esa::esaProcessor::emitRelocation()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
