BBP::std::ELF::SectionBuilder
NAME
BBP::std::ELF::SectionBuilder
SYNOPSIS
#include <ELF.h>
Public Member Functions
std::word name (void)
void name (std::word)
std::word type (void)
void type (std::word)
std::word flags (void)
void flags (std::word)
std::address_t addr (void)
void addr (std::address_t)
std::offset_t offset (void)
void offset (std::offset_t)
std::word size (void)
void size (std::word)
std::word link (void)
void link (std::word)
std::word info (void)
void info (std::word)
std::word addralign (void)
void addralign (std::word)
std::word entsize (void)
void entsize (std::word)
void Append (std::size_t)
void Extend (std::size_t)
void close ()
SectionBuilder (ELFBuilder *, std::offset_t)
SectionBuilder (ELFBuilder *, string_element *, std::size_t)
Data Fields
PAGE< string_element > header
Stack< string_element > stack
PAGE< string_element > data
ELFBuilder * elf
bool isMemUnique
Detailed Description
Definition at line 199 of file ELF.h.
Constructor & Destructor Documentation
BBP::std::ELF::SectionBuilder::SectionBuilder (ELFBuilder * elf, std::offset_t offset)
Definition at line 37 of file SectionBuilderGettersSetters.cpp.
    : header(PAGE<string_element>(ELF_SEGMENT_HEADERSIZE, elf->file.data + offset)),
    stack(&data, 0),
    data(PAGE<string_element>()),
    elf(elf),
    isMemUnique(false) {}
BBP::std::ELF::SectionBuilder::SectionBuilder (ELFBuilder *, string_element *, std::size_t)
Member Function Documentation
void BBP::std::ELF::SectionBuilder::addr (std::address_t value)
Definition at line 54 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_ADDROFFSET); }
References ELF_SECTION_ADDROFFSET, and writeWord().
BBP::std::address_t BBP::std::ELF::SectionBuilder::addr (void)
Definition at line 53 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_ADDROFFSET); }
References ELF_SECTION_ADDROFFSET, and readWord().
void BBP::std::ELF::SectionBuilder::addralign (std::word value)
Definition at line 69 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_ADDRALIGNOFFSET); }
References ELF_SECTION_ADDRALIGNOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::addralign (void)
Definition at line 68 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_ADDRALIGNOFFSET); }
References ELF_SECTION_ADDRALIGNOFFSET, and readWord().
void BBP::std::ELF::SectionBuilder::Append (std::size_t size)
Definition at line 3 of file SectionBuilder.cpp.
{
    // If size is 0, do nothing
    if (size == 0)
        return;
    // If builder is null, signal SIGSEV
    if (elf == nullptr)
    {
        __SIGNAL__(SIGSEGV);
    }
    // Do not overwrite old data. if old data exists, throw error
    if (data.dataSize)
        throw std::exception("Data overwrite attempt.", EALREADY);
    // Get current length of elf page
    std::size_t currentLength = std::seqlen(elf->file);
    // Save offset and size to header
    offset(currentLength);
    this->size(size);
    // Now create a new page
    data = std::string(size, (std::string_element *)elf->allocator->calloc(size, sizeof(std::string_element)));
    isMemUnique = true;
    // Then set the stack to that page
    stack = std::Stack<string_element>(&data, size);
    // Then append the data
    std::last(elf->file).nextPage = &data;
}
References __SIGNAL__, BBP::std::ELF::ELFBuilder::allocator, BBP::std::ResourceManager::calloc(), data, BBP::std::PAGE< T >::dataSize, EALREADY, elf, BBP::std::exception(), BBP::std::ELF::ELFBuilder::file, isMemUnique, BBP::std::last(), offset(), BBP::std::seqlen(), BBP::std::SIGSEGV, size(), and stack.
void BBP::std::ELF::SectionBuilder::close ()
Definition at line 59 of file SectionBuilder.cpp.
{
    // If builder is null, signal SIGSEV
    if (elf == nullptr)
    {
        __SIGNAL__(SIGSEGV);
    }
    // If mem is unique, free it.
    if (isMemUnique)
        elf->allocator->free(data.data);
}
References __SIGNAL__, and BBP::std::SIGSEGV.
Referenced by BBP::std::ELF::ELFBuilder::close().
void BBP::std::ELF::SectionBuilder::entsize (std::word value)
Definition at line 72 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_ENTSIZEOFFSET); }
References ELF_SECTION_ENTSIZEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::entsize (void)
Definition at line 71 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_ENTSIZEOFFSET); }
References ELF_SECTION_ENTSIZEOFFSET, and readWord().
Referenced by BBP::std::ELF::ELFBuilder::ELFBuilder().
void BBP::std::ELF::SectionBuilder::Extend (std::size_t size)
Definition at line 37 of file SectionBuilder.cpp.
{
    // If builder is null, signal SIGSEV
    if (elf == nullptr)
    {
        __SIGNAL__(SIGSEGV);
    }
    // Can only extend old data, so if data does not exist, throw error.
    if (!data.dataSize)
        throw std::exception("Attempt to extend empty data.", EADDRNOTAVAIL);
    stack.Extend(elf->allocator, size);
    // Then update the size variable in this header
    this->size(this->size() + size);
    // Then recalculate offsets only for sections and headers after this one
    elf->recalculateOffsets(offset(), size);
}
References __SIGNAL__, EADDRNOTAVAIL, BBP::std::exception(), and BBP::std::SIGSEGV.
void BBP::std::ELF::SectionBuilder::flags (std::word value)
Definition at line 51 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_FLAGSOFFSET); }
References ELF_SECTION_FLAGSOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::flags (void)
Definition at line 50 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_FLAGSOFFSET); }
References ELF_SECTION_FLAGSOFFSET, and readWord().
void BBP::std::ELF::SectionBuilder::info (std::word value)
Definition at line 66 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_INFOOFFSET); }
References ELF_SECTION_INFOOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::info (void)
Definition at line 65 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_INFOOFFSET); }
References ELF_SECTION_INFOOFFSET, and readWord().
void BBP::std::ELF::SectionBuilder::link (std::word value)
Definition at line 63 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_LINKOFFSET); }
References ELF_SECTION_LINKOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::link (void)
Definition at line 62 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_LINKOFFSET); }
References ELF_SECTION_LINKOFFSET, and readWord().
Referenced by BBP::std::ELF::ELFBuilder::ELFBuilder().
void BBP::std::ELF::SectionBuilder::name (std::word value)
Definition at line 45 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_NAMEOFFSET); }
References ELF_SECTION_NAMEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::name (void)
Definition at line 44 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_NAMEOFFSET); }
References ELF_SECTION_NAMEOFFSET, and readWord().
void BBP::std::ELF::SectionBuilder::offset (std::offset_t value)
Definition at line 57 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_OFFSETOFFSET); }
References ELF_SECTION_OFFSETOFFSET, and writeWord().
BBP::std::offset_t BBP::std::ELF::SectionBuilder::offset (void)
Definition at line 56 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_OFFSETOFFSET); }
References ELF_SECTION_OFFSETOFFSET, and readWord().
Referenced by Append(), and BBP::smile_main().
void BBP::std::ELF::SectionBuilder::size (std::word value)
Definition at line 60 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_SIZEOFFSET); }
References ELF_SECTION_SIZEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::size (void)
Definition at line 59 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_SIZEOFFSET); }
References ELF_SECTION_SIZEOFFSET, and readWord().
Referenced by Append(), and BBP::std::ELF::ELFBuilder::ELFBuilder().
void BBP::std::ELF::SectionBuilder::type (std::word value)
Definition at line 48 of file SectionBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SECTION_TYPEOFFSET); }
References ELF_SECTION_TYPEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SectionBuilder::type (void)
Definition at line 47 of file SectionBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SECTION_TYPEOFFSET); }
References ELF_SECTION_TYPEOFFSET, and readWord().
Field Documentation
PAGE<string_element> BBP::std::ELF::SectionBuilder::data
Definition at line 235 of file ELF.h.
Referenced by Append().
ELFBuilder* BBP::std::ELF::SectionBuilder::elf
Definition at line 242 of file ELF.h.
Referenced by Append(), readWord(), and writeWord().
PAGE<string_element> BBP::std::ELF::SectionBuilder::header
Definition at line 233 of file ELF.h.
Referenced by readWord(), and writeWord().
bool BBP::std::ELF::SectionBuilder::isMemUnique
Definition at line 243 of file ELF.h.
Referenced by Append().
Stack<string_element> BBP::std::ELF::SectionBuilder::stack
Definition at line 234 of file ELF.h.
Referenced by BBP::esa::ACTION(), Append(), and BBP::esa::esaProcessor::setProcedureAddress().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.