BBP::esa::BinaryApplication
NAME
BBP::esa::BinaryApplication
SYNOPSIS
#include <ELSABackend.h>
Public Member Functions
BinaryApplication (std::conststring fileName, std::size_t extraSegments, std::size_t extraSections, std::size_t extraSymbols)
void addDataToSection (std::index_t, dataEntry &)
void addSymbol (dataEntry &, std::conststring)
void addSymbol (dataEntry &, std::conststring, std::index_t)
void emitSymbol (std::index_t, dataEntry &, std::conststring, std::hash_t, std::index_t)
bool emitSymbolHash (std::hash_t hash, std::index_t symbol)
void setSource (std::conststring)
void appendSymbols (std::index_t)
void mangle (std::conststring name, std::Lexer::lex_thing &thing, dataEntry &entry)
void save ()
void close ()
Data Fields
std::ELF::ELFBuilder builder
std::Stack< std::string_element > builderStack
std::FILE file
std::static_string< 128 > mangledPage
std::Stack< std::string_element > mangled
Detailed Description
Definition at line 58 of file ELSABackend.h.
Constructor & Destructor Documentation
BBP::esa::BinaryApplication::BinaryApplication (std::conststring fileName, std::size_t extraSegments, std::size_t extraSections, std::size_t extraSymbols)
Definition at line 5 of file Builder.cpp.
    :
    builder(std::activemem, extraSegments, 14 + extraSections, 1 + extraSymbols),
    builderStack(&builder.file, std::seqlen(builder.file)),
    file(builderStack, name),
    mangled(&mangledPage, 128)
{
    // Form the standard stuff
    builder.formStandard(255, 255, 255, 255);
}
References builder, and BBP::std::ELF::ELFBuilder::formStandard().
Member Function Documentation
void BBP::esa::BinaryApplication::addDataToSection (std::index_t section, esa::dataEntry & entry)
Definition at line 16 of file Builder.cpp.
{
    // If the section has a size of 0, append then recalculate
    if (builder.sections[section].stack.max_elements == 0)
    {
        builder.sections[section].Append(entry.size);
        builder.sections[section].size(entry.size);
        // Then recalculate offsets only for sections and headers after this one
        builder.recalculateOffsets(builder.sections[section].offset(), entry.size);
    }
    // Get offset within section
    entry.offset = builder.sections[section].stack.atElement;
    entry.elfData = &builder.sections[section].stack[entry.offset];
    // If the section offset is bigger than the requested data,
    if (entry.offset + entry.size > builder.sections[section].stack.max_elements)
    {
        // If section does not have shentsize, do this
        if (builder.sections[section].entsize() == 0)
            builder.sections[section].Extend(entry.size > 128 ? entry.size : 128);
        else
        {
            // Otherwise, just print something out
            std::word deficit = entry.offset + entry.size - builder.sections[section].stack.max_elements;
            std::word esize = builder.sections[section].entsize();
            // Calculate the amount of times entsize needs to be expanded
            std::halfword leftOver = deficit % esize;
            std::word count = (deficit / esize) + !!(leftOver);
            builder.sections[section].Extend(count * esize);
        }
    }
    // Then write the data, if it exists.
    Goto::Hell();
    if (entry.data != nullptr)
        for (std::index_t idx = 0; idx < entry.size; idx++)
            builder.sections[section].stack << entry.data[idx];
    else
        builder.sections[section].stack.atElement += entry.size; // If it doesn't, just artificially move the stack.
}
References BBP::esa::dataEntry::data, BBP::esa::dataEntry::elfData, Goto::Hell(), BBP::esa::dataEntry::offset, and BBP::esa::dataEntry::size.
void BBP::esa::BinaryApplication::addSymbol (esa::dataEntry & entry, std::conststring name)
Definition at line 62 of file Builder.cpp.
{
    // Get next symbol
    entry.symbol = builder.symbols.atElement;
    builder.symbols.atElement++;
    // Rename symbol to name
    builder.renameSymbol(entry.symbol, name);
    // Also save data size
    builder.symbols[entry.symbol].size(entry.size);
    // Then set type
    builder.symbols[entry.symbol].info(entry.type);
}
References BBP::esa::dataEntry::size, BBP::esa::dataEntry::symbol, and BBP::esa::dataEntry::type.
void BBP::esa::BinaryApplication::addSymbol (esa::dataEntry & entry, std::conststring name, std::index_t _override)
Definition at line 79 of file Builder.cpp.
{
    // Get next symbol
    entry.symbol = _override;
    // Rename symbol to name
    builder.renameSymbol(entry.symbol, name);
    // Also save data size
    builder.symbols[entry.symbol].size(entry.size);
    // Then set type
    builder.symbols[entry.symbol].info(entry.type);
}
References BBP::esa::dataEntry::size, BBP::esa::dataEntry::symbol, and BBP::esa::dataEntry::type.
void BBP::esa::BinaryApplication::appendSymbols (std::index_t n)
Definition at line 102 of file Builder.cpp.
{
    // Save atElement
    std::index_t atElement = builder.symbols.atElement;
    // Extend symbol table
    builder._symtab().Extend(ELF_SYMBOL_ENTRYSIZE * n);
    builder.symbols.Extend(builder.allocator, n);
    builder.symbolCount += n;
    builder._symtab().info(builder.symbolCount);
    // Set ELF Info
    for (std::index_t index = 0; index < n; index++)
    {
        builder.symbols[builder.symbolCount - 1 - index].elf = &builder;
        builder.symbols[builder.symbolCount - 1 - index].header.bytes = ELF_SYMBOL_ENTRYSIZE;
        builder.symbols[builder.symbolCount - 1 - index].header.data = builder.sections[builder.symtab].data.data + ELF_SYMBOL_ENTRYSIZE * (builder.symbolCount - 1 - index);
    }
    // Extend hash table
    builder._hashtab().Extend((sizeof(std::word) / sizeof(std::byte)) * n);
    builder.hashChainCount = builder.symbolCount;
    // Testing
    builder._symtab().stack.atElement = 6 * 16;
    // Restore atElement
    builder.symbols.atElement = atElement;
}
References ELF_SYMBOL_ENTRYSIZE, and BBP::Locale::Japanese::n.
void BBP::esa::BinaryApplication::close ()
Definition at line 213 of file Builder.cpp.
{
    builder.close();
    file.close();
}
void BBP::esa::BinaryApplication::emitSymbol (std::index_t section, esa::dataEntry & entry, std::conststring name, std::hash_t hash, std::index_t _override)
Definition at line 132 of file Builder.cpp.
{
    // Check for symbol memory uniqueness, since an overwrite could loose data
    if (builder.symbols[entry.symbol].isMemUnique)
        throw std::exception("Symbol overwrite looses unique data.", EADDRINUSE);
    // If overriding, override. Otherwise, dont. LOL
    if (_override)
        addSymbol(entry, name, _override);
    else
    {
        // If symbol has reached max, extend symbols
        if (builder.symbols.atElement >= builder.symbolCount)
            appendSymbols(6);
        // Add symbol
        addSymbol(entry, name);
    }
    // Write data to section, if section is not equal to 0
    if (section)
        addDataToSection(section, entry);
    // Then also update the remaining values
    builder.symbols[entry.symbol].shndx(section);
    builder.symbols[entry.symbol].value(entry.offset);
    builder.symbols[entry.symbol].data = std::string(builder.symbols[entry.symbol].size(), entry.elfData);
    // Emit symbol hash.
    bool couldHash = emitSymbolHash(hash, entry.symbol);
    if (!couldHash)
        std::printf("ELF Builder: Failed to hash symbol\n");
}
References EADDRINUSE, BBP::esa::dataEntry::elfData, BBP::std::exception(), BBP::Locale::Japanese::hash, BBP::esa::dataEntry::offset, BBP::std::printf(), and BBP::esa::dataEntry::symbol.
bool BBP::esa::BinaryApplication::emitSymbolHash (std::hash_t hash, std::index_t symbol)
Definition at line 168 of file Builder.cpp.
{
    // Create page for 32 bit sized values
    std::PAGE<std::word> hashTable(2 + builder.hashBucketCount + builder.hashChainCount, (std::word *)builder.sections[builder.hashtab].data.data);
    // Then also write the has to the corresponding hash table.
    std::word bucket = hash % builder.hashBucketCount;
    // Check what is at bucket
    std::word bucketValue = std::read(&hashTable, 2 + bucket);
    // If value is 0, start an new bucket and stop
    if (bucketValue == 0)
    {
        std::write(&hashTable, symbol, 2 + bucket);
        return true;
    }
    // Read chain value
    for (std::index_t chainIndex = std::read(&hashTable, 2 + bucket); chainIndex < builder.hashChainCount; chainIndex++)
    {
        // Read value at chain
        std::word chainValue = std::read(&hashTable, 2 + builder.hashBucketCount + chainIndex);
        // If chain has value, continue at next chain
        if (chainValue)
        {
            chainIndex = chainValue - 1;
            continue;
        }
        // Empty symbol, write index then return
        std::write(&hashTable, symbol, 2 + builder.hashBucketCount + chainIndex);
        return true;
    }
    // Failed to hash
    return false;
}
References BBP::Locale::Japanese::hash, BBP::std::read(), and BBP::std::write().
void BBP::esa::BinaryApplication::mangle (std::conststring name, std::Lexer::lex_thing & thing, dataEntry & entry)
Definition at line 5 of file EABI.cpp.
{
    // Just a test
    mangled.page = &mangledPage;
    // Clear mangled string
    mangled.atElement = 0;
    // Then write '_Z'
    mangled << "_Z";
    // Calculate the length of the string
    std::size_t length = std::strlen(str);
    // Prepend length
    mangled < length;
    // Then write name
    mangled << str;
    if ((entry.type & std::ELF::SYM_OBJECT || thing.subtype & SYMTACC_VIRTUAL) && !(entry.type & std::ELF::SYM_FUNC))
    {
        // If variable, do the following:
        // If the thing is virtual, do the following
        if (thing.subtype & SYMTACC_VIRTUAL)
        {
            // Append the size of the object
            switch (thing.subtype & 0b111111100000)
            {
            case SYMTSZ_DN:
            case SYMTSZ_DB:
                mangled << "Z1";
                break;
            case SYMTSZ_DH:
                mangled << "Z2";
                break;
            case SYMTSZ_DA:
            case SYMTSZ_DW:
            case SYMTSZ_DI:
            case SYMTSZ_NIL:
            default:
                mangled << "Z4";
                break;
            }
            // Then append NData if this is also the data that goes into .bss
            if (entry.type != std::ELF::SYM_LOCAL)
                mangled << "NData";
        }
        else
        {
            // Otherwise, just append the size of the thing (in bytes)
            switch (thing.subtype & 0b111111100000)
            {
            case SYMTSZ_DN:
            case SYMTSZ_DB:
                mangled << "Z1";
                break;
            case SYMTSZ_DH:
                mangled << "Z2";
                break;
            case SYMTSZ_DA:
            case SYMTSZ_DW:
            case SYMTSZ_DI:
            case SYMTSZ_NIL:
            default:
                mangled << "Z4";
                break;
            }
        }
        
    }
    else if (entry.type & std::ELF::SYM_FUNC)
    {
        // If procedure, add 'P'
        mangled << "P";
        // Then write the amount of arguments it takes.
        mangled < thing.subtype;
    }
    // Then 0 terminate
    mangled << '\0';
}
References BBP::std::Stack< K >::atElement, mangled, mangledPage, BBP::std::Stack< K >::page, BBP::std::strlen(), BBP::std::Lexer::lex_thing::subtype, BBP::std::ELF::SYM_FUNC, BBP::std::ELF::SYM_LOCAL, BBP::std::ELF::SYM_OBJECT, BBP::esa::SYMTACC_VIRTUAL, BBP::esa::SYMTSZ_DA, BBP::esa::SYMTSZ_DB, BBP::esa::SYMTSZ_DH, BBP::esa::SYMTSZ_DI, BBP::esa::SYMTSZ_DN, BBP::esa::SYMTSZ_DW, BBP::esa::SYMTSZ_NIL, and BBP::esa::dataEntry::type.
void BBP::esa::BinaryApplication::save ()
Definition at line 208 of file Builder.cpp.
{
    file.writeFileToDisk();
}
void BBP::esa::BinaryApplication::setSource (std::conststring name)
Definition at line 95 of file Builder.cpp.
{
    dataEntry source("", std::ELF::SYM_FILE);
    addSymbol(source, name);
    builder.symbols[source.symbol].shndx(std::ELF::SHN_ABS);
}
References BBP::std::ELF::SHN_ABS, BBP::std::ELF::SYM_FILE, and BBP::esa::dataEntry::symbol.
Field Documentation
std::ELF::ELFBuilder BBP::esa::BinaryApplication::builder
Definition at line 87 of file ELSABackend.h.
Referenced by BBP::esa::ACTION(), BinaryApplication(), and BBP::esa::esaProcessor::setProcedureAddress().
std::Stack<std::string_element> BBP::esa::BinaryApplication::builderStack
Definition at line 88 of file ELSABackend.h.
std::FILE BBP::esa::BinaryApplication::file
Definition at line 89 of file ELSABackend.h.
std::Stack<std::string_element> BBP::esa::BinaryApplication::mangled
Definition at line 93 of file ELSABackend.h.
Referenced by mangle().
std::static_string<128> BBP::esa::BinaryApplication::mangledPage
Definition at line 92 of file ELSABackend.h.
Referenced by mangle().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.