BBP::std::ELF::SegmentBuilder
NAME
BBP::std::ELF::SegmentBuilder
SYNOPSIS
#include <ELF.h>
Public Member Functions
void Append (std::size_t dataSize)
std::word type (void)
void type (std::word)
std::offset_t offset (void)
void offset (std::offset_t)
std::address_t vaddr (void)
void vaddr (std::address_t)
std::address_t paddr (void)
void paddr (std::address_t)
std::word filesz (void)
void filesz (std::word)
std::word memsz (void)
void memsz (std::word)
std::word flags (void)
void flags (std::word)
std::word align (void)
void align (std::word)
void close ()
SegmentBuilder (ELFBuilder *, std::offset_t)
SegmentBuilder (ELFBuilder *, string_element *, std::size_t)
Data Fields
PAGE< string_element > header
Stack< string_element > stack
PAGE< string_element > data
ELFBuilder * elf
bool isMemUnique
Detailed Description
Definition at line 258 of file ELF.h.
Constructor & Destructor Documentation
BBP::std::ELF::SegmentBuilder::SegmentBuilder (ELFBuilder * elf, std::offset_t offset)
Definition at line 37 of file SegmentBuilderGettersSetters.cpp.
    : header(PAGE<string_element>(ELF_SEGMENT_HEADERSIZE, elf->file.data + offset)),
    stack(&data, 0),
    data(PAGE<string_element>()),
    elf(elf),
    isMemUnique(false) {}
BBP::std::ELF::SegmentBuilder::SegmentBuilder (ELFBuilder *, string_element *, std::size_t)
Member Function Documentation
void BBP::std::ELF::SegmentBuilder::align (std::word value)
Definition at line 66 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_ALIGNOFFSET); }
References ELF_SEGMENT_ALIGNOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SegmentBuilder::align (void)
Definition at line 65 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_ALIGNOFFSET); }
References ELF_SEGMENT_ALIGNOFFSET, and readWord().
void BBP::std::ELF::SegmentBuilder::Append (std::size_t dataSize)
Definition at line 4 of file SegmentBuilder.cpp.
{
    // If builder is null, signal SIGSEV
    if (elf == nullptr)
    {
        __SIGNAL__(SIGSEGV);
    }
    // Get current length of elf page
    std::size_t currentLength = std::seqlen(elf->file);
    // Save offset and size to header
    offset(currentLength);
    filesz(size);
    memsz(size);
    // Now create a new page
    data = std::string(size, (std::string_element *)elf->allocator->calloc(size, sizeof(std::string_element)));
    isMemUnique = true;
    // Then set the stack to that page
    stack = std::Stack<string_element>(&data, size);
    // Then append the data
    std::last(elf->file).nextPage = &data;
}
References __SIGNAL__, BBP::std::ELF::ELFBuilder::allocator, BBP::std::ResourceManager::calloc(), data, elf, BBP::std::ELF::ELFBuilder::file, filesz(), isMemUnique, BBP::std::last(), memsz(), offset(), BBP::std::seqlen(), BBP::std::SIGSEGV, and stack.
void BBP::std::ELF::SegmentBuilder::close ()
Definition at line 31 of file SegmentBuilder.cpp.
{
    // If builder is null, signal SIGSEV
    if (elf == nullptr)
    {
        __SIGNAL__(SIGSEGV);
    }
    // If mem is unique, free it.
    if (isMemUnique)
        elf->allocator->free(data.data);
}
References __SIGNAL__, and BBP::std::SIGSEGV.
Referenced by BBP::std::ELF::ELFBuilder::close().
void BBP::std::ELF::SegmentBuilder::filesz (std::word value)
Definition at line 60 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_FILESZOFFSET); }
References ELF_SEGMENT_FILESZOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SegmentBuilder::filesz (void)
Definition at line 59 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_FILESZOFFSET); }
References ELF_SEGMENT_FILESZOFFSET, and readWord().
Referenced by Append().
void BBP::std::ELF::SegmentBuilder::flags (std::word value)
Definition at line 48 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_FLAGSOFFSET); }
References ELF_SEGMENT_FLAGSOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SegmentBuilder::flags (void)
Definition at line 47 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_FLAGSOFFSET); }
References ELF_SEGMENT_FLAGSOFFSET, and readWord().
void BBP::std::ELF::SegmentBuilder::memsz (std::word value)
Definition at line 63 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_MEMSZOFFSET); }
References ELF_SEGMENT_MEMSZOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SegmentBuilder::memsz (void)
Definition at line 62 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_MEMSZOFFSET); }
References ELF_SEGMENT_MEMSZOFFSET, and readWord().
Referenced by Append().
void BBP::std::ELF::SegmentBuilder::offset (std::offset_t value)
Definition at line 51 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_OFFSETOFFSET); }
References ELF_SEGMENT_OFFSETOFFSET, and writeWord().
BBP::std::offset_t BBP::std::ELF::SegmentBuilder::offset (void)
Definition at line 50 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_OFFSETOFFSET); }
References ELF_SEGMENT_OFFSETOFFSET, and readWord().
Referenced by Append().
void BBP::std::ELF::SegmentBuilder::paddr (std::address_t value)
Definition at line 57 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_PADDROFFSET); }
References ELF_SEGMENT_PADDROFFSET, and writeWord().
BBP::std::address_t BBP::std::ELF::SegmentBuilder::paddr (void)
Definition at line 56 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_PADDROFFSET); }
References ELF_SEGMENT_PADDROFFSET, and readWord().
void BBP::std::ELF::SegmentBuilder::type (std::word value)
Definition at line 45 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_TYPEOFFSET); }
References ELF_SEGMENT_TYPEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SegmentBuilder::type (void)
Definition at line 44 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_TYPEOFFSET); }
References ELF_SEGMENT_TYPEOFFSET, and readWord().
void BBP::std::ELF::SegmentBuilder::vaddr (std::address_t value)
Definition at line 54 of file SegmentBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SEGMENT_VADDROFFSET); }
References ELF_SEGMENT_VADDROFFSET, and writeWord().
BBP::std::address_t BBP::std::ELF::SegmentBuilder::vaddr (void)
Definition at line 53 of file SegmentBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SEGMENT_VADDROFFSET); }
References ELF_SEGMENT_VADDROFFSET, and readWord().
Field Documentation
PAGE<string_element> BBP::std::ELF::SegmentBuilder::data
Definition at line 290 of file ELF.h.
Referenced by Append().
ELFBuilder* BBP::std::ELF::SegmentBuilder::elf
Definition at line 295 of file ELF.h.
Referenced by Append(), readWord(), and writeWord().
PAGE<string_element> BBP::std::ELF::SegmentBuilder::header
Definition at line 288 of file ELF.h.
Referenced by readWord(), and writeWord().
bool BBP::std::ELF::SegmentBuilder::isMemUnique
Definition at line 297 of file ELF.h.
Referenced by Append().
Stack<string_element> BBP::std::ELF::SegmentBuilder::stack
Definition at line 289 of file ELF.h.
Referenced by Append().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.