BBP::std::R2D
NAME
BBP::std::R2D
SYNOPSIS
Functions
RGBA_t convertUCHARtoINT (chan_t r, chan_t g, chan_t b, chan_t a)
void convertINTtoUCHAR (chan_t *r, chan_t *g, chan_t *b, RGBA_t rgb)
void convertINTtoUCHAR (chan_t *r, chan_t *g, chan_t *b, chan_t *a, RGBA_t rgba)
void newWindow (window *, pos_t width, pos_t height, chan_t r, chan_t g, chan_t b)
void newWindow (window *, chan_t r, chan_t g, chan_t b)
void background (window *, chan_t r, chan_t g, chan_t b)
void background (window *, chan_t r, chan_t g, chan_t b, chan_t a)
void background (window *, RGBA_t rgb)
void background (window *, RGBA_t rgb, chan_t a)
void stroke (window *, chan_t r, chan_t g, chan_t b)
void stroke (window *, chan_t r, chan_t g, chan_t b, chan_t a)
void stroke (window *, RGBA_t rgb)
void stroke (window *, RGBA_t rgb, chan_t a)
void strokeWeight (window *, word weight)
void noStroke (window *)
void fill (window *, chan_t r, chan_t g, chan_t b)
void fill (window *, chan_t r, chan_t g, chan_t b, chan_t a)
void fill (window *, RGBA_t rgb)
void fill (window *, RGBA_t rgb, chan_t a)
void noFill (window *)
void Line (window *, int x1, int y1, int x2, int y2)
void Hrule (window *, pos_t x1, pos_t x2, pos_t y)
void Vrule (window *, pos_t y1, pos_t y2, pos_t x)
void Line (window *, int x1, int y1, int x2, int y2, chan_t r, chan_t g, chan_t b)
void Hrule (window *, pos_t x1, pos_t x2, pos_t y, chan_t r, chan_t g, chan_t b)
void Vrule (window *, pos_t y1, pos_t y2, pos_t x, chan_t r, chan_t g, chan_t b)
void Line (window *, int x1, int y1, int x2, int y2, RGBA_t rgb)
void Hrule (window *, pos_t x1, pos_t x2, pos_t y, RGBA_t rgb)
void Vrule (window *, pos_t y1, pos_t y2, pos_t x, RGBA_t rgb)
void Rect (window *, pos_t x, pos_t y, pos_t w, pos_t h)
void Box (window *, pos_t x, pos_t y, pos_t w, pos_t h)
void Frame (window *, pos_t x, pos_t y, pos_t w, pos_t h)
void RectPixelMask (window *, pos_t x, pos_t y, mask_t mask)
void RectPixelMask (window *, pos_t x, pos_t y, word size, mask_t mask)
void RectPixelMaskAligned (window *, pos_t x, pos_t y, word size, mask_t mask)
void RectPixelMask (window *, pos_t x, pos_t y, mask_t *maskv, word maskc)
void RectPixelMask (window *, pos_t x, pos_t y, word size, mask_t *maskv, word maskc)
void RectPixelMaskAligned (window *, pos_t x, pos_t y, word size, mask_t *maskv, word maskc)
RGBA_t readPixel (window *, pos_t x, pos_t y)
void setPixel (window *, pos_t x, pos_t y)
void setPixel (window *, pos_t x, pos_t y, word size)
void setPixelAligned (window *, pos_t x, pos_t y, word size)
void PixelMask (window *, pos_t x, pos_t y, mask_t mask)
void PixelMask (window *, pos_t x, pos_t y, word size, mask_t mask)
void PixelMaskAligned (window *, pos_t x, pos_t y, word size, mask_t mask)
void PixelMask (window *, pos_t x, pos_t y, mask_t *maskv, word maskc)
void PixelMask (window *, pos_t x, pos_t y, word size, mask_t *maskv, word maskc)
void PixelMaskAligned (window *, pos_t x, pos_t y, word size, mask_t *maskv, word maskc)
void PrintCharacterAt (window *, pos_t x, pos_t y, ustring_element ch)
void PrintCharacterAt (window *, pos_t x, pos_t y, ustring_element ch, word size)
void print (window *, ustring_element ch)
void print (window *, ustring_element *str)
void print (window *, conststring str)
void print (window *, mem_t *str, word str_c)
void setCursorPos (window *, pos_t x, pos_t y)
void GetFontFromFile (window *, std::PATH &)
Function Documentation
void BBP::std::R2D::background (window * window, chan_t r, chan_t g, chan_t b)
Definition at line 220 of file R2D.cpp.
        {
            RGBA_t colour = R2D::convertUCHARtoINT(r, g, b, 255);
            for (std::index_t n = 0; n < window->width * window->height; n++)
                write(&window->backBuffer, colour, n);
        }
References BBP::std::window::backBuffer, convertUCHARtoINT(), BBP::std::window::height, BBP::Locale::Japanese::n, BBP::std::window::width, and BBP::std::write().
Referenced by newWindow().
void BBP::std::R2D::background (window * window, chan_t r, chan_t g, chan_t b, chan_t a)
Definition at line 226 of file R2D.cpp.
        {
            RGBA_t colour = R2D::convertUCHARtoINT(r, g, b, a);
            for (std::index_t n = 0; n < window->width * window->height; n++)
                window->backBuffer.data[n] = colour;
        }
References BBP::Locale::Japanese::a, BBP::std::window::backBuffer, convertUCHARtoINT(), BBP::std::PAGE< T >::data, BBP::std::window::height, BBP::Locale::Japanese::n, and BBP::std::window::width.
void BBP::std::R2D::background (window * window, RGBA_t rgb)
Definition at line 232 of file R2D.cpp.
        {
            for (std::index_t n = 0; n < window->width * window->height; n++)
                window->backBuffer.data[n] = rgba;
        }
References BBP::std::window::backBuffer, BBP::std::PAGE< T >::data, BBP::std::window::height, BBP::Locale::Japanese::n, and BBP::std::window::width.
void BBP::std::R2D::background (window * window, RGBA_t rgb, chan_t a)
Definition at line 237 of file R2D.cpp.
        {
            RGBA_t colour = (rgb & ~0xFF) ^ a;
            for (std::index_t n = 0; n < window->width * window->height; n++)
                window->backBuffer.data[n] = colour;
        }
References BBP::Locale::Japanese::a, BBP::std::window::backBuffer, BBP::std::PAGE< T >::data, BBP::std::window::height, BBP::Locale::Japanese::n, and BBP::std::window::width.
void BBP::std::R2D::Box (window * window, pos_t x, pos_t y, pos_t w, pos_t h)
Definition at line 395 of file R2D.cpp.
        {
            for (std::index_t Y = y; Y < y + h; Y++)
                R2D::Hrule(window, x, x + w, Y, window->Fill.R, window->Fill.G, window->Fill.B);
        }
References BBP::std::colour::B, BBP::std::window::Fill, BBP::std::colour::G, Hrule(), and BBP::std::colour::R.
Referenced by Rect(), setPixel(), and setPixelAligned().
void BBP::std::R2D::convertINTtoUCHAR (chan_t * r, chan_t * g, chan_t * b, chan_t * a, RGBA_t rgba)
Definition at line 48 of file R2D.cpp.
        {
            *r = (rgba >> 24) & 0xFF;
            *g = (rgba >> 16) & 0xFF;
            *b = (rgba >> 8) & 0xFF;
            *a = (rgba) & 0xFF;
        }
References BBP::Locale::Japanese::a.
void BBP::std::R2D::convertINTtoUCHAR (chan_t * r, chan_t * g, chan_t * b, RGBA_t rgb)
Definition at line 42 of file R2D.cpp.
        {
            *r = (rgb >> 24) & 0xFF;
            *g = (rgb >> 16) & 0xFF;
            *b = (rgb >> 8) & 0xFF;
        }
Referenced by fill(), and stroke().
RGBA_t BBP::std::R2D::convertUCHARtoINT (chan_t r, chan_t g, chan_t b, chan_t a)
Definition at line 37 of file R2D.cpp.
        {
            int ret = (r << 24) | (g << 16) | (b << 8) | a;
            return ret;
        }
References BBP::Locale::Japanese::a, and BBP::userspace::ret.
Referenced by background(), fill(), Hrule(), stroke(), and Vrule().
void BBP::std::R2D::fill (window * window, chan_t r, chan_t g, chan_t b)
Definition at line 94 of file R2D.cpp.
        {
            window->Fill.R = r;
            window->Fill.G = g;
            window->Fill.B = b;
            window->Fill.RGBA = convertUCHARtoINT(r, g, b, window->Fill.A);
            window->doFill = true;
        }
References BBP::std::colour::A, BBP::std::colour::B, convertUCHARtoINT(), BBP::std::window::doFill, BBP::std::window::Fill, BBP::std::colour::G, BBP::std::colour::R, and BBP::std::colour::RGBA.
Referenced by BBP::std::execute().
void BBP::std::R2D::fill (window * window, chan_t r, chan_t g, chan_t b, chan_t a)
Definition at line 102 of file R2D.cpp.
        {
            window->Fill.R = r;
            window->Fill.G = g;
            window->Fill.B = b;
            window->Fill.A = a;
            window->Fill.RGBA = convertUCHARtoINT(r, g, b, a);
            window->doFill = true;
        }
References BBP::std::colour::A, BBP::Locale::Japanese::a, BBP::std::colour::B, convertUCHARtoINT(), BBP::std::window::doFill, BBP::std::window::Fill, BBP::std::colour::G, BBP::std::colour::R, and BBP::std::colour::RGBA.
void BBP::std::R2D::fill (window * window, RGBA_t rgb)
Definition at line 111 of file R2D.cpp.
        {
            window->Fill.RGBA = rgb;
            convertINTtoUCHAR(&(window->Fill.R), &(window->Fill.G), &(window->Fill.B), rgb);
            window->doFill = true;
        }
References BBP::std::colour::B, convertINTtoUCHAR(), BBP::std::window::doFill, BBP::std::window::Fill, BBP::std::colour::G, BBP::std::colour::R, and BBP::std::colour::RGBA.
void BBP::std::R2D::fill (window * window, RGBA_t rgb, chan_t a)
Definition at line 117 of file R2D.cpp.
        {
            convertINTtoUCHAR(&(window->Fill.R), &(window->Fill.G), &(window->Fill.B), rgb);
            window->Fill.A = a;
            window->Fill.RGBA = convertUCHARtoINT(window->Fill.R, window->Fill.G, window->Fill.B, a);
            window->doFill = true;
        }
References BBP::std::colour::A, BBP::Locale::Japanese::a, BBP::std::colour::B, convertINTtoUCHAR(), convertUCHARtoINT(), BBP::std::window::doFill, BBP::std::window::Fill, BBP::std::colour::G, BBP::std::colour::R, and BBP::std::colour::RGBA.
void BBP::std::R2D::Frame (window * window, pos_t x, pos_t y, pos_t w, pos_t h)
Definition at line 401 of file R2D.cpp.
        {
            R2D::Hrule(window, x, x + w, y);
            R2D::Hrule(window, x, x + w, y + h);
            R2D::Vrule(window, y, y + h, x);
            R2D::Vrule(window, y, y + h, x + w);
        }
References Hrule(), and Vrule().
Referenced by Rect().
void BBP::std::R2D::GetFontFromFile (window * window, std::PATH & path)
Definition at line 167 of file R2D.cpp.
        {
            // If window pointer is invalid, do nothing.
            if (window == nullptr)
                return;
            // Open file from path
            BBP::std::FILE fontFile(path);
            byte *data = (byte *)fontFile.b().page->data;
            // Font is now in fontFile. From this, we can now obtain pointers to the data
            size_t nums = data[0];
            RGBA_t *font = (RGBA_t *)read_a(fontFile.b().page, 4);
            ustring_element *mapping = (ustring_element *)read_ar(fontFile.b().page, 4 + nums * 8);
            // First find the \0 character from ROM
            int nullCharacterIndex = 0;
            for (std::index_t i = 0; i < nums; i++)
            {
                if (mapping[i]) // If the character is not '\0', continue
                    continue;
                nullCharacterIndex = i; // \0 found!
                break;
            }
            // Then write that font map to each character
            for (std::index_t i = 0; i < 256; i++)
                window->fontMapping[i] = nullCharacterIndex;
            // Then overwrite the known fonts from the map
            for (std::index_t i = 0; i < nums; i++)
                window->fontMapping[mapping[i]] = i;
            // If there is another font stored in window, clear it
            if (window->typeFace.data)
                vmem.free(window->typeFace.data);
            // Then allocate typeface
            window->typeFace = BBP::std::PAGE<mask_t>(2 * nums, (mask_t *)vmem.calloc(2 * nums, sizeof(mask_t)));
            // Copy data
            for (BBP::std::index_t idx = 0; idx < window->typeFace.dataSize; idx++)
            {
                // TODO: Not compiler agnostic! Needs to be changed.
                word swapped = __builtin_bswap32(font[idx]);
                window->typeFace.data[idx] = swapped;
            }
            // Since everything has been copied, close the font file
            fontFile.close();
        }
References BBP::std::FILE::b(), BBP::std::ResourceManager::calloc(), BBP::std::FILE::close(), BBP::std::PAGE< T >::data, BBP::std::PAGE< T >::dataSize, BBP::std::window::fontMapping, BBP::std::ResourceManager::free(), BBP::Locale::Japanese::i, BBP::std::Stack< K >::page, BBP::std::read_a(), BBP::std::read_ar(), BBP::std::window::typeFace, and BBP::std::vmem.
void BBP::std::R2D::Hrule (window * window, pos_t x1, pos_t x2, pos_t y)
Definition at line 244 of file R2D.cpp.
        {
            RGBA_t colour = R2D::convertUCHARtoINT(window->Stroke.R, window->Stroke.G, window->Stroke.B, window->Stroke.A);
            for (std::index_t i = x1; i < x2; i++)
                window->backBuffer.data[i + window->width * y] = colour;
        }
References BBP::std::colour::A, BBP::std::colour::B, BBP::std::window::backBuffer, convertUCHARtoINT(), BBP::std::PAGE< T >::data, BBP::std::colour::G, BBP::Locale::Japanese::i, BBP::std::colour::R, BBP::std::window::Stroke, and BBP::std::window::width.
Referenced by Box(), and Frame().
void BBP::std::R2D::Hrule (window * window, pos_t x1, pos_t x2, pos_t y, chan_t r, chan_t g, chan_t b)
Definition at line 258 of file R2D.cpp.
        {
            RGBA_t colour = R2D::convertUCHARtoINT(r, g, b, 255);
            for (std::index_t i = x1; i < x2; i++)
                window->backBuffer.data[i + window->width * y] = colour;
        }
References BBP::std::window::backBuffer, convertUCHARtoINT(), BBP::std::PAGE< T >::data, BBP::Locale::Japanese::i, and BBP::std::window::width.
void BBP::std::R2D::Hrule (window * window, pos_t x1, pos_t x2, pos_t y, RGBA_t rgb)
Definition at line 272 of file R2D.cpp.
        {
            for (std::index_t i = x1; i < x2; i++)
                window->backBuffer.data[i + window->width * y] = rgb;
        }
References BBP::std::window::backBuffer, BBP::std::PAGE< T >::data, BBP::Locale::Japanese::i, and BBP::std::window::width.
void BBP::std::R2D::Line (window * window, int x1, int y1, int x2, int y2)
Definition at line 330 of file R2D.cpp.
        {
            int steep = absolute(y1 - y0) > absolute(x1 - x0);
            // swap the co-ordinates if slope > 1 or we
            // draw backwards
            if (steep)
            {
                swap(&x0, &y0);
                swap(&x1, &y1);
            }
            if (x0 > x1)
            {
                swap(&x0, &x1);
                swap(&y0, &y1);
            }
            //compute the slope
            float dx = x1 - x0;
            float dy = y1 - y0;
            float gradient = dy / dx;
            if (dx == 0.0)
                gradient = 1;
            int xpxl1 = x0;
            int xpxl2 = x1;
            float intersectY = y0;
            // main loop
            if (steep)
            {
                int x;
                for (x = xpxl1; x <= xpxl2; x++)
                {
                    // pixel coverage is determined by fractional
                    // part of y co-ordinate
                    R2D::setPixel(window, iPartOfNumber(intersectY), x);
                    R2D::setPixel(window, iPartOfNumber(intersectY) - 1, x);
                    intersectY += gradient;
                }
            }
            else
            {
                int x;
                for (x = xpxl1; x <= xpxl2; x++)
                {
                    // pixel coverage is determined by fractional
                    // part of y co-ordinate
                    R2D::setPixel(window, x, iPartOfNumber(intersectY));
                    R2D::setPixel(window, x, iPartOfNumber(intersectY) - 1);
                    intersectY += gradient;
                }
            }
        }
References BBP::std::absolute(), BBP::std::iPartOfNumber(), setPixel(), and BBP::std::swap().
void BBP::std::R2D::Line (window *, int x1, int y1, int x2, int y2, chan_t r, chan_t g, chan_t b)
void BBP::std::R2D::Line (window *, int x1, int y1, int x2, int y2, RGBA_t rgb)
void BBP::std::R2D::newWindow (window * window, chan_t r, chan_t g, chan_t b)
Definition at line 159 of file R2D.cpp.
        {
            if (window == nullptr)
                return;
            R2D::background(window, r, g, b);
        }
References background().
void BBP::std::R2D::newWindow (window * window, pos_t width, pos_t height, chan_t r, chan_t g, chan_t b)
Definition at line 130 of file R2D.cpp.
        {
            if (window == nullptr)
                return;
            // If dimensions match last window, no need to re-allocate memory
            if (window->width != width || window->height != height)
            {
                // Check if backbuffer is actually allocated
                if (window->backBuffer.data)
                    vmem.free(window->backBuffer.data);
                // Allocate new backbuffer.
                window->backBuffer = std::PAGE<RGBA_t>(width * height, (RGBA_t *)vmem.calloc(width * height, sizeof(RGBA_t)));
            }
            // If nothing was stored last time, then we might as well just re-alloc
            if ((width && !window->width) || (height && !window->height))
            {
                // Allocate new backbuffer.
                //window->backBuffer = std::PAGE<int>(width * height, (int *)vmem.calloc(width * height, sizeof(int)));
            }
            
            window->width = width;
            window->height = height;
            R2D::background(window, r, g, b);
        }
References BBP::std::window::backBuffer, background(), BBP::std::ResourceManager::calloc(), BBP::std::PAGE< T >::data, BBP::std::ResourceManager::free(), BBP::std::window::height, BBP::std::vmem, and BBP::std::window::width.
void BBP::std::R2D::noFill (window * window)
Definition at line 125 of file R2D.cpp.
        {
            window->doFill = false;
        }
References BBP::std::window::doFill.
void BBP::std::R2D::noStroke (window * window)
Definition at line 84 of file R2D.cpp.
        {
            window->doStroke = false;
        }
References BBP::std::window::doStroke.
void BBP::std::R2D::PixelMask (window * window, pos_t x, pos_t y, mask_t * maskv, word maskc)
Definition at line 493 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < maskc; i++)
                PixelMask(window, x, y + i, maskv[i]);
        }
References BBP::Locale::Japanese::i, and PixelMask().
void BBP::std::R2D::PixelMask (window * window, pos_t x, pos_t y, mask_t mask)
Definition at line 472 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < 32; i++)
                if ((mask >> (i)) & 0x1)
                    setPixel(window, x + i, y);
        }
References BBP::Locale::Japanese::i, and setPixel().
Referenced by PixelMask().
void BBP::std::R2D::PixelMask (window * window, pos_t x, pos_t y, word size, mask_t * maskv, word maskc)
Definition at line 499 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < maskc; i++)
                PixelMask(window, x, y + i * size, size, maskv[i]);
        }
References BBP::Locale::Japanese::i, and PixelMask().
void BBP::std::R2D::PixelMask (window * window, pos_t x, pos_t y, word size, mask_t mask)
Definition at line 479 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < 32; i++)
                if ((mask >> (i)) & 0x1)
                    setPixel(window, x + i * size, y, size);
        }
References BBP::Locale::Japanese::i, and setPixel().
void BBP::std::R2D::PixelMaskAligned (window * window, pos_t x, pos_t y, word size, mask_t * maskv, word maskc)
Definition at line 505 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < maskc; i++)
                PixelMaskAligned(window, x, y + i * size, size, maskv[i]);
        }
References BBP::Locale::Japanese::i, and PixelMaskAligned().
void BBP::std::R2D::PixelMaskAligned (window * window, pos_t x, pos_t y, word size, mask_t mask)
Definition at line 486 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < 32; i++)
                if ((mask >> (i)) & 0x1)
                    setPixelAligned(window, x + i * size, y, size);
        }
References BBP::Locale::Japanese::i, and setPixelAligned().
Referenced by PixelMaskAligned().
void BBP::std::R2D::print (window * window, conststring str)
Definition at line 552 of file R2D.cpp.
        {
            ustring_element *str_ptr = (ustring_element *)str;
            while (*str_ptr)
            {
                R2D::print(window, (ustring_element)(*str_ptr));
                str_ptr++;
            }
        }
References print().
void BBP::std::R2D::print (window *, mem_t * str, word str_c)
void BBP::std::R2D::print (window *, ustring_element * str)
void BBP::std::R2D::print (window * window, ustring_element ch)
Definition at line 523 of file R2D.cpp.
        {
            // TODO expand
#ifdef BBP_DEBUG
            BBP::Debug::printToConsole(ch);
#endif
            switch (ch)
            {
            case '\n':
                window->coloumn = 0;
                window->line++;
                return;
            default:
                R2D::PrintCharacterAt(window, window->cursorPosX + window->fontSize * window->fontSpacing * window->coloumn++, window->cursorPosY + window->fontSize * window->fontSpacing * window->line * 2, ch, window->fontSize);
                break;
            }
        }
References BBP::std::window::coloumn, BBP::std::window::cursorPosX, BBP::std::window::cursorPosY, BBP::std::window::fontSize, BBP::std::window::fontSpacing, BBP::std::window::line, and PrintCharacterAt().
Referenced by print().
void BBP::std::R2D::PrintCharacterAt (window * window, pos_t x, pos_t y, ustring_element ch)
Definition at line 512 of file R2D.cpp.
        {
            
            R2D::RectPixelMask(window, x, y, window->typeFace.data + window->fontMapping[ch] * 2, 2);
        }
References BBP::std::PAGE< T >::data, BBP::std::window::fontMapping, RectPixelMask(), and BBP::std::window::typeFace.
Referenced by print().
void BBP::std::R2D::PrintCharacterAt (window * window, pos_t x, pos_t y, ustring_element ch, word size)
Definition at line 518 of file R2D.cpp.
        {
            R2D::RectPixelMask(window, x, y, size, window->typeFace.data + window->fontMapping[ch] * 2, 2);
        }
References BBP::std::PAGE< T >::data, BBP::std::window::fontMapping, RectPixelMask(), and BBP::std::window::typeFace.
RGBA_t BBP::std::R2D::readPixel (window * window, pos_t x, pos_t y)
Definition at line 452 of file R2D.cpp.
        {
            return window->backBuffer.data[window->width * y + x];
        }
References BBP::std::window::backBuffer, BBP::std::PAGE< T >::data, and BBP::std::window::width.
void BBP::std::R2D::Rect (window * window, pos_t x, pos_t y, pos_t w, pos_t h)
Definition at line 386 of file R2D.cpp.
        {
            if (window->doFill)
                R2D::Box(window, x, y, w, h);
            if (window->doStroke)
                for (std::index_t i = 0; i < window->strokeWeight; i++)
                    R2D::Frame(window, x + i, y + i, w - i * 2, h - i * 2);
        }
References Box(), BBP::std::window::doFill, BBP::std::window::doStroke, Frame(), BBP::Locale::Japanese::i, and BBP::std::window::strokeWeight.
void BBP::std::R2D::RectPixelMask (window * window, pos_t x, pos_t y, mask_t * maskv, word maskc)
Definition at line 434 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < maskc; i++)
                RectPixelMask(window, x, y + i * 4, maskv[i]);
        }
References BBP::Locale::Japanese::i, and RectPixelMask().
void BBP::std::R2D::RectPixelMask (window * window, pos_t x, pos_t y, mask_t mask)
Definition at line 410 of file R2D.cpp.
        {
            for (int X = 0; X < 8; X++)
                for (int Y = 0; Y < 4; Y++)
                    if ((mask >> (31 - (7 - X) - Y * 8)) & 0x1)
                        setPixel(window, x + X, y + Y);
        }
References setPixel().
Referenced by PrintCharacterAt(), and RectPixelMask().
void BBP::std::R2D::RectPixelMask (window * window, pos_t x, pos_t y, word size, mask_t * maskv, word maskc)
Definition at line 440 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < maskc; i++)
                RectPixelMask(window, x, y + i * size * 4, size, maskv[i]);
        }
References BBP::Locale::Japanese::i, and RectPixelMask().
void BBP::std::R2D::RectPixelMask (window * window, pos_t x, pos_t y, word size, mask_t mask)
Definition at line 418 of file R2D.cpp.
        {
            for (int X = 0; X < 8; X++)
                for (int Y = 0; Y < 4; Y++)
                    if ((mask >> (31 - (7 - X) - Y * 8)) & 0x1)
                        setPixel(window, x + X * size, y + Y * size, size);
        }
References setPixel().
void BBP::std::R2D::RectPixelMaskAligned (window * window, pos_t x, pos_t y, word size, mask_t * maskv, word maskc)
Definition at line 446 of file R2D.cpp.
        {
            for (std::index_t i = 0; i < maskc; i++)
                RectPixelMaskAligned(window, x, y + i * size * 4, size, maskv[i]);
        }
References BBP::Locale::Japanese::i, and RectPixelMaskAligned().
void BBP::std::R2D::RectPixelMaskAligned (window * window, pos_t x, pos_t y, word size, mask_t mask)
Definition at line 426 of file R2D.cpp.
        {
            for (int X = 0; X < 8; X++)
                for (int Y = 0; Y < 4; Y++)
                    if ((mask >> (31 - (7 - X) - Y * 8)) & 0x1)
                        setPixelAligned(window, x + X * size, y + Y * size, size);
        }
References setPixelAligned().
Referenced by RectPixelMaskAligned().
void BBP::std::R2D::setCursorPos (window * window, pos_t x, pos_t y)
Definition at line 569 of file R2D.cpp.
        {
            window->cursorPosX = x;
            window->cursorPosY = y;
            window->coloumn = 0;
            window->line = 0;
        }
References BBP::std::window::coloumn, BBP::std::window::cursorPosX, BBP::std::window::cursorPosY, and BBP::std::window::line.
void BBP::std::R2D::setPixel (window * window, pos_t x, pos_t y) [inline]
Definition at line 457 of file R2D.cpp.
        {
            window->backBuffer.data[window->width * y + x] = window->Stroke.RGBA;
        }
References BBP::std::window::backBuffer, BBP::std::PAGE< T >::data, BBP::std::colour::RGBA, BBP::std::window::Stroke, and BBP::std::window::width.
Referenced by Line(), PixelMask(), and RectPixelMask().
void BBP::std::R2D::setPixel (window * window, pos_t x, pos_t y, word size) [inline]
Definition at line 462 of file R2D.cpp.
        {
            R2D::Box(window, x, y, size, size);
        }
References Box().
void BBP::std::R2D::setPixelAligned (window * window, pos_t x, pos_t y, word size) [inline]
Definition at line 467 of file R2D.cpp.
        {
            R2D::Box(window, x * size, y * size, size, size);
        }
References Box().
Referenced by PixelMaskAligned(), and RectPixelMaskAligned().
void BBP::std::R2D::stroke (window * window, chan_t r, chan_t g, chan_t b)
Definition at line 57 of file R2D.cpp.
        {
            window->Stroke.R = r;
            window->Stroke.G = g;
            window->Stroke.B = b;
            window->Stroke.RGBA = convertUCHARtoINT(r, g, b, window->Stroke.A);
        }
References BBP::std::colour::A, BBP::std::colour::B, convertUCHARtoINT(), BBP::std::colour::G, BBP::std::colour::R, BBP::std::colour::RGBA, and BBP::std::window::Stroke.
void BBP::std::R2D::stroke (window * window, chan_t r, chan_t g, chan_t b, chan_t a)
Definition at line 64 of file R2D.cpp.
        {
            window->Stroke.R = r;
            window->Stroke.G = g;
            window->Stroke.B = b;
            window->Stroke.A = a;
            window->Stroke.RGBA = convertUCHARtoINT(r, g, b, a);
        }
References BBP::std::colour::A, BBP::Locale::Japanese::a, BBP::std::colour::B, convertUCHARtoINT(), BBP::std::colour::G, BBP::std::colour::R, BBP::std::colour::RGBA, and BBP::std::window::Stroke.
void BBP::std::R2D::stroke (window * window, RGBA_t rgb)
Definition at line 72 of file R2D.cpp.
        {
            window->Stroke.RGBA = rgb;
            convertINTtoUCHAR(&(window->Stroke.R), &(window->Stroke.G), &(window->Stroke.B), rgb);
        }
References BBP::std::colour::B, convertINTtoUCHAR(), BBP::std::colour::G, BBP::std::colour::R, BBP::std::colour::RGBA, and BBP::std::window::Stroke.
void BBP::std::R2D::stroke (window * window, RGBA_t rgb, chan_t a)
Definition at line 77 of file R2D.cpp.
        {
            convertINTtoUCHAR(&(window->Stroke.R), &(window->Stroke.G), &(window->Stroke.B), rgb);
            window->Stroke.A = a;
            window->Stroke.RGBA = convertUCHARtoINT(window->Stroke.R, window->Stroke.G, window->Stroke.B, a);
        }
References BBP::std::colour::A, BBP::Locale::Japanese::a, BBP::std::colour::B, convertINTtoUCHAR(), convertUCHARtoINT(), BBP::std::colour::G, BBP::std::colour::R, BBP::std::colour::RGBA, and BBP::std::window::Stroke.
void BBP::std::R2D::strokeWeight (window * window, word weight)
Definition at line 89 of file R2D.cpp.
        {
            window->strokeWeight = weight;
        }
References BBP::std::window::strokeWeight.
void BBP::std::R2D::Vrule (window * window, pos_t y1, pos_t y2, pos_t x)
Definition at line 251 of file R2D.cpp.
        {
            RGBA_t colour = R2D::convertUCHARtoINT(window->Stroke.R, window->Stroke.G, window->Stroke.B, window->Stroke.A);
            for (std::index_t i = y1; i < y2; i++)
                window->backBuffer.data[x + window->width * i] = colour;
        }
References BBP::std::colour::A, BBP::std::colour::B, BBP::std::window::backBuffer, convertUCHARtoINT(), BBP::std::PAGE< T >::data, BBP::std::colour::G, BBP::Locale::Japanese::i, BBP::std::colour::R, BBP::std::window::Stroke, and BBP::std::window::width.
Referenced by Frame().
void BBP::std::R2D::Vrule (window * window, pos_t y1, pos_t y2, pos_t x, chan_t r, chan_t g, chan_t b)
Definition at line 265 of file R2D.cpp.
        {
            RGBA_t colour = R2D::convertUCHARtoINT(r, g, b, 255);
            for (std::index_t i = y1; i < y2; i++)
                window->backBuffer.data[x + window->width * i] = colour;
        }
References BBP::std::window::backBuffer, convertUCHARtoINT(), BBP::std::PAGE< T >::data, BBP::Locale::Japanese::i, and BBP::std::window::width.
void BBP::std::R2D::Vrule (window * window, pos_t y1, pos_t y2, pos_t x, RGBA_t rgb)
Definition at line 278 of file R2D.cpp.
        {
            for (std::index_t i = y1; i < y2; i++)
                window->backBuffer.data[x + window->width * i] = rgb;
        }
References BBP::std::window::backBuffer, BBP::std::PAGE< T >::data, BBP::Locale::Japanese::i, and BBP::std::window::width.
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.