.TH "BBP::esa::dataEntry" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::esa::dataEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ELSABackend\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdataEntry\fP (\fBstd::conststring\fP msg, \fBstd::size_t\fP len)"
.br
.ti -1c
.RI "\fBdataEntry\fP (\fBstd::conststring\fP msg, \fBstd::size_t\fP len, \fBstd::byte\fP _type)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::conststring\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBstd::size_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBstd::c_string\fP \fBelfData\fP"
.br
.ti -1c
.RI "\fBstd::offset_t\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBstd::index_t\fP \fBsymbol\fP"
.br
.ti -1c
.RI "\fBstd::byte\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBstd::hash_t\fP \fBhash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ELSABackend\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BBP::esa::dataEntry::dataEntry (\fBstd::conststring\fP msg, \fBstd::size_t\fP len)\fC [inline]\fP"

.PP
Definition at line 36 of file ELSABackend\&.h\&.
.PP
.nf
37                 : data(msg),
38                 size(len),
39                 elfData(nullptr),
40                 offset(0),
41                 symbol(0),
42                 type(0),
43                 hash(0)
44             {}
.fi
.SS "BBP::esa::dataEntry::dataEntry (\fBstd::conststring\fP msg, \fBstd::size_t\fP len, \fBstd::byte\fP _type)\fC [inline]\fP"

.PP
Definition at line 46 of file ELSABackend\&.h\&.
.PP
.nf
47                 : data(msg),
48                 size(len),
49                 elfData(nullptr),
50                 offset(0),
51                 symbol(0),
52                 type(_type),
53                 hash(0)
54             {}
.fi
.SH "Field Documentation"
.PP 
.SS "\fBstd::conststring\fP BBP::esa::dataEntry::data"

.PP
Definition at line 16 of file ELSABackend\&.h\&.
.PP
Referenced by BBP::esa::BinaryApplication::addDataToSection()\&.
.SS "\fBstd::c_string\fP BBP::esa::dataEntry::elfData"

.PP
Definition at line 22 of file ELSABackend\&.h\&.
.PP
Referenced by BBP::esa::BinaryApplication::addDataToSection(), and BBP::esa::BinaryApplication::emitSymbol()\&.
.SS "\fBstd::hash_t\fP BBP::esa::dataEntry::hash"

.PP
Definition at line 34 of file ELSABackend\&.h\&.
.SS "\fBstd::offset_t\fP BBP::esa::dataEntry::offset"

.PP
Definition at line 25 of file ELSABackend\&.h\&.
.PP
Referenced by BBP::esa::BinaryApplication::addDataToSection(), and BBP::esa::BinaryApplication::emitSymbol()\&.
.SS "\fBstd::size_t\fP BBP::esa::dataEntry::size"

.PP
Definition at line 19 of file ELSABackend\&.h\&.
.PP
Referenced by BBP::esa::BinaryApplication::addDataToSection(), and BBP::esa::BinaryApplication::addSymbol()\&.
.SS "\fBstd::index_t\fP BBP::esa::dataEntry::symbol"

.PP
Definition at line 28 of file ELSABackend\&.h\&.
.PP
Referenced by BBP::esa::BinaryApplication::addSymbol(), BBP::esa::esaProcessor::emitProcedure(), BBP::esa::BinaryApplication::emitSymbol(), and BBP::esa::BinaryApplication::setSource()\&.
.SS "\fBstd::byte\fP BBP::esa::dataEntry::type"

.PP
Definition at line 31 of file ELSABackend\&.h\&.
.PP
Referenced by BBP::esa::BinaryApplication::addSymbol(), and BBP::esa::BinaryApplication::mangle()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
