.TH "BBP::std::Lexer::lex_keyword" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::Lexer::lex_keyword
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::conststring\fP \fBword\fP"
.br
.ti -1c
.RI "\fBstd::size_t\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBlex_action\fP \fBaction\fP"
.br
.ti -1c
.RI "bool \fBforceEvaluation\fP"
.br
.ti -1c
.RI "bool \fBforceParseInComments\fP"
.br
.ti -1c
.RI "bool \fBforceParseInLiterals\fP"
.br
.ti -1c
.RI "bool \fBforceParseOutsideComments\fP"
.br
.ti -1c
.RI "bool \fBforceParseOutsideLiterals\fP"
.br
.ti -1c
.RI "bool \fBactAsDelimiter\fP"
.br
.ti -1c
.RI "char \fBconsiderCommentDepth\fP"
.br
.ti -1c
.RI "char \fBconsiderLiteralDepth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file Lex\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool BBP::std::Lexer::lex_keyword::actAsDelimiter"

.PP
Definition at line 44 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "\fBlex_action\fP BBP::std::Lexer::lex_keyword::action"

.PP
Definition at line 36 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::executeKeywordAction()\&.
.SS "char BBP::std::Lexer::lex_keyword::considerCommentDepth"

.PP
Definition at line 46 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "char BBP::std::Lexer::lex_keyword::considerLiteralDepth"

.PP
Definition at line 47 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "bool BBP::std::Lexer::lex_keyword::forceEvaluation"

.PP
Definition at line 39 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "bool BBP::std::Lexer::lex_keyword::forceParseInComments"

.PP
Definition at line 40 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "bool BBP::std::Lexer::lex_keyword::forceParseInLiterals"

.PP
Definition at line 41 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "bool BBP::std::Lexer::lex_keyword::forceParseOutsideComments"

.PP
Definition at line 42 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "bool BBP::std::Lexer::lex_keyword::forceParseOutsideLiterals"

.PP
Definition at line 43 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "\fBstd::size_t\fP BBP::std::Lexer::lex_keyword::length"

.PP
Definition at line 33 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::executeKeywordAction(), BBP::esa::esaProcessor::ExpectDelimiters(), and BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "\fBuint32_t\fP BBP::std::Lexer::lex_keyword::mask"

.PP
Definition at line 35 of file Lex\&.h\&.
.PP
Referenced by BBP::std::Lexer::lex_context::moveToNextKeyword()\&.
.SS "\fBstd::conststring\fP BBP::std::Lexer::lex_keyword::word"

.PP
Definition at line 32 of file Lex\&.h\&.
.PP
Referenced by BBP::esa::esaProcessor::ExpectDelimiters(), and BBP::std::Lexer::lex_context::moveToNextKeyword()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
