.TH "BBP::std::executableFrame" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::executableFrame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Executable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPID_t\fP \fBPID\fP"
.br
.ti -1c
.RI "\fBstd::ResourceManager\fP * \fBpmem\fP"
.br
.ti -1c
.RI "bool \fBisActiveFrame\fP"
.br
.ti -1c
.RI "bool \fBisExecuting\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file Executable\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int BBP::std::executableFrame::argc"

.PP
Definition at line 49 of file Executable\&.h\&.
.SS "bool BBP::std::executableFrame::isActiveFrame"

.PP
Definition at line 43 of file Executable\&.h\&.
.SS "bool BBP::std::executableFrame::isExecuting"

.PP
Definition at line 46 of file Executable\&.h\&.
.PP
Referenced by BBP::std::execute()\&.
.SS "\fBPID_t\fP BBP::std::executableFrame::PID"

.PP
Definition at line 37 of file Executable\&.h\&.
.PP
Referenced by BBP::std::execute()\&.
.SS "\fBstd::ResourceManager\fP* BBP::std::executableFrame::pmem"

.PP
Definition at line 40 of file Executable\&.h\&.
.PP
Referenced by BBP::std::execute()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
