.TH "BBP::userspace::BinaryExecutable" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::userspace::BinaryExecutable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BinaryExecutable\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 13 of file BinaryExecutable\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
