.TH "BBP::std::Terminal" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::Terminal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ECMA35\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminal\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP (\fBwindow\fP *)"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBput\fP (\fBstring_element\fP)"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBputs\fP (\fBstring\fP &)"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBputs\fP (\fBconststring\fP)"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBputs\fP (\fBc_string\fP)"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBBell\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBBackspace\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBTab\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBLineFeed\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBFormFeed\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBCarriageReturn\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBEscape\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBSS2\fP ()"
.br
.ti -1c
.RI "\fBTerminal\fP & \fBSS3\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::Stack\fP< \fBstd::string_element\fP > \fBout\fP"
.br
.ti -1c
.RI "\fBstd::Stack\fP< \fBstd::string_element\fP > \fBin\fP"
.br
.ti -1c
.RI "\fBstd::Stack\fP< \fBstd::string_element\fP > \fBerr\fP"
.br
.ti -1c
.RI "bool \fBusesGUI\fP"
.br
.ti -1c
.RI "\fBwindow\fP * \fBGUI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ECMA35\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BBP::std::Terminal::Terminal ()"

.SS "BBP::std::Terminal::Terminal (\fBwindow\fP *)"

.SH "Member Function Documentation"
.PP 
.SS "\fBTerminal\fP& BBP::std::Terminal::Backspace ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::Bell ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::CarriageReturn ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::Escape ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::FormFeed ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::LineFeed ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::put (\fBstring_element\fP)"

.SS "\fBTerminal\fP& BBP::std::Terminal::puts (\fBc_string\fP)"

.SS "\fBTerminal\fP& BBP::std::Terminal::puts (\fBconststring\fP)"

.SS "\fBTerminal\fP& BBP::std::Terminal::puts (\fBstring\fP &)"

.SS "\fBTerminal\fP& BBP::std::Terminal::SS2 ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::SS3 ()"

.SS "\fBTerminal\fP& BBP::std::Terminal::Tab ()"

.SH "Field Documentation"
.PP 
.SS "\fBstd::Stack\fP<\fBstd::string_element\fP> BBP::std::Terminal::err"

.PP
Definition at line 33 of file ECMA35\&.h\&.
.SS "\fBwindow\fP* BBP::std::Terminal::GUI"

.PP
Definition at line 37 of file ECMA35\&.h\&.
.SS "\fBstd::Stack\fP<\fBstd::string_element\fP> BBP::std::Terminal::in"

.PP
Definition at line 32 of file ECMA35\&.h\&.
.SS "\fBstd::Stack\fP<\fBstd::string_element\fP> BBP::std::Terminal::out"

.PP
Definition at line 31 of file ECMA35\&.h\&.
.SS "bool BBP::std::Terminal::usesGUI"

.PP
Definition at line 36 of file ECMA35\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
