BBP::std::ELF::SymbolBuilder
NAME
BBP::std::ELF::SymbolBuilder
SYNOPSIS
#include <ELF.h>
Public Member Functions
std::word name (void)
void name (std::word)
std::address_t value (void)
void value (std::address_t)
std::word size (void)
void size (std::word)
std::byte info (void)
void info (std::byte)
std::byte other (void)
void other (std::byte)
std::halfword shndx (void)
void shndx (std::halfword)
void close ()
SymbolBuilder (ELFBuilder *, std::offset_t)
SymbolBuilder (ELFBuilder *, string_element *, std::size_t)
Data Fields
PAGE< string_element > header
Stack< string_element > stack
PAGE< string_element > data
ELFBuilder * elf
bool isMemUnique
Detailed Description
Definition at line 152 of file ELF.h.
Constructor & Destructor Documentation
BBP::std::ELF::SymbolBuilder::SymbolBuilder (ELFBuilder * elf, std::offset_t offset)
Definition at line 70 of file SymbolBuilderGettersSetters.cpp.
    : header(PAGE<string_element>(ELF_SYMBOL_ENTRYSIZE, elf->file.data + offset)),
    stack(&data, 0),
    data(PAGE<string_element>()),
    elf(elf),
    isMemUnique(false) {}
BBP::std::ELF::SymbolBuilder::SymbolBuilder (ELFBuilder *, string_element *, std::size_t)
Member Function Documentation
void BBP::std::ELF::SymbolBuilder::close ()
Definition at line 4 of file SymbolBuilder.cpp.
{
}
Referenced by BBP::std::ELF::ELFBuilder::close().
void BBP::std::ELF::SymbolBuilder::info (std::byte value)
Definition at line 87 of file SymbolBuilderGettersSetters.cpp.
{ writeByte(this, value, ELF_SYMBOL_INFOOFFSET); }
References ELF_SYMBOL_INFOOFFSET, and writeByte().
BBP::std::byte BBP::std::ELF::SymbolBuilder::info (void)
Definition at line 86 of file SymbolBuilderGettersSetters.cpp.
{ return readByte(this, ELF_SYMBOL_INFOOFFSET); }
References ELF_SYMBOL_INFOOFFSET, and readByte().
Referenced by BBP::std::ELF::ELFBuilder::ELFBuilder().
void BBP::std::ELF::SymbolBuilder::name (std::word value)
Definition at line 78 of file SymbolBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SYMBOL_NAMEOFFSET); }
References ELF_SYMBOL_NAMEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SymbolBuilder::name (void)
Definition at line 77 of file SymbolBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SYMBOL_NAMEOFFSET); }
References ELF_SYMBOL_NAMEOFFSET, and readWord().
Referenced by BBP::std::ELF::ELFBuilder::ELFBuilder().
void BBP::std::ELF::SymbolBuilder::other (std::byte value)
Definition at line 90 of file SymbolBuilderGettersSetters.cpp.
{ writeByte(this, value, ELF_SYMBOL_OTHEROFFSET); }
References ELF_SYMBOL_OTHEROFFSET, and writeByte().
BBP::std::byte BBP::std::ELF::SymbolBuilder::other (void)
Definition at line 89 of file SymbolBuilderGettersSetters.cpp.
{ return readByte(this, ELF_SYMBOL_OTHEROFFSET); }
References ELF_SYMBOL_OTHEROFFSET, and readByte().
void BBP::std::ELF::SymbolBuilder::shndx (std::halfword value)
Definition at line 93 of file SymbolBuilderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_SYMBOL_SHNDXOFFSET); }
References ELF_SYMBOL_SHNDXOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::SymbolBuilder::shndx (void)
Definition at line 92 of file SymbolBuilderGettersSetters.cpp.
{ return readHalfWord(this, ELF_SYMBOL_SHNDXOFFSET); }
References ELF_SYMBOL_SHNDXOFFSET, and readHalfWord().
void BBP::std::ELF::SymbolBuilder::size (std::word value)
Definition at line 84 of file SymbolBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SYMBOL_SIZEOFFSET); }
References ELF_SYMBOL_SIZEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SymbolBuilder::size (void)
Definition at line 83 of file SymbolBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SYMBOL_SIZEOFFSET); }
References ELF_SYMBOL_SIZEOFFSET, and readWord().
void BBP::std::ELF::SymbolBuilder::value (std::address_t value)
Definition at line 81 of file SymbolBuilderGettersSetters.cpp.
{ writeWord(this, value, ELF_SYMBOL_VALUEOFFSET); }
References ELF_SYMBOL_VALUEOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::SymbolBuilder::value (void)
Definition at line 80 of file SymbolBuilderGettersSetters.cpp.
{ return readWord(this, ELF_SYMBOL_VALUEOFFSET); }
References ELF_SYMBOL_VALUEOFFSET, and readWord().
Field Documentation
PAGE<string_element> BBP::std::ELF::SymbolBuilder::data
Definition at line 176 of file ELF.h.
ELFBuilder* BBP::std::ELF::SymbolBuilder::elf
Definition at line 181 of file ELF.h.
Referenced by readHalfWord(), readWord(), writeHalfWord(), and writeWord().
PAGE<string_element> BBP::std::ELF::SymbolBuilder::header
Definition at line 174 of file ELF.h.
Referenced by readByte(), readHalfWord(), readWord(), writeByte(), writeHalfWord(), and writeWord().
bool BBP::std::ELF::SymbolBuilder::isMemUnique
Definition at line 183 of file ELF.h.
Stack<string_element> BBP::std::ELF::SymbolBuilder::stack
Definition at line 175 of file ELF.h.
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.