.TH "BBP::std::ELF::RelaEntry" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::ELF::RelaEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ELF32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::address_t\fP \fBr_offset\fP"
.br
.ti -1c
.RI "\fBstd::word\fP \fBr_info\fP"
.br
.ti -1c
.RI "\fBstd::halfword\fP \fBr_addend\fP"
.br
.ti -1c
.RI "\fBstd::dword\fP \fBr_offset\fP"
.br
.ti -1c
.RI "\fBstd::dword\fP \fBr_info\fP"
.br
.ti -1c
.RI "\fBstd::dword\fP \fBr_addend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 226 of file ELF32\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBstd::dword\fP BBP::std::ELF::RelaEntry::r_addend"

.PP
Definition at line 202 of file ELF64\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::RelaEntry::r_addend"

.PP
Definition at line 229 of file ELF32\&.h\&.
.SS "\fBstd::dword\fP BBP::std::ELF::RelaEntry::r_info"

.PP
Definition at line 201 of file ELF64\&.h\&.
.SS "\fBstd::word\fP BBP::std::ELF::RelaEntry::r_info"

.PP
Definition at line 228 of file ELF32\&.h\&.
.SS "\fBstd::dword\fP BBP::std::ELF::RelaEntry::r_offset"

.PP
Definition at line 200 of file ELF64\&.h\&.
.SS "\fBstd::address_t\fP BBP::std::ELF::RelaEntry::r_offset"

.PP
Definition at line 227 of file ELF32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
