.TH "BBP::std::VOLUME" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::VOLUME
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileSys\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVOLUME\fP (char l, \fBstd::conststring\fP)"
.br
.ti -1c
.RI "\fBVOLUME\fP (char l)"
.br
.ti -1c
.RI "\fB~VOLUME\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPATH\fP \fBvolumePath\fP"
.br
.ti -1c
.RI "char \fBlabel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file FileSys\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BBP::std::VOLUME::VOLUME (char l, \fBstd::conststring\fP path)"

.PP
Definition at line 4 of file Volume\&.cpp\&.
.PP
.nf
5     : volumePath(this, path), label(l)
6 {
7 
8 
9 }
.fi
.SS "BBP::std::VOLUME::VOLUME (char l)\fC [inline]\fP"

.PP
Definition at line 91 of file FileSys\&.h\&.
.PP
.nf
91 : VOLUME(l, "/") {}
.fi
.SS "BBP::std::VOLUME::~VOLUME ()"

.PP
Definition at line 11 of file Volume\&.cpp\&.
.PP
.nf
12 {
13     
14 }
.fi
.SH "Field Documentation"
.PP 
.SS "char BBP::std::VOLUME::label"

.PP
Definition at line 96 of file FileSys\&.h\&.
.SS "\fBPATH\fP BBP::std::VOLUME::volumePath"

.PP
Definition at line 95 of file FileSys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
