BBP::esa::esaProcessor
NAME
BBP::esa::esaProcessor
SYNOPSIS
#include <ELSA.h>
Public Member Functions
esaProcessor ()
std::errno_t translate (std::PATH &, std::PATH &)
std::conststring unkown (std::index_t from, std::index_t to)
std::conststring resolve (std::index_t from, std::index_t to)
std::conststring numerical (std::Lexer::numerical_t numerical, bool isFloat)
std::conststring numericalArgument (std::Lexer::numerical_t numerical, bool isFloat)
void reserveRegisters ()
void emitRelocation (std::index_t)
std::word calculateArgumentOffset ()
std::word calculateAbsoluteArgumentOffset ()
void addReservedIdentifier (std::conststring, userspace::Instruction::Arg)
std::conststring markVirtual ()
std::conststring markExtern ()
std::conststring markConst ()
std::conststring markStatic ()
std::conststring setHash (std::hash_t)
std::conststring setSize (std::size_t)
void addWord (std::word)
void addHalfword (std::halfword)
void addByte (std::byte)
std::conststring addNumerical (std::Lexer::numerical_t, bool)
void resetSymbol ()
std::index_t lookupSymbol (std::index_t, std::index_t, std::word *, std::hash_t &)
void setInstruction (userspace::OPCODES, std::byte, std::nibble flags, std::nibble args)
void expectLiteral (std::byte n)
void expectAddress (std::byte n)
void expectAny (std::byte n)
void surpressArgCountWarning (std::byte n)
void surpressArgCountWarning ()
std::conststring setArg (userspace::Instruction::Arg &arg)
std::conststring setReference (std::word address, std::word page)
std::conststring setDereference (std::word address, std::word, std::byte count)
void logInstruction ()
void resetInstruction ()
void setProcedureAddress ()
void setProcedureIdentifier (std::index_t, std::index_t, std::hash_t)
void setProcedureArgCount (std::byte)
void setupBackend (std::conststring, std::size_t, std::size_t, std::size_t)
void saveAndClose ()
void discardAndClose ()
std::errno_t buildSymbol ()
std::conststring emitProcedure ()
std::conststring emitInstruction ()
void saveIdentifier (std::index_t start, std::index_t end)
std::hash_t hashIdentifier (BBP::esa::dataEntry &)
BBP::std::conststring mangleSymbolIdentifier (BBP::esa::dataEntry &entry)
std::errno_t ExpectDelimiters (std::Lexer::lex_context *, std::index_t argc, std::Lexer::lex_keywordhandle const argv[], bool singleLine, std::index_t min, std::index_t maxDepth, std::Lexer::lex_keywordhandle escape, std::Lexer::lex_keywordhandle stop)
std::conststring includeFile (std::Lexer::lex_context *, std::index_t)
bool includeFromPath (std::FILE &, std::PATH &, std::Stack< std::string_element > &, std::PATH &out)
Data Fields
std::Lexer::lex_context esaParser
std::Lexer::lex_thing symbol
std::STATIC_PAGE< std::byte, 512 > symbolDataPage
std::Stack< std::byte > symbolDataByte
std::PAGE< std::halfword > symbolDataPageHalfword
std::Stack< std::halfword > symbolDataHalfword
std::PAGE< std::word > symbolDataPageWord
std::Stack< std::word > symbolDataWord
userspace::Instruction instruction
std::byte atArgument
bool surpress [8]
std::index_t startedAt
std::index_t endedAt
std::hash_t procedureHash
std::STATIC_PAGE< std::string_element, 100 > procedureName
std::index_t procedureNameStart
std::index_t procedureNameEnd
std::byte procedureArgumentCount
bool doneDeclaringProcedure
bool externProcedure
std::STATIC_PAGE< std::hash_t, 256 > reservedIdentifiers
std::STATIC_PAGE< userspace::Instruction::Arg, 256 > reservedIdentifiersValues
std::STATIC_PAGE< std::hash_t, 256 > quasiSymbols
std::STATIC_PAGE< std::word, 256 > quasiSymbolValues
esa::BinaryApplication * application
std::STATIC_PAGE< std::index_t, 32 > routineStartsPage
std::STATIC_PAGE< std::index_t, 32 > routineSubscriberCount
std::Stack< std::index_t > routineStarts
std::STATIC_PAGE< std::index_t, 128 > subscribersPage
std::Stack< std::index_t > subscribers
bool beVerbose
std::Lexer::lex_keywordhandle handle
std::Lexer::lex_keywordhandle lastOpener
std::Lexer::lex_keywordhandle firstCloser
std::STATIC_PAGE< std::Lexer::lex_keywordhandle, 32 > delimiterPage
std::Stack< std::Lexer::lex_keywordhandle > delimiterStack
std::word delimiterDepth = 0
bool lineIsDefiningSymbolDefinition
bool lineIsDefiningInstruction
bool lineIsDefiningProcedure
Detailed Description
Definition at line 14 of file ELSA.h.
Constructor & Destructor Documentation
BBP::esa::esaProcessor::esaProcessor ()
Definition at line 92 of file Processor.cpp.
    : symbolDataByte(&symbolDataPage, 512),
    symbolDataPageHalfword(256, (std::halfword *)symbolDataPage.data),
    symbolDataHalfword(&symbolDataPageHalfword, 256),
    symbolDataPageWord(128, (std::word *)symbolDataPage.data),
    symbolDataWord(&symbolDataPageWord, 128),
    application(nullptr),
    delimiterStack(&delimiterPage, 32),
    routineStarts(&routineStartsPage, routineStartsPage.dataSize),
    subscribers(&subscribersPage, subscribersPage.dataSize)
{
    // Initialize keyword count to .
    esaParser.keywordStack.atElement = keywordCount + tokenCount + mnemonicsCount;
    // Read all keywords into parser
    for (unsigned int k = 0; k < keywordCount; k++)
        esaParser.keywordStack[k] = { keywords[k], std::strlen(keywords[k]), 0, keywordActions[k], false, false, false, false, false, false, 0, 0 };
    // Read instructions into parser
    for (unsigned int k = 0; k < mnemonicsCount; k++)
        esaParser.keywordStack[k + keywordCount + tokenCount] = { mnemonics[k], std::strlen(mnemonics[k]), 0, mnemonicsActions[k], false, false, false, false, false, false, 0, 0 };
    // Read tokens into parser
    for (unsigned int k = 0; k < tokenCount; k++)
        esaParser.keywordStack[k + keywordCount] = { tokens[k], std::strlen(tokens[k]), 0, tokenActions[k],
                                                                    (bool)flags[k][0], (bool)flags[k][1], (bool)flags[k][2], (bool)flags[k][3], (bool)flags[k][4], (bool)flags[k][5], flags[k][6], flags[k][7] };
    // Manually set some stuff
    esaParser.keywordStack[ELSE_HANDLE].considerCommentDepth = 4;
    esaParser.keywordStack[ENDIF_HANDLE].considerCommentDepth = 4;
    esaParser.abort = false;
    // Initialize system paths
    esaParser.syspaths <<= "/usr/include/";
    esaParser.syspaths <<= "/usr/local/include/";
    // Set debug information
    esaParser.debugInformation.procedure.data = procedureName.static_data;
    esaParser.debugInformation.procedure.dataSize = procedureName.dataSize;
    // Add reserved identifier
    reserveRegisters();
}
References esaParser, BBP::esa::keywordActions, BBP::esa::keywordCount, BBP::esa::keywords, BBP::std::Lexer::lex_context::keywordStack, BBP::esa::mnemonicsCount, BBP::std::strlen(), and BBP::esa::tokenCount.
Member Function Documentation
void BBP::esa::esaProcessor::addByte (std::byte w)
Definition at line 191 of file Frontend.cpp.
{
    symbolDataWord++;
    symbolDataHalfword++;
    symbolDataByte << w;
}
void BBP::esa::esaProcessor::addHalfword (std::halfword w)
Definition at line 184 of file Frontend.cpp.
{
    symbolDataWord++;
    symbolDataHalfword << w;
    symbolDataByte.atElement += 2;
}
BBP::std::conststring BBP::esa::esaProcessor::addNumerical (std::Lexer::numerical_t numerical, bool isFloat)
Definition at line 198 of file Frontend.cpp.
{
    // Check if symbol is extern
    if (symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN)
        return "ECannot add data to extern symbol";
    // If no size specified, default to nil
    if (!(symbol.subtype & 0b111111100000))
        setSize(0);
    
    // If is quasi symbol or virtual, return error if multi-byte
    if ((symbol.subtype & SYMTSZ_NIL) && symbolDataByte.atElement >= 4)
        return "EQuasi symbols cannot be a multi word sequence. (Default size specifier is 32 bit, maybe you forgot a 'db'?)";
    // If we want to add a float, always do a 32bit word.
    if (isFloat)
    {
        // Just add the word
        std::word intermediate = *((std::word *)&numerical.f);
        addWord(intermediate);
        // If it is a 32bit variable, do nothing.
        if (symbol.subtype & (SYMTSZ_DW))
            return nullptr;
        // Else, log warning.
        esaParser.debugInformation.errName = "-Wfloat-size-mismatch";
        return "WFloat in non-32bit size sequence.";
    }
    // Add based on size
    esaParser.debugInformation.errName = "-Wtruncated-literal";
    switch (symbol.subtype & 0b111111100000)
    {
    case SYMTSZ_DN:
    case SYMTSZ_DB:
        addByte(numerical.i);
        if (numerical.i > 0xFFFF)
            return "WTruncated 32 bit literal to 8 bits.";
        else if (numerical.i > 0xFF)
            return "WTruncated 16 bit literal to 8 bits.";
        break;
    case SYMTSZ_DH:
        addHalfword(numerical.i);
        if (numerical.i > 0xFFFF)
            return "WTruncated 32 bit literal to 8 bits.";
        break;
    case SYMTSZ_DA:
    case SYMTSZ_DW:
    case SYMTSZ_DI:
        addWord(numerical.i);
        break;
    case SYMTSZ_NIL:
        addWord(numerical.i);
        break;
    }
    // Do nothing
    esaParser.debugInformation.errName = nullptr;
    return nullptr;
}
References BBP::std::Lexer::numerical_t::f, BBP::std::Lexer::numerical_t::i, BBP::esa::SYMTMOD_EXTERN, BBP::esa::SYMTSZ_DA, BBP::esa::SYMTSZ_DB, BBP::esa::SYMTSZ_DH, BBP::esa::SYMTSZ_DI, BBP::esa::SYMTSZ_DN, BBP::esa::SYMTSZ_DW, and BBP::esa::SYMTSZ_NIL.
Referenced by numerical(), and BBP::esa::TOKEN().
void BBP::esa::esaProcessor::addReservedIdentifier (std::conststring identifier, userspace::Instruction::Arg data)
Definition at line 493 of file Frontend.cpp.
{
    // Check for nullptr
    if (identifier == nullptr)
        throw std::exception("Cannot add nullptr identifier.", EDOM);
    // Hash string
    std::hash_t identifierHash = 0;
    std::size_t identifierSize = std::strlen(identifier);
    // Calculate hash
    for (std::index_t index = 0; index < identifierSize; index++)
    {
        // Get character
        std::string_element c = identifier[index];
        // Operate on character
        identifierHash = (identifierHash * 33) + c;
    }
    // Look for identifier
    for (std::index_t identifierIndex = 0; identifierIndex < processor.reservedIdentifiers.dataSize; identifierIndex++)
    {
        // Get value
        std::hash_t storedValue = std::read(&processor.reservedIdentifiers, identifierIndex);
        // If non-zero, continue
        if (storedValue)
            continue;
        // Save data
        std::write(&processor.reservedIdentifiers, identifierHash, identifierIndex);
        std::write(&processor.reservedIdentifiersValues, data, identifierIndex);
        // Return
        return;
    }
    throw std::exception("No free reserved identifiers.", ENOBUFS);
}
References BBP::std::PAGE< T >::dataSize, EDOM, ENOBUFS, BBP::std::exception(), BBP::esa::processor, BBP::std::read(), reservedIdentifiers, reservedIdentifiersValues, BBP::std::strlen(), and BBP::std::write().
void BBP::esa::esaProcessor::addWord (std::word w)
Definition at line 177 of file Frontend.cpp.
{
    symbolDataWord << w;
    symbolDataHalfword.atElement += 2;
    symbolDataByte.atElement += 4;
}
BBP::std::errno_t BBP::esa::esaProcessor::buildSymbol ()
Definition at line 90 of file Backend.cpp.
{
    // Look for already existing symbol
    std::hash_t hash = 0;
    std::word byteSize = 0;
    std::index_t existingSymbol = lookupSymbol(symbol.start, symbol.end, &byteSize, hash);
    bool symbolExists = existingSymbol != 0;
    // if symbol exists and is not 'extern'
    if (symbolExists && application->builder.symbols[existingSymbol].shndx())
        return EADDRINUSE;
    // if symbol exists, is marked 'extern', but is a procedure,
    if (symbolExists && application->builder.symbols[existingSymbol].info() & std::ELF::SYM_FUNC)
        return EBADR; // Cannot do that
    // Declare entry
    dataEntry entry = dataEntry(nullptr, 0, std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
    
    // If entry is extern, just mangle and set to section 0.
    if (symbol.subtype & SYMTMOD_EXTERN)
    {
        // Create empty entry
        entry = dataEntry(nullptr, 0, std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
        // Emit
        application->emitSymbol(0, entry, mangleSymbolIdentifier(entry), hashIdentifier(entry), existingSymbol);
        // Return
        resetSymbol();
        return 0;
    }
    // Do rules based on flags set
    // If access is 'static'
    if (symbol.subtype & SYMTACC_STATIC)
    {
        // Is it const?
        std::index_t section = (symbol.subtype & SYMTMOD_CONST) ? application->builder.rodata : application->builder.data;
        // Emit and return
        entry = dataEntry((std::conststring)symbolDataWord.page->data, symbolDataByte.atElement, std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
        application->emitSymbol(section, entry, mangleSymbolIdentifier(entry), hashIdentifier(entry), existingSymbol);
        // Return
        resetSymbol();
        return 0;
    }
    else if (symbol.subtype & SYMTACC_VIRTUAL) // Are we virtual?
    {
        // Are we also marked constant?
        if (symbol.subtype & SYMTMOD_STATIC)
        {
            // Create another entry
            std::size_t size = application->builder.sections[application->builder.bss].stack.atElement;
            dataEntry staticEntry = dataEntry((std::conststring)&size, 4, std::ELF::SYM_LOCAL);
            // Are we also const?
            std::index_t section = (symbol.subtype & SYMTMOD_CONST) ? application->builder.rodata : application->builder.data;
            // Add data to .bss (.bss gets removed later)
            entry = dataEntry((std::conststring)symbolDataWord.page->data, symbolDataByte.atElement, std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
            application->emitSymbol(application->builder.bss, entry, mangleSymbolIdentifier(entry), hashIdentifier(entry), existingSymbol);
            // Emit static symbol
            application->emitSymbol(section, staticEntry, mangleSymbolIdentifier(staticEntry), hashIdentifier(staticEntry), existingSymbol);
            // Return
            resetSymbol();
            return 0;
        }
        else
        {
            // Not virtual, just do it normally then.
            // Add data to .bss (.bss gets removed later)
            entry = dataEntry((std::conststring)symbolDataWord.page->data, symbolDataByte.atElement, std::ELF::SYM_OBJECT | std::ELF::SYM_GLOBAL);
            
            // Emit
            application->emitSymbol(application->builder.bss, entry, mangleSymbolIdentifier(entry), hashIdentifier(entry), existingSymbol);
            // Return
            resetSymbol();
            return 0;
        }
    }
    // Quasi symbol cannot be exported.
    // Find empty quasi symbol spot
    std::index_t emptyQuasi = 0;
    for (; emptyQuasi < processor.quasiSymbols.dataSize; emptyQuasi++)
    {
        // Get value
        std::hash_t value = std::read(&processor.quasiSymbols, emptyQuasi);
        // If value is 0, break out.
        if (value != 0)
            continue;
        // Do nothing
        break;
    }
    // Check for error condition
    if (emptyQuasi == processor.quasiSymbols.dataSize)
        return ENOBUFS;
    // Calculate hash
    std::hash_t quasiHash = hashIdentifier(entry);
    // Set hash to that, then set value
    std::write(&processor.quasiSymbols, quasiHash, emptyQuasi);
    std::write(&processor.quasiSymbolValues, symbolDataWord[0], emptyQuasi);
    // Reset symbol
    resetSymbol();
    return 0;
}
References BBP::std::conststring, BBP::std::PAGE< T >::dataSize, EADDRINUSE, EBADR, ENOBUFS, BBP::Locale::Japanese::hash, BBP::esa::processor, quasiSymbols, quasiSymbolValues, BBP::std::read(), BBP::std::ELF::SYM_FUNC, BBP::std::ELF::SYM_GLOBAL, BBP::std::ELF::SYM_LOCAL, BBP::std::ELF::SYM_OBJECT, BBP::esa::SYMTACC_STATIC, BBP::esa::SYMTACC_VIRTUAL, BBP::esa::SYMTMOD_CONST, BBP::esa::SYMTMOD_EXTERN, BBP::esa::SYMTMOD_STATIC, and BBP::std::write().
Referenced by BBP::esa::TOKEN().
BBP::std::word BBP::esa::esaProcessor::calculateAbsoluteArgumentOffset ()
Definition at line 356 of file Auxiliary.cpp.
{
    std::word offset = 1;
    for (std::word index = 0; index < atArgument; index++)
        offset += instruction.args[index].trailerCount + 1;
    offset *= 4;
    return offset + application->builder.sections[application->builder.text].stack.atElement;
}
Referenced by BBP::esa::TOKEN().
BBP::std::word BBP::esa::esaProcessor::calculateArgumentOffset ()
Definition at line 346 of file Auxiliary.cpp.
{
    std::word offset = 1;
    for (std::word index = 0; index < atArgument; index++)
        offset += instruction.args[index].trailerCount + 1;
    offset *= 4;
    return offset;
}
void BBP::esa::esaProcessor::discardAndClose ()
Definition at line 66 of file Backend.cpp.
{
    application->close();
    std::activemem->_delete(application);
    application = nullptr;
}
References BBP::std::ResourceManager::_delete(), and BBP::std::activemem.
BBP::std::conststring BBP::esa::esaProcessor::emitInstruction ()
Definition at line 291 of file Backend.cpp.
{
    // Check if right amount of arguments is reached.
    bool hasRightArguments = atArgument == instruction.header.args || surpress[atArgument];
    instruction.header.args = atArgument;
    // Check if there is room to do so
    // Worst case scenario: 1+8+4*8 = 41 words for an instruction.
    if (application->builder._text().stack.atElement + 41 >= application->builder._text().stack.max_elements)
    {
        std::word extendBy = (application->builder._text().stack.atElement + 41 + 128 < application->builder._text().stack.max_elements) ? 128 : (application->builder._text().stack.atElement + 41 + 128 - application->builder._text().stack.max_elements);
        application->builder._text().Extend(extendBy);
    }
    
    // Emit header
    application->builder._text().stack << instruction.header.prefix;
    application->builder._text().stack << instruction.header.opcode;
    application->builder._text().stack << instruction.header.suffix;
    application->builder._text().stack << (((instruction.header.flags & 0xF) << 4) | (instruction.header.args & 0xF));
    // Emit Arguments
    for (std::byte arg = 0; arg < instruction.header.args; arg++)
    {
        // If literal value,
        if (instruction.args[arg].isLiteralArg)
        {
            // Just emit that and continue.
            application->builder._text().stack << ((instruction.args[arg].data >> 24) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].data >> 16) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].data >> 8) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].data >> 0) & 0xFF);
        }
        else
        {
            application->builder._text().stack << (((instruction.args[arg].referenced << 8) | (instruction.args[arg].dereferenced << 7) |
                ((instruction.args[arg].offset & 0xF) << 2) | (instruction.args[arg].trailerCount & 0x7)));
            application->builder._text().stack << ((instruction.args[arg].data >> 16) & 0b11111111);
            application->builder._text().stack << ((instruction.args[arg].data >> 8) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].data >> 0) & 0xFF);
        }
        // Then emit trailers
        for (std::byte trailer = 0; trailer < instruction.args[arg].trailerCount; trailer++)
        {
            application->builder._text().stack << ((instruction.args[arg].trailers[trailer] >> 24) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].trailers[trailer] >> 16) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].trailers[trailer] >> 8) & 0xFF);
            application->builder._text().stack << ((instruction.args[arg].trailers[trailer] >> 0) & 0xFF);
        }
    }
    if (hasRightArguments)
        return nullptr;
    esaParser.debugInformation.errName = "-Wmismatched-arg-count";
    return "WAmount of arguments supplied does not match the amount of arguments expected.";
}
Referenced by BBP::esa::TOKEN().
BBP::std::conststring BBP::esa::esaProcessor::emitProcedure ()
Definition at line 210 of file Backend.cpp.
{
    // Before doing anything, emit a 'ret 0'
    setInstruction(userspace::CTRL, userspace::ret, 0, 1);
    expectLiteral(0);
    numericalArgument({ 0 }, false);
    emitInstruction();
    resetInstruction();
    // Create procedure.
    dataEntry procedure(nullptr, 0, std::ELF::SYM_FUNC | std::ELF::SYM_GLOBAL);
    
    // Define symbol
    symbol = std::Lexer::lex_thing{ &esaParser, startedAt, endedAt, nullptr, esa::PROCEDURE_T, procedureArgumentCount, procedureHash };
    // Mangle procedure name
    application->mangle(procedureName.static_data, symbol, procedure);
    // Hash identifier
    std::hash_t hash = 0;
    for (std::index_t index = 0; index < procedureName.dataSize; index++)
    {
        // Get character
        std::string_element c = procedureName.static_data[index];
        // If c is 0, break out of loop.
        if (c == 0)
            break;
        // Operate on the hash
        hash = (hash * 33) + c;
    }
    // Yeah yeah extraction whatever idc right now
    // Check for symbol memory uniqueness, since an overwrite could loose data
    if (application->builder.symbols[procedure.symbol].isMemUnique)
        throw std::exception("Symbol overwrite looses unique data.", EADDRINUSE);
    // Check if procedure already exists
    std::hash_t hasher = 0;
    std::word byteSize = 0;
    std::index_t existingSymbol = lookupSymbol(procedureNameStart, procedureNameEnd, &byteSize, hasher);
    bool symbolExists = existingSymbol != 0;
    // if symbol exists and is not 'extern'
    if (symbolExists && application->builder.symbols[existingSymbol].shndx())
        return "EProcedure name already in use.";
    // if symbol exists, is marked 'extern', but is a procedure,
    if (symbolExists && !(application->builder.symbols[existingSymbol].info() & std::ELF::SYM_FUNC))
        return "ECannot do that."; // Cannot do that
    // If exists, override
    if (symbolExists)
        application->addSymbol(procedure, application->mangledPage.static_data, existingSymbol);
    else
    {
        // If symbol has reached max, extend symbols
        if (application->builder.symbols.atElement >= application->builder.symbolCount)
            application->appendSymbols(6);
        application->addSymbol(procedure, application->mangledPage.static_data);
    }
    // Then also update the remaining values
    application->builder.symbols[procedure.symbol].shndx(externProcedure ? 0 : application->builder.text);
    application->builder.symbols[procedure.symbol].value(externProcedure ? 0 : startedAt);
    application->builder.symbols[procedure.symbol].size(externProcedure ? 0 : (endedAt - startedAt));
    // Emit symbol hash.
    bool couldHash = application->emitSymbolHash(hash, procedure.symbol);
    if (!couldHash)
        std::printf("ELF Builder: Failed to hash symbol\n");
    return nullptr;
}
References BBP::userspace::CTRL, EADDRINUSE, BBP::std::exception(), BBP::Locale::Japanese::hash, BBP::std::printf(), BBP::esa::PROCEDURE_T, BBP::userspace::ret, BBP::std::ELF::SYM_FUNC, BBP::std::ELF::SYM_GLOBAL, and BBP::esa::dataEntry::symbol.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
void BBP::esa::esaProcessor::emitRelocation (std::index_t symbolIndex)
Definition at line 74 of file Backend.cpp.
{
    // Calculate offset of instruction from .text (in words)
    std::word offset = calculateArgumentOffset();
    // Create data entry
    std::ELF::RelEntry rel_entry;
    rel_entry.r_offset = application->builder._text().stack.atElement + offset;
    rel_entry.r_info = symbolIndex << 8 | 1;
    std::word rel_data[2] = { rel_entry.r_offset, rel_entry.r_info };
    dataEntry entry((char *)rel_data, 8, 0);
    application->addDataToSection(application->builder.rel_text, entry);
}
References BBP::std::ELF::RelEntry::r_info, and BBP::std::ELF::RelEntry::r_offset.
void BBP::esa::esaProcessor::expectAddress (std::byte n)
Definition at line 366 of file Frontend.cpp.
{
    // Reset prefix
    instruction.header.prefix |= (0x1 << n);
    // Reset flags
    instruction.args[n].isLiteralArg = false;
    instruction.args[n].anyvalue = false;
}
References BBP::Locale::Japanese::n.
Referenced by BBP::esa::INSTRUCTION().
void BBP::esa::esaProcessor::expectAny (std::byte n)
Definition at line 376 of file Frontend.cpp.
{
    // Only this needs to be set
    instruction.args[n].anyvalue = true;
}
References BBP::Locale::Japanese::n.
Referenced by BBP::esa::INSTRUCTION().
BBP::std::errno_t BBP::esa::esaProcessor::ExpectDelimiters (std::Lexer::lex_context * context, std::index_t argc, std::Lexer::lex_keywordhandle const argv[], bool singleLine, std::index_t min, std::index_t maxDepth, std::Lexer::lex_keywordhandle escape, std::Lexer::lex_keywordhandle stop)
Definition at line 5 of file Auxiliary.cpp.
{
    // Check if context is valid
    if (context == nullptr)
        return EFAULT; // Bad context address.
    // If argc is not 0, check if argv is not null
    if (argc != 0 && argv == nullptr)
        return EFAULT; // Bad argv address.
    // If argc is not a multiple of 2, throw error
    if (argc % 2 != 0)
        return EDOM; // EDOM because odd numbers are not within the domain of this function
    // Reset delimiter stack
    delimiterStack.atElement = 0;
    // Reset depth
    delimiterDepth = 0;
    // Save index of here
    std::index_t start = context->atPosition;
    context->debugInformation.highlight = start;
    // This variable stores the 'depth' of the delimiter
    std::word depth = 0;
    // Although possible through the stack alone, allocating a new variable optimizes the read time and thus the speed of this function.
    std::Lexer::lex_keywordhandle lastIndex = argc; // Initializing this to 'argc' tells the algorithm to ignore this value.
    // If true, the depth is increasing. Otherwise, decreasing.
    bool isAscending = true;
    // If false, the minimum amount of things hasn't been reached yet.
    bool hasReachedMinimum = min == 0;
    do
    {
        // Get handle to next keyword
        handle = context->moveToNextKeyword();
        // Update delimiter depth
        delimiterDepth = (delimiterDepth < depth) ? depth : delimiterDepth;
        // If handle is EOF, return error
        if (handle == context->keywordStack.atElement)
            return EEOF;
        // Get keyword
        std::Lexer::lex_keyword *keyword = &context->keywordStack[handle];
        // If handle is new line or stop, and delimiter stack is not balanced, and expected within one line, return error
        if ((context->isNewLine(keyword->word[0]) || handle == stop) && depth && (singleLine || handle == stop))
            return ELINEEND;
        // Otherwise, if we have reached 'stop' normally, just break out.
        if (handle == stop && depth == 0)
            break;
        // Aux variables
        bool isIncluded = false;
        std::index_t index = 0;
        // Check if delimiter is included in argv
        for (; index < argc; index++)
        {
            if (argv[index] != handle)
                continue;
            isIncluded = true;
            break;
        }
        // If handle is escape, and also less than EOF, advance one position and then skip.
        if (handle == escape && handle != context->keywordStack.atElement)
        {
            context->atPosition++;
            continue;
        }
        
        // If not included, just skip
        if (!isIncluded)
            continue;
        // The first check checks to see if the handle matches the closing delimiter of the last found delimiter
        if (index == lastIndex + 1)
        {
            // This delimiter is the closing delimiter to the last found delimiter.
            // Decrease the depth by 1, and retrieve the last index from stack.
            depth--;
            
            // If there is depth (I.E., there is still a closing delimiter needed)
            if (depth)
            {
                for (std::index_t i = 0; i < argc; i++)
                {
                    if (argv[i] != delimiterStack[depth - 1])
                        continue;
                    lastIndex = i;
                    break;
                }
            }
            // Since this must be first closer, set index here
            if (isAscending)
                firstCloser = context->atPosition - keyword->length;
            // Set flag to descending
            isAscending = false;
            // Then add the handle to the stack
            delimiterStack << handle;
            continue;
        }
        // Set last index to this
        lastIndex = index;
        // If true, this handle is for an opening keyword.
        bool isOpening = (index % 2 == 0);
        // If is opening and ascending, overwrite previous last opener
        if (isOpening && isAscending)
            lastOpener = context->atPosition;
        // If is not opening but still ascending, its about to close. Write once to firstCloser
        if (!isOpening && isAscending)
            firstCloser = context->atPosition - keyword->length;
        // If not opening, the sequence must be descending.
        isAscending &= isOpening;
        // If the handle is closing, and the depth is 0, return error..
        if (!isOpening && depth == 0)
            return ENOANO; // No anode (because closing delimiters are cathodes).
        // If the handle is closing, and is not the expected type, return error..
        if (!isOpening && lastIndex > argc - 1)
            return EILSEQ; // Illegal sequence of delimiters.
        // If the handle is opening, and the sequence is descending, return error.
        if (isOpening && !isAscending)
            return EUNFOCS; // Try again, but with the other function.
        // Increase depth by one.
        depth++;
        hasReachedMinimum |= depth >= min;
        // If opening, check for max depth. If would cause overflow, return error.
        if (isOpening && depth > maxDepth)
            return EOVERFLOW;
        // Move handle to stack
        delimiterStack << handle;
    } while (depth);
    // If minimum has not been reached, return error
    if (!hasReachedMinimum)
        return ENOMSG; // Nothing was found, so no message.
    // If done successfully, congrats! My algorithm worked! Good job me :)
    return ENONE;
}
References BBP::std::Stack< K >::atElement, BBP::std::Lexer::lex_context::atPosition, BBP::std::Lexer::lex_context::debugInformation, delimiterDepth, delimiterStack, EDOM, EEOF, EFAULT, EILSEQ, ELINEEND, ENOANO, ENOMSG, ENONE, EOVERFLOW, EUNFOCS, firstCloser, handle, BBP::std::Lexer::lex_debugInfo::highlight, BBP::Locale::Japanese::i, BBP::std::Lexer::lex_context::isNewLine(), BBP::std::Lexer::lex_context::keywordStack, lastOpener, BBP::std::Lexer::lex_keyword::length, BBP::std::Lexer::lex_context::moveToNextKeyword(), and BBP::std::Lexer::lex_keyword::word.
Referenced by BBP::esa::PRAGMA().
void BBP::esa::esaProcessor::expectLiteral (std::byte n)
Definition at line 356 of file Frontend.cpp.
{
    // Reset prefix
    instruction.header.prefix &= ~(0x1 << n);
    // Reset flags
    instruction.args[n].isLiteralArg = true;
    instruction.args[n].anyvalue = false;
}
References BBP::Locale::Japanese::n.
Referenced by BBP::esa::INSTRUCTION().
BBP::std::hash_t BBP::esa::esaProcessor::hashIdentifier (BBP::esa::dataEntry & entry)
Definition at line 26 of file Backend.cpp.
{
    // Save the identifier
    saveIdentifier(symbol.start, symbol.end);
    // Define hash number 'h'
    std::hash_t hash = 0;
    for (std::index_t index = 0; index < Identifier.dataSize; index++)
    {
        // Get character
        std::string_element c = Identifier.static_data[index];
        // If c is 0, break out of loop.
        if (c == 0)
            break;
        // Operate on the hash
        hash = (hash * 33) + c;
    }
    // Return hash
    return hash;
}
References BBP::Locale::Japanese::hash, and Identifier.
BBP::std::conststring BBP::esa::esaProcessor::includeFile (std::Lexer::lex_context * context, std::index_t idx)
Definition at line 242 of file Auxiliary.cpp.
{
    // allocate a page for path
    std::static_string<std::max_path_length> requestedPath = std::static_string<std::max_path_length>();
    // Then write into requestedPath, the file requested
    char nul = '\0';
    for (std::index_t index = lastOpener, k = 0; index < firstCloser; index++, k++)
        __UNSAFE__(std::write)(&requestedPath, __UNSAFE__(std::read)(&context->data, index), k);
    __UNSAFE__(std::write)(&requestedPath, nul, firstCloser - lastOpener);
    // Now that we know which file we want to include, we can do this
    std::FILE file;
    std::PATH imported;
    std::PATH filename(requestedPath);
    bool opened = false;
    // Choose which paths to search based on delimiter used
    switch (delimiterStack[0])
    {
    case DOUBLEQUOTES_HANDLE:
        opened = includeFromPath(file, filename, context->usrpaths, imported);
        break;
    case OPENANGLEBRACKET_HANDLE:
        opened = includeFromPath(file, filename, context->syspaths, imported);
        break;
    }
    if (opened)
    {
        // Start including file if verbose flag is set
        if (beVerbose)
            std::printf("Including file: '%s'\n\n", imported.relName());
        // Ensure null termination. Don't know why I need to do this. Shouldn't this be done somewhere else already anyway?
        imported.fileName()[std::strlen(requestedPath)] = 0;
        // Save old file name
        std::static_string<128> oldFileName;
        std::memcpy(context->activeFile, oldFileName, 128);
        // Save old file data
        std::string oldString(context->data);
        std::size_t oldLength = context->dataSize;
        // Save debug information
        std::Lexer::lex_debugInfo oldInfo(context->debugInformation);
        // Add the included path into the usr path
        context->usrpaths <<= imported.pathName();
        // Wipe all the debug data before and after parsing
        context->resetInfo(context->debugInformation);
        // Keep track of comment and literal depth
        char commentD = context->commentDepth;
        char literalD = context->literalDepth;
        std::index_t posNow = context->atPosition;
        context->commentDepth = 0;
        context->literalDepth = 0;
        // Start parsing second file
        context->parseFile(imported);
        // Close the file since we are done with it.
        file.close();
        // Restore comment and literal depths
        context->atPosition = posNow;
        context->literalDepth = literalD;
        context->commentDepth = commentD;
        // Wipe all the debug data before and after parsing
        context->resetInfo(context->debugInformation);
        // Remove that path again. Since 'requestedPath' is not needed anymore, just get rid of it.
        context->usrpaths >>= &requestedPath.data;
        // Restore debug information
        context->debugInformation = oldInfo;
        // Restore old file data
        context->data = oldString;
        context->dataSize = oldLength;
        // Restore old file name
        std::memcpy(oldFileName, context->activeFile, 128);
        if (beVerbose)
            std::printf("File '%s' done. Returning to: '%s'.\n", imported.relName(), context->activeFile.data);
        context->resetInfo(context->debugInformation);
        return nullptr;
    }
    context->debugInformation.highlight = idx;
    context->debugInformation.highlightLength = firstCloser - idx + 1;
    context->debugInformation.highlightmsg = "NIncluded here";
    return "ENo such file or directory.";
}
References __UNSAFE__, BBP::std::Lexer::lex_context::activeFile, BBP::std::Lexer::lex_context::atPosition, BBP::std::FILE::close(), BBP::std::Lexer::lex_context::commentDepth, BBP::std::PAGE< T >::data, BBP::std::Lexer::lex_context::data, BBP::std::Lexer::lex_context::dataSize, BBP::std::Lexer::lex_context::debugInformation, DOUBLEQUOTES_HANDLE, BBP::std::PATH::fileName(), BBP::std::Lexer::lex_debugInfo::highlight, BBP::std::Lexer::lex_debugInfo::highlightLength, BBP::std::Lexer::lex_debugInfo::highlightmsg, BBP::std::Lexer::lex_context::literalDepth, BBP::std::memcpy(), OPENANGLEBRACKET_HANDLE, BBP::std::Lexer::lex_context::parseFile(), BBP::std::PATH::pathName(), BBP::std::printf(), BBP::std::read(), BBP::std::PATH::relName(), BBP::std::Lexer::lex_context::resetInfo(), BBP::std::strlen(), BBP::std::Lexer::lex_context::syspaths, BBP::std::Lexer::lex_context::usrpaths, and BBP::std::write().
Referenced by BBP::esa::PRAGMA().
bool BBP::esa::esaProcessor::includeFromPath (std::FILE & file, std::PATH & filename, std::Stack< std::string_element > & dirs, std::PATH & out)
Definition at line 170 of file Auxiliary.cpp.
{
    // Save stack state
    std::index_t oldPointer = dirs.atElement;
    // Create char to write indicies to.
    char *path = 0;
    // If a file is found, this will be set to true.
    bool exists = false;
    // Continue for all paths
    while (dirs.atElement)
    {
        // Read next path into 'path'
        dirs >>= &path;
        // Then create path from stored string.
        std::PATH searchIn(BBP::std::primaryVolume, path);
        // Make searchIn relative to physical root.
        searchIn.makeAbsolutePath(nullptr);
        // Create path which will eventually become the fullpath.
        std::PATH rel(filename);
        // Make the file relative to searchin.
        rel.makeAbsolutePath(&searchIn);
        if (beVerbose)
            std::printf("Searching directory: %s ... ", rel.relName());
        try
        {
            // Try to open file. If it does not exist, an exception is thrown.
            file = std::FILE(rel);
            // If this point is reached, file opened succesfully.
            exists = true;
            // Also write to out
            out = rel;
            // Print message
            if (beVerbose)
                std::printf("\[0;32mExists\[0;37m.\n");
            // File exists, exit from loop
            break;
        }
        catch (std::except &e)
        {
            // File does not exist
            if (beVerbose)
            {
                if (e.code)
                    std::printf("\[0;31mFile does not exist\[0;37m\n");
                else
                    std::printf("\[0;91mError reading file:\[0;37m %u\n", e.code);
            }
        }
    }
    // Restore stack state
    dirs.atElement = oldPointer;
    return exists;
}
References BBP::std::Stack< K >::atElement, BBP::Locale::Japanese::e, BBP::std::PATH::makeAbsolutePath(), BBP::std::primaryVolume, BBP::std::printf(), and BBP::std::PATH::relName().
void BBP::esa::esaProcessor::logInstruction ()
Definition at line 272 of file Frontend.cpp.
{
    // Print header
    std::printf("Instruction: 0x%02x (0x%02x), %u args.\n", instruction.header.opcode, instruction.header.suffix, instruction.header.args);
    
    for (std::byte i = 0; i < instruction.header.args; i++)
    {
        // Print argument number
        std::printf("\tArg %u:\t", i);
        // Print argument type
        if (!((instruction.header.prefix >> i) & 1))
        {
            std::printf("(Literal):\t0x%08x\n", instruction.args[i].data);
            continue;
        }
        else
            std::printf("(Reference)\t");
        // Check for referenced or dereferenced
        if (instruction.args[i].dereferenced)
            std::printf("*");
        
        if (instruction.args[i].referenced)
            std::printf("&");
        if (instruction.args[i].dereferenced && instruction.args[i].referenced)
            std::printf("\[0;31mILLEGAL\[0;37m");
        std::printf("\t");
        switch (instruction.args[i].offset)
        {
        case 0b00: // Starts at beginning of this instance
            std::printf("Rel: Instance\t");
            break;
        case 0b01: // Starts at beginning of whole chain
            std::printf("Rel: Chain\t");
            break;
        case 0b10: // Starts at beginning of shared user memory
            std::printf("Rel: User\t");
            break;
        case 0b11: // Starts at beginning of shared system memory
            std::printf("Rel: System\t");
            break;
        }
        std::printf("Page: 0x%01x\t", instruction.args[i].data >> 20);
        std::printf("Address: 0x%05x\n", instruction.args[i].data & 0x4ff);
        std::printf("\t\tTrailers: %u\n", instruction.args[i].trailerCount);
        for (std::byte k = 0; k < instruction.args[i].trailerCount; k++)
            std::printf("\t\tTrailer %u: 0x%08x\n", k, instruction.args[i].trailers[k]);
        std::printf("\n");
    }
}
References BBP::Locale::Japanese::i, and BBP::std::printf().
BBP::std::index_t BBP::esa::esaProcessor::lookupSymbol (std::index_t from, std::index_t to, std::word * byteSize, std::hash_t & hash)
Definition at line 47 of file Secondary.cpp.
{
    // Calculate hash
    for (std::index_t index = from; index < to; index++)
    {
        // Get character
        std::string_element c = std::read(&esaParser.data, index);
        // Operate on character
        hash = (hash * 33) + c;
    }
    // Create page for 32 bit sized values
    std::PAGE<std::word> hashTable(2 + application->builder.hashBucketCount + application->builder.hashChainCount, (std::word *)application->builder.sections[application->builder.hashtab].data.data);
    // Get bucket
    std::word bucket = hash % application->builder.hashBucketCount;
    // Check what is at bucket
    std::word bucketValue = std::read(&hashTable, 2 + bucket);
    // If value is 0, return invalid
    if (bucketValue == 0)
    {
        return 0;
    }
    else
    {
        // Move elsewhere later, idc right now.
        // Walk through each symbol table
        char *c = &application->builder._strtab().stack[application->builder.symbols[bucketValue].name()] + 2;
        // Get string size
        std::size_t nameSize = 0;
        std::word radix = 1;
        for (; *c; c++)
        {
            // Get numerical
            std::byte numeral = esaParser.isDecimalNumeral(*c);
            if (numeral == 0)
                break;
            // Update length
            nameSize += (numeral - 10) * radix;
            radix *= 10;
        }
        for (std::index_t character = 0; character < nameSize; character++)
        {
            // Get each character to be able to check later
            std::string_element c1 = std::read(&esaParser.data, from + character);
            std::string_element c2 = *(c + character);
            // Compare characters
            if (c1 != c2)
                goto start_chain;
        }
        // Get bytesize
        c += nameSize + 1;
        *byteSize = 0;
        radix = 1;
        for (; *c; c++)
        {
            // Get numerical
            std::byte numeral = esaParser.isDecimalNumeral(*c);
            if (numeral == 0)
                break;
            // Update length
            *byteSize += (numeral - 10) * radix;
            radix *= 10;
        }
        return bucketValue;
    start_chain:
        radix = radix;
    }
    // Read chain value
    for (std::index_t chainIndex = std::read(&hashTable, 2 + bucket); chainIndex < application->builder.hashChainCount; chainIndex++)
    {
        // Read value at chain
        std::word chainValue = std::read(&hashTable, 2 + application->builder.hashBucketCount + chainIndex);
        // If chain has no value, return invalid
        if (chainValue == 0)
            return 0;
        // Walk through each symbol table
        char *c = &application->builder._strtab().stack[application->builder.symbols[chainValue].name()] + 2;
        // Get string size
        std::size_t nameSize = 0;
        std::word radix = 1;
        for (; *c; c++)
        {
            // Get numerical
            std::byte numeral = esaParser.isDecimalNumeral(*c);
            if (numeral == 0)
                break;
            // Update length
            nameSize += (numeral - 10) * radix;
            radix *= 10;
        }
        for (std::index_t character = 0; character < nameSize; character++)
        {
            // Get each character to be able to check later
            std::string_element c1 = std::read(&esaParser.data, from + character);
            std::string_element c2 = *(c + character);
            // Compare characters
            if (c1 != c2)
                goto next_chain;
        }
        // Get bytesize
        c += nameSize + 1;
        *byteSize = 0;
        radix = 1;
        for (; *c; c++)
        {
            // Get numerical
            std::byte numeral = esaParser.isDecimalNumeral(*c);
            if (numeral == 0)
                break;
            // Update length
            *byteSize += (numeral - 10) * radix;
            radix *= 10;
        }
        return chainValue;
    next_chain:
        continue;
    }
    return 0;
}
References BBP::Locale::Japanese::hash, BBP::std::read(), and BBP::Locale::Japanese::to.
BBP::std::conststring BBP::esa::esaProcessor::mangleSymbolIdentifier (BBP::esa::dataEntry & entry)
Definition at line 14 of file Backend.cpp.
{
    // Save the identifier
    saveIdentifier(symbol.start, symbol.end);
    // Then mangle
    application->mangle(Identifier.static_data, symbol, entry);
    // Return mangled name
    return application->mangledPage.static_data;
}
References Identifier.
BBP::std::conststring BBP::esa::esaProcessor::markConst ()
Definition at line 4 of file Frontend.cpp.
{
    // Check if symbol is extern
    if (symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN)
        return "EIllegal 'const': symbol marked extern.";
    // If the size for this symbol has already been defined, return error
    if (this->symbol.subtype & 0b111111100000)
        return "EIllegal 'const' after size definition";
    // If the symbol has already been hashed, return error
    if (this->symbol.hash)
        return "E'Const' modifier must come before identifier.";
    // Check that this is not the access type
    if (!lineIsDefiningSymbolDefinition)
        return "eModifier 'const' is not a valid access type.";
    // Check that symbol isn't already marked const
    if (this->symbol.subtype & SYMBOL_TYPE::SYMTMOD_CONST)
        return "eDuplicate 'const' modifier.";
    this->symbol.subtype |= SYMBOL_TYPE::SYMTMOD_CONST;
    return nullptr;
}
References BBP::std::Lexer::lex_thing::hash, lineIsDefiningSymbolDefinition, BBP::std::Lexer::lex_thing::subtype, symbol, BBP::esa::SYMTMOD_CONST, and BBP::esa::SYMTMOD_EXTERN.
Referenced by BBP::esa::ACTION().
BBP::std::conststring BBP::esa::esaProcessor::markExtern ()
Definition at line 56 of file Frontend.cpp.
{
    // Check if symbol is not already marked extern
    if (symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN)
        return "ERemove excess extern.";
    // Check if extern comes after name
    if (symbol.hash)
        return "E'Extern' keyword must come before identifier.";
    // Check if subtype is anything at all
    if (symbol.subtype)
        return "E'Extern' keyword may not be used with 'Static', 'Virtual', or 'const'.";
    // Mark symbol extern
    symbol.subtype = SYMBOL_TYPE::SYMTMOD_EXTERN;
    // Mark function extern, just in case
    externProcedure = true;
    return nullptr;
}
References BBP::esa::SYMTMOD_EXTERN.
Referenced by BBP::esa::ACTION().
BBP::std::conststring BBP::esa::esaProcessor::markStatic ()
Definition at line 79 of file Frontend.cpp.
{
    // Check if symbol is extern
    if (symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN)
        return "EIllegal 'static': symbol marked extern.";
    // If the size for this symbol has already been defined, return error
    if (symbol.subtype & 0b111111100000)
        return "EIllegal 'static' after size definition";
    // If the symbol has already been hashed, return error
    if (symbol.hash && symbol.subtype & SYMBOL_TYPE::SYMTACC_STATIC)
        return "E'Static' modifier must come before identifier.";
    else if (symbol.hash)
        return "E'Static' keyword must come before identifier.";
    // If this is used as a modifier, check if it is right after virtual
    if (lineIsDefiningSymbolDefinition && (symbol.subtype & SYMBOL_TYPE::SYMTMOD_CONST || symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN))
        return "E'Static' modifier must come after 'virtual'. Modifier ignored.";
    // Check if it isn't already used
    if (lineIsDefiningSymbolDefinition && symbol.subtype & SYMBOL_TYPE::SYMTACC_STATIC)
        return "ECannot use modifier 'static' on 'static' symbol access type. Modifier ignored.";
    if (lineIsDefiningSymbolDefinition && symbol.subtype & SYMBOL_TYPE::SYMTMOD_STATIC)
        return "eDuplicate 'static' modifier.";
    // Static modifier legal.
    if (lineIsDefiningSymbolDefinition)
        symbol.subtype |= SYMBOL_TYPE::SYMTMOD_STATIC;
    else
        symbol.subtype = SYMBOL_TYPE::SYMTACC_STATIC;
    lineIsDefiningSymbolDefinition = true;
    return nullptr;
}
References BBP::esa::SYMTACC_STATIC, BBP::esa::SYMTMOD_CONST, BBP::esa::SYMTMOD_EXTERN, and BBP::esa::SYMTMOD_STATIC.
Referenced by BBP::esa::ACTION().
BBP::std::conststring BBP::esa::esaProcessor::markVirtual ()
Definition at line 30 of file Frontend.cpp.
{
    // Check if symbol is extern
    if (symbol.subtype & SYMBOL_TYPE::SYMTMOD_EXTERN)
        return "EIllegal 'virtual': symbol marked extern.";
    // If the size for this symbol has already been defined, return error
    if (this->symbol.subtype & 0b111111100000)
        return "EIllegal 'virtual' after size definition";
    // If the symbol has already been hashed, return error
    if (this->symbol.hash)
        return "E'Virtual' keyword must come before identifier.";
    // Not a modifier, so if called and line is already being defined it means that the line is illegal
    if (lineIsDefiningSymbolDefinition)
        return "eMisplaced 'virtual': virtual is not modifier.";
    lineIsDefiningSymbolDefinition = true;
    // Otherwise, flag can be set
    // Since that pretty much eliminates any other case, just set this, and return with success.
    this->symbol.subtype = SYMBOL_TYPE::SYMTACC_VIRTUAL;
    return nullptr;
}
References BBP::esa::SYMTACC_VIRTUAL, and BBP::esa::SYMTMOD_EXTERN.
Referenced by BBP::esa::ACTION().
BBP::std::conststring BBP::esa::esaProcessor::numerical (std::Lexer::numerical_t numerical, bool isFloat)
Definition at line 6 of file Secondary.cpp.
{
    // If line is defining whatever, don't do anything
    if (lineIsDefiningProcedure)
        return nullptr;
    return addNumerical(numerical, isFloat);
}
References addNumerical(), and lineIsDefiningProcedure.
Referenced by _numerical().
BBP::std::conststring BBP::esa::esaProcessor::numericalArgument (std::Lexer::numerical_t numerical, bool isFloat)
Definition at line 15 of file Secondary.cpp.
{
    // Check if correct thing is expected
    bool expectsLiteral = instruction.args[atArgument].isLiteralArg || instruction.args[atArgument].anyvalue;
    // Now set to non-literal
    expectLiteral(atArgument);
    // Get intermediate and write
    std::word intermediate = isFloat ? (*((std::word*)&numerical.f)) : numerical.i;
    instruction.args[atArgument].data = intermediate;
    // Move up argument
    atArgument++;
    // If literal was not expected, return warning
    if (expectsLiteral)
        return nullptr;
    esaParser.debugInformation.errName = "-WUnexpected-arg-type";
    return "WDid not expect supplied argument to be numerical literal.";
}
References BBP::std::Lexer::numerical_t::f, and BBP::std::Lexer::numerical_t::i.
Referenced by _numerical(), and BBP::esa::TOKEN().
void BBP::esa::esaProcessor::reserveRegisters ()
Definition at line 93 of file EABI.cpp.
{
    addReservedIdentifier("eax", { 1, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ax", { 1 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ah", { 1 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("al", { 1 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ecx", { 2, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("cx", { 2 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ch", { 2 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("cl", { 2 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("edx", { 3, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("dx", { 3 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("dh", { 3 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("dl", { 3 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ebx", { 4, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("bx", { 4 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("bh", { 4 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("bl", { 4 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("esi", { 5, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("six", { 5 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("sih", { 5 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("sil", { 5 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("edi", { 6, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("dix", { 6 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("dih", { 6 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("dil", { 6 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("tix", { 7, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("st", { 7 | userspace::HIHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ob", { 7 | userspace::HIHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("tb", { 7 | userspace::HIHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ct", { 7 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("pp", { 7 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("tp", { 7 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ssx", { 8, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("hv", { 8 | userspace::HIHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ho", { 8 | userspace::HIHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ht", { 8 | userspace::HIHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ss", { 8 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("cs", { 8 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("sf", { 8 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("sui", { 9, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("asi", { 9 | userspace::HIHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("gsi", { 9 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("eip", { 10, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ip", { 10 | userspace::LOHW, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("ih", { 10 | userspace::LOHW | userspace::HIBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("il", { 10 | userspace::LOHW | userspace::LOBY, false, true, 0, 1, {1, 0, 0, 0}, false, false });
    addReservedIdentifier("sip", { 11, false, true, 0, 1, {1, 0, 0, 0}, false, false });
}
References BBP::userspace::HIBY, BBP::userspace::HIHW, BBP::userspace::LOBY, and BBP::userspace::LOHW.
void BBP::esa::esaProcessor::resetInstruction ()
Definition at line 448 of file Frontend.cpp.
{
    // Clear head
    instruction.header = userspace::Instruction::Head{ 0, 0, 0, 0, 0 };
    // Clear arguments
    for (std::byte i = 0; i < 8; i++)
        instruction.args[i] = userspace::Instruction::Arg{ 0, false, false, 0, 0, {0, 0, 0, 0}, false, false };
    // Now reset to argument 0
    atArgument = 0;
}
References BBP::userspace::Instruction::Head::args, and BBP::Locale::Japanese::i.
Referenced by BBP::esa::TOKEN().
void BBP::esa::esaProcessor::resetSymbol ()
Definition at line 260 of file Frontend.cpp.
{
    // Reset flags
    symbol.hash = 0;
    symbol.subtype = 0;
    lineIsDefiningSymbolDefinition = false;
    symbolDataByte.atElement = 0;
    symbolDataHalfword.atElement = 0;
    symbolDataWord.atElement = 0;
}
Referenced by BBP::esa::TOKEN().
BBP::std::conststring BBP::esa::esaProcessor::resolve (std::index_t from, std::index_t to)
Definition at line 203 of file Secondary.cpp.
{
    // Since file names can appear between '<>' or '""' (but not both), create the following handle
    std::Lexer::lex_keywordhandle handles[] = { OPENANGLEBRACKET_HANDLE, CLOSEANGLEBRACKET_HANDLE, OPENCURLBRACKET_HANDLE, CLOSECURLBRACKET_HANDLE, OPENSQBRACKET_HANDLE, CLOSESQBRACKET_HANDLE };
    // Store position information
    std::index_t position = esaParser.atPosition;
    // Move to beginning of word
    esaParser.atPosition--;
    esaParser.moveToStartOfThisWord(true);
    esaParser.atPosition--;
    // Now save start
    std::index_t start = esaParser.atPosition++;
    // Get delimiters
    esaParser.inhibitSpecialFunctions = true;
    std::errno_t error = ExpectDelimiters(&esaParser, 6, handles, true, 0, 32, BACKSLASH_HANDLE, COMMA_HANDLE);
    esaParser.inhibitSpecialFunctions = false;
    // Restore position
    esaParser.atPosition = position;
    switch (error)
    {
    case EFAULT: // Somehow a nullpointer got here. Abort immediately.
        atArgument++;
        return "AEFAULT";
    case EDOM: // Somehow, an odd number ended up as argc. Either programmer fault, or stack error. Abort immediately.
        atArgument++;
        return "AEDOM";
    case EEOF: // Found End Of File before anything was found.
        atArgument++;
        return "EEOF";
    case ENOMSG:// Found End of Line before anything was found.
        atArgument++;
        return "ENOMSG";
    case ELINEEND: // End of Line found before second delimiter
        atArgument++;
        return "ELINEEND";
    case ENOANO: // Attempted to close delimiter before starting it.
        atArgument++;
        return "EENOANO";
    case EILSEQ: // Mismatched delimiters
        atArgument++;
        return "EILSEQ";
    case EUNFOCS: // Somehow unfocused?
        atArgument++;
        return "AUNFOCS";
    case EOVERFLOW: // More than one delimiter, can only really happen with <
        atArgument++;
        return "EOVERFLOW";
    }
    std::halfword referenceDepth = 0;
    std::halfword dereferenceDepth = 0;
    std::word sizeDepth = 0;
    // Parse out delimiters
    for (std::index_t i = 0; i < delimiterDepth; i++)
    {
        switch (delimiterStack[i])
        {
        case OPENSQBRACKET_HANDLE:
            dereferenceDepth++;
            break;
        case OPENCURLBRACKET_HANDLE:
            referenceDepth++;
            break;
        case OPENANGLEBRACKET_HANDLE:
            sizeDepth++;
        }
    }
    // Check if the request is legal
    if (sizeDepth && (referenceDepth || dereferenceDepth))
        return "ECannot do that";
    // Look for symbol
    std::hash_t hash = 0;
    std::word byteSize = 0;
    std::index_t symbol = lookupSymbol(delimiterDepth ? lastOpener : (start + 1), delimiterDepth ? firstCloser : (position - 1), &byteSize, hash);
    // If symbol is 0, try to resolve quasi or reserved.
    if (symbol == 0)
    {
        // Check if value is quasi symbol
        for (std::index_t quasiSymbol = 0; quasiSymbol < quasiSymbols.dataSize; quasiSymbol++)
        {
            // Get value
            std::hash_t quasiHash = std::read(&quasiSymbols, quasiSymbol);
            // If hash is not equal to hash, skip this part
            if (quasiHash != hash)
                continue;
            // Symbol is quasi symbol. Get value
            std::word quasiValue = std::read(&quasiSymbolValues, quasiSymbol);
            // Check if the user is trying to reference or dereference symbol
            if (referenceDepth || dereferenceDepth)
            {
                esaParser.debugInformation.errName = nullptr;
                return "ECannot reference or dereference quasi symbol";
            }
            // Check if the user is trying to obtain size info
            if (sizeDepth)
            {
                // Check if size depth is higher than 2
                if (sizeDepth > 2)
                {
                    esaParser.debugInformation.errName = nullptr;
                    return "EInvalid size request: Must be '<<>>' or '<>'.";
                }
                if (sizeDepth == 1)
                    return numericalArgument({ 4 }, false);
                return numericalArgument({ 32 }, false);
            }
            return numericalArgument({ quasiValue }, false);
        }
        for (std::index_t reservedIndex = 0; reservedIndex < reservedIdentifiers.dataSize; reservedIndex++)
        {
            // Get value
            std::hash_t reservedHash = std::read(&reservedIdentifiers, reservedIndex);
            // Skip if not what we are looking for
            if (reservedHash != hash)
                continue;
            // Check if depth requested
            if (sizeDepth)
            {
                // Save numerical error based on thingy
                std::conststring numericalError = nullptr;
                if (sizeDepth == 2)
                    numericalError = numericalArgument({ 4 }, false);
                else if (sizeDepth == 1)
                    numericalError = numericalArgument({ 32 }, false);
                else
                    return "EInvalid size request: Must be '<<>>' or '<>'.";
                esaParser.debugInformation.errName = "-WUnsupported-size-collapse";
                return "WSize request is not yet supported for registers. Defaulting to 4 bytes.";
            }
            // Get argument
            userspace::Instruction::Arg argument = std::read(&reservedIdentifiersValues, reservedIndex);
            // Check if referenced
            if (referenceDepth == 1)
                argument.referenced = true;
            else if (referenceDepth)
                return "ECannot reference a reference.";
            else
                argument.trailers[0] += dereferenceDepth;
            // Now emit data
            return setArg(argument);
        }
        esaParser.resetInfo(esaParser.debugInformation);
        esaParser.debugInformation.highlight = start + 1;
        esaParser.debugInformation.highlightLength = position - start - 2;
        esaParser.debugInformation.highlightmsg = "NHere:";
        esaParser.calculateDebugPosition();
        atArgument++;
        return "ELinker error: Cannot find reference for a given identifier.";
    }
    std::address_t value = application->builder.symbols[symbol].value();
    std::word atPage = application->builder.symbols[symbol].shndx();
    // Check if page is 0
    if (atPage == 0)
    {
    }
    // If looking for size
    if (sizeDepth)
    {
        // Check if symbol is extern
        if (atPage == 0)
            return "ECannot resolve sizes for extern symbols.";
        // Check if request is legal
        if (sizeDepth > 2)
            return "ECannot resolve more than 2 size layers.";
        // Do action based on depth. FIX: What am I trying to do here?
        if (sizeDepth == 1)
            return numericalArgument({ byteSize }, false);
        return numericalArgument({ byteSize * 8 }, false);
    }
    // Check if reference was expected
    bool expectedReference = !instruction.args[atArgument].isLiteralArg || instruction.args[atArgument].anyvalue;
    esaParser.debugInformation.errName = "-WUnexpected-arg-type";
    // Get total referenced
    BBP::int32_t totalRefDepth = dereferenceDepth - referenceDepth;
    // Check if page is 0
    // TODO: Move to different function
    if (atPage == 0)
        emitRelocation(symbol);
    // Check if request is legal
    if (totalRefDepth < -1)
        return "ECannot reference a value more than once.";
    // If totalRefDepth is -1, emit symbol
    if (totalRefDepth == -1)
        return setReference(value, 1);
    
    // Otherwise, just emit dereferenced.
    return setDereference(value, atPage, totalRefDepth + 1);
}
References BBP::userspace::argument, BACKSLASH_HANDLE, CLOSEANGLEBRACKET_HANDLE, CLOSECURLBRACKET_HANDLE, CLOSESQBRACKET_HANDLE, COMMA_HANDLE, BBP::std::conststring, EDOM, EEOF, EFAULT, EILSEQ, ELINEEND, ENOANO, ENOMSG, EOVERFLOW, EUNFOCS, BBP::Locale::Japanese::hash, BBP::Locale::Japanese::i, OPENANGLEBRACKET_HANDLE, OPENCURLBRACKET_HANDLE, OPENSQBRACKET_HANDLE, and BBP::std::read().
Referenced by _unkown().
void BBP::esa::esaProcessor::saveAndClose ()
Definition at line 57 of file Backend.cpp.
{
    application->save();
    application->close();
    std::activemem->_delete(application);
    application = nullptr;
}
References BBP::std::ResourceManager::_delete(), and BBP::std::activemem.
void BBP::esa::esaProcessor::saveIdentifier (std::index_t start, std::index_t end)
Definition at line 7 of file Backend.cpp.
{
    for (BBP::std::index_t idx = start, n = 0; idx < end; idx++, n++)
        Identifier.static_data[n] = BBP::esa::processor.esaParser.data.data[idx];
    Identifier.static_data[end - start] = 0;
}
References BBP::std::PAGE< T >::data, BBP::std::Lexer::lex_context::data, esaParser, Identifier, BBP::Locale::Japanese::n, and BBP::esa::processor.
BBP::std::conststring BBP::esa::esaProcessor::setArg (userspace::Instruction::Arg & arg)
Definition at line 433 of file Frontend.cpp.
{
    // If arg is literal, do this
    if (arg.isLiteralArg)
        return numericalArgument({ arg.data }, false);
    // Otherwise, do the following
    if (arg.referenced)
        return setReference(arg.data, arg.offset);
    else if (arg.dereferenced)
        return setDereference(arg.data, arg.offset, arg.trailers[0]);
    return "ECannot add argument that is of no type.";
}
References BBP::userspace::Instruction::Arg::data, BBP::userspace::Instruction::Arg::dereferenced, BBP::userspace::Instruction::Arg::isLiteralArg, BBP::userspace::Instruction::Arg::offset, BBP::userspace::Instruction::Arg::referenced, and BBP::userspace::Instruction::Arg::trailers.
BBP::std::conststring BBP::esa::esaProcessor::setDereference (std::word address, std::word page, std::byte count)
Definition at line 412 of file Frontend.cpp.
{
    // Save value
    bool expectedReference = !instruction.args[atArgument].isLiteralArg || instruction.args[atArgument].anyvalue;
    // Turn this argument into address
    expectAddress(atArgument);
    // Set instruction info
    instruction.args[atArgument].dereferenced = true;
    instruction.args[atArgument].trailerCount = 1;
    instruction.args[atArgument].trailers[0] = count;
    instruction.args[atArgument].data = (page << 20 | address);
    // Increment argument counter and return warning if needed
    atArgument++;
    if (!expectedReference)
        return "WDid not expect supplied argument to be address.";
    return nullptr;
}
BBP::std::conststring BBP::esa::esaProcessor::setHash (std::hash_t hash)
Definition at line 116 of file Frontend.cpp.
{
    // Cannot hash if: Hash already exists
    // Symbol has already been hashed
    // Check if the symbol doesn't already have a hash
    if (symbol.hash)
        return "EIgnoring misplaced identifier.";
    symbol.hash = hash;
    return nullptr;
}
References BBP::Locale::Japanese::hash.
Referenced by BBP::esa::TOKEN().
void BBP::esa::esaProcessor::setInstruction (userspace::OPCODES opcode, std::byte suffix, std::nibble flags, std::nibble args)
Definition at line 337 of file Frontend.cpp.
{
    // Set flags
    processor.lineIsDefiningSymbolDefinition = false;
    processor.lineIsDefiningProcedure = false;
    processor.lineIsDefiningInstruction = true;
    instruction.header.prefix = suffix;
    instruction.header.opcode = opcode;
    instruction.header.flags = flags;
    instruction.header.args = args;
    // Set suffix
    instruction.header.suffix = suffix;
}
References BBP::esa::flags, lineIsDefiningInstruction, lineIsDefiningProcedure, lineIsDefiningSymbolDefinition, and BBP::esa::processor.
Referenced by BBP::esa::INSTRUCTION().
void BBP::esa::esaProcessor::setProcedureAddress ()
Definition at line 461 of file Frontend.cpp.
{
    startedAt = processor.application->builder._text().stack.atElement;
}
References BBP::std::ELF::ELFBuilder::_text(), application, BBP::std::Stack< K >::atElement, BBP::esa::BinaryApplication::builder, BBP::esa::processor, and BBP::std::ELF::SectionBuilder::stack.
Referenced by BBP::esa::ACTION().
void BBP::esa::esaProcessor::setProcedureArgCount (std::byte count)
Definition at line 487 of file Frontend.cpp.
{
    procedureArgumentCount = count;
    doneDeclaringProcedure = true;
}
Referenced by BBP::esa::TOKEN().
void BBP::esa::esaProcessor::setProcedureIdentifier (std::index_t start, std::index_t end, std::hash_t hash)
Definition at line 466 of file Frontend.cpp.
{
    // Iterate over the text
    for (std::index_t index = start, i = 0; index < end; index++, i++)
    {
        // Write into procedure name the procedure
        std::write(&procedureName, std::read(&esaParser.data, index), i);
    }
    // Then write terminating null
    std::string_element nil = 0;
    std::write(&procedureName, nil, end - start);
    // Then write hash
    procedureHash = hash;
    // And set approriate names
    procedureNameStart = start;
    procedureNameEnd = end;
}
References BBP::Locale::Japanese::hash, BBP::Locale::Japanese::i, BBP::Locale::Japanese::nil, BBP::std::read(), and BBP::std::write().
Referenced by BBP::esa::TOKEN().
BBP::std::conststring BBP::esa::esaProcessor::setReference (std::word address, std::word page)
Definition at line 393 of file Frontend.cpp.
{
    // Save value
    bool expectedReference = !instruction.args[atArgument].isLiteralArg || instruction.args[atArgument].anyvalue;
    // Turn this argument into address
    expectAddress(atArgument);
    // Set instruction info
    instruction.args[atArgument].referenced = true;
    instruction.args[atArgument].data = (page << 20 | address);
    // Increment argument counter and return warning if needed
    atArgument++;
    if (!expectedReference)
        return "WDid not expect supplied argument to be address.";
    return nullptr;
}
BBP::std::conststring BBP::esa::esaProcessor::setSize (std::size_t size)
Definition at line 130 of file Frontend.cpp.
{
    // Return error if size already defined
    if (symbol.subtype & 0b111111100000)
    {
        esaParser.debugInformation.errName = "-Wsize-redefinition-unsupported";
        return "WSize already defined: ignored size directive.";
    }
    switch (size)
    {
    case 0: // No size
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_NIL;
        break;
    case 4: // Nibble
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DN;
        break;
    case 8: // Byte
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DB;
        break;
    case 16: // Half word
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DH;
        break;
    case 20: // Index
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DI;
        break;
    case 24: // Address
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DA;
        break;
    case 32: // Word
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DW;
        break;
    default: // Unkown
        symbol.subtype |= SYMBOL_TYPE::SYMTSZ_DW;
        esaParser.debugInformation.errName = "-Wunkown-size";
        return "WUnkown size, defaulting to 32 bits.";
    }
    // If this comes at a time where a symbol isn't defined, return error
    if (!lineIsDefiningSymbolDefinition)
    {
        esaParser.debugInformation.errName = "-Wanonymous-size-declaration";
        return "WSize declaration for anonymous symbols will be ignored.";
    }
}
References BBP::esa::SYMTSZ_DA, BBP::esa::SYMTSZ_DB, BBP::esa::SYMTSZ_DH, BBP::esa::SYMTSZ_DI, BBP::esa::SYMTSZ_DN, BBP::esa::SYMTSZ_DW, and BBP::esa::SYMTSZ_NIL.
Referenced by BBP::esa::TOKEN().
void BBP::esa::esaProcessor::setupBackend (std::conststring str, std::size_t seg, std::size_t sec, std::size_t sym)
Definition at line 51 of file Backend.cpp.
{
    application = std::activemem->add_object(new BinaryApplication(str, seg, sec, sym));
    application->setSource(esaParser.activeFile.static_data);
}
References BBP::std::activemem, and BBP::std::ResourceManager::add_object().
void BBP::esa::esaProcessor::surpressArgCountWarning ()
Definition at line 387 of file Frontend.cpp.
{
    for (std::byte n = 0; n < 8; n++)
        surpress[n] = true;
}
References BBP::Locale::Japanese::n.
void BBP::esa::esaProcessor::surpressArgCountWarning (std::byte n)
Definition at line 382 of file Frontend.cpp.
{
    surpress[n] = true;
}
References BBP::Locale::Japanese::n.
Referenced by BBP::esa::INSTRUCTION().
BBP::std::errno_t BBP::esa::esaProcessor::translate (std::PATH & path, std::PATH & dst)
Definition at line 152 of file Processor.cpp.
{
    esaParser.onUnkown = _unkown;
    esaParser.onNumericalLiteral = _numerical;
    setupBackend(dst.relName(), 0, 0, 6);
    esaParser.translateUnit(path);
    
    if (esaParser.illformed || esaParser.abort)
        discardAndClose();
    else
        saveAndClose();
    return 0;
}
References _numerical(), _unkown(), and BBP::std::PATH::relName().
Referenced by BBP::smile_main().
BBP::std::conststring BBP::esa::esaProcessor::unkown (std::index_t from, std::index_t to)
Definition at line 38 of file Secondary.cpp.
{
    esaParser.debugInformation.highlight = lastspace;
    esaParser.debugInformation.highlightLength = at - lastspace;
    esaParser.debugInformation.highlightmsg = "NHere";
    return "EUnrecognized character sequence.";
}
References BBP::Locale::Japanese::at.
Referenced by _unkown().
Field Documentation
esa::BinaryApplication* BBP::esa::esaProcessor::application
Definition at line 102 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and setProcedureAddress().
std::byte BBP::esa::esaProcessor::atArgument
Definition at line 48 of file ELSA.h.
bool BBP::esa::esaProcessor::beVerbose
Definition at line 131 of file ELSA.h.
Referenced by BBP::esa::PRAGMA().
std::word BBP::esa::esaProcessor::delimiterDepth = 0
Definition at line 139 of file ELSA.h.
Referenced by ExpectDelimiters().
std::STATIC_PAGE<std::Lexer::lex_keywordhandle, 32> BBP::esa::esaProcessor::delimiterPage
Definition at line 137 of file ELSA.h.
std::Stack<std::Lexer::lex_keywordhandle> BBP::esa::esaProcessor::delimiterStack
Definition at line 138 of file ELSA.h.
Referenced by ExpectDelimiters().
bool BBP::esa::esaProcessor::doneDeclaringProcedure
Definition at line 59 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::index_t BBP::esa::esaProcessor::endedAt
Definition at line 53 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::Lexer::lex_context BBP::esa::esaProcessor::esaParser
Definition at line 19 of file ELSA.h.
Referenced by esaProcessor(), BBP::esa::INSTRUCTION(), and saveIdentifier().
bool BBP::esa::esaProcessor::externProcedure
Definition at line 60 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::Lexer::lex_keywordhandle BBP::esa::esaProcessor::firstCloser
Definition at line 136 of file ELSA.h.
Referenced by ExpectDelimiters(), and BBP::esa::PRAGMA().
std::Lexer::lex_keywordhandle BBP::esa::esaProcessor::handle
Definition at line 134 of file ELSA.h.
Referenced by ExpectDelimiters(), and BBP::esa::PRAGMA().
userspace::Instruction BBP::esa::esaProcessor::instruction
Definition at line 47 of file ELSA.h.
Referenced by BBP::esa::TOKEN().
std::Lexer::lex_keywordhandle BBP::esa::esaProcessor::lastOpener
Definition at line 135 of file ELSA.h.
Referenced by ExpectDelimiters(), and BBP::esa::PRAGMA().
bool BBP::esa::esaProcessor::lineIsDefiningInstruction
Definition at line 142 of file ELSA.h.
Referenced by BBP::esa::ACTION(), setInstruction(), and BBP::esa::TOKEN().
bool BBP::esa::esaProcessor::lineIsDefiningProcedure
Definition at line 143 of file ELSA.h.
Referenced by BBP::esa::ACTION(), numerical(), setInstruction(), and BBP::esa::TOKEN().
bool BBP::esa::esaProcessor::lineIsDefiningSymbolDefinition
Definition at line 141 of file ELSA.h.
Referenced by BBP::esa::ACTION(), markConst(), setInstruction(), and BBP::esa::TOKEN().
std::byte BBP::esa::esaProcessor::procedureArgumentCount
Definition at line 58 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::hash_t BBP::esa::esaProcessor::procedureHash
Definition at line 54 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::STATIC_PAGE<std::string_element, 100> BBP::esa::esaProcessor::procedureName
Definition at line 55 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::index_t BBP::esa::esaProcessor::procedureNameEnd
Definition at line 57 of file ELSA.h.
std::index_t BBP::esa::esaProcessor::procedureNameStart
Definition at line 56 of file ELSA.h.
std::STATIC_PAGE<std::hash_t, 256> BBP::esa::esaProcessor::quasiSymbols
Definition at line 65 of file ELSA.h.
Referenced by buildSymbol().
std::STATIC_PAGE<std::word, 256> BBP::esa::esaProcessor::quasiSymbolValues
Definition at line 66 of file ELSA.h.
Referenced by buildSymbol().
std::STATIC_PAGE<std::hash_t, 256> BBP::esa::esaProcessor::reservedIdentifiers
Definition at line 63 of file ELSA.h.
Referenced by addReservedIdentifier().
std::STATIC_PAGE<userspace::Instruction::Arg, 256> BBP::esa::esaProcessor::reservedIdentifiersValues
Definition at line 64 of file ELSA.h.
Referenced by addReservedIdentifier().
std::Stack<std::index_t> BBP::esa::esaProcessor::routineStarts
Definition at line 111 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::STATIC_PAGE<std::index_t, 32> BBP::esa::esaProcessor::routineStartsPage
Definition at line 109 of file ELSA.h.
std::STATIC_PAGE<std::index_t, 32> BBP::esa::esaProcessor::routineSubscriberCount
Definition at line 110 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::index_t BBP::esa::esaProcessor::startedAt
Definition at line 52 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::Stack<std::index_t> BBP::esa::esaProcessor::subscribers
Definition at line 113 of file ELSA.h.
Referenced by BBP::esa::ACTION(), and BBP::esa::TOKEN().
std::STATIC_PAGE<std::index_t, 128> BBP::esa::esaProcessor::subscribersPage
Definition at line 112 of file ELSA.h.
bool BBP::esa::esaProcessor::surpress[8]
Definition at line 49 of file ELSA.h.
Referenced by BBP::esa::INSTRUCTION().
std::Lexer::lex_thing BBP::esa::esaProcessor::symbol
Definition at line 38 of file ELSA.h.
Referenced by markConst(), and BBP::esa::TOKEN().
std::Stack<std::byte> BBP::esa::esaProcessor::symbolDataByte
Definition at line 40 of file ELSA.h.
std::Stack<std::halfword> BBP::esa::esaProcessor::symbolDataHalfword
Definition at line 42 of file ELSA.h.
std::STATIC_PAGE<std::byte, 512> BBP::esa::esaProcessor::symbolDataPage
Definition at line 39 of file ELSA.h.
std::PAGE<std::halfword> BBP::esa::esaProcessor::symbolDataPageHalfword
Definition at line 41 of file ELSA.h.
std::PAGE<std::word> BBP::esa::esaProcessor::symbolDataPageWord
Definition at line 43 of file ELSA.h.
std::Stack<std::word> BBP::esa::esaProcessor::symbolDataWord
Definition at line 44 of file ELSA.h.
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.