BBP::std::PATH
NAME
BBP::std::PATH
SYNOPSIS
#include <FileSys.h>
Public Member Functions
std::c_string pathName ()
std::c_string fileName ()
std::c_string relName ()
bool isRelativeToRoot ()
bool isDefinedFromRoot ()
PATH & makeAbsolutePath (PATH *currentPath)
PATH & resolveAbsolutes ()
void makeRelative (PATH &reference, PATH &dir)
PATH (VOLUME *, std::string &path)
PATH (VOLUME *, std::conststring path)
PATH (std::string &path)
PATH (std::conststring path)
PATH (std::PATH &)
PATH ()
~PATH ()
Private Member Functions
PATH & getFileAndPaths ()
Private Attributes
std::static_string< max_path_length > _path
std::static_string< max_path_length > rawPath
std::index_t fileNameStartIndex
std::ResourceManager * allocator
VOLUME * Volume
Detailed Description
Definition at line 40 of file FileSys.h.
Constructor & Destructor Documentation
BBP::std::PATH::PATH (std::VOLUME * v, std::string & path)
Definition at line 16 of file Path.cpp.
    : PATH(v, str.data) {}
BBP::std::PATH::PATH (std::VOLUME * v, std::conststring path)
Definition at line 19 of file Path.cpp.
    : fileNameStartIndex(0), allocator(BBP::std::activemem), Volume(v)
{
    // Get string sizes
    std::size_t pathlength = std::strlen(str);
    // Copy string into rawPath
    std::strcpy(&rawPath, str);
    // Then prepare _path
    this->getFileAndPaths();
}
References getFileAndPaths(), rawPath, BBP::std::strcpy(), and BBP::std::strlen().
BBP::std::PATH::PATH (std::string & path)
Definition at line 8 of file Path.cpp.
    : PATH(BBP::std::primaryVolume, str)
{}
BBP::std::PATH::PATH (std::conststring path)
Definition at line 12 of file Path.cpp.
    : PATH(BBP::std::primaryVolume, str)
{}
BBP::std::PATH::PATH (std::PATH & path)
Definition at line 34 of file Path.cpp.
    : PATH((std::conststring)path.relName())
{
}
BBP::std::PATH::PATH ()
Definition at line 4 of file Path.cpp.
    : Volume(nullptr), allocator(nullptr), fileNameStartIndex(0)
{
}
BBP::std::PATH::~PATH ()
Definition at line 40 of file Path.cpp.
{
    
}
Member Function Documentation
BBP::std::c_string BBP::std::PATH::fileName ()
Definition at line 45 of file Path.cpp.
{
    // Move to somewhere else?
    _path.data = _path.static_data;
    return std::read_a(&_path, fileNameStartIndex + 2);
}
References BBP::std::read_a().
Referenced by BBP::esa::esaProcessor::includeFile(), and BBP::std::Lexer::lex_context::parseFile().
BBP::std::PATH & BBP::std::PATH::getFileAndPaths () [private]
Definition at line 93 of file Path.cpp.
{
    // Get length of rawPath, and create copy
    std::size_t rawPathLength = std::strlen(rawPath);
    char nul = '\0';
    // Copy over string
    for (index_t index = 0; index < rawPathLength; index++)
    {
        char c = __UNSAFE__(read)(&rawPath, index);
        if (c == '/')
            this->fileNameStartIndex = index;
        __UNSAFE__(write)(&_path, c, index);
    }
    if (fileNameStartIndex)
    {
        // Then seperate last FILLME
        for (index_t index = fileNameStartIndex; index < rawPathLength; index++)
            __UNSAFE__(write)(&_path, __UNSAFE__(read)(&rawPath, index), index + 1);
        __UNSAFE__(write)(&_path, nul, fileNameStartIndex + 1);
    }
    else
    {
        for (index_t index = fileNameStartIndex; index < rawPathLength; index++)
            __UNSAFE__(write)(&_path, __UNSAFE__(read)(&rawPath, index), index + 2);
        __UNSAFE__(write)(&_path, nul, 0);
    }
    return *this;
}
References __UNSAFE__, BBP::std::read(), BBP::std::strlen(), and BBP::std::write().
Referenced by PATH().
bool BBP::std::PATH::isDefinedFromRoot ()
Definition at line 74 of file Path.cpp.
{
    // Check if char is '/'
    if (this->Volume == nullptr)
        return false;
    // Check if volume is not the same as ..
    std::size_t VolPathLength = std::strlen(this->Volume->volumePath.relName());
    for (std::index_t idx = 0; idx < VolPathLength; idx++)
    {
        char c1 = this->Volume->volumePath.relName()[idx];
        char c2 = __UNSAFE__(std::read)(&rawPath, idx);
        if (c1 != c2)
            return false;
    }
    return true;
}
References __UNSAFE__, BBP::std::read(), and BBP::std::strlen().
bool BBP::std::PATH::isRelativeToRoot ()
Definition at line 66 of file Path.cpp.
{
    // Get first character
    char first = __UNSAFE__(std::read)(&rawPath, 0);
    return first == '/';
}
References __UNSAFE__, BBP::std::first(), and BBP::std::read().
Referenced by makeRelative().
BBP::std::PATH & BBP::std::PATH::makeAbsolutePath (std::PATH * currentDir)
Definition at line 126 of file Path.cpp.
{
    if (!isDefinedFromRoot())
    {
        // Check if dir is relative to root
        bool isRelToRootDir = isRelativeToRoot();
        // Declare strings used to calculate absolute path
        std::c_string relativeTo;
        std::c_string activeDirectory = rawPath.data;
        // Check if this path is relative or absolute
        if (isRelToRootDir)
        {
            if (Volume == nullptr)
                throw std::exception("ERR_UNDEF_VOL", EFAULT);
            relativeTo = Volume->volumePath.rawPath.data;
        }
        else
        {
            if (currentDir == nullptr)
                throw std::exception("ERR_UNDEF_DIR", ENOENT);
            relativeTo = currentDir->rawPath.data;
        }
        // Create buffers
        std::static_string<2 * std::max_path_length> result;
        // Calculate path lengths
        std::size_t relativeToLength = std::strlen(relativeTo);
        std::size_t activeDirectoryLength = std::strlen(activeDirectory);
        // If paths are larger than ...
        if (relativeToLength + activeDirectoryLength + 1 > std::max_page_elements)
        {
            allocator->free(result.data);
            throw std::exception("REL_DIR_TOOLONG", ENAMETOOLONG);
        }
        // Buffer whatever
        if (isRelToRootDir)
            std::sprintf(result.data, "%s%s", relativeTo, activeDirectory + 1);
        else
            std::sprintf(result.data, "%s%s", relativeTo, activeDirectory);
        // Copy result stuff into rawData
        std::strcpy(&rawPath, result.data);
    }
    // Resolve paths
    return resolveAbsolutes();;
}
References BBP::std::PAGE< T >::data, EFAULT, ENAMETOOLONG, ENOENT, BBP::std::exception(), BBP::std::max_page_elements, rawPath, BBP::std::sprintf(), BBP::std::strcpy(), and BBP::std::strlen().
Referenced by BBP::std::FileNode::FileNode(), BBP::std::FILE::getINodeIndex(), BBP::esa::esaProcessor::includeFromPath(), makeRelative(), and BBP::shell().
void BBP::std::PATH::makeRelative (PATH & reference, PATH & dir)
Definition at line 252 of file Path.cpp.
{
    if (!dir.isRelativeToRoot())
    {
        
        dir.makeAbsolutePath(&reference);
        if (reference.isRelativeToRoot())
            dir.makeAbsolutePath(nullptr);
    }
}
References isRelativeToRoot(), and makeAbsolutePath().
BBP::std::c_string BBP::std::PATH::pathName ()
Definition at line 53 of file Path.cpp.
{
    return std::read_a(&_path, 0);
}
References BBP::std::read_a().
Referenced by BBP::esa::esaProcessor::includeFile(), and BBP::std::Lexer::lex_context::translateUnit().
BBP::std::c_string BBP::std::PATH::relName ()
Definition at line 58 of file Path.cpp.
{
    // Move to somewhere else?
    rawPath.data = rawPath.static_data;
    return rawPath.data;
}
Referenced by BBP::std::FileNode::FileNode(), BBP::std::FILE::getINodeIndex(), BBP::esa::esaProcessor::includeFile(), BBP::esa::esaProcessor::includeFromPath(), BBP::esa::esaProcessor::translate(), and BBP::std::Lexer::lex_context::translateUnit().
BBP::std::PATH & BBP::std::PATH::resolveAbsolutes ()
Definition at line 179 of file Path.cpp.
{
    // Get rawPath length
    std::size_t rawPathLength = std::strlen(rawPath);
    // Stack to
    std::PAGE<index_t> separatorPage(64, (std::index_t *)allocator->calloc(64, sizeof(std::index_t)));
    std::Stack<index_t> separatorStack(&separatorPage, 64);
    for (index_t index = 0; index < rawPathLength - 1; index++)
    {
        // Get current and next character
        char c = __UNSAFE__(read)(&rawPath, index);
        char nextC = __UNSAFE__(read)(&rawPath, index + 1);
        char nextnextC = __UNSAFE__(read)(&rawPath, index + 2);
        // If next character is null, break out of loop
        if (nextC == '\0')
            break;
        // If this character is a '/', do some things based on next character
        if (c == '/')
        {
            // If next character is '/', just move everything left by one
            if (nextC == '/')
            {
                for (index_t i = index; i < rawPathLength; i++)
                    __UNSAFE__(write)(&rawPath, __UNSAFE__(read)(&rawPath, i + 1), i);
                index--;
            }
            else // Otherwise
            {
                separatorStack << index;
            }
            continue;
        }
        // If this character is a '.', do some things based on next character
        if (c == '.')
        {
            // If next character is a '/', just move everything left by two
            if (nextC == '/')
            {
                for (index_t i = index; i < rawPathLength; i++)
                    __UNSAFE__(write)(&rawPath, __UNSAFE__(read)(&rawPath, i + 2), i);
                index--;
            }
            else if (nextC == '.' && nextnextC == '/')
            {
                // Read last two '/''s from stack
                index_t from, to;
                separatorStack >> to >> from;
                // Looping
                for (index_t idx = 0; idx + to + 2 < rawPathLength; idx++)
                    __UNSAFE__(write)(&rawPath, __UNSAFE__(read)(&rawPath, idx + to + 4), idx + from + 1);
                // Move back to 'from'
                index = from - 1;
            }
            continue;
        }
        
    }
    // Deallocate separatorPage data
    allocator->free(separatorPage.data);
    // Mirror edited stuff into ...
    return getFileAndPaths();
}
References __UNSAFE__, BBP::std::PAGE< T >::data, BBP::Locale::Japanese::i, BBP::std::read(), BBP::std::strlen(), BBP::Locale::Japanese::to, and BBP::std::write().
Field Documentation
std::static_string<max_path_length> BBP::std::PATH::_path [private]
Definition at line 69 of file FileSys.h.
std::ResourceManager* BBP::std::PATH::allocator [private]
Definition at line 78 of file FileSys.h.
std::index_t BBP::std::PATH::fileNameStartIndex [private]
Definition at line 75 of file FileSys.h.
std::static_string<max_path_length> BBP::std::PATH::rawPath [private]
Definition at line 72 of file FileSys.h.
Referenced by makeAbsolutePath(), and PATH().
VOLUME* BBP::std::PATH::Volume [private]
Definition at line 81 of file FileSys.h.
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.