.TH "BBP::std::SIGNAL" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::SIGNAL
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Signal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSIGNAL\fP (\fBsignal_t\fP sig)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsignal_t\fP \fB_sig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file Signal\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BBP::std::SIGNAL::SIGNAL (\fBsignal_t\fP sig)\fC [inline]\fP"

.PP
Definition at line 21 of file Signal\&.h\&.
.PP
.nf
22                 : _sig(sig)
23             {
24             }
.fi
.SH "Field Documentation"
.PP 
.SS "\fBsignal_t\fP BBP::std::SIGNAL::_sig"

.PP
Definition at line 19 of file Signal\&.h\&.
.PP
Referenced by BBP::std::execute()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
