.TH "BBP::std::PAGE< T >" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::PAGE< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Memory\&.h>\fP
.PP
Inherited by \fBBBP::std::STATIC_PAGE< T, K >\fP\fC [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPAGE\fP (\fBsize_t\fP Size, T *dat)"
.br
.ti -1c
.RI "\fBPAGE\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsize_t\fP \fBdataSize\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBbytes\fP"
.br
.ti -1c
.RI "\fBPAGE\fP< T > * \fBprevPage\fP"
.br
.ti -1c
.RI "\fBPAGE\fP< T > * \fBnextPage\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBmem_t\fP * \fBraw\fP"
.br
.ti -1c
.RI "   T * \fBdata\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct BBP::std::PAGE< T >"

.PP
Definition at line 33 of file Memory\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBBBP::std::PAGE\fP< T >::\fBPAGE\fP (\fBsize_t\fP Size, T * dat)\fC [inline]\fP"

.PP
Definition at line 46 of file Memory\&.h\&.
.PP
.nf
46 : dataSize(Size), bytes(Size * (sizeof(T) / sizeof(mem_t))), prevPage(nullptr), nextPage(nullptr), data(dat) {}
.fi
.SS "template<typename T > \fBBBP::std::PAGE\fP< T >::\fBPAGE\fP ()\fC [inline]\fP"

.PP
Definition at line 47 of file Memory\&.h\&.
.PP
.nf
47 : dataSize(0), bytes(0), prevPage(0), nextPage(0), data(nullptr) {}
.fi
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "template<typename T > \fBsize_t\fP \fBBBP::std::PAGE\fP< T >::bytes"

.PP
Definition at line 36 of file Memory\&.h\&.
.SS "template<typename T > T* \fBBBP::std::PAGE\fP< T >::data"

.PP
Definition at line 43 of file Memory\&.h\&.
.PP
Referenced by BBP::std::R2D::background(), BBP::badapple_main(), BBP::std::ELF::ELFBuilder::close(), BBP::std::ELF::ELFBuilder::ELFBuilder(), BBP::std::Stack< BBP::std::DIRECTORY >::Extend(), BBP::std::fprintf(), BBP::std::R2D::GetFontFromFile(), BBP::std::R2D::Hrule(), BBP::esa::esaProcessor::includeFile(), BBP::std::Lexer::lex_context::Log(), BBP::std::PATH::makeAbsolutePath(), BBP::std::R2D::newWindow(), BBP::std::R2D::PrintCharacterAt(), readByte(), readHalfWord(), BBP::std::R2D::readPixel(), readWord(), BBP::std::PATH::resolveAbsolutes(), BBP::esa::esaProcessor::saveIdentifier(), BBP::std::R2D::setPixel(), BBP::shell(), BBP::smile_main(), BBP::std::strcmp(), BBP::std::R2D::Vrule(), writeByte(), writeHalfWord(), and writeWord()\&.
.SS "template<typename T > \fBsize_t\fP \fBBBP::std::PAGE\fP< T >::dataSize"

.PP
Definition at line 35 of file Memory\&.h\&.
.PP
Referenced by BBP::esa::esaProcessor::addReservedIdentifier(), BBP::std::ELF::SectionBuilder::Append(), BBP::esa::esaProcessor::buildSymbol(), BBP::std::ELF::ELFBuilder::ELFBuilder(), BBP::std::Stack< BBP::std::DIRECTORY >::Extend(), BBP::std::R2D::GetFontFromFile(), and BBP::shell()\&.
.SS "template<typename T > \fBPAGE\fP<T>* \fBBBP::std::PAGE\fP< T >::nextPage"

.PP
Definition at line 39 of file Memory\&.h\&.
.PP
Referenced by BBP::std::ELF::ELFBuilder::close(), and BBP::std::Stack< BBP::std::DIRECTORY >::Extend()\&.
.SS "template<typename T > \fBPAGE\fP<T>* \fBBBP::std::PAGE\fP< T >::prevPage"

.PP
Definition at line 38 of file Memory\&.h\&.
.PP
Referenced by BBP::std::Stack< BBP::std::DIRECTORY >::Extend()\&.
.SS "template<typename T > \fBmem_t\fP* \fBBBP::std::PAGE\fP< T >::raw"

.PP
Definition at line 42 of file Memory\&.h\&.
.PP
Referenced by BBP::shell()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
