BBP::std::ELF::ELFBuilder
NAME
BBP::std::ELF::ELFBuilder
SYNOPSIS
#include <ELF.h>
Public Member Functions
ELFBuilder (ResourceManager *res, std::size_t segCount, std::size_t secCount, std::size_t symCount)
ELFBuilder (PAGE< string_element > *_file, ResourceManager *res)
std::byte ident (std::byte)
void ident (std::byte, std::byte)
std::halfword type (void)
void type (std::halfword)
std::halfword machine (void)
void machine (std::halfword)
std::word version (void)
void version (std::word)
std::address_t entry (void)
void entry (std::address_t)
std::offset_t phoff (void)
void phoff (std::offset_t)
std::offset_t shoff (void)
void shoff (std::offset_t)
std::word flags (void)
void flags (std::word)
std::halfword ehsize (void)
void ehsize (std::halfword)
std::halfword phentsize (void)
void phentsize (std::halfword)
std::halfword phnum (void)
void phnum (std::halfword)
std::halfword shentsize (void)
void shentsize (std::halfword)
std::halfword shnum (void)
void shnum (std::halfword)
std::halfword shstrndx (void)
void shstrndx (std::halfword)
void emitHeader ()
std::size_t calculateHeaderSize ()
void emitELFHeaders ()
SectionBuilder & _shstrtab ()
SectionBuilder & _strtab ()
SectionBuilder & _symtab ()
SectionBuilder & _hashtab ()
SectionBuilder & _bss ()
SectionBuilder & _data ()
SectionBuilder & _data1 ()
SectionBuilder & _fini ()
SectionBuilder & _init ()
SectionBuilder & _rodata ()
SectionBuilder & _rodata1 ()
SectionBuilder & _text ()
SectionBuilder & _rel_text ()
void recalculateOffsets (std::offset_t after, std::size_t byHowMuch)
void formStandard (std::size_t textSize, std::size_t dataSize, std::size_t rodataSize, std::size_t bssSize)
void renameSymbol (std::index_t, conststring)
void close ()
Data Fields
ResourceManager * allocator
PAGE< string_element > file
bool Endian
Stack< SegmentBuilder > segments
Stack< SectionBuilder > sections
Stack< SymbolBuilder > symbols
std::index_t shstrtab
std::index_t strtab
std::index_t symtab
std::index_t hashtab
std::index_t bss
std::index_t data
std::index_t data1
std::index_t fini
std::index_t init
std::index_t rodata
std::index_t rodata1
std::index_t text
std::index_t rel_text
std::size_t symbolCount
std::word hashBucketCount
std::word hashChainCount
Private Attributes
PAGE< SegmentBuilder > segPages
PAGE< SectionBuilder > secPages
PAGE< SymbolBuilder > symPages
bool isMemUnique
Detailed Description
Definition at line 22 of file ELF.h.
Constructor & Destructor Documentation
BBP::std::ELF::ELFBuilder::ELFBuilder (ResourceManager * res, std::size_t segCount, std::size_t secCount, std::size_t symCount)
Definition at line 7 of file ELFHeader.cpp.
    : allocator(res),
    file(PAGE<string_element>(52 + segCount * ELF_SEGMENT_HEADERSIZE + secCount * ELF_SECTION_HEADERSIZE, (std::string_element *)res->calloc(52 + segCount * ELF_SEGMENT_HEADERSIZE + secCount * ELF_SECTION_HEADERSIZE, sizeof(std::string_element)))),
    Endian(false),
    segments(Stack<SegmentBuilder>(&segPages, segCount)),
    sections(Stack<SectionBuilder>(&secPages, secCount)),
    symbols(Stack<SymbolBuilder>(&symPages, symCount)),
    symbolCount(symCount),
    segPages(PAGE<SegmentBuilder>(segCount, (SegmentBuilder *)res->calloc(segCount, sizeof(SegmentBuilder)))),
    secPages(PAGE<SectionBuilder>(secCount, (SectionBuilder *)res->calloc(secCount, sizeof(SectionBuilder)))),
    symPages(PAGE<SymbolBuilder>(symCount, (SymbolBuilder *)res->calloc(symCount, sizeof(SymbolBuilder)))),
    isMemUnique(true),
    hashBucketCount(4),
    hashChainCount(symCount)
{
    for (index_t index = 0; index < segCount; index++)
    {
        segments[index] = ELF::SegmentBuilder(this, 0);
        segments[index].elf = this;
    }
    for (index_t index = 0; index < secCount; index++)
    {
        sections[index] = ELF::SectionBuilder(this, 0);
        sections[index].elf = this;
    }
    for (index_t index = 0; index < symCount; index++)
    {
        symbols[index] = ELF::SymbolBuilder(this, 0);
        symbols[index].elf = this;
    }
    phnum(segCount);
    shnum(secCount);
}
References phnum(), sections, segments, shnum(), and symbols.
BBP::std::ELF::ELFBuilder::ELFBuilder (PAGE< string_element > * _file, ResourceManager * res)
Definition at line 42 of file ELFHeader.cpp.
    : allocator(res),
    file(PAGE<string_element>(0, nullptr)),
    Endian(false),
    segments(Stack<SegmentBuilder>(&segPages, 0)),
    sections(Stack<SectionBuilder>(&secPages, 0)),
    symbols(Stack<SymbolBuilder>(&symPages, 0)),
    symbolCount(0),
    segPages(PAGE<SegmentBuilder>()),
    secPages(PAGE<SectionBuilder>()),
    symPages(PAGE<SymbolBuilder>()),
    isMemUnique(false),
    hashBucketCount(4),
    hashChainCount(0)
{
    // Check if file is not nullptr
    if (_file == nullptr)
        throw std::exception("Invalid file", ENOENT);
    // Check if resource allocator is nullptr
    if (res == nullptr)
        throw std::exception("Invalid resource allocator", ENOENT);
    // Check if file size is at least 52 bytes
    if (std::seqlen(*_file) < 52)
        throw std::exception("File is not ELF file: too small.", ENODATA);
    // Set file
    file = std::PAGE<std::string_element>(_file->dataSize, _file->data);
    // Get magic
    std::word magic = (ident(0) << 24) | (ident(1) << 16) | (ident(2) << 8) | ident(3);
    // Validate magic
    if (magic != 0x7f454c46)
        throw std::exception("FIle is not ELF file: wrong magic", ENODATA);
    // Get phnum and shnum count
    std::size_t sectionCount = shnum();
    std::size_t segmentCount = phnum();
    // Create resources
    secPages = std::PAGE<SectionBuilder>(sectionCount, (SectionBuilder *)res->calloc(sectionCount, sizeof(SectionBuilder)));
    segPages = std::PAGE<SegmentBuilder>(segmentCount, (SegmentBuilder *)res->calloc(segmentCount, sizeof(SegmentBuilder)));
    
    // And assign stacks
    sections = std::Stack<SectionBuilder>(&secPages, sectionCount);
    segments = std::Stack<SegmentBuilder>(&segPages, segmentCount);
    // Get offsets of program and section headers
    std::offset_t sectionOffsets = shoff();
    std::offset_t segmentOffsets = phoff();
    // Now also get size of program and section headers
    std::size_t sectionSize = shentsize();
    std::size_t segmentSize = phentsize();
    // Now initialize them
    for (index_t index = 0; index < segmentCount; index++)
    {
        segments[index] = ELF::SegmentBuilder(this, segmentOffsets + index * segmentSize);
        segments[index].elf = this;
    }
    for (index_t index = 0; index < sectionCount; index++)
    {
        sections[index] = ELF::SectionBuilder(this, sectionOffsets + index * sectionSize);
        sections[index].elf = this;
    }
    // Now, each section should now be initialized. Find the string tab.
    shstrtab = shstrndx();
    // If strings are invalid, return error
    if (shstrtab == 0)
        throw std::exception("No string table present", ENODATA);
    // If string table type is not string table, throw error
    if (_shstrtab().type() != std::ELF::SHT_STRTAB)
        throw std::exception("Invalid string table type", EINVAL);
    // Try to parse each string stuff
    for (std::index_t index = 0; index < sectionCount; index++)
    {
        // Get string
        std::c_string sectionName = file.data + sections[shstrtab].offset() + sections[index].name();
        // Hash string
        std::hash_t nameHash = std::strhsh(sectionName);
        // Switch based on name
        switch (nameHash)
        {
        case 0x12b9abd7: /*.text*/
            text = index;
            break;
        case 0x04079010: /*.rel.text*/
            rel_text = index;
            break;
        case 0x12b2faba: /*.init*/
            init = index;
            break;
        case 0x121a2ae8: /*.fini*/
            fini = index;
            break;
        case 0x11ac0ad4: /*.data*/
            data = index;
            break;
        case 0x2d1158c8: /*.rodata*/
            rodata = index;
            break;
        case 0x119dc248: /*.bss*/
            bss = index;
            break;
        case 0x0ea7e788: /*.data1*/
            data1 = index;
            break;
        case 0x0c25337e: /*.rodata1*/
            rodata1 = index;
            break;
        case 0x0700b1c6: /*.symtab*/
            symtab = index;
            break;
        case 0x0eb7addf: /*.shstrtab*/
            shstrtab = index;
            break;
        case 0x0702e4dc: /*.strtab*/
            strtab = index;
            break;
        case 0x0ed1cab6: /*.hashtab*/
            hashtab = index;
            break;
        }
    }
    // If symbols exist, check how many exist
    // Early return ignored since more conditions may be added later.
    if (symtab)
    {
        // Get count by dividing size by entsize
        symbolCount = _symtab().size() / _symtab().entsize();
        // Remove empty symbols
        for (std::index_t index = 0; index < symbolCount; index++)
        {
            // Create symbol builder
            SymbolBuilder sym(this, _symtab().offset() + _symtab().entsize() * index);
            // Get name
            std::c_string symName = file.data + sections[_symtab().link()].offset() + sym.name();
            // Symbol is wasted if index is 0 and name is 0.
            if (sym.info() == 0 && sym.name() == 0)
                symbolCount--;
        }
        // Create page and stack
        symPages = std::PAGE<SymbolBuilder>(symbolCount, (SymbolBuilder *)res->calloc(symbolCount, sizeof(SymbolBuilder)));
        symbols = std::Stack<SymbolBuilder>(&symPages, symbolCount);
        // Assign stuff now
        for (std::index_t index = 0; index < symbolCount; index++)
        {
            // Constructor
            symbols[index] = SymbolBuilder(this, _symtab().offset() + _symtab().entsize() * index);
            // Save data if it has any.
            if (!(symbols[index].info() == 0 && symbols[index].name() == 0) && index != 0)
                symbols[index].data = std::PAGE<std::string_element>(symbols[index].size(), file.data + sections[symbols[index].shndx()].offset() + symbols[index].value());
        }
        // and that's basically it.
    }
}
References _shstrtab(), _symtab(), bss, BBP::std::ResourceManager::calloc(), BBP::std::PAGE< T >::data, data, data1, BBP::std::PAGE< T >::dataSize, EINVAL, ENODATA, ENOENT, BBP::std::ELF::SectionBuilder::entsize(), BBP::std::exception(), file, fini, hashtab, ident(), BBP::std::ELF::SymbolBuilder::info(), init, BBP::std::ELF::SectionBuilder::link(), BBP::std::ELF::SymbolBuilder::name(), phentsize(), phnum(), phoff(), rel_text, rodata, rodata1, secPages, sections, segments, segPages, BBP::std::seqlen(), shentsize(), shnum(), shoff(), shstrndx(), shstrtab, BBP::std::ELF::SHT_STRTAB, BBP::std::ELF::SectionBuilder::size(), BBP::std::strhsh(), strtab, symbolCount, symbols, symPages, symtab, text, and type().
Member Function Documentation
SectionBuilder& BBP::std::ELF::ELFBuilder::_bss ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_data ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_data1 ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_fini ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_hashtab ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_init ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_rel_text ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_rodata ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_rodata1 ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_shstrtab ()
Referenced by ELFBuilder().
SectionBuilder& BBP::std::ELF::ELFBuilder::_strtab ()
SectionBuilder& BBP::std::ELF::ELFBuilder::_symtab ()
Referenced by ELFBuilder().
SectionBuilder& BBP::std::ELF::ELFBuilder::_text ()
Referenced by BBP::esa::ACTION(), BBP::esa::esaProcessor::setProcedureAddress(), and BBP::smile_main().
BBP::std::size_t BBP::std::ELF::ELFBuilder::calculateHeaderSize ()
Definition at line 26 of file ELF.cpp.
{
    return 52 + phnum() * ELF_SEGMENT_HEADERSIZE + shnum() * ELF_SECTION_HEADERSIZE;
}
References ELF_SECTION_HEADERSIZE, and ELF_SEGMENT_HEADERSIZE.
void BBP::std::ELF::ELFBuilder::close ()
Definition at line 222 of file ELFHeader.cpp.
{
    segments.atElement = segments.max_elements;
    sections.atElement = sections.max_elements;
    symbols.atElement = symbols.max_elements;
    segments.foreach([](SegmentBuilder &segment) { segment.close(); });
    sections.foreach([](SectionBuilder &section) { section.close(); });
    symbols.foreach([](SymbolBuilder &symbol) { symbol.close(); });
    // Loop over until no more
    std::PAGE<std::ELF::SegmentBuilder> *segmentptr = segments.page;
    std::PAGE<std::ELF::SectionBuilder> *sectionptr = sections.page;
    std::PAGE<std::ELF::SymbolBuilder> *symbolptr = symbols.page;
    do
    {
        std::PAGE<std::ELF::SegmentBuilder> *tmp = segmentptr->nextPage;
        allocator->free(segmentptr->data);
        segmentptr = tmp;
    } while (segmentptr);
    do
    {
        std::PAGE<std::ELF::SectionBuilder> *tmp = sectionptr->nextPage;
        allocator->free(sectionptr->data);
        sectionptr = tmp;
    } while (sectionptr);
    do
    {
        std::PAGE<std::ELF::SymbolBuilder> *tmp = symbolptr->nextPage;
        allocator->free(symbolptr->data);
        symbolptr = tmp;
    } while (symbolptr);
    //allocator->free(segments.page->data);
    //allocator->free(sections.page->data);
    //allocator->free(symbols.page->data);
    if (isMemUnique)
        allocator->free(file.data);
}
References BBP::std::ELF::SymbolBuilder::close(), BBP::std::ELF::SectionBuilder::close(), BBP::std::ELF::SegmentBuilder::close(), BBP::std::PAGE< T >::data, and BBP::std::PAGE< T >::nextPage.
Referenced by BBP::smile_main().
void BBP::std::ELF::ELFBuilder::ehsize (std::halfword value)
Definition at line 96 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_EHSIZEOFFSET); }
References ELF_HEADER_EHSIZEOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::ehsize (void)
Definition at line 95 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_EHSIZEOFFSET); }
References ELF_HEADER_EHSIZEOFFSET, and readHalfWord().
void BBP::std::ELF::ELFBuilder::emitELFHeaders ()
Definition at line 4 of file ELF.cpp.
{
    // Set phnum and shnum
    phnum(segments.max_elements);
    shnum(sections.max_elements);
    // If phnum is not 0, set offset directly after header
    if (segments.max_elements)
    {
        phoff(52);
        // Then, if shnum is not 0, set shoff directly after program headers
        if (sections.max_elements)
            shoff(52 + segments.max_elements * ELF_SEGMENT_HEADERSIZE);
    }
    else if (sections.max_elements)
    {
        // Otherwise set shoff to 52 if it has sections
        shoff(52);
    }
}
References ELF_SEGMENT_HEADERSIZE, phnum(), phoff(), sections, segments, shnum(), and shoff().
void BBP::std::ELF::ELFBuilder::emitHeader ()
Definition at line 32 of file ELF.cpp.
{
    // Write the 16 magic ident bytes
    ident(0, 0x7F);
    ident(1, 'E');
    ident(2, 'L');
    ident(3, 'F');
    // 32 Bits
    ident(4, 0x01);
    
    // Endian-nes
    ident(5, Endian + 1);
    // ELF header version, always 1
    ident(6, 1);
    // OS ABI (version 1)
    ident(7, 0x1);
    // Default is relocatable
    type(1);
    // Custom instruction set, so set to whatever
    machine(0);
    // Set version to 1
    version(1);
    // Since this is relocatable, entry is 0
    entry(32);
    // Set phnum and shnum
    phnum(segments.max_elements);
    shnum(sections.max_elements);
    // Emit the other headers
    emitELFHeaders();
    // Set the respective pages for each segment
    std::offset_t phOffset = phoff();
    for (std::index_t segment = 0; segment < segments.max_elements; segment++)
        this->segments[segment].header = std::string(ELF_SEGMENT_HEADERSIZE, file.data + phOffset + segment * ELF_SEGMENT_HEADERSIZE);
    // ... and section
    std::offset_t shOffset = shoff();
    for (std::index_t section = 0; section < sections.max_elements; section++)
        this->sections[section].header = std::string(ELF_SECTION_HEADERSIZE, file.data + shOffset + section * ELF_SECTION_HEADERSIZE);
    // No flags
    flags(0);
    // Header size, which is always 52
    ehsize(52);
    // Set sizes
    phentsize(ELF_SEGMENT_HEADERSIZE);
    shentsize(ELF_SECTION_HEADERSIZE);
    // No string index
    shstrndx(0);
}
References ELF_SECTION_HEADERSIZE, ELF_SEGMENT_HEADERSIZE, and BBP::esa::flags.
void BBP::std::ELF::ELFBuilder::entry (std::address_t value)
Definition at line 84 of file ELFHeaderGettersSetters.cpp.
{ writeWord(this, value, ELF_HEADER_ENTRYOFFSET); }
References ELF_HEADER_ENTRYOFFSET, and writeWord().
BBP::std::address_t BBP::std::ELF::ELFBuilder::entry (void)
Definition at line 83 of file ELFHeaderGettersSetters.cpp.
{ return readWord(this, ELF_HEADER_ENTRYOFFSET); }
References ELF_HEADER_ENTRYOFFSET, and readWord().
void BBP::std::ELF::ELFBuilder::flags (std::word value)
Definition at line 93 of file ELFHeaderGettersSetters.cpp.
{ writeWord(this, value, ELF_HEADER_FLAGSOFFSET); }
References ELF_HEADER_FLAGSOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::ELFBuilder::flags (void)
Definition at line 92 of file ELFHeaderGettersSetters.cpp.
{ return readWord(this, ELF_HEADER_FLAGSOFFSET); }
References ELF_HEADER_FLAGSOFFSET, and readWord().
void BBP::std::ELF::ELFBuilder::formStandard (std::size_t textSize, std::size_t dataSize, std::size_t rodataSize, std::size_t bssSize)
Definition at line 288 of file ELFHeader.cpp.
{
    // Emit headers so we can actually modify them
    emitHeader();
    // Define the different sections indicies
    text = 1;
    rel_text = 2;
    init = 3;
    fini = 4;
    data = 5;
    bss = 6;
    data1 = 7;
    rodata = 8;
    rodata1 = 9;
    symtab = 10;
    shstrtab = 11;
    strtab = 12;
    hashtab = 13;
    // Now set types
    sections[text].type(SHT_PROGBITS);
    sections[rel_text].type(SHT_REL);
    sections[init].type(SHT_PROGBITS);
    sections[fini].type(SHT_PROGBITS);
    sections[data].type(SHT_PROGBITS);
    sections[rodata].type(SHT_PROGBITS);
    sections[bss].type(SHT_NOBITS);
    sections[data1].type(SHT_PROGBITS);
    sections[rodata1].type(SHT_PROGBITS);
    sections[symtab].type(SHT_SYMTAB);
    sections[strtab].type(SHT_STRTAB);
    sections[shstrtab].type(SHT_STRTAB);
    sections[hashtab].type(SHT_HASH);
    // Set ent sizes
    sections[symtab].entsize(ELF_SYMBOL_ENTRYSIZE);
    sections[rel_text].entsize(8);
    // Set names
    sections[shstrtab].Append(128);
    sections[shstrtab].stack++;
    sections[text].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".text";
    sections[rel_text].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".rel.text";
    sections[init].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".init";
    sections[fini].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".fini";
    sections[data].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".data";
    sections[rodata].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".rodata";
    sections[bss].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".bss";
    sections[data1].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".data1";
    sections[rodata1].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".rodata1";
    sections[symtab].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".symtab";
    sections[strtab].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".strtab";
    sections[shstrtab].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".shstrtab";
    sections[hashtab].name(sections[shstrtab].stack.atElement);
    sections[shstrtab].stack <<= ".hashtab";
    // Update header
    shstrndx(shstrtab);
    // Update link and info fields
    sections[rel_text].link(symtab);
    sections[rel_text].info(text);
    sections[symtab].link(strtab);
    sections[symtab].info(symbolCount);
    sections[hashtab].link(symtab);
    IHate::Myself();
    // Add symbols
    sections[symtab].Append(symbolCount * ELF_SYMBOL_ENTRYSIZE);
    sections[strtab].Append(1024);
    
    // Set symbol entry flags
    for (index_t i = 0; i < symbolCount; i++)
    {
        symbols[i].header.bytes = ELF_SYMBOL_ENTRYSIZE;
        symbols[i].header.data = sections[symtab].data.data + ELF_SYMBOL_ENTRYSIZE * i;
    }
    // Now Append data sizes and so
    sections[text].Append(textSize);
    sections[data].Append(dataSize);
    sections[rodata].Append(rodataSize);
    sections[bss].Append(bssSize);
    // Now set hashtab ready. Size has to be multiplied by sizeof(word) / sizeof(byte)
    sections[hashtab].Append((hashBucketCount + hashChainCount + 2) * (sizeof(std::word) / sizeof(std::byte)));
    sections[hashtab].stack << hashBucketCount;
    sections[hashtab].stack << hashChainCount;
    // We want .text sections to be executable,
    sections[text].flags(std::ELF::Executable);
    // We also want .data and .bss to be allocated and writeable
    sections[bss].flags(std::ELF::Allocator | std::ELF::Writeable);
    sections[data].flags(std::ELF::Allocator | std::ELF::Writeable);
    sections[data1].flags(std::ELF::Allocator | std::ELF::Writeable);
    // We want rodata to be allocateable, but not writeable
    sections[rodata].flags(std::ELF::Allocator);
    sections[rodata1].flags(std::ELF::Allocator);
}
References BBP::std::ELF::Allocator, ELF_SYMBOL_ENTRYSIZE, BBP::std::ELF::Executable, BBP::Locale::Japanese::i, IHate::Myself(), BBP::std::ELF::SHT_HASH, BBP::std::ELF::SHT_NOBITS, BBP::std::ELF::SHT_PROGBITS, BBP::std::ELF::SHT_REL, BBP::std::ELF::SHT_STRTAB, BBP::std::ELF::SHT_SYMTAB, and BBP::std::ELF::Writeable.
Referenced by BBP::esa::BinaryApplication::BinaryApplication().
BBP::std::byte BBP::std::ELF::ELFBuilder::ident (std::byte idx)
Definition at line 71 of file ELFHeaderGettersSetters.cpp.
{ return readByte(this, ELF_HEADER_IDENTOFFSET + idx); }
References ELF_HEADER_IDENTOFFSET, and readByte().
Referenced by ELFBuilder().
void BBP::std::ELF::ELFBuilder::ident (std::byte idx, std::byte value)
Definition at line 72 of file ELFHeaderGettersSetters.cpp.
{ writeByte(this, value, ELF_HEADER_IDENTOFFSET + idx); }
References ELF_HEADER_IDENTOFFSET, and writeByte().
void BBP::std::ELF::ELFBuilder::machine (std::halfword value)
Definition at line 78 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_MACHINEOFFSET); }
References ELF_HEADER_MACHINEOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::machine (void)
Definition at line 77 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_MACHINEOFFSET); }
References ELF_HEADER_MACHINEOFFSET, and readHalfWord().
void BBP::std::ELF::ELFBuilder::phentsize (std::halfword value)
Definition at line 99 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_PHENTSIZEOFFSET); }
References ELF_HEADER_PHENTSIZEOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::phentsize (void)
Definition at line 98 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_PHENTSIZEOFFSET); }
References ELF_HEADER_PHENTSIZEOFFSET, and readHalfWord().
Referenced by ELFBuilder().
void BBP::std::ELF::ELFBuilder::phnum (std::halfword value)
Definition at line 102 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_PHNUMOFFSET); }
References ELF_HEADER_PHNUMOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::phnum (void)
Definition at line 101 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_PHNUMOFFSET); }
References ELF_HEADER_PHNUMOFFSET, and readHalfWord().
Referenced by ELFBuilder(), and emitELFHeaders().
void BBP::std::ELF::ELFBuilder::phoff (std::offset_t value)
Definition at line 87 of file ELFHeaderGettersSetters.cpp.
{ writeWord(this, value, ELF_HEADER_PHOFFOFFSET); }
References ELF_HEADER_PHOFFOFFSET, and writeWord().
BBP::std::offset_t BBP::std::ELF::ELFBuilder::phoff (void)
Definition at line 86 of file ELFHeaderGettersSetters.cpp.
{ return readWord(this, ELF_HEADER_PHOFFOFFSET); }
References ELF_HEADER_PHOFFOFFSET, and readWord().
Referenced by ELFBuilder(), and emitELFHeaders().
void BBP::std::ELF::ELFBuilder::recalculateOffsets (std::offset_t after, std::size_t byHowMuch)
Definition at line 96 of file ELF.cpp.
{
    std::size_t PHnum = phnum();
    for (index_t index = 0; index < PHnum; index++)
    {
        // If segment is below or equal to this one, do nothing
        if (segments[index].offset() <= after)
            continue;
        // If segment has no data, do nothing
        if (segments[index].filesz() == 0)
            continue;
        // Add offset
        segments[index].offset(segments[index].offset() + howmuch);
    }
    std::size_t SHnum = shnum();
    for (index_t index = 0; index < SHnum; index++)
    {
        // If section is below or equal to this one, do nothing
        if (sections[index].offset() <= after)
            continue;
        // If section has no data, do nothing
        if (sections[index].size() == 0)
            continue;
        // Add offset
        sections[index].offset(sections[index].offset() + howmuch);
    }
}
void BBP::std::ELF::ELFBuilder::renameSymbol (std::index_t, conststring)
Definition at line 404 of file ELFHeader.cpp.
{
    if (symb >= symbolCount)
        throw std::exception("Symbol out of range.", ERANGE);
    sections[strtab].stack++;
    symbols[symb].name(sections[strtab].stack.atElement);
    sections[strtab].stack <<= name;
}
References ERANGE, and BBP::std::exception().
void BBP::std::ELF::ELFBuilder::shentsize (std::halfword value)
Definition at line 105 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_SHENTSIZEOFFSET); }
References ELF_HEADER_SHENTSIZEOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::shentsize (void)
Definition at line 104 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_SHENTSIZEOFFSET); }
References ELF_HEADER_SHENTSIZEOFFSET, and readHalfWord().
Referenced by ELFBuilder().
void BBP::std::ELF::ELFBuilder::shnum (std::halfword value)
Definition at line 108 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_SHNUMOFFSET); }
References ELF_HEADER_SHNUMOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::shnum (void)
Definition at line 107 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_SHNUMOFFSET); }
References ELF_HEADER_SHNUMOFFSET, and readHalfWord().
Referenced by ELFBuilder(), and emitELFHeaders().
void BBP::std::ELF::ELFBuilder::shoff (std::offset_t value)
Definition at line 90 of file ELFHeaderGettersSetters.cpp.
{ writeWord(this, value, ELF_HEADER_SHOFFOFFSET); }
References ELF_HEADER_SHOFFOFFSET, and writeWord().
BBP::std::offset_t BBP::std::ELF::ELFBuilder::shoff (void)
Definition at line 89 of file ELFHeaderGettersSetters.cpp.
{ return readWord(this, ELF_HEADER_SHOFFOFFSET); }
References ELF_HEADER_SHOFFOFFSET, and readWord().
Referenced by ELFBuilder(), and emitELFHeaders().
void BBP::std::ELF::ELFBuilder::shstrndx (std::halfword value)
Definition at line 111 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_SHSTRNDXOFFSET); }
References ELF_HEADER_SHSTRNDXOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::shstrndx (void)
Definition at line 110 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_SHSTRNDXOFFSET); }
References ELF_HEADER_SHSTRNDXOFFSET, and readHalfWord().
Referenced by ELFBuilder().
void BBP::std::ELF::ELFBuilder::type (std::halfword value)
Definition at line 75 of file ELFHeaderGettersSetters.cpp.
{ writeHalfWord(this, value, ELF_HEADER_TYPEOFFSET); }
References ELF_HEADER_TYPEOFFSET, and writeHalfWord().
BBP::std::halfword BBP::std::ELF::ELFBuilder::type (void)
Definition at line 74 of file ELFHeaderGettersSetters.cpp.
{ return readHalfWord(this, ELF_HEADER_TYPEOFFSET); }
References ELF_HEADER_TYPEOFFSET, and readHalfWord().
Referenced by ELFBuilder().
void BBP::std::ELF::ELFBuilder::version (std::word value)
Definition at line 81 of file ELFHeaderGettersSetters.cpp.
{ writeWord(this, value, ELF_HEADER_VERSIONOFFSET); }
References ELF_HEADER_VERSIONOFFSET, and writeWord().
BBP::std::word BBP::std::ELF::ELFBuilder::version (void)
Definition at line 80 of file ELFHeaderGettersSetters.cpp.
{ return readWord(this, ELF_HEADER_VERSIONOFFSET); }
References ELF_HEADER_VERSIONOFFSET, and readWord().
Field Documentation
ResourceManager* BBP::std::ELF::ELFBuilder::allocator
Definition at line 30 of file ELF.h.
Referenced by BBP::std::ELF::SectionBuilder::Append(), and BBP::std::ELF::SegmentBuilder::Append().
std::index_t BBP::std::ELF::ELFBuilder::bss
Definition at line 100 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::data
Definition at line 101 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::data1
Definition at line 102 of file ELF.h.
Referenced by ELFBuilder().
bool BBP::std::ELF::ELFBuilder::Endian
Definition at line 36 of file ELF.h.
Referenced by readHalfWord(), readWord(), writeHalfWord(), and writeWord().
PAGE<string_element> BBP::std::ELF::ELFBuilder::file
Definition at line 33 of file ELF.h.
Referenced by BBP::std::ELF::SectionBuilder::Append(), BBP::std::ELF::SegmentBuilder::Append(), ELFBuilder(), readByte(), readHalfWord(), readWord(), BBP::smile_main(), writeByte(), writeHalfWord(), and writeWord().
std::index_t BBP::std::ELF::ELFBuilder::fini
Definition at line 103 of file ELF.h.
Referenced by ELFBuilder().
std::word BBP::std::ELF::ELFBuilder::hashBucketCount
Definition at line 139 of file ELF.h.
std::word BBP::std::ELF::ELFBuilder::hashChainCount
Definition at line 140 of file ELF.h.
std::index_t BBP::std::ELF::ELFBuilder::hashtab
Definition at line 98 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::init
Definition at line 104 of file ELF.h.
Referenced by ELFBuilder().
bool BBP::std::ELF::ELFBuilder::isMemUnique [private]
Definition at line 147 of file ELF.h.
std::index_t BBP::std::ELF::ELFBuilder::rel_text
Definition at line 108 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::rodata
Definition at line 105 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::rodata1
Definition at line 106 of file ELF.h.
Referenced by ELFBuilder().
PAGE<SectionBuilder> BBP::std::ELF::ELFBuilder::secPages [private]
Definition at line 144 of file ELF.h.
Referenced by ELFBuilder().
Stack<SectionBuilder> BBP::std::ELF::ELFBuilder::sections
Definition at line 42 of file ELF.h.
Referenced by BBP::esa::ACTION(), ELFBuilder(), and emitELFHeaders().
Stack<SegmentBuilder> BBP::std::ELF::ELFBuilder::segments
Definition at line 39 of file ELF.h.
Referenced by ELFBuilder(), and emitELFHeaders().
PAGE<SegmentBuilder> BBP::std::ELF::ELFBuilder::segPages [private]
Definition at line 143 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::shstrtab
Definition at line 95 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::strtab
Definition at line 96 of file ELF.h.
Referenced by ELFBuilder().
std::size_t BBP::std::ELF::ELFBuilder::symbolCount
Definition at line 136 of file ELF.h.
Referenced by ELFBuilder(), and BBP::smile_main().
Stack<SymbolBuilder> BBP::std::ELF::ELFBuilder::symbols
Definition at line 45 of file ELF.h.
Referenced by ELFBuilder(), and BBP::smile_main().
PAGE<SymbolBuilder> BBP::std::ELF::ELFBuilder::symPages [private]
Definition at line 145 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::symtab
Definition at line 97 of file ELF.h.
Referenced by ELFBuilder().
std::index_t BBP::std::ELF::ELFBuilder::text
Definition at line 107 of file ELF.h.
Referenced by BBP::esa::ACTION(), and ELFBuilder().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.