.TH "BBP::std::ELF::ElfHeader" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::ELF::ElfHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ELF32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::byte\fP \fBe_ident\fP [16]"
.br
.RI "[7f 45 4c 46] [ 00=invalid 01=32bit 02=64bit ] [ 00=invalid 01=LSB first 02=MSB first ] [ 01 00 00 00 00 00 00 00 00 00] "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_type\fP"
.br
.RI "See E_TYPE enum\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_machine\fP"
.br
.RI "See E_MACHINE enum\&. "
.ti -1c
.RI "\fBstd::word\fP \fBe_version\fP"
.br
.RI "Always 1\&. "
.ti -1c
.RI "\fBstd::address_t\fP \fBe_entry\fP"
.br
.RI "Entry point address for executables, Constructor address for shared libraries, otherwise 0\&. "
.ti -1c
.RI "\fBstd::offset_t\fP \fBe_phoff\fP"
.br
.RI "Program Header Offset (Relative to File start) "
.ti -1c
.RI "\fBstd::offset_t\fP \fBe_shoff\fP"
.br
.RI "Section Header Offset (Relative to File start) "
.ti -1c
.RI "\fBstd::word\fP \fBe_flags\fP"
.br
.RI "Flags\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_ehsize\fP"
.br
.RI "Elf header size\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_phentsize\fP"
.br
.RI "Program header entry size\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_phnum\fP"
.br
.RI "Program header entry count\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_shentsize\fP"
.br
.RI "Section header entry size\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_shnum\fP"
.br
.RI "Section header entry count\&. "
.ti -1c
.RI "\fBstd::halfword\fP \fBe_shstrndx\fP"
.br
.RI "Section header string table index\&. "
.ti -1c
.RI "\fBstd::dword\fP \fBe_entry\fP"
.br
.RI "Entry point address for executables, Constructor address for shared libraries, otherwise 0\&. "
.ti -1c
.RI "\fBstd::dword\fP \fBe_phoff\fP"
.br
.RI "Program Header Offset (Relative to File start) "
.ti -1c
.RI "\fBstd::dword\fP \fBe_shoff\fP"
.br
.RI "Section Header Offset (Relative to File start) "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 165 of file ELF32\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_ehsize"

.PP
Elf header size\&. 
.PP
Definition at line 174 of file ELF32\&.h\&.
.SS "\fBstd::dword\fP BBP::std::ELF::ElfHeader::e_entry"

.PP
Entry point address for executables, Constructor address for shared libraries, otherwise 0\&. 
.PP
Definition at line 149 of file ELF64\&.h\&.
.SS "\fBstd::address_t\fP BBP::std::ELF::ElfHeader::e_entry"

.PP
Entry point address for executables, Constructor address for shared libraries, otherwise 0\&. 
.PP
Definition at line 170 of file ELF32\&.h\&.
.SS "\fBstd::word\fP BBP::std::ELF::ElfHeader::e_flags"

.PP
Flags\&. 
.PP
Definition at line 173 of file ELF32\&.h\&.
.SS "\fBstd::byte\fP BBP::std::ELF::ElfHeader::e_ident"

.PP
[7f 45 4c 46] [ 00=invalid 01=32bit 02=64bit ] [ 00=invalid 01=LSB first 02=MSB first ] [ 01 00 00 00 00 00 00 00 00 00] 
.PP
Definition at line 166 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_machine"

.PP
See E_MACHINE enum\&. 
.PP
Definition at line 168 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_phentsize"

.PP
Program header entry size\&. 
.PP
Definition at line 175 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_phnum"

.PP
Program header entry count\&. 
.PP
Definition at line 176 of file ELF32\&.h\&.
.SS "\fBstd::dword\fP BBP::std::ELF::ElfHeader::e_phoff"

.PP
Program Header Offset (Relative to File start) 
.PP
Definition at line 150 of file ELF64\&.h\&.
.SS "\fBstd::offset_t\fP BBP::std::ELF::ElfHeader::e_phoff"

.PP
Program Header Offset (Relative to File start) 
.PP
Definition at line 171 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_shentsize"

.PP
Section header entry size\&. 
.PP
Definition at line 177 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_shnum"

.PP
Section header entry count\&. 
.PP
Definition at line 178 of file ELF32\&.h\&.
.SS "\fBstd::dword\fP BBP::std::ELF::ElfHeader::e_shoff"

.PP
Section Header Offset (Relative to File start) 
.PP
Definition at line 151 of file ELF64\&.h\&.
.SS "\fBstd::offset_t\fP BBP::std::ELF::ElfHeader::e_shoff"

.PP
Section Header Offset (Relative to File start) 
.PP
Definition at line 172 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_shstrndx"

.PP
Section header string table index\&. 
.PP
Definition at line 179 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::ElfHeader::e_type"

.PP
See E_TYPE enum\&. 
.PP
Definition at line 167 of file ELF32\&.h\&.
.SS "\fBstd::word\fP BBP::std::ELF::ElfHeader::e_version"

.PP
Always 1\&. 
.PP
Definition at line 169 of file ELF32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
