.TH "BBP::std::ELF::SymbolEntry" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::ELF::SymbolEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ELF32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstd::word\fP \fBst_name\fP = 0"
.br
.RI "Name of the symbol (relative to string table (string table is a section!)) "
.ti -1c
.RI "\fBstd::address_t\fP \fBst_value\fP = 0"
.br
.RI "Value of symbol (So for example where 'main' starts) "
.ti -1c
.RI "\fBstd::word\fP \fBst_size\fP = 0"
.br
.RI "The size of whatever this symbol is (for example the size of 'main') "
.ti -1c
.RI "\fBstd::byte\fP \fBst_info\fP = 0"
.br
.RI "0x\&.0 - Local, 0x\&.1 - Global, 0x\&.2 - Weak, 0x0\&. - no type, 0x1\&. - object, 0x2\&. - function "
.ti -1c
.RI "\fBstd::byte\fP \fBst_other\fP = 0"
.br
.ti -1c
.RI "\fBstd::halfword\fP \fBst_shndx\fP = 0"
.br
.RI "the section to which the symbol is relative "
.ti -1c
.RI "\fBstd::dword\fP \fBst_size\fP = 0"
.br
.RI "The size of whatever this symbol is (for example the size of 'main') "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 212 of file ELF32\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBstd::byte\fP BBP::std::ELF::SymbolEntry::st_info = 0"

.PP
0x\&.0 - Local, 0x\&.1 - Global, 0x\&.2 - Weak, 0x0\&. - no type, 0x1\&. - object, 0x2\&. - function 
.PP
Definition at line 216 of file ELF32\&.h\&.
.SS "\fBstd::word\fP BBP::std::ELF::SymbolEntry::st_name = 0"

.PP
Name of the symbol (relative to string table (string table is a section!)) Name of the symbol (relative to string table (string table is a section!) 
.PP
Definition at line 213 of file ELF32\&.h\&.
.SS "\fBstd::byte\fP BBP::std::ELF::SymbolEntry::st_other = 0"

.PP
Definition at line 217 of file ELF32\&.h\&.
.SS "\fBstd::halfword\fP BBP::std::ELF::SymbolEntry::st_shndx = 0"

.PP
the section to which the symbol is relative 
.PP
Definition at line 218 of file ELF32\&.h\&.
.SS "\fBstd::dword\fP BBP::std::ELF::SymbolEntry::st_size = 0"

.PP
The size of whatever this symbol is (for example the size of 'main') 
.PP
Definition at line 188 of file ELF64\&.h\&.
.SS "\fBstd::word\fP BBP::std::ELF::SymbolEntry::st_size = 0"

.PP
The size of whatever this symbol is (for example the size of 'main') 
.PP
Definition at line 215 of file ELF32\&.h\&.
.SS "\fBstd::address_t\fP BBP::std::ELF::SymbolEntry::st_value = 0"

.PP
Value of symbol (So for example where 'main' starts) Value of symbol (So for example where 'main' starts\&. 
.PP
Definition at line 214 of file ELF32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
