.TH "BBP::std::window" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BBP::std::window
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Graphics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwindow\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPAGE\fP< \fBRGBA_t\fP > \fBbackBuffer\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBwidth\fP = 0"
.br
.ti -1c
.RI "\fBsize_t\fP \fBheight\fP = 0"
.br
.ti -1c
.RI "\fBpos_t\fP \fBxPos\fP = 0"
.br
.ti -1c
.RI "\fBpos_t\fP \fByPos\fP = 0"
.br
.ti -1c
.RI "\fBpos_t\fP \fBzPos\fP = 0"
.br
.ti -1c
.RI "\fBcolour\fP \fBStroke\fP = \fBcolour\fP()"
.br
.ti -1c
.RI "\fBcolour\fP \fBFill\fP = \fBcolour\fP()"
.br
.ti -1c
.RI "\fBcolour\fP \fBChroma\fP = \fBcolour\fP()"
.br
.ti -1c
.RI "bool \fBdoStroke\fP = true"
.br
.ti -1c
.RI "bool \fBdoFill\fP = true"
.br
.ti -1c
.RI "\fBchan_t\fP \fBstrokeWeight\fP = 5"
.br
.ti -1c
.RI "\fBPAGE\fP< \fBmask_t\fP > \fBtypeFace\fP"
.br
.ti -1c
.RI "int \fBfontCount\fP"
.br
.ti -1c
.RI "\fBPAGE\fP< \fBstring_element\fP > \fBcharMapping\fP"
.br
.ti -1c
.RI "\fBstring_element\fP \fBfontMapping\fP [256]"
.br
.ti -1c
.RI "\fBchan_t\fP \fBfontSize\fP = 3"
.br
.ti -1c
.RI "\fBchan_t\fP \fBfontSpacing\fP = 8"
.br
.ti -1c
.RI "\fBpos_t\fP \fBcursorPosX\fP = 0"
.br
.ti -1c
.RI "\fBpos_t\fP \fBcursorPosY\fP = 0"
.br
.ti -1c
.RI "\fBchan_t\fP \fBcoloumn\fP = 0"
.br
.ti -1c
.RI "\fBchan_t\fP \fBline\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file Graphics\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BBP::std::window::window ()\fC [inline]\fP"

.PP
Definition at line 74 of file Graphics\&.h\&.
.PP
.nf
75             {
76                 width = 0;
77                 height = 0;
78 
79                 xPos = 0;
80                 yPos = 0;
81                 zPos = 0;
82             }
.fi
.PP
References height, width, xPos, yPos, and zPos\&.
.SH "Field Documentation"
.PP 
.SS "\fBPAGE\fP<\fBRGBA_t\fP> BBP::std::window::backBuffer"

.PP
Definition at line 41 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::background(), BBP::std::R2D::Hrule(), BBP::std::R2D::newWindow(), BBP::std::R2D::readPixel(), BBP::std::R2D::setPixel(), and BBP::std::R2D::Vrule()\&.
.SS "\fBPAGE\fP<\fBstring_element\fP> BBP::std::window::charMapping"

.PP
Definition at line 62 of file Graphics\&.h\&.
.SS "\fBcolour\fP BBP::std::window::Chroma = \fBcolour\fP()"

.PP
Definition at line 52 of file Graphics\&.h\&.
.SS "\fBchan_t\fP BBP::std::window::coloumn = 0"

.PP
Definition at line 71 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::print(), and BBP::std::R2D::setCursorPos()\&.
.SS "\fBpos_t\fP BBP::std::window::cursorPosX = 0"

.PP
Definition at line 68 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::print(), and BBP::std::R2D::setCursorPos()\&.
.SS "\fBpos_t\fP BBP::std::window::cursorPosY = 0"

.PP
Definition at line 69 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::print(), and BBP::std::R2D::setCursorPos()\&.
.SS "bool BBP::std::window::doFill = true"

.PP
Definition at line 55 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::fill(), BBP::std::R2D::noFill(), and BBP::std::R2D::Rect()\&.
.SS "bool BBP::std::window::doStroke = true"

.PP
Definition at line 54 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::noStroke(), and BBP::std::R2D::Rect()\&.
.SS "\fBcolour\fP BBP::std::window::Fill = \fBcolour\fP()"

.PP
Definition at line 51 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::Box(), and BBP::std::R2D::fill()\&.
.SS "int BBP::std::window::fontCount"

.PP
Definition at line 60 of file Graphics\&.h\&.
.SS "\fBstring_element\fP BBP::std::window::fontMapping[256]"

.PP
Definition at line 63 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::GetFontFromFile(), and BBP::std::R2D::PrintCharacterAt()\&.
.SS "\fBchan_t\fP BBP::std::window::fontSize = 3"

.PP
Definition at line 65 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::execute(), and BBP::std::R2D::print()\&.
.SS "\fBchan_t\fP BBP::std::window::fontSpacing = 8"

.PP
Definition at line 66 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::execute(), and BBP::std::R2D::print()\&.
.SS "\fBsize_t\fP BBP::std::window::height = 0"

.PP
Definition at line 44 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::background(), BBP::std::R2D::newWindow(), and window()\&.
.SS "\fBchan_t\fP BBP::std::window::line = 0"

.PP
Definition at line 72 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::print(), and BBP::std::R2D::setCursorPos()\&.
.SS "\fBcolour\fP BBP::std::window::Stroke = \fBcolour\fP()"

.PP
Definition at line 50 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::Hrule(), BBP::std::R2D::setPixel(), BBP::std::R2D::stroke(), and BBP::std::R2D::Vrule()\&.
.SS "\fBchan_t\fP BBP::std::window::strokeWeight = 5"

.PP
Definition at line 57 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::Rect(), and BBP::std::R2D::strokeWeight()\&.
.SS "\fBPAGE\fP<\fBmask_t\fP> BBP::std::window::typeFace"

.PP
Definition at line 59 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::GetFontFromFile(), and BBP::std::R2D::PrintCharacterAt()\&.
.SS "\fBsize_t\fP BBP::std::window::width = 0"

.PP
Definition at line 43 of file Graphics\&.h\&.
.PP
Referenced by BBP::std::R2D::background(), BBP::std::R2D::Hrule(), BBP::std::R2D::newWindow(), BBP::std::R2D::readPixel(), BBP::std::R2D::setPixel(), BBP::std::R2D::Vrule(), and window()\&.
.SS "\fBpos_t\fP BBP::std::window::xPos = 0"

.PP
Definition at line 46 of file Graphics\&.h\&.
.PP
Referenced by window()\&.
.SS "\fBpos_t\fP BBP::std::window::yPos = 0"

.PP
Definition at line 47 of file Graphics\&.h\&.
.PP
Referenced by window()\&.
.SS "\fBpos_t\fP BBP::std::window::zPos = 0"

.PP
Definition at line 48 of file Graphics\&.h\&.
.PP
Referenced by window()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
