.TH "CPPApplications.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPPApplications.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBBP::shell_main\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBBBP::boot_main\fP (int, char **)"
.br
.ti -1c
.RI "int \fBBBP::logout_main\fP (int, char **)"
.br
.ti -1c
.RI "int \fBBBP::neofetch_main\fP (int, char **)"
.br
.ti -1c
.RI "int \fBBBP::badapple_main\fP (int, char **)"
.br
.ti -1c
.RI "int \fBBBP::smile_main\fP (int, char **)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
