.TH "Cunts" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cunts
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StressRelief\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBallOfYou\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file StressRelief\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Cunts::allOfYou ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 14 of file StressRelief\&.h\&.
.PP
.nf
15     {}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
