.TH "ELF.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELF.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Memory\&.h'\fP
.br
\fC#include 'Strings\&.h'\fP
.br
\fC#include 'Resources\&.h'\fP
.br
\fC#include 'ELF32\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBBP::std::ELF::ELFBuilder\fP"
.br
.ti -1c
.RI "class \fBBBP::std::ELF::SymbolBuilder\fP"
.br
.ti -1c
.RI "class \fBBBP::std::ELF::SectionBuilder\fP"
.br
.ti -1c
.RI "class \fBBBP::std::ELF::SegmentBuilder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.ti -1c
.RI " \fBBBP::std::ELF\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
