.TH "ELF64.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELF64.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stddef\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBBP::std::ELF::ElfHeader\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::ELF::ProgramHeader\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::ELF::SectionHeader\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::ELF::SymbolEntry\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::ELF::RelEntry\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::ELF::RelaEntry\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.ti -1c
.RI " \fBBBP::std::ELF\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBELF_HEADER_IDENTOFFSET\fP   0"
.br
.ti -1c
.RI "#define \fBELF_HEADER_IDENTSIZE\fP   16"
.br
.ti -1c
.RI "#define \fBELF_HEADER_TYPEOFFSET\fP   16"
.br
.ti -1c
.RI "#define \fBELF_HEADER_TYPESIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_MACHINEOFFSET\fP   18"
.br
.ti -1c
.RI "#define \fBELF_HEADER_MACHINESIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_VERSIONOFFSET\fP   20"
.br
.ti -1c
.RI "#define \fBELF_HEADER_VERSIONSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_HEADER_ENTRYOFFSET\fP   24"
.br
.ti -1c
.RI "#define \fBELF_HEADER_ENTRYSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_HEADER_PHOFFOFFSET\fP   32"
.br
.ti -1c
.RI "#define \fBELF_HEADER_PHOFFSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHOFFOFFSET\fP   40"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHOFFSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_HEADER_FLAGSOFFSET\fP   48"
.br
.ti -1c
.RI "#define \fBELF_HEADER_FLAGSSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_HEADER_EHSIZEOFFSET\fP   52"
.br
.ti -1c
.RI "#define \fBELF_HEADER_EHSIZESIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_PHENTSIZEOFFSET\fP   54"
.br
.ti -1c
.RI "#define \fBELF_HEADER_PHENTSIZESIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_PHNUMOFFSET\fP   56"
.br
.ti -1c
.RI "#define \fBELF_HEADER_PHNUMSIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHENTSIZEOFFSET\fP   58"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHENTSIZESIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHNUMOFFSET\fP   60"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHNUMSIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHSTRNDXOFFSET\fP   62"
.br
.ti -1c
.RI "#define \fBELF_HEADER_SHSTRNDXSIZE\fP   2"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_HEADERSIZE\fP   32"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_TYPEOFFSET\fP   0"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_TYPESIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_FLAGSOFFSET\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_FLAGSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_OFFSETOFFSET\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_OFFSETSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_VADDROFFSET\fP   12"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_VADDRSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_PADDROFFSET\fP   16"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_PADDRSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_FILESZOFFSET\fP   20"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_FILESZSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_MEMSZOFFSET\fP   24"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_MEMSZSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_ALIGNOFFSET\fP   28"
.br
.ti -1c
.RI "#define \fBELF_SEGMENT_ALIGNSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SECTION_HEADERSIZE\fP   64"
.br
.ti -1c
.RI "#define \fBELF_SECTION_NAMEOFFSET\fP   0"
.br
.ti -1c
.RI "#define \fBELF_SECTION_NAMESIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SECTION_TYPEOFFSET\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SECTION_TYPESIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SECTION_FLAGSOFFSET\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SECTION_FLAGSSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SECTION_ADDROFFSET\fP   16"
.br
.ti -1c
.RI "#define \fBELF_SECTION_ADDRSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SECTION_OFFSETOFFSET\fP   24"
.br
.ti -1c
.RI "#define \fBELF_SECTION_OFFSETSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SECTION_SIZEOFFSET\fP   32"
.br
.ti -1c
.RI "#define \fBELF_SECTION_SIZESIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SECTION_LINKOFFSET\fP   40"
.br
.ti -1c
.RI "#define \fBELF_SECTION_LINKSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SECTION_INFOOFFSET\fP   44"
.br
.ti -1c
.RI "#define \fBELF_SECTION_INFOSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SECTION_ADDRALIGNOFFSET\fP   48"
.br
.ti -1c
.RI "#define \fBELF_SECTION_ADDRALIGNSIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SECTION_ENTSIZEOFFSET\fP   56"
.br
.ti -1c
.RI "#define \fBELF_SECTION_ENTSIZESIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_ENTRYSIZE\fP   20"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_NAMEOFFSET\fP   0"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_NAMESIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_VALUEOFFSET\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_VALUESIZE\fP   4"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_SIZEOFFSET\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_SIZESIZE\fP   8"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_INFOOFFSET\fP   16"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_INFOSIZE\fP   1"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_OTHEROFFSET\fP   17"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_OTHERSIZE\fP   1"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_SHNDXOFFSET\fP   18"
.br
.ti -1c
.RI "#define \fBELF_SYMBOL_SHNDXSIZE\fP   2"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBBP::std::ELF::E_TYPE\fP { \fBBBP::std::ELF::ET_NONE\fP = 0, \fBBBP::std::ELF::ET_REL\fP = 1, \fBBBP::std::ELF::ET_EXEC\fP = 2, \fBBBP::std::ELF::ET_DYN\fP = 3, \fBBBP::std::ELF::ET_CORE\fP = 4, \fBBBP::std::ELF::ET_NONE\fP = 0, \fBBBP::std::ELF::ET_REL\fP = 1, \fBBBP::std::ELF::ET_EXEC\fP = 2, \fBBBP::std::ELF::ET_DYN\fP = 3, \fBBBP::std::ELF::ET_CORE\fP = 4 }"
.br
.ti -1c
.RI "enum \fBBBP::std::ELF::E_MACHINE\fP { \fBBBP::std::ELF::X86\fP = 0x03, \fBBBP::std::ELF::MIPS\fP = 0x08, \fBBBP::std::ELF::ARM\fP = 0x28, \fBBBP::std::ELF::AMD64\fP = 0x3E, \fBBBP::std::ELF::ARMV8\fP = 0xB7, \fBBBP::std::ELF::RISCV\fP = 0xF3, \fBBBP::std::ELF::X86\fP = 0x03, \fBBBP::std::ELF::MIPS\fP = 0x08, \fBBBP::std::ELF::ARM\fP = 0x28, \fBBBP::std::ELF::AMD64\fP = 0x3E, \fBBBP::std::ELF::ARMV8\fP = 0xB7, \fBBBP::std::ELF::RISCV\fP = 0xF3 }"
.br
.ti -1c
.RI "enum \fBBBP::std::ELF::P_TYPE\fP { \fBBBP::std::ELF::PT_NILL\fP = 0, \fBBBP::std::ELF::PT_LOAD\fP = 1, \fBBBP::std::ELF::PT_DYNAMIC\fP = 2, \fBBBP::std::ELF::PT_INTERP\fP = 3, \fBBBP::std::ELF::PT_NOTE\fP = 4, \fBBBP::std::ELF::PT_SHLIB\fP = 5, \fBBBP::std::ELF::PT_PHDR\fP = 6, \fBBBP::std::ELF::PT_TLS\fP = 7, \fBBBP::std::ELF::PT_NILL\fP = 0, \fBBBP::std::ELF::PT_LOAD\fP = 1, \fBBBP::std::ELF::PT_DYNAMIC\fP = 2, \fBBBP::std::ELF::PT_INTERP\fP = 3, \fBBBP::std::ELF::PT_NOTE\fP = 4, \fBBBP::std::ELF::PT_SHLIB\fP = 5, \fBBBP::std::ELF::PT_PHDR\fP = 6, \fBBBP::std::ELF::PT_TLS\fP = 7 }"
.br
.ti -1c
.RI "enum \fBBBP::std::ELF::SH_TYPE\fP { \fBBBP::std::ELF::SHT_NILL\fP = 0, \fBBBP::std::ELF::SHT_PROGBITS\fP = 1, \fBBBP::std::ELF::SHT_SYMTAB\fP = 2, \fBBBP::std::ELF::SHT_STRTAB\fP = 3, \fBBBP::std::ELF::SHT_RELA\fP = 4, \fBBBP::std::ELF::SHT_HASH\fP = 5, \fBBBP::std::ELF::SHT_DYNAMIC\fP = 6, \fBBBP::std::ELF::SHT_NOTE\fP = 7, \fBBBP::std::ELF::SHT_NOBITS\fP = 8, \fBBBP::std::ELF::SHT_REL\fP = 9, \fBBBP::std::ELF::SHT_SHLIB\fP = 10, \fBBBP::std::ELF::SHT_DYNSYM\fP = 11, \fBBBP::std::ELF::SHT_NILL\fP = 0, \fBBBP::std::ELF::SHT_PROGBITS\fP = 1, \fBBBP::std::ELF::SHT_SYMTAB\fP = 2, \fBBBP::std::ELF::SHT_STRTAB\fP = 3, \fBBBP::std::ELF::SHT_RELA\fP = 4, \fBBBP::std::ELF::SHT_HASH\fP = 5, \fBBBP::std::ELF::SHT_DYNAMIC\fP = 6, \fBBBP::std::ELF::SHT_NOTE\fP = 7, \fBBBP::std::ELF::SHT_NOBITS\fP = 8, \fBBBP::std::ELF::SHT_REL\fP = 9, \fBBBP::std::ELF::SHT_SHLIB\fP = 10, \fBBBP::std::ELF::SHT_DYNSYM\fP = 11 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ELF_HEADER_EHSIZEOFFSET   52"

.PP
Definition at line 22 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_EHSIZESIZE   2"

.PP
Definition at line 23 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_ENTRYOFFSET   24"

.PP
Definition at line 14 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_ENTRYSIZE   8"

.PP
Definition at line 15 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_FLAGSOFFSET   48"

.PP
Definition at line 20 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_FLAGSSIZE   4"

.PP
Definition at line 21 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_IDENTOFFSET   0"

.PP
Definition at line 6 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_IDENTSIZE   16"

.PP
Definition at line 7 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_MACHINEOFFSET   18"

.PP
Definition at line 10 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_MACHINESIZE   2"

.PP
Definition at line 11 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_PHENTSIZEOFFSET   54"

.PP
Definition at line 24 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_PHENTSIZESIZE   2"

.PP
Definition at line 25 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_PHNUMOFFSET   56"

.PP
Definition at line 26 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_PHNUMSIZE   2"

.PP
Definition at line 27 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_PHOFFOFFSET   32"

.PP
Definition at line 16 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_PHOFFSIZE   8"

.PP
Definition at line 17 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHENTSIZEOFFSET   58"

.PP
Definition at line 28 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHENTSIZESIZE   2"

.PP
Definition at line 29 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHNUMOFFSET   60"

.PP
Definition at line 30 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHNUMSIZE   2"

.PP
Definition at line 31 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHOFFOFFSET   40"

.PP
Definition at line 18 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHOFFSIZE   8"

.PP
Definition at line 19 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHSTRNDXOFFSET   62"

.PP
Definition at line 32 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_SHSTRNDXSIZE   2"

.PP
Definition at line 33 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_TYPEOFFSET   16"

.PP
Definition at line 8 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_TYPESIZE   2"

.PP
Definition at line 9 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_VERSIONOFFSET   20"

.PP
Definition at line 12 of file ELF64\&.h\&.
.SS "#define ELF_HEADER_VERSIONSIZE   4"

.PP
Definition at line 13 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_ADDRALIGNOFFSET   48"

.PP
Definition at line 70 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_ADDRALIGNSIZE   8"

.PP
Definition at line 71 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_ADDROFFSET   16"

.PP
Definition at line 60 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_ADDRSIZE   8"

.PP
Definition at line 61 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_ENTSIZEOFFSET   56"

.PP
Definition at line 72 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_ENTSIZESIZE   8"

.PP
Definition at line 73 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_FLAGSOFFSET   8"

.PP
Definition at line 58 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_FLAGSSIZE   8"

.PP
Definition at line 59 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_HEADERSIZE   64"

.PP
Definition at line 53 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_INFOOFFSET   44"

.PP
Definition at line 68 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_INFOSIZE   4"

.PP
Definition at line 69 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_LINKOFFSET   40"

.PP
Definition at line 66 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_LINKSIZE   4"

.PP
Definition at line 67 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_NAMEOFFSET   0"

.PP
Definition at line 54 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_NAMESIZE   4"

.PP
Definition at line 55 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_OFFSETOFFSET   24"

.PP
Definition at line 62 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_OFFSETSIZE   8"

.PP
Definition at line 63 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_SIZEOFFSET   32"

.PP
Definition at line 64 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_SIZESIZE   8"

.PP
Definition at line 65 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_TYPEOFFSET   4"

.PP
Definition at line 56 of file ELF64\&.h\&.
.SS "#define ELF_SECTION_TYPESIZE   4"

.PP
Definition at line 57 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_ALIGNOFFSET   28"

.PP
Definition at line 50 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_ALIGNSIZE   4"

.PP
Definition at line 51 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_FILESZOFFSET   20"

.PP
Definition at line 46 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_FILESZSIZE   4"

.PP
Definition at line 47 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_FLAGSIZE   4"

.PP
Definition at line 39 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_FLAGSOFFSET   4"

.PP
Definition at line 38 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_HEADERSIZE   32"

.PP
Definition at line 35 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_MEMSZOFFSET   24"

.PP
Definition at line 48 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_MEMSZSIZE   4"

.PP
Definition at line 49 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_OFFSETOFFSET   8"

.PP
Definition at line 40 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_OFFSETSIZE   4"

.PP
Definition at line 41 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_PADDROFFSET   16"

.PP
Definition at line 44 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_PADDRSIZE   4"

.PP
Definition at line 45 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_TYPEOFFSET   0"

.PP
Definition at line 36 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_TYPESIZE   4"

.PP
Definition at line 37 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_VADDROFFSET   12"

.PP
Definition at line 42 of file ELF64\&.h\&.
.SS "#define ELF_SEGMENT_VADDRSIZE   4"

.PP
Definition at line 43 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_ENTRYSIZE   20"

.PP
Definition at line 75 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_INFOOFFSET   16"

.PP
Definition at line 82 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_INFOSIZE   1"

.PP
Definition at line 83 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_NAMEOFFSET   0"

.PP
Definition at line 76 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_NAMESIZE   4"

.PP
Definition at line 77 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_OTHEROFFSET   17"

.PP
Definition at line 84 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_OTHERSIZE   1"

.PP
Definition at line 85 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_SHNDXOFFSET   18"

.PP
Definition at line 86 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_SHNDXSIZE   2"

.PP
Definition at line 87 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_SIZEOFFSET   8"

.PP
Definition at line 80 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_SIZESIZE   8"

.PP
Definition at line 81 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_VALUEOFFSET   4"

.PP
Definition at line 78 of file ELF64\&.h\&.
.SS "#define ELF_SYMBOL_VALUESIZE   4"

.PP
Definition at line 79 of file ELF64\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
