ELFHeaderGettersSetters.cpp
NAME
ELFHeaderGettersSetters.cpp
SYNOPSIS
#include '../include/ELF.h'
Functions
BBP::std::byte readByte (BBP::std::ELF::ELFBuilder *elf, BBP::std::offset_t offset)
void writeByte (BBP::std::ELF::ELFBuilder *elf, BBP::std::byte byte, BBP::std::offset_t offset)
BBP::std::halfword readHalfWord (BBP::std::ELF::ELFBuilder *elf, BBP::std::offset_t offset)
void writeHalfWord (BBP::std::ELF::ELFBuilder *elf, BBP::std::halfword halfword, BBP::std::offset_t offset)
BBP::std::word readWord (BBP::std::ELF::ELFBuilder *elf, BBP::std::offset_t offset)
void writeWord (BBP::std::ELF::ELFBuilder *elf, BBP::std::word word, BBP::std::offset_t offset)
Function Documentation
BBP::std::byte readByte (BBP::std::ELF::ELFBuilder * elf, BBP::std::offset_t offset)
Definition at line 3 of file ELFHeaderGettersSetters.cpp.
{
    return elf->file.data[offset];
}
References BBP::std::PAGE< T >::data, and BBP::std::ELF::ELFBuilder::file.
Referenced by BBP::std::ELF::ELFBuilder::ident().
BBP::std::halfword readHalfWord (BBP::std::ELF::ELFBuilder * elf, BBP::std::offset_t offset)
Definition at line 11 of file ELFHeaderGettersSetters.cpp.
{
    BBP::std::byte a = elf->file.data[offset];
    BBP::std::byte b = elf->file.data[offset + 1];
    if (!elf->Endian)
        return a | (b << 8);
    return b | (a << 8);
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::ELFBuilder::file.
Referenced by BBP::std::ELF::ELFBuilder::ehsize(), BBP::std::ELF::ELFBuilder::machine(), BBP::std::ELF::ELFBuilder::phentsize(), BBP::std::ELF::ELFBuilder::phnum(), BBP::std::ELF::ELFBuilder::shentsize(), BBP::std::ELF::ELFBuilder::shnum(), BBP::std::ELF::ELFBuilder::shstrndx(), and BBP::std::ELF::ELFBuilder::type().
BBP::std::word readWord (BBP::std::ELF::ELFBuilder * elf, BBP::std::offset_t offset)
Definition at line 36 of file ELFHeaderGettersSetters.cpp.
{
    BBP::std::byte a = elf->file.data[offset];
    BBP::std::byte b = elf->file.data[offset + 1];
    BBP::std::byte c = elf->file.data[offset + 2];
    BBP::std::byte d = elf->file.data[offset + 3];
    if (!elf->Endian)
        return a | (b << 8) | (c << 16) | (d << 24);
    return d | (c << 8) | (b << 16) | (a << 24);
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::ELFBuilder::file.
Referenced by BBP::std::ELF::ELFBuilder::entry(), BBP::std::ELF::ELFBuilder::flags(), BBP::std::ELF::ELFBuilder::phoff(), BBP::std::ELF::ELFBuilder::shoff(), and BBP::std::ELF::ELFBuilder::version().
void writeByte (BBP::std::ELF::ELFBuilder * elf, BBP::std::byte byte, BBP::std::offset_t offset)
Definition at line 7 of file ELFHeaderGettersSetters.cpp.
{
    elf->file.data[offset] = byte;
}
References BBP::std::PAGE< T >::data, and BBP::std::ELF::ELFBuilder::file.
Referenced by BBP::std::ELF::ELFBuilder::ident().
void writeHalfWord (BBP::std::ELF::ELFBuilder * elf, BBP::std::halfword halfword, BBP::std::offset_t offset)
Definition at line 20 of file ELFHeaderGettersSetters.cpp.
{
    BBP::std::byte a = (halfword >> 0) & 0xFF;
    BBP::std::byte b = (halfword >> 8) & 0xFF;
    if (!elf->Endian)
    {
        elf->file.data[offset] = a;
        elf->file.data[offset + 1] = b;
    }
    else
    {
        elf->file.data[offset] = b;
        elf->file.data[offset + 1] = a;
    }
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::ELFBuilder::file.
Referenced by BBP::std::ELF::ELFBuilder::ehsize(), BBP::std::ELF::ELFBuilder::machine(), BBP::std::ELF::ELFBuilder::phentsize(), BBP::std::ELF::ELFBuilder::phnum(), BBP::std::ELF::ELFBuilder::shentsize(), BBP::std::ELF::ELFBuilder::shnum(), BBP::std::ELF::ELFBuilder::shstrndx(), and BBP::std::ELF::ELFBuilder::type().
void writeWord (BBP::std::ELF::ELFBuilder * elf, BBP::std::word word, BBP::std::offset_t offset)
Definition at line 47 of file ELFHeaderGettersSetters.cpp.
{
    BBP::std::byte a = (word >> 0) & 0xFF;
    BBP::std::byte b = (word >> 8) & 0xFF;
    BBP::std::byte c = (word >> 16) & 0xFF;
    BBP::std::byte d = (word >> 24) & 0xFF;
    if (!elf->Endian)
    {
        elf->file.data[offset] = a;
        elf->file.data[offset + 1] = b;
        elf->file.data[offset + 2] = c;
        elf->file.data[offset + 3] = d;
    }
    else
    {
        elf->file.data[offset] = d;
        elf->file.data[offset + 1] = c;
        elf->file.data[offset + 2] = b;
        elf->file.data[offset + 3] = a;
    }
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::ELFBuilder::file.
Referenced by BBP::std::ELF::ELFBuilder::entry(), BBP::std::ELF::ELFBuilder::flags(), BBP::std::ELF::ELFBuilder::phoff(), BBP::std::ELF::ELFBuilder::shoff(), and BBP::std::ELF::ELFBuilder::version().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.