.TH "ELSABackend.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELSABackend.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ELF\&.h'\fP
.br
\fC#include 'FileSys\&.h'\fP
.br
\fC#include 'Lex\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBBP::esa::dataEntry\fP"
.br
.ti -1c
.RI "class \fBBBP::esa::BinaryApplication\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::esa\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
