.TH "errno.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errno.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stddef\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENONE\fP   0"
.br
.ti -1c
.RI "#define \fBEPERM\fP   1"
.br
.ti -1c
.RI "#define \fBENOENT\fP   2"
.br
.ti -1c
.RI "#define \fBESRCH\fP   3"
.br
.ti -1c
.RI "#define \fBEINTR\fP   4"
.br
.ti -1c
.RI "#define \fBEIO\fP   5"
.br
.ti -1c
.RI "#define \fBENXIO\fP   6"
.br
.ti -1c
.RI "#define \fBE2BIG\fP   7"
.br
.ti -1c
.RI "#define \fBENOEXEC\fP   8"
.br
.ti -1c
.RI "#define \fBEBADF\fP   9"
.br
.ti -1c
.RI "#define \fBECHILD\fP   10"
.br
.ti -1c
.RI "#define \fBEAGAIN\fP   11"
.br
.ti -1c
.RI "#define \fBENOMEM\fP   12"
.br
.ti -1c
.RI "#define \fBEACCES\fP   13"
.br
.ti -1c
.RI "#define \fBEFAULT\fP   14"
.br
.ti -1c
.RI "#define \fBENOTBLK\fP   15"
.br
.ti -1c
.RI "#define \fBEBUSY\fP   16"
.br
.ti -1c
.RI "#define \fBEEXIST\fP   17"
.br
.ti -1c
.RI "#define \fBEXDEV\fP   18"
.br
.ti -1c
.RI "#define \fBENODEV\fP   19"
.br
.ti -1c
.RI "#define \fBENOTDIR\fP   20"
.br
.ti -1c
.RI "#define \fBEISDIR\fP   21"
.br
.ti -1c
.RI "#define \fBEINVAL\fP   22"
.br
.ti -1c
.RI "#define \fBENFILE\fP   23"
.br
.ti -1c
.RI "#define \fBEMFILE\fP   24"
.br
.ti -1c
.RI "#define \fBENOTTY\fP   25"
.br
.ti -1c
.RI "#define \fBETXTBSY\fP   26"
.br
.ti -1c
.RI "#define \fBEFBIG\fP   27"
.br
.ti -1c
.RI "#define \fBENOSPC\fP   28"
.br
.ti -1c
.RI "#define \fBESPIPE\fP   29"
.br
.ti -1c
.RI "#define \fBEROFS\fP   30"
.br
.ti -1c
.RI "#define \fBEMLINK\fP   31"
.br
.ti -1c
.RI "#define \fBEPIPE\fP   32"
.br
.ti -1c
.RI "#define \fBEDOM\fP   33"
.br
.ti -1c
.RI "#define \fBERANGE\fP   34"
.br
.ti -1c
.RI "#define \fBEDEADLK\fP   35"
.br
.ti -1c
.RI "#define \fBENAMETOOLONG\fP   36"
.br
.ti -1c
.RI "#define \fBENOLCK\fP   37"
.br
.ti -1c
.RI "#define \fBENOSYS\fP   38"
.br
.ti -1c
.RI "#define \fBENOTEMPTY\fP   39"
.br
.ti -1c
.RI "#define \fBELOOP\fP   40"
.br
.ti -1c
.RI "#define \fBENOMSG\fP   42"
.br
.ti -1c
.RI "#define \fBEIDRM\fP   43"
.br
.ti -1c
.RI "#define \fBECHRNG\fP   44"
.br
.ti -1c
.RI "#define \fBEL2NSYNC\fP   45"
.br
.ti -1c
.RI "#define \fBEL3HLT\fP   46"
.br
.ti -1c
.RI "#define \fBEL3RST\fP   47"
.br
.ti -1c
.RI "#define \fBELNRNG\fP   48"
.br
.ti -1c
.RI "#define \fBEUNATCH\fP   49"
.br
.ti -1c
.RI "#define \fBENOCSI\fP   50"
.br
.ti -1c
.RI "#define \fBEL2HLT\fP   51"
.br
.ti -1c
.RI "#define \fBEBADE\fP   52"
.br
.ti -1c
.RI "#define \fBEBADR\fP   53"
.br
.ti -1c
.RI "#define \fBEXFULL\fP   54"
.br
.ti -1c
.RI "#define \fBENOANO\fP   55"
.br
.ti -1c
.RI "#define \fBEBADRQC\fP   56"
.br
.ti -1c
.RI "#define \fBBADSLT\fP   57"
.br
.ti -1c
.RI "#define \fBEBFONT\fP   59"
.br
.ti -1c
.RI "#define \fBENOSTR\fP   60"
.br
.ti -1c
.RI "#define \fBENODATA\fP   61"
.br
.ti -1c
.RI "#define \fBETIME\fP   62"
.br
.ti -1c
.RI "#define \fBENOSR\fP   63"
.br
.ti -1c
.RI "#define \fBENONET\fP   64"
.br
.ti -1c
.RI "#define \fBENOPKG\fP   65"
.br
.ti -1c
.RI "#define \fBEREMOTE\fP   66"
.br
.ti -1c
.RI "#define \fBENOLINK\fP   67"
.br
.ti -1c
.RI "#define \fBEADV\fP   68"
.br
.ti -1c
.RI "#define \fBESRMNT\fP   69"
.br
.ti -1c
.RI "#define \fBECOMM\fP   70"
.br
.ti -1c
.RI "#define \fBEPROTO\fP   71"
.br
.ti -1c
.RI "#define \fBEMULTIHOP\fP   72"
.br
.ti -1c
.RI "#define \fBEDOTDOT\fP   73"
.br
.ti -1c
.RI "#define \fBBADMSG\fP   74"
.br
.ti -1c
.RI "#define \fBEOVERFLOW\fP   75"
.br
.ti -1c
.RI "#define \fBENOTUNIQ\fP   76"
.br
.ti -1c
.RI "#define \fBEBADFD\fP   77"
.br
.ti -1c
.RI "#define \fBEREMCHG\fP   78"
.br
.ti -1c
.RI "#define \fBELIBACC\fP   79"
.br
.ti -1c
.RI "#define \fBELIBBAD\fP   80"
.br
.ti -1c
.RI "#define \fBELIBSCN\fP   81"
.br
.ti -1c
.RI "#define \fBELIBMAX\fP   82"
.br
.ti -1c
.RI "#define \fBELIBEXEC\fP   83"
.br
.ti -1c
.RI "#define \fBEILSEQ\fP   84"
.br
.ti -1c
.RI "#define \fBERESTART\fP   85"
.br
.ti -1c
.RI "#define \fBESTRPIPE\fP   86"
.br
.ti -1c
.RI "#define \fBEUSERS\fP   87"
.br
.ti -1c
.RI "#define \fBENOTSOCK\fP   88"
.br
.ti -1c
.RI "#define \fBEDESTADDREQ\fP   89"
.br
.ti -1c
.RI "#define \fBEMSGSIZE\fP   90"
.br
.ti -1c
.RI "#define \fBEPROTOTYPE\fP   91"
.br
.ti -1c
.RI "#define \fBENOPROTOOPT\fP   92"
.br
.ti -1c
.RI "#define \fBEPROTONOSUPPORT\fP   93"
.br
.ti -1c
.RI "#define \fBESOCKTNOSUPPORT\fP   94"
.br
.ti -1c
.RI "#define \fBEOPNOTSUPP\fP   95"
.br
.ti -1c
.RI "#define \fBEPFNOSUPPORT\fP   96"
.br
.ti -1c
.RI "#define \fBEAFNOSUPPORT\fP   97"
.br
.ti -1c
.RI "#define \fBEADDRINUSE\fP   98"
.br
.ti -1c
.RI "#define \fBEADDRNOTAVAIL\fP   99"
.br
.ti -1c
.RI "#define \fBENETDOWN\fP   100"
.br
.ti -1c
.RI "#define \fBENETUNREACH\fP   101"
.br
.ti -1c
.RI "#define \fBENETRESET\fP   102"
.br
.ti -1c
.RI "#define \fBECONNABORTED\fP   103"
.br
.ti -1c
.RI "#define \fBECONNRESET\fP   104"
.br
.ti -1c
.RI "#define \fBENOBUFS\fP   105"
.br
.ti -1c
.RI "#define \fBEISCONN\fP   106"
.br
.ti -1c
.RI "#define \fBENOTCONN\fP   107"
.br
.ti -1c
.RI "#define \fBESHUTDOWN\fP   108"
.br
.ti -1c
.RI "#define \fBETOOMANYREFS\fP   109"
.br
.ti -1c
.RI "#define \fBETIMEDOUT\fP   110"
.br
.ti -1c
.RI "#define \fBECONNREFUSED\fP   111"
.br
.ti -1c
.RI "#define \fBEHOSTDOWN\fP   112"
.br
.ti -1c
.RI "#define \fBEHOSTUNREACH\fP   113"
.br
.ti -1c
.RI "#define \fBEALREADY\fP   114"
.br
.ti -1c
.RI "#define \fBEINPROGRESS\fP   115"
.br
.ti -1c
.RI "#define \fBESTALE\fP   116"
.br
.ti -1c
.RI "#define \fBEUCLEAN\fP   117"
.br
.ti -1c
.RI "#define \fBENOTNAM\fP   118"
.br
.ti -1c
.RI "#define \fBENAVAIL\fP   119"
.br
.ti -1c
.RI "#define \fBEISNAM\fP   120"
.br
.ti -1c
.RI "#define \fBEREMOTEIO\fP   121"
.br
.ti -1c
.RI "#define \fBEDQUOT\fP   122"
.br
.ti -1c
.RI "#define \fBENOMEDIUM\fP   123"
.br
.ti -1c
.RI "#define \fBEMEDIUMTYPE\fP   124"
.br
.ti -1c
.RI "#define \fBECANCELED\fP   125"
.br
.ti -1c
.RI "#define \fBENOKEY\fP   126"
.br
.ti -1c
.RI "#define \fBEKEYEXPIRED\fP   127"
.br
.ti -1c
.RI "#define \fBEKEYREVOKED\fP   128"
.br
.ti -1c
.RI "#define \fBEKEYREJECTED\fP   129"
.br
.ti -1c
.RI "#define \fBEOWNERDEAD\fP   130"
.br
.ti -1c
.RI "#define \fBENOTRECOVERABLE\fP   131"
.br
.ti -1c
.RI "#define \fBERFKILL\fP   132"
.br
.ti -1c
.RI "#define \fBEHWPOISON\fP   133"
.br
.ti -1c
.RI "#define \fBEEOF\fP   134"
.br
.ti -1c
.RI "#define \fBEUNFSEQ\fP   135"
.br
.ti -1c
.RI "#define \fBELINEEND\fP   136"
.br
.ti -1c
.RI "#define \fBEUNFOCS\fP   137"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBBBP::std::errno_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BADMSG   74"

.PP
Definition at line 84 of file errno\&.h\&.
.SS "#define BADSLT   57"

.PP
Definition at line 68 of file errno\&.h\&.
.SS "#define E2BIG   7"

.PP
Definition at line 19 of file errno\&.h\&.
.SS "#define EACCES   13"

.PP
Definition at line 25 of file errno\&.h\&.
.SS "#define EADDRINUSE   98"

.PP
Definition at line 108 of file errno\&.h\&.
.SS "#define EADDRNOTAVAIL   99"

.PP
Definition at line 109 of file errno\&.h\&.
.SS "#define EADV   68"

.PP
Definition at line 78 of file errno\&.h\&.
.SS "#define EAFNOSUPPORT   97"

.PP
Definition at line 107 of file errno\&.h\&.
.SS "#define EAGAIN   11"

.PP
Definition at line 23 of file errno\&.h\&.
.SS "#define EALREADY   114"

.PP
Definition at line 124 of file errno\&.h\&.
.SS "#define EBADE   52"

.PP
Definition at line 63 of file errno\&.h\&.
.SS "#define EBADF   9"

.PP
Definition at line 21 of file errno\&.h\&.
.SS "#define EBADFD   77"

.PP
Definition at line 87 of file errno\&.h\&.
.SS "#define EBADR   53"

.PP
Definition at line 64 of file errno\&.h\&.
.SS "#define EBADRQC   56"

.PP
Definition at line 67 of file errno\&.h\&.
.SS "#define EBFONT   59"

.PP
Definition at line 69 of file errno\&.h\&.
.SS "#define EBUSY   16"

.PP
Definition at line 28 of file errno\&.h\&.
.SS "#define ECANCELED   125"

.PP
Definition at line 135 of file errno\&.h\&.
.SS "#define ECHILD   10"

.PP
Definition at line 22 of file errno\&.h\&.
.SS "#define ECHRNG   44"

.PP
Definition at line 55 of file errno\&.h\&.
.SS "#define ECOMM   70"

.PP
Definition at line 80 of file errno\&.h\&.
.SS "#define ECONNABORTED   103"

.PP
Definition at line 113 of file errno\&.h\&.
.SS "#define ECONNREFUSED   111"

.PP
Definition at line 121 of file errno\&.h\&.
.SS "#define ECONNRESET   104"

.PP
Definition at line 114 of file errno\&.h\&.
.SS "#define EDEADLK   35"

.PP
Definition at line 47 of file errno\&.h\&.
.SS "#define EDESTADDREQ   89"

.PP
Definition at line 99 of file errno\&.h\&.
.SS "#define EDOM   33"

.PP
Definition at line 45 of file errno\&.h\&.
.SS "#define EDOTDOT   73"

.PP
Definition at line 83 of file errno\&.h\&.
.SS "#define EDQUOT   122"

.PP
Definition at line 132 of file errno\&.h\&.
.SS "#define EEOF   134"

.PP
Definition at line 144 of file errno\&.h\&.
.SS "#define EEXIST   17"

.PP
Definition at line 29 of file errno\&.h\&.
.SS "#define EFAULT   14"

.PP
Definition at line 26 of file errno\&.h\&.
.SS "#define EFBIG   27"

.PP
Definition at line 39 of file errno\&.h\&.
.SS "#define EHOSTDOWN   112"

.PP
Definition at line 122 of file errno\&.h\&.
.SS "#define EHOSTUNREACH   113"

.PP
Definition at line 123 of file errno\&.h\&.
.SS "#define EHWPOISON   133"

.PP
Definition at line 143 of file errno\&.h\&.
.SS "#define EIDRM   43"

.PP
Definition at line 54 of file errno\&.h\&.
.SS "#define EILSEQ   84"

.PP
Definition at line 94 of file errno\&.h\&.
.SS "#define EINPROGRESS   115"

.PP
Definition at line 125 of file errno\&.h\&.
.SS "#define EINTR   4"

.PP
Definition at line 16 of file errno\&.h\&.
.SS "#define EINVAL   22"

.PP
Definition at line 34 of file errno\&.h\&.
.SS "#define EIO   5"

.PP
Definition at line 17 of file errno\&.h\&.
.SS "#define EISCONN   106"

.PP
Definition at line 116 of file errno\&.h\&.
.SS "#define EISDIR   21"

.PP
Definition at line 33 of file errno\&.h\&.
.SS "#define EISNAM   120"

.PP
Definition at line 130 of file errno\&.h\&.
.SS "#define EKEYEXPIRED   127"

.PP
Definition at line 137 of file errno\&.h\&.
.SS "#define EKEYREJECTED   129"

.PP
Definition at line 139 of file errno\&.h\&.
.SS "#define EKEYREVOKED   128"

.PP
Definition at line 138 of file errno\&.h\&.
.SS "#define EL2HLT   51"

.PP
Definition at line 62 of file errno\&.h\&.
.SS "#define EL2NSYNC   45"

.PP
Definition at line 56 of file errno\&.h\&.
.SS "#define EL3HLT   46"

.PP
Definition at line 57 of file errno\&.h\&.
.SS "#define EL3RST   47"

.PP
Definition at line 58 of file errno\&.h\&.
.SS "#define ELIBACC   79"

.PP
Definition at line 89 of file errno\&.h\&.
.SS "#define ELIBBAD   80"

.PP
Definition at line 90 of file errno\&.h\&.
.SS "#define ELIBEXEC   83"

.PP
Definition at line 93 of file errno\&.h\&.
.SS "#define ELIBMAX   82"

.PP
Definition at line 92 of file errno\&.h\&.
.SS "#define ELIBSCN   81"

.PP
Definition at line 91 of file errno\&.h\&.
.SS "#define ELINEEND   136"

.PP
Definition at line 146 of file errno\&.h\&.
.SS "#define ELNRNG   48"

.PP
Definition at line 59 of file errno\&.h\&.
.SS "#define ELOOP   40"

.PP
Definition at line 52 of file errno\&.h\&.
.SS "#define EMEDIUMTYPE   124"

.PP
Definition at line 134 of file errno\&.h\&.
.SS "#define EMFILE   24"

.PP
Definition at line 36 of file errno\&.h\&.
.SS "#define EMLINK   31"

.PP
Definition at line 43 of file errno\&.h\&.
.SS "#define EMSGSIZE   90"

.PP
Definition at line 100 of file errno\&.h\&.
.SS "#define EMULTIHOP   72"

.PP
Definition at line 82 of file errno\&.h\&.
.SS "#define ENAMETOOLONG   36"

.PP
Definition at line 48 of file errno\&.h\&.
.SS "#define ENAVAIL   119"

.PP
Definition at line 129 of file errno\&.h\&.
.SS "#define ENETDOWN   100"

.PP
Definition at line 110 of file errno\&.h\&.
.SS "#define ENETRESET   102"

.PP
Definition at line 112 of file errno\&.h\&.
.SS "#define ENETUNREACH   101"

.PP
Definition at line 111 of file errno\&.h\&.
.SS "#define ENFILE   23"

.PP
Definition at line 35 of file errno\&.h\&.
.SS "#define ENOANO   55"

.PP
Definition at line 66 of file errno\&.h\&.
.SS "#define ENOBUFS   105"

.PP
Definition at line 115 of file errno\&.h\&.
.SS "#define ENOCSI   50"

.PP
Definition at line 61 of file errno\&.h\&.
.SS "#define ENODATA   61"

.PP
Definition at line 71 of file errno\&.h\&.
.SS "#define ENODEV   19"

.PP
Definition at line 31 of file errno\&.h\&.
.SS "#define ENOENT   2"

.PP
Definition at line 14 of file errno\&.h\&.
.SS "#define ENOEXEC   8"

.PP
Definition at line 20 of file errno\&.h\&.
.SS "#define ENOKEY   126"

.PP
Definition at line 136 of file errno\&.h\&.
.SS "#define ENOLCK   37"

.PP
Definition at line 49 of file errno\&.h\&.
.SS "#define ENOLINK   67"

.PP
Definition at line 77 of file errno\&.h\&.
.SS "#define ENOMEDIUM   123"

.PP
Definition at line 133 of file errno\&.h\&.
.SS "#define ENOMEM   12"

.PP
Definition at line 24 of file errno\&.h\&.
.SS "#define ENOMSG   42"

.PP
Definition at line 53 of file errno\&.h\&.
.SS "#define ENONE   0"

.PP
Definition at line 12 of file errno\&.h\&.
.SS "#define ENONET   64"

.PP
Definition at line 74 of file errno\&.h\&.
.SS "#define ENOPKG   65"

.PP
Definition at line 75 of file errno\&.h\&.
.SS "#define ENOPROTOOPT   92"

.PP
Definition at line 102 of file errno\&.h\&.
.SS "#define ENOSPC   28"

.PP
Definition at line 40 of file errno\&.h\&.
.SS "#define ENOSR   63"

.PP
Definition at line 73 of file errno\&.h\&.
.SS "#define ENOSTR   60"

.PP
Definition at line 70 of file errno\&.h\&.
.SS "#define ENOSYS   38"

.PP
Definition at line 50 of file errno\&.h\&.
.SS "#define ENOTBLK   15"

.PP
Definition at line 27 of file errno\&.h\&.
.SS "#define ENOTCONN   107"

.PP
Definition at line 117 of file errno\&.h\&.
.SS "#define ENOTDIR   20"

.PP
Definition at line 32 of file errno\&.h\&.
.SS "#define ENOTEMPTY   39"

.PP
Definition at line 51 of file errno\&.h\&.
.SS "#define ENOTNAM   118"

.PP
Definition at line 128 of file errno\&.h\&.
.SS "#define ENOTRECOVERABLE   131"

.PP
Definition at line 141 of file errno\&.h\&.
.SS "#define ENOTSOCK   88"

.PP
Definition at line 98 of file errno\&.h\&.
.SS "#define ENOTTY   25"

.PP
Definition at line 37 of file errno\&.h\&.
.SS "#define ENOTUNIQ   76"

.PP
Definition at line 86 of file errno\&.h\&.
.SS "#define ENXIO   6"

.PP
Definition at line 18 of file errno\&.h\&.
.SS "#define EOPNOTSUPP   95"

.PP
Definition at line 105 of file errno\&.h\&.
.SS "#define EOVERFLOW   75"

.PP
Definition at line 85 of file errno\&.h\&.
.SS "#define EOWNERDEAD   130"

.PP
Definition at line 140 of file errno\&.h\&.
.SS "#define EPERM   1"

.PP
Definition at line 13 of file errno\&.h\&.
.SS "#define EPFNOSUPPORT   96"

.PP
Definition at line 106 of file errno\&.h\&.
.SS "#define EPIPE   32"

.PP
Definition at line 44 of file errno\&.h\&.
.SS "#define EPROTO   71"

.PP
Definition at line 81 of file errno\&.h\&.
.SS "#define EPROTONOSUPPORT   93"

.PP
Definition at line 103 of file errno\&.h\&.
.SS "#define EPROTOTYPE   91"

.PP
Definition at line 101 of file errno\&.h\&.
.SS "#define ERANGE   34"

.PP
Definition at line 46 of file errno\&.h\&.
.SS "#define EREMCHG   78"

.PP
Definition at line 88 of file errno\&.h\&.
.SS "#define EREMOTE   66"

.PP
Definition at line 76 of file errno\&.h\&.
.SS "#define EREMOTEIO   121"

.PP
Definition at line 131 of file errno\&.h\&.
.SS "#define ERESTART   85"

.PP
Definition at line 95 of file errno\&.h\&.
.SS "#define ERFKILL   132"

.PP
Definition at line 142 of file errno\&.h\&.
.SS "#define EROFS   30"

.PP
Definition at line 42 of file errno\&.h\&.
.SS "#define ESHUTDOWN   108"

.PP
Definition at line 118 of file errno\&.h\&.
.SS "#define ESOCKTNOSUPPORT   94"

.PP
Definition at line 104 of file errno\&.h\&.
.SS "#define ESPIPE   29"

.PP
Definition at line 41 of file errno\&.h\&.
.SS "#define ESRCH   3"

.PP
Definition at line 15 of file errno\&.h\&.
.SS "#define ESRMNT   69"

.PP
Definition at line 79 of file errno\&.h\&.
.SS "#define ESTALE   116"

.PP
Definition at line 126 of file errno\&.h\&.
.SS "#define ESTRPIPE   86"

.PP
Definition at line 96 of file errno\&.h\&.
.SS "#define ETIME   62"

.PP
Definition at line 72 of file errno\&.h\&.
.SS "#define ETIMEDOUT   110"

.PP
Definition at line 120 of file errno\&.h\&.
.SS "#define ETOOMANYREFS   109"

.PP
Definition at line 119 of file errno\&.h\&.
.SS "#define ETXTBSY   26"

.PP
Definition at line 38 of file errno\&.h\&.
.SS "#define EUCLEAN   117"

.PP
Definition at line 127 of file errno\&.h\&.
.SS "#define EUNATCH   49"

.PP
Definition at line 60 of file errno\&.h\&.
.SS "#define EUNFOCS   137"

.PP
Definition at line 147 of file errno\&.h\&.
.SS "#define EUNFSEQ   135"

.PP
Definition at line 145 of file errno\&.h\&.
.SS "#define EUSERS   87"

.PP
Definition at line 97 of file errno\&.h\&.
.SS "#define EXDEV   18"

.PP
Definition at line 30 of file errno\&.h\&.
.SS "#define EXFULL   54"

.PP
Definition at line 65 of file errno\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
