.TH "Except.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Except.h
.SH SYNOPSIS
.br
.PP
\fC#include 'errno\&.h'\fP
.br
\fC#include 'Memory\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "except \fBBBP::std::exception\fP (const char *msg, errno_t _errno)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
