.TH "Executable.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Executable.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Executable\&.h'\fP
.br
\fC#include '\&.\&./include/CPPApplications\&.h'\fP
.br
\fC#include '\&.\&./include/stdio\&.h'\fP
.br
\fC#include '\&.\&./include/Graphics\&.h'\fP
.br
\fC#include '\&.\&./include/OS\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBBP::std::Stack\fP< \fBBBP::std::executableFrame\fP > \fBBBP::std::Processes\fP & \fBprocFrames\fP"
.br
.ti -1c
.RI "\fBBBP::std::PID_t\fP \fBpidCounter\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBBBP::std::PID_t\fP pidCounter = 0"

.PP
Definition at line 120 of file Executable\&.cpp\&.
.PP
Referenced by BBP::std::getNextAvailablePID()\&.
.SS "\fBBBP::std::Stack\fP<\fBBBP::std::executableFrame\fP> \fBBBP::std::Processes\fP& procFrames"

.PP
Definition at line 10 of file Executable\&.cpp\&.
.PP
Referenced by BBP::std::execute()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
