.TH "Executable.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Executable.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Strings\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBBP::std::Executable\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::executableFrame\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC0\fP   0xBB"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC1\fP   0x66"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC2\fP   0x00"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC3\fP   0x77"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC0IDX\fP   8"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC1IDX\fP   9"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC2IDX\fP   10"
.br
.ti -1c
.RI "#define \fBBBP_EXEC_MAGIC3IDX\fP   11"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBBBP::std::executable_main\fP) (int argc, char **argv)"
.br
.ti -1c
.RI "typedef uint8_t \fBBBP::std::PID_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "PID_t \fBBBP::std::getNextAvailablePID\fP ()"
.br
.ti -1c
.RI "PID_t \fBBBP::std::spawnExecutable\fP (executable_main, std::string &)"
.br
.ti -1c
.RI "void \fBBBP::std::execute\fP (executable_main, int argc, char **argv)"
.br
.ti -1c
.RI "void \fBBBP::std::exit\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "STATIC_PAGE< executableFrame, 12 > \fBBBP::std::procFrames\fP"
.br
.ti -1c
.RI "Stack< executableFrame > \fBBBP::std::Processes\fP"
.br
.ti -1c
.RI "PID_t \fBBBP::std::activeExecutable\fP = 0"
.br
.ti -1c
.RI "const Executable \fBBBP::std::executables\fP [] = {{shell_main, '/proc/shell'}}"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BBP_EXEC_MAGIC0   0xBB"

.PP
Definition at line 6 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC0IDX   8"

.PP
Definition at line 11 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC1   0x66"

.PP
Definition at line 7 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC1IDX   9"

.PP
Definition at line 12 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC2   0x00"

.PP
Definition at line 8 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC2IDX   10"

.PP
Definition at line 13 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC3   0x77"

.PP
Definition at line 9 of file Executable\&.h\&.
.SS "#define BBP_EXEC_MAGIC3IDX   11"

.PP
Definition at line 14 of file Executable\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
