.TH "FileSys.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileSys.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Strings\&.h'\fP
.br
\fC#include 'Resources\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBBP::std::PATH\fP"
.br
.ti -1c
.RI "class \fBBBP::std::VOLUME\fP"
.br
.ti -1c
.RI "class \fBBBP::std::FILE\fP"
.br
.ti -1c
.RI "class \fBBBP::std::DIRECTORY\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::FileNode\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::DirectoryNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBBP_STDLIB_FILESYS_OVERWRITEEXISTINGFILES\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::index_t \fBBBP::std::noderef_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBBBP::std::fprintf\fP (\fBBBP::std::FILE\fP &file, std::conststring format, Args\&.\&.\&. args)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static constexpr std::size_t \fBBBP::std::max_open_files\fP = 32"
.br
.ti -1c
.RI "static constexpr std::size_t \fBBBP::std::max_path_length\fP = 128"
.br
.ti -1c
.RI "std::STATIC_PAGE< FileNode, max_open_files > \fBBBP::std::fileTable\fP"
.br
.ti -1c
.RI "PATH * \fBBBP::std::workingDirectory\fP"
.br
.ti -1c
.RI "VOLUME * \fBBBP::std::primaryVolume\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BBP_STDLIB_FILESYS_OVERWRITEEXISTINGFILES"

.PP
Definition at line 9 of file FileSys\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
