.TH "Goto" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Goto
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StressRelief\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBHell\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file StressRelief\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Goto::Hell ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 21 of file StressRelief\&.h\&.
.PP
.nf
22     {}
.fi
.PP
Referenced by BBP::esa::BinaryApplication::addDataToSection()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
