.TH "IHate" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IHate
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StressRelief\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAllOfYou\fP ()"
.br
.ti -1c
.RI "static void \fBEverything\fP ()"
.br
.ti -1c
.RI "static void \fBMyself\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file StressRelief\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void IHate::AllOfYou ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 28 of file StressRelief\&.h\&.
.PP
.nf
29     {}
.fi
.SS "static void IHate::Everything ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 30 of file StressRelief\&.h\&.
.PP
.nf
31     {}
.fi
.SS "static void IHate::Myself ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 32 of file StressRelief\&.h\&.
.PP
.nf
33     {}
.fi
.PP
Referenced by BBP::std::ELF::ELFBuilder::formStandard()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
