.TH "Lex.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lex.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Strings\&.h'\fP
.br
\fC#include 'FileSys\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBBBP::std::Lexer::numerical_t\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::Lexer::lex_keyword\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::Lexer::lex_thing\fP"
.br
.ti -1c
.RI "struct \fBBBP::std::Lexer::lex_debugInfo\fP"
.br
.ti -1c
.RI "class \fBBBP::std::Lexer::lex_context\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.ti -1c
.RI " \fBBBP::std::Lexer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBBBP::std::Lexer::lex_type\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBBBP::std::Lexer::lex_specialty\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBBBP::std::Lexer::lex_keywordhandle\fP"
.br
.ti -1c
.RI "typedef std::conststring(* \fBBBP::std::Lexer::lex_action\fP) (lex_context *, std::index_t, lex_keywordhandle)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
