.TH "neofetch.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
neofetch.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/stdio\&.h'\fP
.br
\fC#include '\&.\&./include/Signal\&.h'\fP
.br
\fC#include '\&.\&./include/Resources\&.h'\fP
.br
\fC#include '\&.\&./include/ELF\&.h'\fP
.br
\fC#include '\&.\&./include/FileSys\&.h'\fP
.br
\fC#include '\&.\&./include/Lex\&.h'\fP
.br
\fC#include '\&.\&./include/CPPApplications\&.h'\fP
.br
\fC#include '\&.\&./include/Executable\&.h'\fP
.br
\fC#include '\&.\&./include/System\&.h'\fP
.br
\fC#include '\&.\&./include/Time\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRED\fP   '\\e[0;31m'"
.br
.ti -1c
.RI "#define \fBNORM\fP   '\\e[0;37m'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NORM   '\\e[0;37m'"

.PP
Definition at line 14 of file neofetch\&.cpp\&.
.SS "#define RED   '\\e[0;31m'"

.PP
Definition at line 13 of file neofetch\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
