Processor.cpp
NAME
Processor.cpp
SYNOPSIS
#include '../include/ELSA.h'
#include '../include/ELSABackend.h'
#include 'Actions.h'
Namespaces
 BBP
 BBP::esa
Functions
BBP::std::conststring _unkown (BBP::std::index_t from, BBP::std::index_t to)
BBP::std::conststring _numerical (BBP::std::Lexer::numerical_t numerical, bool isFloat)
Variables
static const char *const BBP::esa::keywords []
static const char *const BBP::esa::tokens [] = { '\r', '\n', ';', '(', ')', ',', '[', ']', '{', '}', '^', '<', '>', '\'', ''', ':', '\\', 'dn', 'db', 'dh', 'di', 'da', 'dw' }
static const char *const BBP::esa::mnemonics []
static constexpr std::size_t BBP::esa::keywordCount = 18
static constexpr std::size_t BBP::esa::tokenCount = 23
static constexpr std::size_t BBP::esa::mnemonicsCount = 110
static const std::Lexer::lex_action BBP::esa::keywordActions []
static const std::Lexer::lex_action BBP::esa::tokenActions []
static const std::Lexer::lex_action BBP::esa::mnemonicsActions []
static const char BBP::esa::flags [23][8]
esaProcessor BBP::esa::processor
Function Documentation
BBP::std::conststring _numerical (BBP::std::Lexer::numerical_t numerical, bool isFloat)
Definition at line 145 of file Processor.cpp.
{
    if (!BBP::esa::processor.lineIsDefiningInstruction)
        return BBP::esa::processor.numerical(numerical, isFloat);
    return BBP::esa::processor.numericalArgument(numerical, isFloat);
}
References BBP::esa::esaProcessor::numerical(), BBP::esa::esaProcessor::numericalArgument(), and BBP::esa::processor.
Referenced by BBP::esa::esaProcessor::translate().
BBP::std::conststring _unkown (BBP::std::index_t from, BBP::std::index_t to)
Definition at line 137 of file Processor.cpp.
{
    // If not defining an instruction, do this
    if (!BBP::esa::processor.lineIsDefiningInstruction)
        return BBP::esa::processor.unkown(from, to);
    return BBP::esa::processor.resolve(from, to);
}
References BBP::esa::processor, BBP::esa::esaProcessor::resolve(), BBP::Locale::Japanese::to, and BBP::esa::esaProcessor::unkown().
Referenced by BBP::esa::esaProcessor::translate().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.