.TH "R2D.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
R2D.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Graphics\&.h'\fP
.br
\fC#include '\&.\&./include/FileSys\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBBP::std::swap\fP (int *a, int *b)"
.br
.ti -1c
.RI "float \fBBBP::std::absolute\fP (float x)"
.br
.ti -1c
.RI "int \fBBBP::std::iPartOfNumber\fP (float x)"
.br
.ti -1c
.RI "int \fBBBP::std::roundNumber\fP (float x)"
.br
.ti -1c
.RI "float \fBBBP::std::fPartOfNumber\fP (float x)"
.br
.ti -1c
.RI "float \fBBBP::std::rfPartOfNumber\fP (float x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBResourceManager\fP \fBBBP::std::vmem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
