.TH "RAE.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RAE.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Hyperv\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBBP::userspace::RAE\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::userspace\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
