.TH "Resources.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resources.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Resources\&.h'\fP
.br
\fC#include '\&.\&./include/stdio\&.h'\fP
.br
\fC#include '\&.\&./include/Signal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_32_BITS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_32_BITS"

.PP
Definition at line 1 of file Resources\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
