SectionBuilderGettersSetters.cpp
NAME
SectionBuilderGettersSetters.cpp
SYNOPSIS
#include '../include/ELF.h'
Functions
BBP::std::word readWord (BBP::std::ELF::SectionBuilder *sec, BBP::std::offset_t offset)
void writeWord (BBP::std::ELF::SectionBuilder *sec, BBP::std::word word, BBP::std::offset_t offset)
Function Documentation
BBP::std::word readWord (BBP::std::ELF::SectionBuilder * sec, BBP::std::offset_t offset)
Definition at line 3 of file SectionBuilderGettersSetters.cpp.
{
    BBP::std::byte a = sec->header.data[offset];
    BBP::std::byte b = sec->header.data[offset + 1];
    BBP::std::byte c = sec->header.data[offset + 2];
    BBP::std::byte d = sec->header.data[offset + 3];
    if (!sec->elf->Endian)
        return a | (b << 8) | (c << 16) | (d << 24);
    return d | (c << 8) | (b << 16) | (a << 24);
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SectionBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SectionBuilder::header.
Referenced by BBP::std::ELF::SectionBuilder::addr(), BBP::std::ELF::SectionBuilder::addralign(), BBP::std::ELF::SectionBuilder::entsize(), BBP::std::ELF::SectionBuilder::flags(), BBP::std::ELF::SectionBuilder::info(), BBP::std::ELF::SectionBuilder::link(), BBP::std::ELF::SectionBuilder::name(), BBP::std::ELF::SectionBuilder::offset(), BBP::std::ELF::SectionBuilder::size(), and BBP::std::ELF::SectionBuilder::type().
void writeWord (BBP::std::ELF::SectionBuilder * sec, BBP::std::word word, BBP::std::offset_t offset)
Definition at line 14 of file SectionBuilderGettersSetters.cpp.
{
    BBP::std::byte a = (word >> 0) & 0xFF;
    BBP::std::byte b = (word >> 8) & 0xFF;
    BBP::std::byte c = (word >> 16) & 0xFF;
    BBP::std::byte d = (word >> 24) & 0xFF;
    if (!sec->elf->Endian)
    {
        sec->header.data[offset] = a;
        sec->header.data[offset + 1] = b;
        sec->header.data[offset + 2] = c;
        sec->header.data[offset + 3] = d;
    }
    else
    {
        sec->header.data[offset] = d;
        sec->header.data[offset + 1] = c;
        sec->header.data[offset + 2] = b;
        sec->header.data[offset + 3] = a;
    }
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SectionBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SectionBuilder::header.
Referenced by BBP::std::ELF::SectionBuilder::addr(), BBP::std::ELF::SectionBuilder::addralign(), BBP::std::ELF::SectionBuilder::entsize(), BBP::std::ELF::SectionBuilder::flags(), BBP::std::ELF::SectionBuilder::info(), BBP::std::ELF::SectionBuilder::link(), BBP::std::ELF::SectionBuilder::name(), BBP::std::ELF::SectionBuilder::offset(), BBP::std::ELF::SectionBuilder::size(), and BBP::std::ELF::SectionBuilder::type().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.