SegmentBuilderGettersSetters.cpp
NAME
SegmentBuilderGettersSetters.cpp
SYNOPSIS
#include '../include/ELF.h'
Functions
BBP::std::word readWord (BBP::std::ELF::SegmentBuilder *seg, BBP::std::offset_t offset)
void writeWord (BBP::std::ELF::SegmentBuilder *seg, BBP::std::word word, BBP::std::offset_t offset)
Function Documentation
BBP::std::word readWord (BBP::std::ELF::SegmentBuilder * seg, BBP::std::offset_t offset)
Definition at line 3 of file SegmentBuilderGettersSetters.cpp.
{
    BBP::std::byte a = seg->header.data[offset];
    BBP::std::byte b = seg->header.data[offset + 1];
    BBP::std::byte c = seg->header.data[offset + 2];
    BBP::std::byte d = seg->header.data[offset + 3];
    if (!seg->elf->Endian)
        return a | (b << 8) | (c << 16) | (d << 24);
    return d | (c << 8) | (b << 16) | (a << 24);
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SegmentBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SegmentBuilder::header.
Referenced by BBP::std::ELF::SegmentBuilder::align(), BBP::std::ELF::SegmentBuilder::filesz(), BBP::std::ELF::SegmentBuilder::flags(), BBP::std::ELF::SegmentBuilder::memsz(), BBP::std::ELF::SegmentBuilder::offset(), BBP::std::ELF::SegmentBuilder::paddr(), BBP::std::ELF::SegmentBuilder::type(), and BBP::std::ELF::SegmentBuilder::vaddr().
void writeWord (BBP::std::ELF::SegmentBuilder * seg, BBP::std::word word, BBP::std::offset_t offset)
Definition at line 14 of file SegmentBuilderGettersSetters.cpp.
{
    BBP::std::byte a = (word >> 0) & 0xFF;
    BBP::std::byte b = (word >> 8) & 0xFF;
    BBP::std::byte c = (word >> 16) & 0xFF;
    BBP::std::byte d = (word >> 24) & 0xFF;
    if (!seg->elf->Endian)
    {
        seg->header.data[offset] = a;
        seg->header.data[offset + 1] = b;
        seg->header.data[offset + 2] = c;
        seg->header.data[offset + 3] = d;
    }
    else
    {
        seg->header.data[offset] = d;
        seg->header.data[offset + 1] = c;
        seg->header.data[offset + 2] = b;
        seg->header.data[offset + 3] = a;
    }
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SegmentBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SegmentBuilder::header.
Referenced by BBP::std::ELF::SegmentBuilder::align(), BBP::std::ELF::SegmentBuilder::filesz(), BBP::std::ELF::SegmentBuilder::flags(), BBP::std::ELF::SegmentBuilder::memsz(), BBP::std::ELF::SegmentBuilder::offset(), BBP::std::ELF::SegmentBuilder::paddr(), BBP::std::ELF::SegmentBuilder::type(), and BBP::std::ELF::SegmentBuilder::vaddr().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.