.TH "SegmentBuilderGettersSetters.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentBuilderGettersSetters.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/ELF\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBBP::std::word\fP \fBreadWord\fP (\fBBBP::std::ELF::SegmentBuilder\fP *seg, \fBBBP::std::offset_t\fP offset)"
.br
.ti -1c
.RI "void \fBwriteWord\fP (\fBBBP::std::ELF::SegmentBuilder\fP *seg, \fBBBP::std::word\fP word, \fBBBP::std::offset_t\fP offset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBBBP::std::word\fP readWord (\fBBBP::std::ELF::SegmentBuilder\fP * seg, \fBBBP::std::offset_t\fP offset)"

.PP
Definition at line 3 of file SegmentBuilderGettersSetters\&.cpp\&.
.PP
.nf
4 {
5     BBP::std::byte a = seg->header\&.data[offset];
6     BBP::std::byte b = seg->header\&.data[offset + 1];
7     BBP::std::byte c = seg->header\&.data[offset + 2];
8     BBP::std::byte d = seg->header\&.data[offset + 3];
9 
10     if (!seg->elf->Endian)
11         return a | (b << 8) | (c << 16) | (d << 24);
12     return d | (c << 8) | (b << 16) | (a << 24);
13 }
.fi
.PP
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SegmentBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SegmentBuilder::header\&.
.PP
Referenced by BBP::std::ELF::SegmentBuilder::align(), BBP::std::ELF::SegmentBuilder::filesz(), BBP::std::ELF::SegmentBuilder::flags(), BBP::std::ELF::SegmentBuilder::memsz(), BBP::std::ELF::SegmentBuilder::offset(), BBP::std::ELF::SegmentBuilder::paddr(), BBP::std::ELF::SegmentBuilder::type(), and BBP::std::ELF::SegmentBuilder::vaddr()\&.
.SS "void writeWord (\fBBBP::std::ELF::SegmentBuilder\fP * seg, \fBBBP::std::word\fP word, \fBBBP::std::offset_t\fP offset)"

.PP
Definition at line 14 of file SegmentBuilderGettersSetters\&.cpp\&.
.PP
.nf
15 {
16     BBP::std::byte a = (word >> 0) & 0xFF;
17     BBP::std::byte b = (word >> 8) & 0xFF;
18     BBP::std::byte c = (word >> 16) & 0xFF;
19     BBP::std::byte d = (word >> 24) & 0xFF;
20 
21     if (!seg->elf->Endian)
22     {
23         seg->header\&.data[offset] = a;
24         seg->header\&.data[offset + 1] = b;
25         seg->header\&.data[offset + 2] = c;
26         seg->header\&.data[offset + 3] = d;
27     }
28     else
29     {
30         seg->header\&.data[offset] = d;
31         seg->header\&.data[offset + 1] = c;
32         seg->header\&.data[offset + 2] = b;
33         seg->header\&.data[offset + 3] = a;
34     }
35 }
.fi
.PP
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SegmentBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SegmentBuilder::header\&.
.PP
Referenced by BBP::std::ELF::SegmentBuilder::align(), BBP::std::ELF::SegmentBuilder::filesz(), BBP::std::ELF::SegmentBuilder::flags(), BBP::std::ELF::SegmentBuilder::memsz(), BBP::std::ELF::SegmentBuilder::offset(), BBP::std::ELF::SegmentBuilder::paddr(), BBP::std::ELF::SegmentBuilder::type(), and BBP::std::ELF::SegmentBuilder::vaddr()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
