.TH "Shell.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shell.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/stdio\&.h'\fP
.br
\fC#include '\&.\&./include/Signal\&.h'\fP
.br
\fC#include '\&.\&./include/Resources\&.h'\fP
.br
\fC#include '\&.\&./include/ELF\&.h'\fP
.br
\fC#include '\&.\&./include/FileSys\&.h'\fP
.br
\fC#include '\&.\&./include/Lex\&.h'\fP
.br
\fC#include '\&.\&./include/CPPApplications\&.h'\fP
.br
\fC#include '\&.\&./include/Executable\&.h'\fP
.br
\fC#include '\&.\&./include/System\&.h'\fP
.br
\fC#include '\&.\&./include/Graphics\&.h'\fP
.br
\fC#include '\&.\&./include/OS\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBBP::shell\fP (\fBBBP::std::string\fP &str)"
.br
.ti -1c
.RI "int \fBBBP::shell\fP (const char *ss)"
.br
.ti -1c
.RI "int \fBBBP::shell_main\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBBBP::std::static_string\fP< 509 > \fBBBP::linePage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
