.TH "Signal.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Signal.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stddef\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBBP::std::SIGNAL\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__SIGNAL__\fP(sig)   BBP::std::__errno = BBP::std::sig + \fBBBP::std::SIGADJ\fP; throw \fBBBP::std::SIGNAL\fP(BBP::std::sig)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBBBP::std::signal_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGINV\fP = 1"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGTERM\fP = 2"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGSEGV\fP = 3"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGINT\fP = 4"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGILL\fP = 5"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGABRT\fP = 6"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGFPE\fP = 7"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGSHTDN\fP = 8"
.br
.ti -1c
.RI "constexpr signal_t \fBBBP::std::SIGADJ\fP = 150"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __SIGNAL__(sig)   BBP::std::__errno = BBP::std::sig + \fBBBP::std::SIGADJ\fP; throw \fBBBP::std::SIGNAL\fP(BBP::std::sig)"

.PP
Definition at line 9 of file Signal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
