.TH "Smile.cpp" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Smile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/stdio\&.h'\fP
.br
\fC#include '\&.\&./include/Signal\&.h'\fP
.br
\fC#include '\&.\&./include/Resources\&.h'\fP
.br
\fC#include '\&.\&./include/ELF\&.h'\fP
.br
\fC#include '\&.\&./include/FileSys\&.h'\fP
.br
\fC#include '\&.\&./include/Lex\&.h'\fP
.br
\fC#include '\&.\&./include/CPPApplications\&.h'\fP
.br
\fC#include '\&.\&./include/Executable\&.h'\fP
.br
\fC#include '\&.\&./include/System\&.h'\fP
.br
\fC#include '\&.\&./include/Graphics\&.h'\fP
.br
\fC#include '\&.\&./include/OS\&.h'\fP
.br
\fC#include '\&.\&./include/Locale\&.h'\fP
.br
\fC#include '\&.\&./include/ELSA\&.h'\fP
.br
\fC#include '\&.\&./include/Threading\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBBBP::std::size_t\fP \fBpoints\fP = 8"
.br
.ti -1c
.RI "const \fBBBP::std::pos_t\fP \fBxpoints\fP [] = { 700, 750, 800, 850, 850, 800, 750, 700 }"
.br
.ti -1c
.RI "const \fBBBP::std::pos_t\fP \fBypoints\fP [] = { 400, 350, 350, 400, 450, 500, 500, 450 }"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBBBP::std::size_t\fP points = 8"

.PP
Definition at line 17 of file Smile\&.cpp\&.
.SS "const \fBBBP::std::pos_t\fP xpoints[] = { 700, 750, 800, 850, 850, 800, 750, 700 }"

.PP
Definition at line 18 of file Smile\&.cpp\&.
.SS "const \fBBBP::std::pos_t\fP ypoints[] = { 400, 350, 350, 400, 450, 500, 500, 450 }"

.PP
Definition at line 19 of file Smile\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
