.TH "Stack.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stack.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Memory\&.h'\fP
.br
\fC#include 'Stack\&.hxx'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBBP::std::Stack< K >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
