.TH "stddef.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stddef.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdint\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__UNSAFE__\fP(func)   func##_unsafe"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBBBP::std::word\fP"
.br
.ti -1c
.RI "typedef int32_t \fBBBP::std::sword\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBBBP::std::dword\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBBBP::std::halfword\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBBBP::std::byte\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBBBP::std::nibble\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBBBP::std::crumb\fP"
.br
.ti -1c
.RI "typedef word \fBBBP::std::offset_t\fP"
.br
.ti -1c
.RI "typedef sword \fBBBP::std::s_offset_t\fP"
.br
.ti -1c
.RI "typedef word \fBBBP::std::address_t\fP"
.br
.ti -1c
.RI "typedef word \fBBBP::std::index_t\fP"
.br
.ti -1c
.RI "typedef word \fBBBP::std::size_t\fP"
.br
.ti -1c
.RI "typedef byte \fBBBP::std::mem_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __UNSAFE__(func)   func##_unsafe"

.PP
Definition at line 6 of file stddef\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
