.TH "stdio.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdio.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Strings\&.h'\fP
.br
\fC#include 'Resources\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBBP::std::print_to_terminal\fP (std::Stack< std::string_element > *stack)"
.br
.ti -1c
.RI "int \fBBBP::std::sprintf\fP (std::c_string buffer, std::conststring format,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBBBP::std::printf\fP (std::conststring format,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBBBP::std::putf\fP (std::Stack< std::string_element > &stream, std::conststring format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBBBP::std::captureInput\fP ()"
.br
.ti -1c
.RI "void \fBBBP::std::stopCapturingInput\fP ()"
.br
.ti -1c
.RI "char \fBBBP::std::getC\fP ()"
.br
.ti -1c
.RI "void \fBBBP::std::getLine\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static_string< 509 > \fBBBP::std::str_STDOUT\fP"
.br
.ti -1c
.RI "static_string< 509 > \fBBBP::std::str_STDIN\fP"
.br
.ti -1c
.RI "static_string< 509 > \fBBBP::std::str_STDERR\fP"
.br
.ti -1c
.RI "std::Stack< std::string_element > \fBBBP::std::STDOUT\fP"
.br
.ti -1c
.RI "std::Stack< std::string_element > \fBBBP::std::STDIN\fP"
.br
.ti -1c
.RI "std::Stack< std::string_element > \fBBBP::std::STDERR\fP"
.br
.ti -1c
.RI "volatile bool \fBBBP::std::_waitforline\fP"
.br
.ti -1c
.RI "volatile bool \fBBBP::std::_echoStuffToTerminal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
