.TH "stdint.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdint.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBBBP::int8_t\fP"
.br
.ti -1c
.RI "typedef short \fBBBP::int16_t\fP"
.br
.ti -1c
.RI "typedef int \fBBBP::int32_t\fP"
.br
.ti -1c
.RI "typedef long long \fBBBP::int64_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBBBP::uint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBBBP::uint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBBBP::uint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBBBP::uint64_t\fP"
.br
.ti -1c
.RI "typedef signed char \fBBBP::int_least8_t\fP"
.br
.ti -1c
.RI "typedef short \fBBBP::int_least16_t\fP"
.br
.ti -1c
.RI "typedef int \fBBBP::int_least32_t\fP"
.br
.ti -1c
.RI "typedef long long \fBBBP::int_least64_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBBBP::uint_least8_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBBBP::uint_least16_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBBBP::uint_least32_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBBBP::uint_least64_t\fP"
.br
.ti -1c
.RI "typedef signed char \fBBBP::int_fast8_t\fP"
.br
.ti -1c
.RI "typedef int \fBBBP::int_fast16_t\fP"
.br
.ti -1c
.RI "typedef int \fBBBP::int_fast32_t\fP"
.br
.ti -1c
.RI "typedef long long \fBBBP::int_fast64_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBBBP::uint_fast8_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBBBP::uint_fast16_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBBBP::uint_fast32_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBBBP::uint_fast64_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBBBP::std::decimals\fP (uint32_t value)"
.br
.ti -1c
.RI "uint8_t \fBBBP::std::getDecimal\fP (uint32_t value, uint32_t position)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
