.TH "StressRelief.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StressRelief.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWhy\fP"
.br
.ti -1c
.RI "class \fBCunts\fP"
.br
.ti -1c
.RI "class \fBGoto\fP"
.br
.ti -1c
.RI "class \fBIHate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBFUCKYOU\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void FUCKYOU ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 36 of file StressRelief\&.h\&.
.PP
.nf
37 {}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
