SymbolBuilderGettersSetters.cpp
NAME
SymbolBuilderGettersSetters.cpp
SYNOPSIS
#include '../include/ELF.h'
Functions
BBP::std::byte readByte (BBP::std::ELF::SymbolBuilder *sym, BBP::std::offset_t offset)
void writeByte (BBP::std::ELF::SymbolBuilder *sym, BBP::std::byte byte, BBP::std::offset_t offset)
BBP::std::halfword readHalfWord (BBP::std::ELF::SymbolBuilder *sym, BBP::std::offset_t offset)
void writeHalfWord (BBP::std::ELF::SymbolBuilder *sym, BBP::std::halfword halfword, BBP::std::offset_t offset)
BBP::std::word readWord (BBP::std::ELF::SymbolBuilder *sym, BBP::std::offset_t offset)
void writeWord (BBP::std::ELF::SymbolBuilder *sym, BBP::std::word word, BBP::std::offset_t offset)
Function Documentation
BBP::std::byte readByte (BBP::std::ELF::SymbolBuilder * sym, BBP::std::offset_t offset)
Definition at line 3 of file SymbolBuilderGettersSetters.cpp.
{
    return sym->header.data[offset];
}
References BBP::std::PAGE< T >::data, and BBP::std::ELF::SymbolBuilder::header.
Referenced by BBP::std::ELF::SymbolBuilder::info(), and BBP::std::ELF::SymbolBuilder::other().
BBP::std::halfword readHalfWord (BBP::std::ELF::SymbolBuilder * sym, BBP::std::offset_t offset)
Definition at line 11 of file SymbolBuilderGettersSetters.cpp.
{
    BBP::std::byte a = sym->header.data[offset];
    BBP::std::byte b = sym->header.data[offset + 1];
    if (!sym->elf->Endian)
        return a | (b << 8);
    return b | (a << 8);
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SymbolBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SymbolBuilder::header.
Referenced by BBP::std::ELF::SymbolBuilder::shndx().
BBP::std::word readWord (BBP::std::ELF::SymbolBuilder * sym, BBP::std::offset_t offset)
Definition at line 36 of file SymbolBuilderGettersSetters.cpp.
{
    BBP::std::byte a = sym->header.data[offset];
    BBP::std::byte b = sym->header.data[offset + 1];
    BBP::std::byte c = sym->header.data[offset + 2];
    BBP::std::byte d = sym->header.data[offset + 3];
    if (!sym->elf->Endian)
        return a | (b << 8) | (c << 16) | (d << 24);
    return d | (c << 8) | (b << 16) | (a << 24);
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SymbolBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SymbolBuilder::header.
Referenced by BBP::std::ELF::SymbolBuilder::name(), BBP::std::ELF::SymbolBuilder::size(), and BBP::std::ELF::SymbolBuilder::value().
void writeByte (BBP::std::ELF::SymbolBuilder * sym, BBP::std::byte byte, BBP::std::offset_t offset)
Definition at line 7 of file SymbolBuilderGettersSetters.cpp.
{
    sym->header.data[offset] = byte;
}
References BBP::std::PAGE< T >::data, and BBP::std::ELF::SymbolBuilder::header.
Referenced by BBP::std::ELF::SymbolBuilder::info(), and BBP::std::ELF::SymbolBuilder::other().
void writeHalfWord (BBP::std::ELF::SymbolBuilder * sym, BBP::std::halfword halfword, BBP::std::offset_t offset)
Definition at line 20 of file SymbolBuilderGettersSetters.cpp.
{
    BBP::std::byte a = (halfword >> 0) & 0xFF;
    BBP::std::byte b = (halfword >> 8) & 0xFF;
    if (!sym->elf->Endian)
    {
        sym->header.data[offset] = a;
        sym->header.data[offset + 1] = b;
    }
    else
    {
        sym->header.data[offset] = b;
        sym->header.data[offset + 1] = a;
    }
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SymbolBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SymbolBuilder::header.
Referenced by BBP::std::ELF::SymbolBuilder::shndx().
void writeWord (BBP::std::ELF::SymbolBuilder * sym, BBP::std::word word, BBP::std::offset_t offset)
Definition at line 47 of file SymbolBuilderGettersSetters.cpp.
{
    BBP::std::byte a = (word >> 0) & 0xFF;
    BBP::std::byte b = (word >> 8) & 0xFF;
    BBP::std::byte c = (word >> 16) & 0xFF;
    BBP::std::byte d = (word >> 24) & 0xFF;
    if (!sym->elf->Endian)
    {
        sym->header.data[offset] = a;
        sym->header.data[offset + 1] = b;
        sym->header.data[offset + 2] = c;
        sym->header.data[offset + 3] = d;
    }
    else
    {
        sym->header.data[offset] = d;
        sym->header.data[offset + 1] = c;
        sym->header.data[offset + 2] = b;
        sym->header.data[offset + 3] = a;
    }
}
References BBP::Locale::Japanese::a, BBP::std::PAGE< T >::data, BBP::std::ELF::SymbolBuilder::elf, BBP::std::ELF::ELFBuilder::Endian, and BBP::std::ELF::SymbolBuilder::header.
Referenced by BBP::std::ELF::SymbolBuilder::name(), BBP::std::ELF::SymbolBuilder::size(), and BBP::std::ELF::SymbolBuilder::value().
Author
Generated automatically by Doxygen for BBP Embedded kernel from the source code.