.TH "System.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSER\fP   'Shell'"
.br
.ti -1c
.RI "#define \fBHOSTNAME\fP   'Strangelf@BBP'"
.br
.ti -1c
.RI "#define \fBOS\fP   'BB607 Hosted environment'"
.br
.ti -1c
.RI "#define \fBKERNEL\fP   '1\&.0\&.0\-BBP_PCID'"
.br
.ti -1c
.RI "#define \fBSHELL\fP   'TSauce'"
.br
.ti -1c
.RI "#define \fBTERMINAL\fP   'SDL'"
.br
.ti -1c
.RI "#define \fBCPU\fP   'Intel i7'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CPU   'Intel i7'"

.PP
Definition at line 10 of file System\&.h\&.
.SS "#define HOSTNAME   'Strangelf@BBP'"

.PP
Definition at line 5 of file System\&.h\&.
.SS "#define KERNEL   '1\&.0\&.0\-BBP_PCID'"

.PP
Definition at line 7 of file System\&.h\&.
.SS "#define OS   'BB607 Hosted environment'"

.PP
Definition at line 6 of file System\&.h\&.
.SS "#define SHELL   'TSauce'"

.PP
Definition at line 8 of file System\&.h\&.
.SS "#define TERMINAL   'SDL'"

.PP
Definition at line 9 of file System\&.h\&.
.SS "#define USER   'Shell'"

.PP
Definition at line 4 of file System\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
