.TH "Time.h" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Time.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdint\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBBP\fP"
.br
.ti -1c
.RI " \fBBBP::std\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBBBP::std::time_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "time_t \fBBBP::std::millis\fP ()"
.br
.ti -1c
.RI "void \fBBBP::std::delay\fP (time_t)"
.br
.ti -1c
.RI "time_t \fBBBP::std::now\fP ()"
.br
.ti -1c
.RI "void \fBBBP::std::initClock\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
