.TH "Why" 3 "Fri Jan 26 2024" "Version 0.2.0" "BBP Embedded kernel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Why
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StressRelief\&.h>\fP
.SS "Static Public Member Functions"
So if i start typing here what happens?
.in +1c
.ti -1c
.RI "static void \fBbecauseFuckYouThatsWhy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file StressRelief\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Why::becauseFuckYouThatsWhy ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 7 of file StressRelief\&.h\&.
.PP
.nf
8     {}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for BBP Embedded kernel from the source code\&.
