# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=DAEMONS

# Source files
MODULE_SRC=compd.cpp execd.cpp filed.cpp hwiod.cpp initd.cpp linkd.cpp resxd.cpp utild.cpp wmand.cpp

# Actually include the makefile
include ../makefile
