# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=FAT

# Source files
MODULE_SRC= FATheader.cpp FATEntry.cpp FATseek.cpp DateTime.cpp

# Actually include the makefile
include ../makefile
