# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=Shell

# Source files
MODULE_SRC= ShellInternals.cpp Singleton.cpp

# Actually include the makefile
include ../makefile
