# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=ELF

# Source files
MODULE_SRC=ELF.cpp ELFHeader.cpp SectionBuilder.cpp SegmentBuilder.cpp SymbolBuilder.cpp ELFHeaderGettersSetters.cpp SectionBuilderGettersSetters.cpp SegmentBuilderGettersSetters.cpp SymbolBuilderGettersSetters.cpp

# Actually include the makefile
include ../makefile
